### ISSUE TITLE
md文件有乱码

### ISSUE THREAD

**Issue by sunzcdev** [Blankj/AndroidUtilCode#1]
我用手机端github打开md有乱码。forkhub
另外，作者可以把这些代码合并成几个utils类

**Comment by Blankj** [comment]
编码已转为utf8无bom，经forkhub测试乱码已解决，后续会考虑整理成utils类的

**Comment by Blankj** [comment]
工具类的话之后我会写在我的Android开发框架里的utils包中的，到时候会放上地址的，这里的话还是md查阅起来比较方便我觉得。
