### ISSUE TITLE
作者你好，ESET-NOD32 检测有存在风险.

### ISSUE THREAD

**Issue by Zziv** [Blankj/AndroidUtilCode#1000]
![Uploading image.png…]()

**Comment by Zziv** [comment]
A Variant Of Android/DataCollector.Utilcode.B potentially unsafe

**Comment by Blankj** [comment]
所以是哪个函数？

**Comment by Zziv** [comment]
你这个工具类 是一个病毒  好好审查一下  因为你这个工具类 直接造成 google play 直接下架 100多万用户没了  给公司批评  ；呼吁更多开发者 看懂他的源码 同时 要用知名度高的博客

**Comment by Blankj** [comment]
那你倒是说清楚哪里呀？

**Comment by Zziv** [comment]
![image](https://user-images.githubusercontent.com/16253266/62681166-a056b180-b9eb-11e9-80e0-874ae31ef49b.png)

**Comment by Blankj** [comment]
混淆开启了吗，还有就是库的版本是多少？

**Comment by Zziv** [comment]
版本：implementation 'com.blankj:utilcode:1.25.0'
混淆没开启，这个是我直接新建一个项目，只引入你的库，其他第三方都没引入，然后打包apk上传检测结果的截图

https://www.virustotal.com/gui/home/upload
用的就是该网站检测的，你可以自己试一下

**Comment by Blankj** [comment]
已找到问题，更新 1.25.7 即可

**Comment by RyanYou** [comment]
作者您好，我用1.29.0 ，并且混淆了，依然还存在这个问题。。如何破？

**Comment by Blankj** [comment]
@RyanYou 那就不知道了
