### ISSUE TITLE
使用 UriUtils 的 uri2File，有时候不能获取到对应的 File，但是资源确实存在的。

### ISSUE THREAD

**Issue by jhwsx** [Blankj/AndroidUtilCode#1003]
Blankj 老师你好，我这边的用法是这样的：
点击sd卡里的一个视频资源，隐式启动我应用里的一个视频播放页面，希望能播放这个视频资源。从 Intent 里获取 uri，把它传给 uri2File 方法。但是，有时候却获取不到对应的 File，但过一会儿却又可以获取了（我记得特别清楚，晚上我还在使用一个视频复现此现象，但第二天过来时却都正常了）。并不是因为没有授予 sd 卡的读取权限，测试出现问题的机型也不集中，版本也不集中。不知道是什么原因了。
我自己考虑，是不是因为有些资源刚下载下来，通过 `context.getContentResolver().query()` 方法暂时查不到，要等系统把它更新了才可以？不过，并没有什么依据。

**Comment by Blankj** [comment]
最新版本 FileUtils.notifySystemToScan()
```java
/**
 * Notify system to scan the file.
 *
 * @param file The file.
 */
public static void notifySystemToScan(final File file) {
    if (file == null || !file.exists()) return;
    Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
    Uri uri = Uri.fromFile(file);
    intent.setData(uri);
    Utils.getApp().sendBroadcast(intent);
}
```

**Comment by jhwsx** [comment]
Blankj 老师：我还是不太明白，因为我这里并没有这个 `File` 对象传给 `notifySystemToScan` 方法。就是说，我们的应用是有一个播放器功能的，希望用户在点击有可能是在别的来源下载的视频，仍然可以使用隐式跳转打开我们的播放器。

**Comment by Blankj** [comment]
我的意思是把 notifySystemToScan 里面的 uri 换成你的 uri 呀。

**Comment by Blankj** [comment]
可以解决吗？

**Comment by jhwsx** [comment]
还没有。
