### ISSUE TITLE
根据安卓文件管理器返回uri，使用UriUtils 的 uri2File 获取外置sd卡，返回null

### ISSUE THREAD

**Issue by lan2001** [Blankj/AndroidUtilCode#1004]
android 9.0 
内部存储返回data=Intent { dat=content://com.android.externalstorage.documents/document/primary:666.mp4 flg=0x1 }  resultCode=-1 没问题
外sd返回 data=Intent { dat=content://com.android.externalstorage.documents/document/6235-6330:哈哈哈哈.mp4 flg=0x1 }  resultCode=-1
获取file为null

主要的问题出现：
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT
                && DocumentsContract.isDocumentUri(Utils.getApp(), uri)) {
            if ("com.android.externalstorage.documents".equals(authority)) {
                final String docId = DocumentsContract.getDocumentId(uri);
                final String[] split = docId.split(":");
                final String type = split[0];
                if ("primary".equalsIgnoreCase(type) {//出现问题
                    return new File(Environment.getExternalStorageDirectory() + "/" + split[1]);
                }
                Log.d("UriUtils", uri.toString() + " parse failed. -> 1_0");
                return null;
            }

里面 if ("primary".equalsIgnoreCase(type) ，但是外置sd路径中不是“primary”

**Comment by Blankj** [comment]
使用 1.25.7-alpha1 版本试试

**Comment by lan2001** [comment]
使用 1.25.7-alpha1 正常。万分感谢。

**Comment by fishwjy** [comment]
AndroidX版本 1.26.0
(1) 华为 mate 30获取 /外置存储根目录/Document下文件，返回为null
原因为：88行 type不为primary，而是home

(2) 华为 mate 30获取 /外置存储根目录/Donwload下文件，返回为null
原因为：141行id为msf:345，无法转为long类型导致NumberFormatException退出

其他目录还没测试，华为ROM真的是😓
