### ISSUE TITLE
建议ThreadUtils的类

### ISSUE THREAD

**Issue by candebbs** [Blankj/AndroidUtilCode#1007]
建议ThreadUtils这个类，在demo提供更多的示例或者api使用，看test之后，自己在项目调用ThreadUtils，调用api，还要测试（还是太菜了）。比如以下的api：
executeByFixed          : 在固定线程池执行任务
executeByFixedWithDelay : 在固定线程池延时执行任务
executeByFixedAtFixRate : 在固定线程池按固定频率执行任务
executeBySingle         : 在单线程池执行任务
executeBySingleWithDelay: 在单线程池延时执行任务
executeBySingleAtFixRate: 在单线程池按固定频率执行任务
executeByCached         : 在缓冲线程池执行任务
executeByCachedWithDelay: 在缓冲线程池延时执行任务
executeByCachedAtFixRate: 在缓冲线程池按固定频率执行任务
executeByIo             : 在 IO 线程池执行任务
executeByIoWithDelay    : 在 IO 线程池延时执行任务
executeByIoAtFixRate    : 在 IO 线程池按固定频率执行任务
executeByCpu            : 在 CPU 线程池执行任务
executeByCpuWithDelay   : 在 CPU 线程池延时执行任务
executeByCpuAtFixRate   : 在 CPU 线程池按固定频率执行任务
executeByCustom         : 在自定义线程池执行任务
executeByCustomWithDelay: 在自定义线程池延时执行任务
executeByCustomAtFixRate: 在自定义线程池按固定频率执行任务

**Comment by Blankj** [comment]
用了第一次之后就熟悉了，你自己项目中写测试那也是应该的哈。

**Comment by candebbs** [comment]
就是第一次使用花太多时间来，没有示例来参考啊

**Comment by Blankj** [comment]
一般我工具类都有一篇文章的 https://blankj.com/2018/05/23/thread-utils/

**Comment by candebbs** [comment]
这个看过了，但还是示例太少了。还是希望下一个版本能给多点示例。
