### ISSUE TITLE
ActivityUtils.startActivityForResult(fragment....

### ISSUE THREAD

**Issue by emreaktrk** [Blankj/AndroidUtilCode#1008]
## ActivityUtils should able to _startActivityForResult_ from a fragment. 
Fragments can start activity for result. If so, fragment can able to call itself _onActivityResult_

Reference : [Fragment#startActivityForResult](https://developer.android.com/reference/android/support/v4/app/Fragment#startactivityforresult)
[Fragment#onActivityResult](https://developer.android.com/reference/android/support/v4/app/Fragment#onactivityresult)

Need a method 
ActivityUtils.startActivityForResult(fragment, MyActivity.class, myRequestCode, ...)

Thanks for this great library!

**Comment by Blankj** [comment]
next version will be support

**Comment by Blankj** [comment]
You can try the version of 1.25.8-alpha1.

**Comment by emreaktrk** [comment]
implementation 'com.blankj:utilcodex:1.25.8-alpha1' -> Failed to resolve

Is it in another artifactory?

**Comment by Blankj** [comment]
I just publish utilcode, not utilcodex. If I publish utilcodex I will notify you again.

**Comment by emreaktrk** [comment]
👍

**Comment by Blankj** [comment]
Try the version of 1.25.9.
