### ISSUE TITLE
CrashUtils 报错

### ISSUE THREAD

**Issue by addappcn** [Blankj/AndroidUtilCode#101]
Utils.getContext().getExternalCacheDir().getPath()  报错  版本1.3.4

**Comment by Blankj** [comment]
错误类型呢

**Comment by addappcn** [comment]
Caused by: java.lang.NullPointerException
at com.blankj.utilcode.utils.CrashUtils.init(CrashUtils.java:66)

**Comment by addappcn** [comment]
crashDir = Utils.getContext().getCacheDir().getPath() + File.separator + "crash" + File.separator; 
就是这一行，是获取缓存目录为空吧
