### ISSUE TITLE
Gson转换带有HTML字符的建议

### ISSUE THREAD

**Issue by SummerMineJack** [Blankj/AndroidUtilCode#1011]
private static Gson createGson(final boolean serializeNulls) {
        final GsonBuilder builder = new GsonBuilder();
        if (serializeNulls) builder.serializeNulls();
        return builder.create();
    }

这里，建议添加一些属性操作，比如：disableHtmlEscaping()；

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布，GsonUtils 已支持自定义 Gson 对象
