### ISSUE TITLE
时间格式需要微调

### ISSUE THREAD

**Issue by 626838956** [Blankj/AndroidUtilCode#1012]
项目中默认的时间格式new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
这个时间格式的String作为文件名时需要切割再拼接，不然文件名有空格。从手机导出有空格文件名的文件需要一个个的加引号，比较复杂。
建议用下划线替换掉空格："yyyy-MM-dd_HH:mm:ss"。

**Comment by Blankj** [comment]
你是指 LogUtils 就是 CrashUtils？

**Comment by 626838956** [comment]
TimeUtils.java -> getNowString            : 获取当前时间字符串   这个方法。"yyyy-MM-dd_HH-mm-ss"这种格式的文件名才行，冒号出现在文件名中也有点问题

**Comment by Blankj** [comment]
TimeUtils 你可以自己传入 format 的
