### ISSUE TITLE
android Q变更 原来的READ_PHONE_STATE权限已经不能获得IMEI和序列号。

### ISSUE THREAD

**Issue by OneGreenHand** [Blankj/AndroidUtilCode#1013]
AndroidQ中去掉了READ_PHONE_STATE权限,取而代之的是一个系统级别的权限:READ_PRIVILEGED_PHONE_STATE,所以Android Q平台无论如何也不会再有IMEI和序列号

**Comment by Blankj** [comment]
对 SDK 大于等于 29 的我直接返回空字符串了。
