### ISSUE TITLE
KeyboardUtils.hideSoftInput(Activity activity)调用后软键盘还处于显示状态

### ISSUE THREAD

**Issue by RubinTry** [Blankj/AndroidUtilCode#1015]
如题，调用隐藏输入法的方法后软键盘是显示着，有时候甚至原先没打开软键盘的，调用完就打开了
版本 'com.blankj:utilcodex:1.25.8'

**Comment by Blankj** [comment]
你调用的传的是哪个参数的方法，最新版再试下？
