### ISSUE TITLE
ToastUtils设置样式之后，出现一个问题

### ISSUE THREAD

**Issue by JoinBelieve** [Blankj/AndroidUtilCode#1018]
## Describe the bug
APP启动之后，第一次调用Toast改变样式无效，第二次才会有效。

- The version of utilcode: 1.25.5
- The device: 锤子2S
- The version of device: API28

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
其他机器呢，上下代码吧

**Comment by JoinBelieve** [comment]
Pixel One也有这个问题

**Comment by JoinBelieve** [comment]
![toast](https://user-images.githubusercontent.com/29223055/63761236-60506380-c8f3-11e9-9d89-e01b41fa5202.jpg)

**Comment by Blankj** [comment]
先设置再 show 就行的。

**Comment by JoinBelieve** [comment]
尴尬了这！谢谢你kj

**Comment by JoinBelieve** [comment]
问题解决了，我close
