### ISSUE TITLE
安裝文件时 FileUriExposedException

### ISSUE THREAD

**Issue by DanteAndroid** [Blankj/AndroidUtilCode#102]
Hi，我使用` AppUtils.installApp(App.context, file);//安装
`安装apk文件时遇到了
`android.os.FileUriExposedException: file:///storage/emulated/0/Download/beauty.apk exposed beyond app through Intent.getData()`

Android OS：Android N

[解决办法看这里](https://www.google.com.hk/search?newwindow=1&q=FileUriExposedException&cad=h)

**Comment by Blankj** [comment]
7.0?

**Comment by DanteAndroid** [comment]
解决办法（已测试）：
```
        Intent install = new Intent(Intent.ACTION_VIEW);
        install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && apkFile.exists()) {
            install.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(context, BuildConfig.APPLICATION_ID + ".fileProvider", apkFile);
            install.setDataAndType(contentUri, "application/vnd.android.package-archive");
        } else {
            Uri apkUri =  Uri.fromFile(apkFile);
            install.setDataAndType(apkUri, "application/vnd.android.package-archive");
        }
        context.startActivity(install); 
```

manifest.xml:
>       <provider
>            android:name="android.support.v4.content.FileProvider"
>           android:authorities="${applicationId}.fileProvider"
>           android:exported="false"
>            android:grantUriPermissions="true">
>
>          <meta-data
>            android:name="android.support.FILE_PROVIDER_PATHS"
>          android:resource="@xml/file_paths"/>
></provider>

file_paths:
```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="download"
        path=""/>
    <external-files-path
        name="Download"
        path=""/>
</paths>
 ```

**Comment by DanteAndroid** [comment]
嗯。。这么多东西，能加到库里吗

**Comment by Blankj** [comment]
恩，我也在stackoverflow看到了，这是7.0的问题

**Comment by Blankj** [comment]
manifest.xml和file_paths得用户自己及配置的，我提供启动而已，只能这么做吧，你有什么建议

**Comment by DanteAndroid** [comment]
要么直接加到你的库的manifest里面看看行不行？我记得依赖库，也会共享其manifest文件（比如库的manifest定义了某权限，那么app也会有这个权限——假设是M之前的版本）。
如果不行，就加在注释里得了。

**Comment by Blankj** [comment]
7.0已完善哈

**Comment by DanteAndroid** [comment]
6666

**Comment by parcool** [comment]
已更新到最新，一配置file_provider，配置如下：
```xml
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <cache-path name="internal" path="boxing" />
    <external-path name="download" path="" />
    <external-files-path name="Download" path="" />
    <external-cache-path name="hm_external_cache" path="thumbs" />
</paths>
```。点击安装后无反应，lifiCycle看到走了onActivityPaused和onActivityResumed。

**Comment by Blankj** [comment]
?我的demo也不行吗

**Comment by parcool** [comment]
忘了回复。适配了动态权限以为就完事了，就忘了8.0的安装权限了。
```xml
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>
```
