### ISSUE TITLE
java.lang.SecurityException

### ISSUE THREAD

**Issue by xsslong** [Blankj/AndroidUtilCode#1020]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
 ActivityUtils.startActivity(new Intent(AActivity.this, BActivity.class));
```

**Comment by Blankj** [comment]
这跟我工具类没啥关系，你正常调用也会报这个错呀，我工具类又不是来强行让你启动不了的 Activity 都能启动的。
