### ISSUE TITLE
KeyboardUtils.showSoftInput(this); 软件盘打开一下又关闭

### ISSUE THREAD

**Issue by cloudmist** [Blankj/AndroidUtilCode#1021]
## Describe the bug

用fragment写的一个回复的输入框布局，点击回复弹出输入框时，同时打开软件盘，软键盘打开一下然后又隐藏掉，看起来像是闪烁的效果

- The version of utilcode:  1.25.9 
- The device:  Sony  G8342 
- The version of device:  API 28 

## The code of bug

 // 写回复
                Bundle bundle = new Bundle();
                bundle.putString("hint", getString(R.string.hint_comment));
                bundle.putBoolean("tu", true);//图片评论
                bundle.putString("p_user_id", "0");
                bundle.putString("post_id", "0");
                CommonUtils.showCommentDialogFragment(this, getSupportFragmentManager(), bundle);
                KeyboardUtils.showSoftInput(this);

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
你点击回复输入框了干嘛还需要调用打开软键盘，除非你把输入框的事件消费掉呀。

**Comment by cloudmist** [comment]
刚描述的不清楚，回复是这样一个按钮，点击按钮，回复对应的用户
![image](https://user-images.githubusercontent.com/26298774/64142166-73a48700-ce3d-11e9-8b19-5a310097051e.png)

然后，我把方法写在dialogfragment中初始化edittext过后，edittext获取焦点，再弹出软键盘就可以了

**Comment by Blankj** [comment]
好的
