### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by aliiteRookie** [Blankj/AndroidUtilCode#1022]
在OPPO A57上，使用isGranted()检查权限状态，分别使用android.permission-group.MICROPHONE 和android.permission.RECORD_AUDIO来检查录音权限，前者为true 后者为false的情况。

**Comment by aliiteRookie** [comment]
不好意思是MIRCROPHONE为false，RECORD_AUDIO为true

**Comment by Blankj** [comment]
设备版本是多少？

**Comment by aliiteRookie** [comment]
6.0.1

**Comment by Blankj** [comment]
MIRCROPHONE 是权限组，具体权限包括 RECORD_AUDIO，判断权限靠的是权限，而不是权限组哦
