### ISSUE TITLE
ActivityUtils.startActivityForResult not work

### ISSUE THREAD

**Issue by batman-dev** [Blankj/AndroidUtilCode#1023]
## ActivityUtils.startActivityForResult not call onActivityResult when finish activity

**Comment by Blankj** [comment]
show me ur code

**Comment by batman-dev** [comment]
## ActivityA.java
### call
```
Bundle extra = new Bundle();
extra.putString("circleId", "DBAD0453-9272-4EDE-9E32-5FBCDDF8D10B");
ActivityUtils.startActivityForResult(extra, ActivityA.this, ActivityB.class, 0x01, R.anim.slide_in_right, R.anim.slide_out_right);

@Override
protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (0x01 == requestCode
            && RESULT_OK == resultCode
            && data != null
            && data.hasExtra(KEY_DYNAMIC_NEW)) {
        CircleTalk circleTalk = data.getParcelableExtra("circleItem");
    }
}
```

## ActivityB.java
```
Intent result = new Intent();
result.putExtra("circleItem", data);
ActivityB.this.setResult(RESULT_OK, result);
ActivityB.this.finish();
```

## ActivityA.onActivityResult not call

**Comment by Blankj** [comment]
Try not to use ActivityUtils. Is it successful?

**Comment by wardenlzr** [comment]
@batman-dev show me ur head

**Comment by batman-dev** [comment]
yes use 
```
Intent intent = new Intent(ActivityA.this, ActivityB.class);
intent.putExtra("circleId", "DBAD0453-9272-4EDE-9E32-5FBCDDF8D10B");
startActivityForResult(intent, 0x01);
```
work ok

**Comment by Blankj** [comment]
@batman-dev I will fix it soon.

**Comment by emreaktrk** [comment]
If you are using launch mode from manifest, it could be your problem.

**Comment by xiexin52k** [comment]
Note that this method should only be used with Intent protocols that are defined to return a result. In other protocols (such as ACTION_MAIN or ACTION_VIEW), you may not get the result when you expect. For example, if the activity you are launching uses the singleTask launch mode(manifest launch mode is singleTask or Intent#FLAG_ACTIVITY_NEW_TASK),  it will not run in your task and thus you will immediately receive a cancel result.
