### ISSUE TITLE
特定情况ActivityUtils.finishActivity没起作用

### ISSUE THREAD

**Issue by lan2001** [Blankj/AndroidUtilCode#1024]
## Describe the bug

- The version of utilcode: '1.25.9'
- The device: 荣耀v10
- The version of device: api28

## The code of bug
ActivityUtils.finishOtherActivities(clz);
ActivityUtils.finishActivity(clz);

打包apk，手机安装完apk之后，先进启动页面，再进入主页面，主页面调用以上方法finish启动页面时没有作用。如果这个时候关闭app，在启动以上方法就起作用了。
首次安装apk，首次进入的时候没有效果。以后进去发现没有问题。

**Comment by Blankj** [comment]
debug 查看下我工具类的 Activity 堆栈

**Comment by lan2001** [comment]
遍历打印所有 Activity显示正常，启动页面遍历就有启动页面actvity，进入主页以后有  启动页面actvity+主页的activity。然后我调用AppManager.finishActivity();之后，再次遍历，发现里面还是存在启动页面actvity+主页的activity。

**Comment by lan2001** [comment]
新创建一个测试的项目：
异常现象：启动进入activity A ，再进入activity B ，在B里面ActivityUtils.finishActivity(A.class)，此时按手机返回键，再点击程序图标，会先进入activity A。
但我发现一个现象，手机安装apk之后，下面有俩按钮“完成”和“打开”，如果安装完点击“打开”按钮就会出现以上说的异常现象。如果apk安装完成之后，点击"完成"按钮，自己在到桌面点击图标进入app，则不会出现以上的问题。

**Comment by Blankj** [comment]
点击「打开」之后的 Activity 堆栈是什么

**Comment by lan2001** [comment]
点击“打开”之后，里面只有activity A

**Comment by lan2001** [comment]
点击“打开”之后，里面只有activity A

**Comment by Blankj** [comment]
既然存在为何 finish 不掉呢？

**Comment by lan2001** [comment]
我去掉ActivityUtils.finishActivity(A.class)代码。就简单的启动app进入activity A ，再进入activity B，然后按home键，再点击桌面图标，会直接进入activity A，而且重新执行A的onCreate。

**Comment by lan2001** [comment]
我去掉ActivityUtils.finishActivity(A.class)代码。安装apk，点击“打开”按钮，启动app进入activity A ，再进入activity B，然后按home键，再点击桌面图标，会直接进入activity A，而且重新执行A的onCreate。

**Comment by Blankj** [comment]
你的 A 是 singletask 导致的吧

**Comment by lan2001** [comment]
不是的，A就配置了<intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>







------------------ 原始邮件 ------------------
发件人: "布兰柯基"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 下午2:09
收件人: "Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com>; 
抄送: "oolo"<2012004573@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Blankj/AndroidUtilCode] 特定情况ActivityUtils.finishActivity没起作用 (#1024)




你的 A 是 singletask 导致的吧

**Comment by Blankj** [comment]
那就是 rom 的问题？

**Comment by lan2001** [comment]
用这个方法解决了  https://blog.csdn.net/shangming150/article/details/78343103




------------------ 原始邮件 ------------------
发件人: "布兰柯基"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 下午2:16
收件人: "Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com>; 
抄送: "oolo"<2012004573@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Blankj/AndroidUtilCode] 特定情况ActivityUtils.finishActivity没起作用 (#1024)




那就是 rom 的问题？
