### ISSUE TITLE
FlashlightUtils 适配 android 9.0

### ISSUE THREAD

**Issue by 121104115wyb** [Blankj/AndroidUtilCode#1025]
FlashlightUtils 适配 android 9.0

**Comment by Blankj** [comment]
我这边没问题呀，https://github.com/Blankj/AndroidUtilCode/releases/download/1.25.9/util_1_25_9_release.apk
你下个 demo 玩玩看

**Comment by 121104115wyb** [comment]
谢谢，已经解决了
