### ISSUE TITLE
为什么我通过 ConvertUtils.dp2px() 方法获取到的值与xml直接写的值不一致

### ISSUE THREAD

**Issue by protectedMan** [Blankj/AndroidUtilCode#1027]
针对一个 view 同样是 15dp,
在xml里写好，然后使用 
layoutParams.height 获取到的高度和 ConvertUtils.dp2px() 方法获取到的值不同
为什么会出现这种情况呢
![image](https://user-images.githubusercontent.com/17565737/64486552-18213180-d261-11e9-898c-c2ad0d6d2c21.png)

**Comment by Blankj** [comment]
layout 的 height 包括 view 的 margin 的；你设置的高度是 15dp 应该取获取 view 的 getHeight；

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/64496784-42173a00-d2db-11e9-93c4-391cc9b75a6c.png)
![image](https://user-images.githubusercontent.com/17565737/64496805-6a9f3400-d2db-11e9-9faa-c68adc8f4705.png)
![image](https://user-images.githubusercontent.com/17565737/64496653-1fd0ec80-d2da-11e9-8cf3-c430b7f25f3d.png)

同样是一个15dp高度的view，通过view测量得到px值和 dp2px方法得到的不同,相关代码已经贴出

**Comment by protectedMan** [comment]
问题发现了 是使用androidautosize的原因
