### ISSUE TITLE
界面有recyclerView显示图片，其上层是fragment容器，使用FragmentUtils显示任何一个fragment后，recyclerview的图片变成白色了，但是仍然能点击；此外，原生getSupportFragmentManager没有出现图片变白异常

### ISSUE THREAD

**Issue by NightMoonCat** [Blankj/AndroidUtilCode#1034]
我的界面有一个recyclerView显示图片，其上层是fragment容器；
使用FragmentUtils显示任何一个fragment后，recyclerview的图片不显示了，一片白；
此外，原生的getSupportFragmentManager显示和隐藏没有出现图片变白的情况

**Comment by Blankj** [comment]
相关代码发上来下方便查找问题
