### ISSUE TITLE
 NullPointerException Utils.processHideSoftInputOnActivityDestroy() 

### ISSUE THREAD

**Issue by imliujun** [Blankj/AndroidUtilCode#1038]
使用版本：com.blankj:utilcodex:1.25.8

<img width="1137" alt="WX20190918-141806@2x" src="https://user-images.githubusercontent.com/9779970/65120456-413f8000-da20-11e9-9472-2438ee8e2bd6.png">

![image](https://user-images.githubusercontent.com/9779970/65120490-50263280-da20-11e9-834d-da0ba6ad29a2.png)

**Comment by Blankj** [comment]
好的

**Comment by imliujun** [comment]
可以的话，先加个try catch 发一个版本吧，项目明天上线。3Q

**Comment by Blankj** [comment]
1.25.10-alpha3
