### ISSUE TITLE
ToastUtil手机未开启通知权限无法显示吐司,吐司会被软键盘遮挡。

### ISSUE THREAD

**Issue by MoMask** [Blankj/AndroidUtilCode#1039]
为何要用通知和window manager 去实现吐司。系统自带的我觉得就行

**Comment by Blankj** [comment]
系统自带的关闭通知你能显示？只有关闭通知情况下才用 WindowManager 实现的，所以会被键盘遮挡。

**Comment by MoMask** [comment]
关闭通知能改成系统的么，因为系统的吐司无论什么情况都是可以正常显示的

**Comment by Blankj** [comment]
你自己试了吗就这么说？

**Comment by MoMask** [comment]
蛋疼，那只能开通知权限了
