### ISSUE TITLE
权限申请空指针

### ISSUE THREAD

**Issue by wangzhanxian** [Blankj/AndroidUtilCode#1042]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.noxgroup.app.hunter/com.blankj.utilcode.util.PermissionUtils$PermissionActivity}: java.lang.NullPointerException: Attempt to read from field 'com.blankj.utilcode.util.PermissionUtils$ThemeCallback com.blankj.utilcode.util.PermissionUtils.mThemeCallback' on a null object reference
1.	android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
2.	android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
3.	android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
4.	android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
5.	android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
6.	android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
7.	android.os.Handler.dispatchMessage(Handler.java:106)
8.	android.os.Looper.loop(Looper.java:201)
9.	android.app.ActivityThread.main(ActivityThread.java:6823)
10.	java.lang.reflect.Method.invoke(Native Method)
11.	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
12.	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Blankj** [comment]
试试 1.26.0 版本
