### ISSUE TITLE
SPUtils  Context.MODE_APPEND 有问题。使用的效果和MODE_PRIVATE一样的

### ISSUE THREAD

**Issue by xslandlr** [Blankj/AndroidUtilCode#1044]
for(ApplicationInfo app : applicationInfos){
            if(allowPackages.contains(app.packageName)){
                String appName = app.loadLabel(pm).toString();
                if(appName.contains("联系人")){
                    SPUtils.getInstance(Context.MODE_APPEND).put(Constant.KEY_HOME_APPS,"," + app.packageName);
                    Log.e("CommUtils", SPUtils.getInstance().getString(Constant.KEY_HOME_APPS) );
                }else if(appName.contains("相机")){
                    SPUtils.getInstance(Context.MODE_APPEND).put(Constant.KEY_HOME_APPS,"," + app.packageName);
                    Log.e("CommUtils", SPUtils.getInstance().getString(Constant.KEY_HOME_APPS) );
                }else if(appName.contains("信息")){
                    SPUtils.getInstance(Context.MODE_APPEND).put(Constant.KEY_HOME_APPS,"," + app.packageName);
                    Log.e("CommUtils", SPUtils.getInstance().getString(Constant.KEY_HOME_APPS) );
                }else if(appName.contains("浏览器")){
                    SPUtils.getInstance(Context.MODE_APPEND).put(Constant.KEY_HOME_APPS,"," + app.packageName);
                    Log.e("CommUtils", SPUtils.getInstance().getString(Constant.KEY_HOME_APPS) );
                }else{
                    AppInfo appInfo = new AppInfo();
                    boolean isSystemApp = (app.flags & ApplicationInfo.FLAG_SYSTEM) != 0;
                    appInfo.setAppName(appName);
                    appInfo.setIcon(pm.getApplicationIcon(app));
                    appInfo.setPackageName(app.packageName);
                    appInfo.setSystemApp(isSystemApp);
                    appInfos.add(appInfo);
                }
            }
        }

**Comment by Blankj** [comment]
你在操作之前 SPUtils.getInstance() 过是吗？
