### ISSUE TITLE
DangerousUtils.installAppSilent安装了老版本再安装新版本会报INSTALL_FAILED_ALREADY_EXISTS

### ISSUE THREAD

**Issue by liangtian123** [Blankj/AndroidUtilCode#1045]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
加参数 -p

**Comment by liangtian123** [comment]
嗯，解决了

**Comment by liangtian123** [comment]
谢谢大佬
