### ISSUE TITLE
考虑添加一下数字转中文功能

### ISSUE THREAD

**Issue by 15050050972** [Blankj/AndroidUtilCode#1047]
数字转化为中文
123456 >>> 十二万三千四百五十六

数字转 数字和中文混合

123456 >>> 12万3千4百5十6  （单位：十）
123456 >>> 12万3千4百            (单位：百）
123456 >>> 12万                       (单位：万）

**Comment by Blankj** [comment]
不是很通用，这个其实也不难，业务方自己维护一个吧
