### ISSUE TITLE
有没有办法注销键盘监听呢?

### ISSUE THREAD

**Issue by TanZhiL** [Blankj/AndroidUtilCode#1048]
## Describe the bug

- The version of utilcode: 1.25.8

**Comment by Blankj** [comment]
使用完了你要注销吗？

**Comment by TanZhiL** [comment]
是的, 需要根据条件来判断是否监听

发送自 Windows 10 版邮件应用

发件人: 布兰柯基
发送时间: 2019年10月8日 14:25
收件人: Blankj/AndroidUtilCode
抄送: 谭志龙; Author
主题: Re: [Blankj/AndroidUtilCode] 有没有办法注销键盘监听呢? (#1048)

使用完了你要注销吗？

**Comment by Blankj** [comment]
把条件写在我给你的回调里呢？

**Comment by TanZhiL** [comment]
可以实现,那就先不用加了吧,我用其他方式替代了,谢谢大佬
发送自 Windows 10 版邮件应用

发件人: 布兰柯基
发送时间: 2019年10月8日 14:41
收件人: Blankj/AndroidUtilCode
抄送: 谭志龙; Author
主题: Re: [Blankj/AndroidUtilCode] 有没有办法注销键盘监听呢? (#1048)

把条件写在我给你的回调里呢？
