### ISSUE TITLE
能不能说明下Utils.init(context)用说明context比较好？

### ISSUE THREAD

**Issue by DearZack** [Blankj/AndroidUtilCode#105]
在初始化的时候用activity的好还是application的好？

**Comment by DanteAndroid** [comment]
请写在Application的onCreate中。`Utils.init(this)`
@Blankj 加入到README吧，最好放在最前面，不然一般人还看不到。。

**Comment by Blankj** [comment]
@DearZack 用哪个都没差别，因为我都转成application的context了
@DanteAndroid Good idea
