### ISSUE TITLE
权限申请异常（少部分机型报错，无法重现）

### ISSUE THREAD

**Issue by androidGhost** [Blankj/AndroidUtilCode#1050]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.camera.s9.camera/com.blankj.utilcode.util.PermissionUtils$PermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
依赖的是最新版本1.25.9

**Comment by Blankj** [comment]
你是自定义主题了吗

**Comment by androidGhost** [comment]
自定义了主题，parent="Theme.AppCompat.Light.NoActionBar"

**Comment by androidGhost** [comment]
影响用户数7
![image](https://user-images.githubusercontent.com/9106628/66731796-b9685c80-ee8b-11e9-9563-76f2cc13667d.png)

**Comment by Blankj** [comment]
你对我的 PermissionActivity 设置了主题？不需要设置的呀

**Comment by androidGhost** [comment]
好，后续观察下结果
