### ISSUE TITLE
新增更新日志

### ISSUE THREAD

**Issue by GodJiong** [Blankj/AndroidUtilCode#1051]
柯基大佬你好，用了你的库让我解放了劳动力，非常感谢你的付出与奉献！这里有一个小提议还望采纳，比如可以在wiki里新增更新日志，这样大家可以根据自己的需求选择版本，以及是否需要更新版本等。

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases
https://github.com/Blankj/AndroidUtilCode/blob/master/CHANGELOG.md
你是要哪个

**Comment by GodJiong** [comment]
@Blankj 我发现1.25.9比1.25.8改动的比较多，这个更新日志好像没写全
