### ISSUE TITLE
URLDecoder异常

### ISSUE THREAD

**Issue by BecauseHappy** [Blankj/AndroidUtilCode#1052]
EncodeUtils.urlDecode()的时候如果传入String包含%会报错
应该是系统方法URLDecoder.decode的错  柯基能不能在调用这个方法之前过滤一下
嘿嘿
URLDecoder异常Illegal hex characters in escape (%)

**Comment by Blankj** [comment]
下版本修复哈

**Comment by Blankj** [comment]
1.26.0 已发布
