### ISSUE TITLE
KeyboardUtils.java的clickBlankArea2HideSoftInput方法有误

### ISSUE THREAD

**Issue by jefshi** [Blankj/AndroidUtilCode#1053]
// Return whether touch the view.
private boolean isShouldHideKeyboard(View v, MotionEvent event) {
	if (v != null && (v instanceof EditText)) {
		int[] l = {0, 0};
		v.getLocationInWindow(l);
		int left = l[0],
				top = l[1],
				bottom = top + v.getHeight(),
				right = left + v.getWidth();
		return !(event.getX() > left && event.getX() < right
				&& event.getY() > top && event.getY() < bottom);
	}
	return false;
}

上述
return !(event.getX() > left && event.getX() < right
		&& event.getY() > top && event.getY() < bottom);
应改为
return !(event.getRawX() > left && event.getRawX() < right
		&& event.getRawY() > top && event.getRawY() < bottom);

**Comment by jefshi** [comment]
这个方法用于【Android点击EditText文本框之外任何地方隐藏键盘】，getX是相对父控件，getRawX是相对屏幕，后者适用范围更广

**Comment by Blankj** [comment]
写在 activity 里的 dispatchTouchEvent 就是 DecorView 的，getX 就是 getRawX 哦。

**Comment by jefshi** [comment]
尴尬，误认为是 view 的 getX。查到的代码，作者刻意注释了这点，还以为必须得用 getRawX
