### ISSUE TITLE
NotificationUtils适配api26 ，然后再丰富一下？

### ISSUE THREAD

**Issue by lan2000** [Blankj/AndroidUtilCode#1054]
## Describe the bug

- The version of utilcode:

**Comment by zaaach** [comment]
同楼上，希望作者可以完善下NotificationUtils

**Comment by Blankj** [comment]
已经写好了，下版本就可用了

**Comment by zaaach** [comment]
哇开心==。

**Comment by Blankj** [comment]
1.26.0 已发布

**Comment by yecaler** [comment]
> 
> ## Describe the bug
> 
> A clear and concise description of what the bug is.
> 
>     * The version of utilcode:
请问大佬如何NotificationUtils使用的？求教！

**Comment by yecaler** [comment]
> 
> 
> 同楼上，希望作者可以完善下NotificationUtils

请问大佬如何NotificationUtils使用的？求教！
Utils.Func1<Void, NotificationCompat.Builder> func1
这个参数怎么配置？

**Comment by Blankj** [comment]
@yecaler AS 智能提示不就能完成么，实在不行就看 demo 呀，https://github.com/Blankj/AndroidUtilCode/blob/master/feature/utilcode/pkg/src/main/java/com/blankj/utilcode/pkg/feature/notification/NotificationActivity.kt

**Comment by whokill** [comment]
有java代码的调用示例吗

**Comment by Blankj** [comment]
@whokill 好好看 readme

**Comment by whokill** [comment]
> @whokill 好好看 readme
示例代码都是kt的呀，没找到java 的

**Comment by Blankj** [comment]
@whokill 你直接看参数不就会了么
