### ISSUE TITLE
isAvailableByPing 方法访问失败

### ISSUE THREAD

**Issue by cy757120553** [Blankj/AndroidUtilCode#1055]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
访问失败是指？

**Comment by cy757120553** [comment]
ip地址，同一局域网，电脑能ping通，手机ping不通

**Comment by Blankj** [comment]
直接调用 isAvailableAsync 即可

**Comment by Blankj** [comment]
解决了吗

**Comment by cy757120553** [comment]
isAvailablePing和isAvailableAsync区别就在异步？

**Comment by Blankj** [comment]
老哥，自己鼠标点击下看下源码，又不是嵌套 10 层，那么懒干嘛
