### ISSUE TITLE
获取的屏幕亮度值超过了255

### ISSUE THREAD

**Issue by zhangshaobo87** [Blankj/AndroidUtilCode#1057]
屏幕亮度不是在0-255之间么，为什么我使用BrightnessUtils 回去的屏幕亮度和窗口亮度都超过了255，最高亮度值为4095，请问这个是咋回事。

**Comment by Blankj** [comment]
我也不是很清楚

**Comment by SerendipityKim** [comment]
> 屏幕亮度不是在0-255之间么，为什么我使用BrightnessUtils 回去的屏幕亮度和窗口亮度都超过了255，最高亮度值为4095，请问这个是咋回事。

小米手机 MIUI系统定制化，修改google api，小米开发者文档有说明
