### ISSUE TITLE
建议: 屏幕适配与字体大小的问题

### ISSUE THREAD

**Issue by prczhb** [Blankj/AndroidUtilCode#1060]
目前AdaptScreenUtils里只有屏幕尺寸的适配 没有关于字体大小的设置适配 建议加入此功能

所有手机都应该有字体大小的设置 部分手机甚至还加入了显示大小的设置(我这里的华为P20)

目前是 用户设置了系统字体的大小, AdaptScreenUtils的尺寸适配是对字体不起作用的 希望加入一个开关(是否支持字体大小变化设置)

只有如下设置才能忽略字体大小的设置
//    @Override
//    public Resources getResources() {
//        Resources res = super.getResources();
//        Configuration configuration = res.getConfiguration();
//        if (configuration.fontScale != 1.0f) {
//            configuration.fontScale = 1.0f;
//            res.updateConfiguration(configuration, res.getDisplayMetrics());
//        }
//        return res;
//    }

但是以上代码针对华为手机的 '显示大小' 设置无效, 用户调整了 '显示大小' 的设置 仍然会使布局失真(系统对尺寸进行一定比例的缩放)(观察来看华为缩放变化比较小 两个手机对比就容易发现了)

AdaptScreenUtils的设置也对 用户针对于 "显示大小" 的设置无效

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/issues/758
参看这个，你想随系统字体改变，系统显示大小改变为何要用我这个百分比显示的适配，你这矛盾啊，你想随系统改变那你字体就用 sp，单位就用 dp 即可。

**Comment by prczhb** [comment]
额 好吧 忘了sp的事了 谢谢大佬提醒

**Comment by prczhb** [comment]
在开发者选项里 设置最小宽度 模拟不同dp宽度的设备 发现AdaptScreenUtils的尺寸适配没效果?

**Comment by Blankj** [comment]
该适配是百分比适配，就是无论你怎么变，布局都是百分比的，你设置不同的最小宽度显示都是不变的。
