### ISSUE TITLE
BarUtils.setNavBarVisibility(this,false);

### ISSUE THREAD

**Issue by houyuehai** [Blankj/AndroidUtilCode#1062]
## Describe the bug

- The version of utilcode: 1.24.3
- The device:荣耀magic 2
- The version of device: 28

BarUtils.setNavBarVisibility(this,false);在荣耀Magic 2设置无法隐藏导航栏。而在荣耀9X上是可以隐藏的。
柯基大佬！

**Comment by houyuehai** [comment]
对了 我是横屏的。

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases
下个 demo 试试看

**Comment by houyuehai** [comment]
我升级到最新版本的auc 可以了。
