### ISSUE TITLE
华为mate20刘海屏幕，状态栏高度不对

### ISSUE THREAD

**Issue by bailibaili** [Blankj/AndroidUtilCode#1063]
## 屏幕适配后，获取的statusBar高度不对

华为系列刘海，水滴屏，设置pt布局后，
用ImmersionBar这个库，和你的库BarUtils.getStatusBarHeight()获取的高度一样，但是值不对。
但是在设置pt布局之前获取的状态栏高度值是对的，猜测应该是异形屏都有问题

- The version of utilcode: 1.25.9
- The device: 华为mate20，Nova 4
- The version of device: android 9

## The code of bug

```java
 @Override
    public Resources getResources() {
        KLog.e(BarUtils.getStatusBarHeight());  //这个值是正确的
        return AdaptScreenUtils.adaptWidth(super.getResources(), 750);
    }
//之后再获取，值错误
 BarUtils.getStatusBarHeight()值错误
```

**Comment by wanghaibao123** [comment]
这个不能这个获取，屏幕适配之后resource改变了

**Comment by wanghaibao123** [comment]
不能这么获取 屏幕适配之后resource改变了，或出现问题
int resourceId = Resources.getSystem().getIdentifier("status_bar_height", "dimen", "android");
使用这个

**Comment by bailibaili** [comment]
> 不能这么获取 屏幕适配之后resource改变了，或出现问题
> int resourceId = Resources.getSystem().getIdentifier("status_bar_height", "dimen", "android");
> 使用这个

如果使用这个是正确的高度，那么util中BarUtils.getStatusBarHeight()这个方法就是有缺陷的

**Comment by wanghaibao123** [comment]
是有一点瑕疵吧

**Comment by bailibaili** [comment]
> 是有一点瑕疵吧

感谢您的答复

**Comment by wyj365372704** [comment]
这个问题麻烦在库里面做一下优化或者适配吧。

**Comment by Blankj** [comment]
所以是 Utils.getApp().getResources(); 和  Resources.getSystem()；哪个获取的值是对的？

**Comment by wanghaibao123** [comment]
> 所以是 Utils.getApp().getResources(); 和 Resources.getSystem()；哪个获取的值是对的？

 使用屏幕适配之后，Resources.getSystem() 的值是正确的

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/issues/689
我太难了

**Comment by wanghaibao123** [comment]
哈哈，尴尬
