### ISSUE TITLE
屏幕适配增加耗时问题

### ISSUE THREAD

**Issue by wanghaibao123** [Blankj/AndroidUtilCode#1066]
在BaseActivity 中重写getResource（）
![image](https://user-images.githubusercontent.com/14246724/67451618-85dbbe00-f653-11e9-960c-5c075feb4767.png)
页面跳转增加了500毫秒左右的耗时，请问有什么方法解决吗

**Comment by Blankj** [comment]
每次都会很慢吗？

**Comment by wanghaibao123** [comment]
是的，每个页面都是这样------------------ 原始邮件 ------------------
发件人: "布兰柯基"<notifications@github.com>
发送时间: 2019年10月24日(星期四) 晚上8:10
收件人: "Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com>;
抄送: "wanghaibao123"<897094453@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Blankj/AndroidUtilCode] 屏幕适配增加耗时问题 (#1066)



每次都会很慢吗？
 
&mdash;

**Comment by wanghaibao123** [comment]
> 每次都会很慢吗？

@Blankj 
找到原因了，是页面渲染很慢，找到一个方法可以解决这个问题，请指正
![image](https://user-images.githubusercontent.com/14246724/67665640-12b0af80-f9a5-11e9-80db-479e4df27d0c.png)
将Resources 设置为全局变量，这样可以加快页面渲染时间

**Comment by Blankj** [comment]
synchronized 是否可以去掉呀，这个应该都是在主线程调用的吧，如果你的 resource 不会变的话，是可以保存下来的，这样就没必要每次都去获取一遍了。

**Comment by wanghaibao123** [comment]
哦，对，是要去掉，谢谢了，很好用的框架
