### ISSUE TITLE
keyboardUtils中，方法isShouldHideKeyboard 判断在有底部导航条的华为手机上出现计算错误bug。

### ISSUE THREAD

**Issue by wyj365372704** [Blankj/AndroidUtilCode#1067]
如题，华为手机上，当底部导航条不开启的状况下，是没有任何问题的。如果开启底部导航条，可能会有一些控件的getLocationInWindow 方法会返回错误，导致整个isShouldHideKeyboard方法的判断错误。

修改为如下，解决了我的问题：

 protected boolean isShouldHideKeyboard(View v, MotionEvent event) {
        if (v != null && (v instanceof EditText)) {
            int[] l = {0, 0};
            v.getLocationOnScreen(l);
            int left = l[0],
                    top = l[1],
                    bottom = top + v.getHeight(),
                    right = left + v.getWidth();
            return !(event.getRawX() > left && event.getRawX() < right
                    && event.getRawY() > top && event.getRawY() < bottom);
        }
        return false;
    }

方法就是获取屏幕的绝对坐标，而不是相对。

**Comment by Blankj** [comment]
getLocationOnScreen 如果应用分屏了就会有问题呀

**Comment by wyj365372704** [comment]
> getLocationOnScreen 如果应用分屏了就会有问题呀，getLocationInWindow 不行吗

特意使用了我的手机试了下分屏模式，不论APP放上部还是下部getLocationOnScreen不会出现问题，应该是getLocationOnScreen没有按照物理屏幕边界计算，而是按照分屏时分配的屏幕边界，但不保证是否和rom有关。

另外，getLocationInWindow 确实不行，改用getLocationOnScreen 以及event的getRawX、getRawY ，问题得到解决。

**Comment by Blankj** [comment]
```java
private static int getDecorViewInvisibleHeight(@NonNull final Window window) {
    final View decorView = window.getDecorView();
    final Rect outRect = new Rect();
    decorView.getWindowVisibleDisplayFrame(outRect);
    Log.d("KeyboardUtils", "getDecorViewInvisibleHeight: "
            + (decorView.getBottom() - outRect.bottom));
    int delta = Math.abs(decorView.getBottom() - outRect.bottom);
    if (delta <= getNavBarHeight() + getStatusBarHeight()) {
        sDecorViewDelta = delta;
        return 0;
    }
    return delta - sDecorViewDelta;
}
```
已经做了 getNavBarHeight() + getStatusBarHeight() 判断了

**Comment by Blankj** [comment]
1.26.0 已发布
