### ISSUE TITLE
PermissionUtils.isGranted(PermissionConstants.STORAGE) 一直返回false，即使已经有读写权限了

### ISSUE THREAD

**Issue by jiqianwen** [Blankj/AndroidUtilCode#1068]
if (PermissionUtils.isGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE) && PermissionUtils.isGranted(Manifest.permission.READ_EXTERNAL_STORAGE)) {
 }

这样判断却是可以的，什么原因？

**Comment by Blankj** [comment]
本来就要这样写呀，isGranted 参数又不带 @Permission 注解的

**Comment by Blankj** [comment]
```java
if (PermissionUtils.isGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE)) {
}
```
可以这样写呀

**Comment by Blankj** [comment]
PermissionUtils.isGranted(PermissionConstants.STORAGE) 直接判断权限组有问题的呀，有的权限组中的权限并不会全都写在清单文件里的呀，是没有权限的呀。

**Comment by jiqianwen** [comment]
> PermissionUtils.isGranted(PermissionConstants.STORAGE) 直接判断权限组有问题的呀，有的权限组中的权限并不会全都写在清单文件里的呀，是没有权限的呀。

好的，了解了，谢谢~
