### ISSUE TITLE
busutils plugin会导致编译时间过长

### ISSUE THREAD

**Issue by zhoujia456888** [Blankj/AndroidUtilCode#1072]
- The version of utilcode: 1.25.9
添加apply plugin: "com.blankj.bus" 之后运行程序Gradle会一直停留在
> Configure project :app
PLUGIN-BUS >>> project(project ':app') apply api gradle plugin!
卡住很长一段时间。

这个是没有添加apply plugin的时间
![TIM截图20191031091307](https://user-images.githubusercontent.com/7905253/67911327-20db1780-fbc1-11e9-80e3-ab1737e5a529.png)

这个是添加了apply plugin的时间
![TIM截图20191031100258](https://user-images.githubusercontent.com/7905253/67912679-a95bb700-fbc5-11e9-8b27-6ddf94a0c42b.png)

com.blankj:bus-gradle-plugin的版本是2.2

**Comment by Blankj** [comment]
用命令行看到底哪个任务慢了 ./gradlew clean assDebug --profile -x lint -x test

**Comment by zhoujia456888** [comment]
貌似是bulid的时候下载高德地图的包一直卡在蒲公英的maven url 上了，很奇怪，明明高德的可以直接jcenter上下的，硬是要跳到蒲公英的地址上去，我下个蒲公英aar替换掉implementation然后删掉蒲公英的maven url 就好了。
我看build一直卡在PLUGIN-BUS还以为是busutils的问题。
![TIM截图20191031114245](https://user-images.githubusercontent.com/7905253/67917464-11b19500-fbd4-11e9-8949-ea6f2cc0222a.png)

但是也很奇怪，我上面删除bus的plugin的时候那个1分16s的时间也不知道是为什么，可能是因为刚打开项目跳过了download 高德的包的过程？？还是因为我高德地图版本号写的是latest.integration？？

Gradle这个东西真的是个迷。。

**Comment by Blankj** [comment]
repositories 配置下先后顺序就行

**Comment by zhoujia456888** [comment]
这个 repositories 配置下先后顺序 是要怎么操作  有没有个教程连接，百度搜索都文不对题的。

**Comment by Blankj** [comment]
哪个写在前面就先去哪个拉，jcenter 放在最前面就会优先到 jcenter 拉，拉不到的话继续往后年的仓库拉，没啥好说的呀

**Comment by zhoujia456888** [comment]
事实是，我jcenter()和mavenCentral()确实是放前面的，甚至我还加了阿里的，可是拉高德的时候依然直接用的蒲公英那个地址。。。很奇葩。
![image](https://user-images.githubusercontent.com/7905253/67918973-7e7b5e00-fbd9-11e9-9272-1b8f7d89e7ca.png)

**Comment by Blankj** [comment]
那说明没找到呗

**Comment by zhoujia456888** [comment]
试了下是高德地图 latest.integration的坑  我直接填4.7.2的版本号就很快，latest就会卡在蒲公英的链接那里
