### ISSUE TITLE
readFile2BytesByStream(final String filePath) 

### ISSUE THREAD

**Issue by houyuehai** [Blankj/AndroidUtilCode#1078]
util:1.25.9   FileIOUtils.readFile2BytesByStream(final String filePath) ;
柯基大佬，这里的参数，是不是为InputStream更好。
或者提供一个将Assets中的文件读成byte[]的方法。（很多第三方SDK只接受path或者byte[]，然后我的文件放在了assets中）

**Comment by Blankj** [comment]
File 只和 File 有关，流可以是很多种，并不一定是文件流，操作 assets 可以用 ResourceUtils

**Comment by houyuehai** [comment]
emmm，明白了。我最后是copy 出来自己在resUtil里
    //从Assets获取byte
    public static byte[] readByteFromAssets(String filePath) {
        int sBufferSize = 1024;
        try {
            InputStream assetsIs = Utils.getApp().getResources().getAssets().open(filePath);
            ByteArrayOutputStream os = null;
            InputStream is = new BufferedInputStream(assetsIs, sBufferSize);
            try {
                os = new ByteArrayOutputStream();
                byte[] b = new byte[sBufferSize];
                int len;
                while ((len = is.read(b, 0, sBufferSize)) != -1) {
                    os.write(b, 0, len);
                }
                return os.toByteArray();
            } catch (IOException e) {
                e.printStackTrace();
                return null;
            } finally {
                try {
                    is.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                try {
                    if (os != null) {
                        os.close();
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
