### ISSUE TITLE
小米MUI-11系统上使用ToastUtil显示默认提示文字为白色，小米系统更新出的bug

### ISSUE THREAD

**Issue by zuojianjian** [Blankj/AndroidUtilCode#1079]
小米MUI-11系统上使用ToastUtil显示默认提示文字为白色，小米系统更新出的bug！！！希望能够兼容最新的小米系统，上一个版本小米系统默认显示的是灰白色！用户更新系统后，系统文字提示变成白色背景也是白色导致用户看不到提示

**Comment by Blankj** [comment]
我这边不做系统的改变，你要改那就自己设置字体颜色和样式就行
