### ISSUE TITLE
建议：ScreenUtils里面希望能增加隐藏底部导航栏的方法

### ISSUE THREAD

**Issue by hapzhu** [Blankj/AndroidUtilCode#1080]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
好好看下 BarUtils
