### ISSUE TITLE
现在使用你的最新版本1.25.9，还用区分Android和AndroidX吗？

### ISSUE THREAD

**Issue by sunchengjian** [Blankj/AndroidUtilCode#1084]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
要区分啊
