### ISSUE TITLE
红米4A 屏幕适配失效

### ISSUE THREAD

**Issue by spd-heshuip** [Blankj/AndroidUtilCode#1088]
## Describe the bug
红米4A 屏幕适配失效

![image](https://user-images.githubusercontent.com/8907462/69111215-ce05c900-0ab7-11ea-9219-0e8c865f3289.png)
这是Pixel XL 模拟器上预览的界面效果 分辨率为1440  * 2560 （411dp  *  711dp）

这是在红米4A 真机上的界面效果  分辨率为720*1280 屏幕5英寸
![image](https://user-images.githubusercontent.com/8907462/69111538-d4487500-0ab8-11ea-8dbe-04d75b522c82.png)

布局界面使用dp为单位
然后在BaseActivity中使用了屏幕适配
  @Override
    public Resources getResources() {
        return AdaptScreenUtils.adaptHeight(super.getResources(),2560);
    }

- The version of utilcode: 1.25.9
- The device: 红米4A
- The version of device: API23

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/issues/758
好好看文章

**Comment by spd-heshuip** [comment]
还是不太明白，不是直接适配高度就行了吗，为啥显示效果还是不行

**Comment by Blankj** [comment]
大哥，好好看文章，我什么时候教你适配高度就行了。。。这是百分比适配

**Comment by spd-heshuip** [comment]
明白了，感谢大佬
