### ISSUE TITLE
setClickSpan下划线

### ISSUE THREAD

**Issue by zcychinese** [Blankj/AndroidUtilCode#1089]
作者大大你好，我使用副文本添加setClickSpan点击事件时，会把这部分的文本添加下划线，有什么办法可以取消么？

**Comment by Blankj** [comment]
看 demo，重写下 updateDrawState
![image](https://user-images.githubusercontent.com/17978187/69115957-7a01e100-0ac5-11ea-9d6e-d97b85abc978.png)

**Comment by zcychinese** [comment]
非常感谢大佬，没有认真看demo。谢谢
