### ISSUE TITLE
ToastUtil的String.format问题

### ISSUE THREAD

**Issue by weibindev** [Blankj/AndroidUtilCode#1092]
我用ToastUtil.showShort()弹出网络请求捕获的异常，但是报错：java.util.UnknownFormatConversionException: Conversion = ':'
接口返回的结果：
```
{"code":500,"data":"","message":"Read time out executing GET ........signDate=2019-11-20%2011:05:34"}
```

**Comment by weibindev** [comment]
使用版本 com.blankj:utilcodex:1.25.2

**Comment by Blankj** [comment]
只能说明你传入的参数有问题，比如你的字符串里有 % 转义问题。

**Comment by Blankj** [comment]
试试 1.26.0 版本，已发布
