### ISSUE TITLE
ImageUtil只有getBitmap，可以添加getDrawalbe吗

### ISSUE THREAD

**Issue by dk568382923** [Blankj/AndroidUtilCode#1095]
如题，只是建议。
我在kotlin用extension添加方法也能达到效果就是了：）

**Comment by Blankj** [comment]
new BitmapDrawable() 不就行了么

**Comment by dk568382923** [comment]
你是说new BitmapDrawble(ImageUtil.getBitpmap(id)) 吗
我觉得是要加一个
public static Bitmap getDrawable(@DrawableRes final int resId)

现在只有
public static Bitmap getBitmap(@DrawableRes final int resId) {
        Drawable drawable = ContextCompat.getDrawable(Utils.getApp(), resId);
        Canvas canvas = new Canvas();
        Bitmap bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(),
                drawable.getIntrinsicHeight(),
                Bitmap.Config.ARGB_8888);
        canvas.setBitmap(bitmap);
        drawable.setBounds(0, 0, drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight());
        drawable.draw(canvas);
        return bitmap;
    }

**Comment by Blankj** [comment]
ResourceUtils 了解一下

**Comment by dk568382923** [comment]
翻了一下，与drawable相关的只有：
/**
     * Return the drawable identifier by name.
     *
     * @param name The name of drawable.
     * @return the drawable identifier by name
     */
    public static int getDrawableIdByName(String name) {
        return Utils.getApp().getResources().getIdentifier(name, "drawable", Utils.getApp().getPackageName());
    }

没有获取drawble的方法

**Comment by Blankj** [comment]
用的什么版本

**Comment by dk568382923** [comment]
1.25.9

**Comment by Blankj** [comment]
试试 1.25.10-alpha5

**Comment by dk568382923** [comment]
.gradle\caches\modules-2\files-2.1\com.blankj\utilcode\1.25.9\83236dfb3b7d67ef28fb37684d96636ad4e689bf\utilcode-1.25.9-sources.jar!\com\blankj\utilcode\util\ResourceUtils.java

**Comment by dk568382923** [comment]
看到getDrawable了(nice.jpg)
