### ISSUE TITLE
老哥新版本改了API没有做兼容处理啊

### ISSUE THREAD

**Issue by liyujiang-gzu** [Blankj/AndroidUtilCode#1096]
老哥新版本改了API没有做兼容处理啊，升级到新版本好几处调用直接报错，诸如：
```java
Bitmap bitmap = com.blankj.utilcode.util.ImageUtils.compressByQuality(srcBitmap, MAX_BYTE_SIZE)
```
变更为：
```java
byte[] bytes = com.blankj.utilcode.util.ImageUtils.compressByQuality(bitmap, MAX_BYTE_SIZE)
```
```java
public static boolean deleteDir(final File dir) {}
```
变更为：
```java
private static boolean deleteDir(final File dir) {}
```
按照[语义化版本规范](https://semver.org)，对于deleteDir()这种不兼容API的变更，过渡额做法是先小版本加上`deprecated`注解，几个版本后再真正的移除，同时发布大版本。
```java
    /**
     * @deprecated Use {#delete(File)} instead.
     */
    @Deprecated
    public static boolean deleteDir(final File dir) {}
```

**Comment by Blankj** [comment]
你的第一个问题，compressByQuality 就是需要返回 bytes 的，采样率降低返回的是 bytes 数减小，而如果返回 Bitmap 是把 bytes 转为了同等尺寸的 Bitmap，涉及到了图片的编码，这样其实 Bitmap 还是占原来大小的，所以其实以前是 bug，这次是修复了这个 bug，而不是改了接口。

文件的 API 变动，其实是不需要让你们关心到底是文件类型还是目录类型，交由我内部来处理，算是 API 的优化，这个全局 replace 一下应该很快的，没啥工作量。

如果涉及到接口的变动，一般都是很简单的变动，不会改的面目全非，而且一般也不会进行改动，改动的话就是之前设计的有问题才会进行改动，毕竟是为了打造更好的 AUC，希望你能理解。

**Comment by liyujiang-gzu** [comment]
支持老哥，老哥辛苦了，这个库为大家平时开发省时省力是有目共睹的
