### ISSUE TITLE
gradle版本太高5.1的  不兼容低版本as,导致androidstudio3.2版本无法用插件com.blankj:bus-gradle-plugin:2.3

### ISSUE THREAD

**Issue by zhishui1314** [Blankj/AndroidUtilCode#1097]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
解决了吗？我觉得不存在这个问题吧？
