### ISSUE TITLE
在androidx环境下，权限申请工具类无法正常弹窗

### ISSUE THREAD

**Issue by jiapengtao** [Blankj/AndroidUtilCode#1100]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
show me your code？

**Comment by zguop** [comment]
1.26.0                      shouldRequest.again(true);
不生效 了

**Comment by Blankj** [comment]
@zguop Demo 可以的呀？

**Comment by zguop** [comment]
是不是改动了什么 我将到59版本 又好了

**Comment by Blankj** [comment]
@zguop 你是在接口里展示弹窗不成功吗？

**Comment by zguop** [comment]
> @zguop 你是在接口里展示弹窗不成功吗？

启动页第一次讯问弹框 拒绝后 启动页有一个按钮 点击 再请发起权限请求，这个权限框就不会再出来了

**Comment by Blankj** [comment]
你是不在 OnRationaleListener.ShouldRequest 中显示提示再次请求的对话框？由于此时栈顶是 FragmentActivity，所以你的弹框不能是 AppCompat 系列的，需要是 Dialog 系列才行

**Comment by zguop** [comment]
![image](https://user-images.githubusercontent.com/16206793/70015308-ee557d80-15b7-11ea-992a-23ba0353678b.png)
我尝试了一下demo 是这样子写 不好使了

**Comment by WO555O** [comment]
我也遇到了，1.26.0版本的shouldRequest.again(true)有bug，改一下吧，拒绝后无法正常申请了

**Comment by Blankj** [comment]
不好意思，是我的问题，目前在 1.26.1-alpha0 版本已修复。

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布并修复
