### ISSUE TITLE
阴影工具类问题

### ISSUE THREAD

**Issue by wuconghui** [Blankj/AndroidUtilCode#1103]
## Describe the bug

- The version of utilcode: 1.26.0
- The device: vivoX6
- The version of device: API 22

## The code of bug

阴影四个角颜色加重

ShadowUtils.Config config = new ShadowUtils.Config();
        config.setShadowRadius(SizeUtils.dp2px(4f))
                .setShadowSize(SizeUtils.dp2px(6f))
                .setShadowColor(ResourceUtils.getColor(R.color.fuzhu_gray));
        ShadowUtils.apply(btnSettingExit, config);

![6627e0ad17f49993cdfec08954478ef](https://user-images.githubusercontent.com/20917354/70018661-cff47f80-15c1-11ea-979c-9b5d73d1e2ce.jpg)

**Comment by Blankj** [comment]
1.27.2 已修复  https://github.com/Blankj/AndroidUtilCode/issues/1213
