### ISSUE TITLE
1.26.0打包失败

### ISSUE THREAD

**Issue by Andy957** [Blankj/AndroidUtilCode#1105]
\build\intermediates\transforms\ajx\release\89.jar': zip file is empty

**Comment by Blankj** [comment]
你使用了什么？

**Comment by Andy957** [comment]
我好像也不知道，反正我用1.25.8没有问题，升级到1.26.0就不行了
你的意思是冲突了吗？

**Comment by Blankj** [comment]
解决了吗？新建项目使用 26 没问题的吧？

**Comment by Andy957** [comment]
还是不行，我不知道是哪里影响了，算了不管了，我用1.25.8吧，谢谢你了

**Comment by protectedMan** [comment]
我也出现这个问题了

**Comment by LeeUsun** [comment]
我也是遇到这个问题了，找了2小时，硬是解决不了，来看看issue，换了1.25.8能正常使用了

**Comment by Blankj** [comment]
是不是用了 gson

**Comment by protectedMan** [comment]
是用了GSON 2.8.5版本

**Comment by Blankj** [comment]
用的是 utilcodex 还是 utilcode

**Comment by protectedMan** [comment]
utilcodex

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布
