### ISSUE TITLE
ThreadUtils Task超时机制问题

### ISSUE THREAD

**Issue by 9kay** [Blankj/AndroidUtilCode#1107]
## Describe the bug
ThreadUtils.Task 同时设置timeout和execute delay，似乎超时会有问题。
超时Timer是以setTimeout()立即开始计时，而不是task真正run执行计时。
若timeout < delay，则会先执行timeout()，task无法启动run。
此时只能把setTimeout()移入doInBackground()内部，但这样写法创建task和配置task分别在不同线程了。
请问下超时计时在setTimeout立即启动的原因是什么？

- The version of utilcode: 1.25.9
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

**Comment by Blankj** [comment]
好问题，当时没有想到 timeout 使用在 delay 中，被你这么一说这么设计 timeout 有问题了。

**Comment by Blankj** [comment]
1.26.1-alpha3 已经解决啦，不过 schedule 这种定时循环执行的是不支持 timeout 的哦。

**Comment by 9kay** [comment]
> 1.26.1-alpha3 已经解决啦，不过 schedule 这种定时循环执行的是不支持 timeout 的哦。
OK 厉害了我的哥！
