### ISSUE TITLE
LanguageUtils.applyLanguage不起作用

### ISSUE THREAD

**Issue by arronvera** [Blankj/AndroidUtilCode#1116]
系统语言为英文，使用LanguageUtils.applyLanguage切换成其他语言没作用。
能提供一下还需要在其他地方使用吗？

**Comment by Blankj** [comment]
上完整代码。

**Comment by arronvera** [comment]
就直接在切换英语的时候调用     
  LanguageUtils.applyLanguage(Locale.US, "")
还需要在application或者baseactivity中配置吗？

**Comment by Blankj** [comment]
是没重启吗？还是重启没生效？

**Comment by hanxiaomeme** [comment]
> 是没重启吗？还是重启没生效？
我请问一下 我用的1.30,6版本,在切换语言之后,打开activity,但是我打开的时候会默认跳出一个dialog,我发现这个dialog 没有语言没有换成应用内语言,布局也没有更换过来.RTL => LTR
