### ISSUE TITLE
在混淆情况下，util类中会有异常现象出现！

### ISSUE THREAD

**Issue by AnandLin** [Blankj/AndroidUtilCode#1121]
在混淆情况下，util类中会有异常现象出现！

`java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode"`

经过查看源码，发现在Util中有使用到反射写法，虽然未使用此工具类，但是一运行就会程序就会崩溃。请问下这块AndroidUtilCode有没对应的混淆规则的！

- The version of utilcode:1.25.9
- The device: 努比亚z17mini
- The version of device: API 23

**Comment by Blankj** [comment]
MultiDex 开启了吗

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布，试试看
