### ISSUE TITLE
更新最新版后ImageUtils.view2Bitmap的问题

### ISSUE THREAD

**Issue by BreezeAndMoon** [Blankj/AndroidUtilCode#1122]
ImageUtils.view2Bitmap更新后新的写法生成出来的图显示是黑色的,而我需要的是白色背景的，应该是view没有设置背景色默认透明问题,但是项目中很多地方都有用到该方法,我不可能把相关的view都加个白色背景吧，所以只能回退旧版本了。。。再比如其他改动：FileUtils.deleteDir方法没了,统一放到了FileUtils.delete，compressByQuality返回值由bitmap改为了[]byte;更新一次要改很多地方，个人建议下能不能新增方法而不是轻易的去改旧的方法呢?

**Comment by Blankj** [comment]
参考这个哈 https://github.com/Blankj/AndroidUtilCode/issues/1096
