### ISSUE TITLE
获取存储卡路径，已经根据路径获取存储卡大小（望采纳）

### ISSUE THREAD

**Issue by lhc9102** [Blankj/AndroidUtilCode#1123]
```java
**
     * 通过反射调用获取内置存储和外置sd卡根路径(现有的方法不能获取外置的)
     *
     * @param mContext    上下文
     * @param is_removale 是否可移除，false返回内部存储路径，true返回外置SD卡路径
     * @return
     */
    public static String getStoragePath(Context mContext, boolean is_removale) {
        String path = "";
        //使用getSystemService(String)检索一个StorageManager用于访问系统存储功能。
        StorageManager mStorageManager = (StorageManager) mContext.getSystemService(Context.STORAGE_SERVICE);
        Class<?> storageVolumeClazz = null;
        try {
            storageVolumeClazz = Class.forName("android.os.storage.StorageVolume");
            Method getVolumeList = mStorageManager.getClass().getMethod("getVolumeList");
            Method getPath = storageVolumeClazz.getMethod("getPath");
            Method isRemovable = storageVolumeClazz.getMethod("isRemovable");
            Object result = getVolumeList.invoke(mStorageManager);

            for (int i = 0; i < Array.getLength(result); i++) {
                Object storageVolumeElement = Array.get(result, i);
                path = (String) getPath.invoke(storageVolumeElement);
                boolean removable = (Boolean) isRemovable.invoke(storageVolumeElement);
                if (is_removale == removable) {
                    return path;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return path;
    }

**
     * 判断外置内存卡是否挂载
     * 
     * @param context上下文
     * @param mountPoint 路径
     * @return
     */
    public static boolean checkMounted(Context context, String mountPoint) {
        if (mountPoint == null) {
            Log.d("SDRemount ", "mountPoint == null");
            return false;
        }
        StorageManager storageManager = (StorageManager) context
                .getSystemService(Context.STORAGE_SERVICE);
        try {
            Method getVolumeState = storageManager.getClass().getMethod(
                    "getVolumeState", String.class);
            String state = (String) getVolumeState.invoke(storageManager,
                    mountPoint);
            //Log.d("SDRemount ","SDCard path " + mountPoint +" and state " +state);
            StatFs statFs = new StatFs(mountPoint);
            long blockSize = statFs.getBlockSizeLong();
            long availableSize = statFs.getAvailableBlocksLong();
            long totalSize = statFs.getBlockCountLong();
            Log.d("SDRemount ", "SDCard path " + mountPoint + " and state " + state +
                    " total size " + totalSize * blockSize + " available size " + availableSize * blockSize);
            return Environment.MEDIA_MOUNTED.equals(state);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
**
     * 根据路径判断内存卡总大小
     * 
     * @param path 路径
     * @return
     */
    public static long getTotalSize(String path) {
        StatFs statFs = new StatFs(path);
        long blockSize = statFs.getBlockSizeLong();
        //long availableSize=statFs.getAvailableBlocksLong();
        long totalSize = statFs.getBlockCountLong();
        long total = blockSize * totalSize;
        Log.d("SDRemount ", "SDCard path " + path + " total size " + total);

        return total;
    }
**
     * 根据路径判断内存卡可用大小
     * 
     * @param path 路径
     * @return
     */
    public static long getAvailableSize(String path) {
        StatFs statFs = new StatFs(path);
        long blockSize = statFs.getBlockSizeLong();
        long availableSize = statFs.getAvailableBlocksLong();
        //long totalSize=statFs.getBlockCountLong();
        long total = blockSize * availableSize;
        Log.d("SDRemount ", "SDCard path " + path + " total size " + total);
        return total;
    }
```

**Comment by lhc9102** [comment]
/**
*
*监听外置内存卡插拔
*/

public static void registerSDCardStatusChangedListener(OnSDCardStatusChangedListener listener) {
        SDCardChangedReceiver.getInstance().registerListener(listener);
    }

    public static void unregisterSDCardStatusChangedListener(OnSDCardStatusChangedListener listener) {
        SDCardChangedReceiver.getInstance().unregisterListener(listener);
    }

    public static final class SDCardChangedReceiver extends BroadcastReceiver {

        private static SDCardChangedReceiver getInstance() {
            return SDCardChangedReceiver.LazyHolder.INSTANCE;
        }

        private Set<OnSDCardStatusChangedListener> mListeners = new HashSet<>();

        void registerListener(final OnSDCardStatusChangedListener listener) {
            if (listener == null) return;
            Utils.runOnUiThread(new Runnable() {
                @SuppressLint("MissingPermission")
                @Override
                public void run() {
                    int preSize = mListeners.size();
                    mListeners.add(listener);
                    if (preSize == 0 && mListeners.size() == 1) {
                        IntentFilter intentFilter = new IntentFilter();
                        intentFilter.addAction(Intent.ACTION_MEDIA_EJECT);
                        intentFilter.addAction(Intent.ACTION_MEDIA_MOUNTED);
                        intentFilter.addDataScheme("file");
                        Utils.getApp().registerReceiver(SDCardChangedReceiver.getInstance(), intentFilter);
                    }
                }
            });
        }

        void unregisterListener(final OnSDCardStatusChangedListener listener) {
            if (listener == null) return;
            Utils.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    int preSize = mListeners.size();
                    mListeners.remove(listener);
                    if (preSize == 1 && mListeners.size() == 0) {
                        Utils.getApp().unregisterReceiver(SDCardChangedReceiver.getInstance());
                    }
                }
            });
        }

        @SuppressLint("MissingPermission")
        @Override
        public void onReceive(Context context, Intent intent) {
            if (Intent.ACTION_MEDIA_EJECT.equals(intent.getAction())) {
                // 拔出
                Utils.runOnUiThreadDelayed(new Runnable() {
                    @Override
                    public void run() {
                        for (OnSDCardStatusChangedListener listener : mListeners) {
                            listener.onSDCardStatusChanged(false);
                        }
                    }
                }, 3000);
            } else if (Intent.ACTION_MEDIA_MOUNTED.equals(intent.getAction())) {
                // 插入
                Utils.runOnUiThreadDelayed(new Runnable() {
                    @Override
                    public void run() {
                        for (OnSDCardStatusChangedListener listener : mListeners) {
                            listener.onSDCardStatusChanged(true);
                        }
                    }
                }, 1000);
            }
        }

        private static class LazyHolder {
            private static final SDCardChangedReceiver INSTANCE = new SDCardChangedReceiver();
        }
    }

    public interface OnSDCardStatusChangedListener {
        void onSDCardStatusChanged(boolean ismounted);
    }

**Comment by lhc9102** [comment]
/**
*SD卡插拔监听
**/
public static void registerSDCardStatusChangedListener(OnSDCardStatusChangedListener listener) {
        SDCardChangedReceiver.getInstance().registerListener(listener);
    }

    public static void unregisterSDCardStatusChangedListener(OnSDCardStatusChangedListener listener) {
        SDCardChangedReceiver.getInstance().unregisterListener(listener);
    }

    public static final class SDCardChangedReceiver extends BroadcastReceiver {

        private static SDCardChangedReceiver getInstance() {
            return SDCardChangedReceiver.LazyHolder.INSTANCE;
        }

        private Set<OnSDCardStatusChangedListener> mListeners = new HashSet<>();

        void registerListener(final OnSDCardStatusChangedListener listener) {
            if (listener == null) return;
            Utils.runOnUiThread(new Runnable() {
                @SuppressLint("MissingPermission")
                @Override
                public void run() {
                    int preSize = mListeners.size();
                    mListeners.add(listener);
                    if (preSize == 0 && mListeners.size() == 1) {
                        IntentFilter intentFilter = new IntentFilter();
                        intentFilter.addAction(Intent.ACTION_MEDIA_EJECT);
                        intentFilter.addAction(Intent.ACTION_MEDIA_MOUNTED);
                        intentFilter.addDataScheme("file");
                        Utils.getApp().registerReceiver(SDCardChangedReceiver.getInstance(), intentFilter);
                    }
                }
            });
        }

        void unregisterListener(final OnSDCardStatusChangedListener listener) {
            if (listener == null) return;
            Utils.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    int preSize = mListeners.size();
                    mListeners.remove(listener);
                    if (preSize == 1 && mListeners.size() == 0) {
                        Utils.getApp().unregisterReceiver(SDCardChangedReceiver.getInstance());
                    }
                }
            });
        }

        @SuppressLint("MissingPermission")
        @Override
        public void onReceive(Context context, Intent intent) {
            if (Intent.ACTION_MEDIA_EJECT.equals(intent.getAction())) {
                // 拔出
                Utils.runOnUiThreadDelayed(new Runnable() {
                    @Override
                    public void run() {
                        for (OnSDCardStatusChangedListener listener : mListeners) {
                            listener.onSDCardStatusChanged(false);
                        }
                    }
                }, 3000);
            } else if (Intent.ACTION_MEDIA_MOUNTED.equals(intent.getAction())) {
                // 插入
                Utils.runOnUiThreadDelayed(new Runnable() {
                    @Override
                    public void run() {
                        for (OnSDCardStatusChangedListener listener : mListeners) {
                            listener.onSDCardStatusChanged(true);
                        }
                    }
                }, 1000);
            }
        }

        private static class LazyHolder {
            private static final SDCardChangedReceiver INSTANCE = new SDCardChangedReceiver();
        }
    }

    public interface OnSDCardStatusChangedListener {
        void onSDCardStatusChanged(boolean ismounted);
    }

**Comment by lhc9102** [comment]
getExternalStoragePath   博主的这个方法获取的不对

**Comment by Blankj** [comment]
你可以试试 getSDCardInfo 这个的
