### ISSUE TITLE
电池状态及充电的百分比（望采纳）

### ISSUE THREAD

**Issue by lhc9102** [Blankj/AndroidUtilCode#1124]
import android.annotation.SuppressLint;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.BatteryManager;

import java.util.HashSet;
import java.util.Set;

public class BatteryUtils {
    public static void registerBatteryStatusChangedListener(OnBatteryStatusChangedListener listener) {
        BatteryChangedReceiver.getInstance().registerListener(listener);
    }

    public static void unregisterBatteryStatusChangedListener(OnBatteryStatusChangedListener listener) {
        BatteryChangedReceiver.getInstance().unregisterListener(listener);
    }
    public static final class BatteryChangedReceiver extends BroadcastReceiver {

        private static BatteryChangedReceiver getInstance() {
            return BatteryChangedReceiver.LazyHolder.INSTANCE;
        }

        private Set<OnBatteryStatusChangedListener> mListeners = new HashSet<>();

        void registerListener(final OnBatteryStatusChangedListener listener) {
            if (listener == null) return;
            Utils.runOnUiThread(new Runnable() {
                @SuppressLint("MissingPermission")
                @Override
                public void run() {
                    int preSize = mListeners.size();
                    mListeners.add(listener);
                    if (preSize == 0 && mListeners.size() == 1) {
                        IntentFilter intentFilter = new IntentFilter();
                        intentFilter.addAction(Intent.ACTION_BATTERY_CHANGED);
                        Utils.getApp().registerReceiver(BatteryChangedReceiver.getInstance(), intentFilter);
                    }
                }
            });
        }

        void unregisterListener(final OnBatteryStatusChangedListener listener) {
            if (listener == null) return;
            Utils.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    int preSize = mListeners.size();
                    mListeners.remove(listener);
                    if (preSize == 1 && mListeners.size() == 0) {
                        Utils.getApp().unregisterReceiver(BatteryChangedReceiver.getInstance());
                    }
                }
            });
        }

        @SuppressLint("MissingPermission")
        @Override
        public void onReceive(Context context, final Intent intent) {
            if (Intent.ACTION_BATTERY_CHANGED.equals(intent.getAction())) {

                Utils.runOnUiThreadDelayed(new Runnable() {
                    @Override
                    public void run() {
                        int level = intent.getIntExtra("level", 0);
                        int status = intent.getIntExtra("status", BatteryManager.BATTERY_STATUS_UNKNOWN);
                        String stat = "";
                        switch (status) {
                            case BatteryManager.BATTERY_STATUS_DISCHARGING:
                                stat = "电池放电中";
                                break;
                            case BatteryManager.BATTERY_STATUS_CHARGING:
                                stat = "充电中";
                                break;
                            case BatteryManager.BATTERY_STATUS_NOT_CHARGING:
                                stat = "未充电";
                                break;
                            case BatteryManager.BATTERY_STATUS_FULL:
                                stat = "充电中，已充满";
                                break;
                            case BatteryManager.BATTERY_STATUS_UNKNOWN:
                                stat = "未知";
                                break;
                        }
                        for (OnBatteryStatusChangedListener listener : mListeners) {
                            listener.onBatteryStatusChanged(level + "%", stat);
                        }
                    }
                }, 500);
            }
        }

        private static class LazyHolder {
            private static final BatteryChangedReceiver INSTANCE = new BatteryChangedReceiver();
        }
    }

    public interface OnBatteryStatusChangedListener {
        void onBatteryStatusChanged(String BatteryLevel, String status);
    }

}

**Comment by Blankj** [comment]
BatteryUtils 放在 subutil 中了哈
