### ISSUE TITLE
获取网卡网关信息（望采纳）

### ISSUE THREAD

**Issue by lhc9102** [Blankj/AndroidUtilCode#1125]
/**
     * 根据adb shell命令获取网卡网关信息
     * @return
     */
    public static String getEthernetGateway() {
        BufferedReader bufferedReader = null;
        String result="";
        String str2 = "";
        String str3 = "ip route list table 0";
        Log.e("===",str3);
        Process exec;
        BufferedReader bufferedReader2 = null;
        try {
            exec = Runtime.getRuntime().exec(str3);
            try {
                bufferedReader2 = new BufferedReader(new InputStreamReader(exec.getInputStream()));
            } catch (Throwable th3) {
                if (bufferedReader != null) {
                    bufferedReader.close();
                }
                if (exec != null) {
                    exec.exitValue();
                }
            }
            try {
                str2 = bufferedReader2.readLine();
                if (str2 != null) {
                    str2= str2.trim();
                    String[] strings=str2.split("\\s+");
                    if (strings.length>3){
                        result= strings[2];
                    }
                }
                try {
                    bufferedReader2.close();
                } catch (IOException iOException222) {
                    iOException222.printStackTrace();
                }
                if (exec != null) {
                    try {
                        exec.exitValue();
                    } catch (Exception e5) {
                    }
                }
            } catch (IOException e6) {
                if (bufferedReader2 != null) {
                    bufferedReader2.close();
                }
                if (exec != null) {
                    exec.exitValue();
                }
                return result;
            }
        } catch (IOException e62) {
            bufferedReader2 = null;
            exec = null;
            if (bufferedReader2 != null) {
                try {
                    bufferedReader2.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (exec != null) {
                exec.exitValue();
            }
            return result;
        } catch (Throwable th4) {
            exec = null;
            if (bufferedReader != null) {
                try {
                    bufferedReader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            if (exec != null) {
                exec.exitValue();
            }
        }
        return result;
    }

**Comment by Blankj** [comment]
你这写的有点丑哈，网关这个不常用吧，看你是拿 shell 拿的，那就可以直接使用 ShellUtils 的哈。
