### ISSUE TITLE
AndroidUtilColde  Toast 问题

### ISSUE THREAD

**Issue by weichunyu123** [Blankj/AndroidUtilCode#1127]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by weichunyu123** [comment]
Utils.init(this);
ToastUtils.showShort(manufacturer);
现在只会弹出一个白色背景框，文字和内容无法弹出

**Comment by Blankj** [comment]
系统原生的呢？

**Comment by weichunyu123** [comment]
是的呢 2389756728 邮箱：2389756728@qq.com 签名由 网易邮箱大师 定制 在2020年01月02日 15:50，布兰柯基 写道： 系统原生的呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Blankj** [comment]
我说系统原生的正常吗？

**Comment by weichunyu123** [comment]
正常的 后来发现是安卓10以上不行 我更新一下最新依赖就可以了 2389756728 邮箱：2389756728@qq.com 签名由 网易邮箱大师 定制 在2020年01月02日 19:47，布兰柯基 写道： 我说系统原生的正常吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Blankj** [comment]
那就是没问题了哦？

**Comment by weichunyu123** [comment]
是的 2389756728 邮箱：2389756728@qq.com 签名由 网易邮箱大师 定制 在2020年01月02日 19:56，布兰柯基 写道： 那就是没问题了哦？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
