### ISSUE TITLE
华为手机设置全屏，状态栏就变黑色

### ISSUE THREAD

**Issue by qianshengta** [Blankj/AndroidUtilCode#1128]
华为P30 Pro
Android 9.0
Utilcode 1.25.9
问题：手机设置全屏的时候，顶部状态栏就变成一片黑色什么都看不见，去掉全屏就正常的

**Comment by qianshengta** [comment]
经过几次测试发现，只要是刘海屏或者水滴屏的手机，设置全屏或者移除顶端状态栏，刘海/水滴那部分就是之前状态栏的那部分就会变黑。可以在手机设置中手动设置躺它显示出来，以华为为例：
在设置->显示-> 更多显示设置->屏幕顶端显示->应用自定义->将app从自动匹配改为显示顶端区域。
就能将黑色部分显示出来了
这个库中的设置全屏是不是就是将状态栏去掉？？？

**Comment by Blankj** [comment]
正常手机应该就是正常全屏，刘海水滴需要全屏貌似需要自己配置是否要现实到刘海区，默认应该就是不显示到刘海区的。
