### ISSUE TITLE
SPUtils.java  貌似有问题,我在用xCrash的时候取出来数据不对

### ISSUE THREAD

**Issue by zjianflys** [Blankj/AndroidUtilCode#1129]
`        ICrashCallback iCrashCallback = (logPath, emergency) -> {
//            SPUtils.getInstance(SPConstant.ERROR_FLAG).put(SPConstant.SP_LOGPATH, logPath);
            SPManager.getInstance().put(SPConstant.SP_LOGPATH, logPath);
            LogUtils.i("logPath:" + logPath);
            Intent intent = new Intent(getApplicationContext(), ErrorActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            ActivityUtils.startActivity(intent);
            android.os.Process.killProcess(android.os.Process.myPid());
            System.exit(0);
        };`
这是我写入的代码
` logPath =SPUtils.getInstance(SPConstant.ERROR_FLAG).getString(SPConstant.SP_LOGPATH);
LogUtils.i(logPath);`
获取代码
这个有时候获取得到 有时候还为空或是上一次的

**Comment by Blankj** [comment]
默认是 apply，这个是异步的，你要用同步的话就得用 commit，put 的时候 最后的参数 isCommit 传入 true。

**Comment by zjianflys** [comment]
ok  明白了 谢谢
