### ISSUE TITLE
checkBox用SpanUtils设置字体大小和颜色无效

### ISSUE THREAD

**Issue by MrDon94** [Blankj/AndroidUtilCode#1133]

**Comment by Blankj** [comment]
这说明你用你自己写的 spannableString 也不支持呀，又不是我的问题

**Comment by MrDon94** [comment]
自己写的 spannableString是支持的

**Comment by MrDon94** [comment]
> 这说明你用你自己写的 spannableString 也不支持呀，又不是我的问题

自己写的spannableString是支持的

**Comment by MrDon94** [comment]
方式用错了，不好意思
