### ISSUE TITLE
荣耀V20获取状态栏高度不正确

### ISSUE THREAD

**Issue by Cassie-7579** [Blankj/AndroidUtilCode#1134]
机型：华为荣耀V20（打孔屏）
系统：Android 10
BarUtils.getStatusBarHeight() 方法获取出来的高度是 9 ....
用的是新的方法：
 try {
     int result = 0;
     int resourceId = context.getResources().getIdentifier("status_bar_height", "dimen", "android");
     if (resourceId > 0) {
         result = context.getResources().getDimensionPixelSize(resourceId);
     }
     return result;
 } catch (Exception e) {
      e.printStackTrace();
 }
 return 0;

**Comment by Blankj** [comment]
是什么版本？

**Comment by Cassie-7579** [comment]
版本是:  1.25.9 
不好意思，我发现其实是因为加上了头像的屏幕适配 AndroidAutoSize 才出现获取不到的问题。正常情况下是可以获取到的。不过我也暂时没找到解决方法。

**Comment by Blankj** [comment]
resource 使用 Resources.getSystem() 即可

**Comment by lklklk2017** [comment]
Blankj 你好呀 我是个小白 刚工作不久  在GitHub上面看到你的开源贡献  觉得你超厉害  就是我的偶像 2020 新年快乐 向你学习

**Comment by Blankj** [comment]
@lklklk2017 加油哈，年轻潜力无限哦。

**Comment by Cassie-7579** [comment]
万分感谢，谢谢大佬哈

**Comment by Blankj** [comment]
@Cassie-7579 看看这个 https://github.com/Blankj/AndroidUtilCode/issues/1063，都是有问题的貌似

**Comment by Cassie-7579** [comment]
@Blankj 是的，感谢大佬
