### ISSUE TITLE
SpanUtils的create()方法调用多次,最后一个append会被添加多个

### ISSUE THREAD

**Issue by gzl003** [Blankj/AndroidUtilCode#1135]
![image](https://user-images.githubusercontent.com/9498945/71473705-247ec980-2813-11ea-9e2f-8355b3183916.png)

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布并修复该问题。
