### ISSUE TITLE
BarUtil setColor overlap app content

### ISSUE THREAD

**Issue by davidpladev** [Blankj/AndroidUtilCode#1138]
I am changing the color of the statusBar from code. The issue is that when I use BarUtils.setStatusBarColor (...), the content of my application appears below the status bar. I read days going crazy with this behavior and I find no solution. Any idea why that happens?
![image](https://user-images.githubusercontent.com/57840484/71610720-6edcaf00-2b61-11ea-9e1b-47f3a33762eb.png)

**Comment by Blankj** [comment]
U can find the file of `BarStatusActivityColor.kt` in my project. Just add a margin top can solve ur problem.
```java
BarUtils.setStatusBarColor(mBaseActivity, ColorUtils.getColor(R.color.colorPrimary));
BarUtils.addMarginTopEqualStatusBarHeight(titleBar);
```
