### ISSUE TITLE
UriUtils.uri2File(uri) miui里获取分享已安装应用文件失败

### ISSUE THREAD

**Issue by abcdisgreat** [Blankj/AndroidUtilCode#1140]
## Describe the bug

- The version of utilcode: 1.26.0
- The device: mi note 3
- The version of device: N

## The code of bug

```java
Uri uri = intent.getParcelableExtra(Intent.EXTRA_STREAM);

File file = UriUtils.uri2File(uri);
```
uri值"content://com.miui.home.fileprovider/root/data/app/com.eg.android.AlipayGphone-ybaLheuqMVFPbxOtSKgIVQ%3D%3D/base.apk"

**Comment by Blankj** [comment]
有相关的解决方案解决吗，这个我也不太清楚

**Comment by abcdisgreat** [comment]
@Blankj 你好，因为需求是要上传文件，所以这里我的解决办法是通过外部分享的uri获取文件流拷贝了一份到app私有目录下，使用新文件进行后续文件上传操作

**Comment by Blankj** [comment]
@abcdisgreat 试试 1.28.2 版本 https://github.com/Blankj/AndroidUtilCode/issues/1223，我这边也做了如果获取到为空则拷贝一份到 cache 下
