### ISSUE TITLE
使用 LanguageUtils 切换语言后，桌面上的应用名称不会随着改变，是正常的吗？

### ISSUE THREAD

**Issue by jhwsx** [Blankj/AndroidUtilCode#1143]
Blankj 老师，今天使用了 `LanguageUtils `来切换语言，发现在切换语言后，桌面上的应用名称没有随着改变。不知道，这是不是正常的？

**Comment by Blankj** [comment]
这个是 launcher 控制的，应该是跟随你系统语言走的。

**Comment by jhwsx** [comment]
好的，那我就放心了。怕测试找我。
