### ISSUE TITLE
关于权限设置问题，1.26版本的权限拒绝后不会再弹窗。

### ISSUE THREAD

**Issue by lchang70163** [Blankj/AndroidUtilCode#1144]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by cervy** [comment]
我查到是因为TransActivity自动销毁了，所以自己传了当前的activity进去

**Comment by Blankj** [comment]
我下版本会修复的哈，最近比较忙，没什么时间

**Comment by Blankj** [comment]
可以暂时用 1.26.1-alpha0 已修复。

**Comment by lchang70163** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"布兰柯基"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上6:24
收件人:&nbsp;"Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com&gt;;
抄送:&nbsp;"迷途"<739727720@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Blankj/AndroidUtilCode] 关于权限设置问题，1.26版本的权限拒绝后不会再弹窗。 (#1144)




可以暂时用 1.26.1-alpha0 已修复。
