### ISSUE TITLE
BarUtils.setNavBarLightMode(activity, true) 方法调用错了, 应该重载调用 setNavBarLightMode(window, true)

### ISSUE THREAD

**Issue by wp292519413** [Blankj/AndroidUtilCode#1146]
## Describe the bug

v1.26.0 的 BarUtils.setNavBarLightMode() 的重载写的有问题, 导致设置导航栏模式失效

- The version of utilcode:  1.26.0
- The device: nome
- The version of device:  none

## The code of bug
```java
BarUtils.setNavBarLightMode(activity, true);
```
## The stack of crash
none

## Screenshots
none

**Comment by Blankj** [comment]
感谢提醒，下版本修复。

**Comment by Blankj** [comment]
目前可以使用 1.26.1-alpha3 已修复
