### ISSUE TITLE
关于busUtils得问题

### ISSUE THREAD

**Issue by HelloAnyu** [Blankj/AndroidUtilCode#1148]
首先感谢大神提供工具类得使用，感谢！
我在使用busUtils这个工具类时，一个Activity在onCreate和onDestroy分别发送了一个bus。
但是这样导致了，onDestroy这个回调不是即使执行得，去掉onCreate中发送得bus就没有问题了，如果您看到，麻烦给点提示，谢谢

**Comment by Blankj** [comment]
首先提供下 bus 的版本，还有就是你描述的有点乱呀，一会说 onDestroy 发送了一个 bus，之后又说onDestroy 这个回调不执行，可以方便上下代码吗？

**Comment by HelloAnyu** [comment]
> 首先提供下bus的版本，还有就是你描述的有点乱呀，一会说onDestroy发送了一个bus，之后又说onDestroy这个可能不执行，可以方便上下代码吗？


[FacePayActivity.txt](https://github.com/Blankj/AndroidUtilCode/files/4028458/FacePayActivity.txt)

我得意思是initView和onDestroy分别发送了事件，但是页面finish得时候，会引起onDestroy不会立刻执行，需要等个4秒或5秒才会执行，但是去掉initView中得发送事件，就可以立即执行。

**Comment by HelloAnyu** [comment]
版本com.blankj:utilcodex:1.25.9

**Comment by HelloAnyu** [comment]
插件版本com.blankj:bus-gradle-plugin:2.0

**Comment by Blankj** [comment]
应该没问题的呀，你 post 的时候打日志看了吗，真正 post 应该立马就能收到的，你可以在 post 上下都打个日志看看。

**Comment by HelloAnyu** [comment]
感谢作者支持！busUtils不存在问题，我用eventbus也是这样，可能是我这边导致内存溢出了。onDestroy没有立刻执行
