### ISSUE TITLE
Some suggestions about your library

### ISSUE THREAD

**Issue by yangshulin2019** [Blankj/AndroidUtilCode#1149]
Hello, Blankj. I find some problem when I use your nice utils library:

1. Utils.getTopActivityByReflect is deprecated. When I check Android Source code of API 29. I find field 'mActivityList' is removed in class ActivityThread. So your method may be fix it.

2. BarUtils.getActionBarSize gets the height of ActionBar by getting dimension of '?android:attr/actionBarSize'. It is not correct on old Android devices. It is seems to be 48dp but not 56 dp on old Android devices when you use '?android:attr/actionBarSize'. But dimension '?attr/actionBarSize' keeps right. So you may use '?attr/actionBarSize' to get ActionBar size.

**Comment by Blankj** [comment]
The first problem I have fixed with version of 1.27.0. The second problem I don't know how to fix it.
