### ISSUE TITLE
1.24升1.26 关于FileUtils的建议

### ISSUE THREAD

**Issue by Shirahane-Suoh** [Blankj/AndroidUtilCode#1150]
升级后，项目大面积报错。
发现是FileUtils.copyFile参数多了个回调。而FileUtils.copy相当于原来的copyFile，
为什么这么设计？加新功能是改动原方法而不是新增方法？

**Comment by Blankj** [comment]
参考看这个 https://github.com/Blankj/AndroidUtilCode/issues/1096
