### ISSUE TITLE
Android 27 与 Android 28 关于versionCode的问题

### ISSUE THREAD

**Issue by prczhb** [Blankj/AndroidUtilCode#1152]
version implementation 'com.blankj:utilcode:1.25.9'

![image](https://user-images.githubusercontent.com/26354648/71959788-7e798900-322e-11ea-9740-afdf0a68dc2e.png)

![image](https://user-images.githubusercontent.com/26354648/71959817-8b967800-322e-11ea-9392-d707f69ec215.png)

![image](https://user-images.githubusercontent.com/26354648/71959830-95b87680-322e-11ea-880e-18910433360c.png)

如上图 Android27 与 Android28 关于versionCode的获取的改变,建议同步一下

**Comment by RookieApe** [comment]
为啥不直接使用 BuildConfig.VERSION_CODE 获取

**Comment by prczhb** [comment]
> 为啥不直接使用 BuildConfig.VERSION_CODE 获取

居然忘了BuildConfig这么个东西了😭.不过在lib里无法获取到主项目的BuildConfig,lib的BuildConfig只是lib的信息,不可用.所以在有些情况下还需要通过这个工具类在lib里获取到主项目的versionCode等等信息

不过话说回来我以为编辑器里的 android.defaultConfig.versionCode现在支持long类型的数了.刚又试了试,不可以. 原来我理解错源码关于getLongVersionCode的意思了😭

**Comment by Blankj** [comment]
@Deprecated 不代表获取不到吧，28 返回的不对了吗
