### ISSUE TITLE
clone的最新代码,运行直接崩溃!!!

### ISSUE THREAD

**Issue by lydlovezjr** [Blankj/AndroidUtilCode#1153]
<img width="712" alt="微信截图_20200109114848" src="https://user-images.githubusercontent.com/19246347/72036595-3f9f0e00-32d6-11ea-92a6-4880cf42ae9c.png">
<img width="806" alt="微信截图_20200109114858" src="https://user-images.githubusercontent.com/19246347/72036596-4037a480-32d6-11ea-8d83-b5afae46fb42.png">
<img width="894" alt="微信截图_20200109114909" src="https://user-images.githubusercontent.com/19246347/72036599-4168d180-32d6-11ea-8954-04f0b4012734.png">

**Comment by lydlovezjr** [comment]
小米8上没有问题

**Comment by MrDon94** [comment]
![image](https://user-images.githubusercontent.com/23396637/72326618-74520180-36ea-11ea-822e-8e426121a1c6.png)
我这里也遇到崩溃问题了

**Comment by Blankj** [comment]
```java
Class.forName("com.blankj.utildebug.DebugUtils");
```
这一行注视掉即可

**Comment by MrDon94** [comment]
> ```java
> Class.forName("com.blankj.utildebug.DebugUtils");
> ```

注释了好像没起作用，还是崩溃报错

**Comment by Blankj** [comment]
@MrDon94 同样的报错？

**Comment by MrDon94** [comment]
> @MrDon94 同样的报错？

是的

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布
