### ISSUE TITLE
AppUtils.isAppInstalled(String pkgName)抛出异常

### ISSUE THREAD

**Issue by ZapFIVE** [Blankj/AndroidUtilCode#1155]
### isAppInstalled方法当判断包名不存在时，抛出NameNotFoundException异常，原因是在isAppInstalled方法中
`public static boolean isAppInstalled(@NonNull final String pkgName) {
        PackageManager packageManager = Utils.getApp().getPackageManager();
        try {
            return packageManager.getApplicationInfo(pkgName, 0) != null;
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
            return false;
        }
    }`
在catch中建议去除e.printStackTrace();

**Comment by Blankj** [comment]
下版本会删掉

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布
