### ISSUE TITLE
无法打开APP

### ISSUE THREAD

**Issue by zmyqucai8** [Blankj/AndroidUtilCode#1159]
AppUtils.launchApp(pkgName);
在部分机型上无法打开APP 比如小米8 安卓10

**Comment by zmyqucai8** [comment]
另外一个问题请教：分身的APP怎么直接打开一个，而不是弹出框选择？

感谢！

**Comment by Blankj** [comment]
这么细的我就不清楚了，我也没碰到过这样的需求
