### ISSUE TITLE
【1.25.9升级到1.26.0后出现bug】重复多次调用PermissionUtils无法弹出dialog

### ISSUE THREAD

**Issue by huwencheng** [Blankj/AndroidUtilCode#1160]
在1.25.9版本时候重复多次调用  PermissionUtils.permission(permission) .rationale {it.again(true) }可以每次都弹出dialog，更新到1.26.0后，同样的方法就不管几次调用都只能弹出一次dialog了。

**Comment by Blankj** [comment]
看看这个 https://github.com/Blankj/AndroidUtilCode/issues/1144
