### ISSUE TITLE
小米8 setStatusBarCustom(View view)方法无效

### ISSUE THREAD

**Issue by xiaoyvyv** [Blankj/AndroidUtilCode#1162]
小米8 setStatusBarCustom(View view)方法无效

 View bar = LayoutInflater.from(activity).inflate(R.layout.view_state_bar, null);
 BarUtils.setStatusBarCustom(bar);

**Comment by Blankj** [comment]
view 是放在你 activity 或者 fragment 布局里的 view，可以看 demo
