### ISSUE TITLE
允许和拒绝权限后都没有走对应的回调

### ISSUE THREAD

**Issue by fengyuxiayin** [Blankj/AndroidUtilCode#1163]
PermissionUtils.permission(PermissionConstants.LOCATION).rationale(shouldRequest -> LogUtils.e("") ).callback(new PermissionUtils.FullCallback() {
                @Override
                public void onGranted(List<String> permissionsGranted) {
                    Toast.makeText(MainActivity.this, "授予权限", Toast.LENGTH_SHORT).show();
                }

                @Override
                public void onDenied(List<String> permissionsDeniedForever, List<String> permissionsDenied) {
                    Toast.makeText(MainActivity.this, "拒绝授予权限", Toast.LENGTH_SHORT).show();
                }
            }).request();
onGranted/onDenied回调都没有执行，想不明白...

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases
下载 demo 试试看
