### ISSUE TITLE
getUniqueDeviceId 同一台设备发现安装 id 不一样

### ISSUE THREAD

**Issue by lijialiang** [Blankj/AndroidUtilCode#1165]
同一台设备通过使用 `DeviceUtils.getUniqueDeviceId()` 获取设备的唯一标识号，一段时间下来发现跟最初拿到的不一样。

**Comment by Blankj** [comment]
你版本是多少，看代码不是下面这样的话升级一下
```java
public static String getUniqueDeviceId(String prefix) {
    if (udid == null) {
        synchronized (DeviceUtils.class) {
            if (udid == null) {
                final String id = Utils.getSpUtils4Utils().getString(KEY_UDID, null);
                if (id != null) {
                    udid = id;
                    return udid;
                }
                try {
                    final String androidId = getAndroidID();
                    if (!TextUtils.isEmpty(androidId)) {
                        return saveUdid(prefix + 2, androidId);
                    }
                } catch (Exception ignore) {/**/}
                return saveUdid(prefix + 9, "");
            }
        }
    }
    return udid;
}
```

**Comment by lijialiang** [comment]
我用的版本是 1.25.9，更新到最新最新 1.26.0 会跟上述代码一样。

但是获取到的唯一标识码，跟之前两个都不一样。

**Comment by lijialiang** [comment]
如：
229baf19447073bc3950f1aa88edbd59a 1.26.0 今天
1da602fcf41213ad68e704c657d1dbca7 1.25.9 今天
1e5a64dc674e33a4284082eb0d8af3350 1.25.9 2019-11-21

**Comment by Blankj** [comment]
2 开头的是 androidid 就不会变了，1 开头是 mac 地址，可以看注释，用最新版本就行。

**Comment by lijialiang** [comment]
那之前版本的数据怎么处理呢？

**Comment by Blankj** [comment]
之前版本应该都是存 sp 里了的，不卸载清数据都是不会变的。
如果你可以获取到老的 deviceId，那可以用 DeviceUtils.isSameDevice 来判断是否是同一 device，是的话那你可以把老的 deviceId 更新为现在的 deviceId 即可。
记得需要用 1.26.1-alpha2 版本哦，老的版本可能会有 bug。

**Comment by lijialiang** [comment]
主要是之前有一批用户已经通过旧版本的 `DeviceUtils.getUniqueDeviceId()` 上传了信息，现在卸载重装了无法在通过 一样的标识号去拉取过往的记录。T-T

**Comment by lijialiang** [comment]
请问会影响到 mac 地址 改变的因素主要有哪些？

**Comment by Blankj** [comment]
卸载重装那就没办法的，Android 10 很多 id 都变了也得变更。设备 id 本来就不是很靠谱的，还是需要以用户纬度来考虑，用户纬度下产生多个设备 id 这样才比较靠谱。
Android 10 的 mac 的地址就是不固定的了。

**Comment by Blankj** [comment]
除非设备是你们自己产的，有唯一 id，那可以这么搞。

**Comment by xushaun** [comment]
> 卸载重装那就没办法的，Android 10 很多 id 都变了也得变更。设备 id 本来就不是很靠谱的，还是需要以用户纬度来考虑，用户纬度下产生多个设备 id 这样才比较靠谱。
> Android 10 的 mac 的地址就是不固定的了。

版本1..25.9 
系统Android 10

调用getUniqueDeviceId 返回的是1开头的mac地址
卸载重新安装 使用4G网络  getUniqueDeviceId没变
卸载重新安装 使用WIif网络  getUniqueDeviceId没变

请问你说的Android 10 mac地址不固定是所有的Android 10 手机每次mac地址随机
还是说只是部分Android 10手机出现这个问题
