### ISSUE TITLE
How to get double IMEI?

### ISSUE THREAD

**Issue by AhmerAfzal1** [Blankj/AndroidUtilCode#1166]
How to get two IMEI using method of `PhoneUtils.getIMEI()` ?

**Comment by Blankj** [comment]
U can check it in the source code. U can't get it when Android SDK version greater than 29.

**Comment by AhmerAfzal1** [comment]
Is there anyway to get both IMEI using method of `PhoneUtils.getIMEI()` ?

**Comment by Blankj** [comment]
The method of PhoneUtils.getIMEI() cannot help you to get double IMEI.
