### ISSUE TITLE
为什么使用CacheDiskUtils后,第二天文件就清空了?

### ISSUE THREAD

**Issue by zzl313703419** [Blankj/AndroidUtilCode#1168]
CacheDiskStaticUtils.setDefaultCacheDiskUtils(CacheDiskUtils.getInstance("app"));
CacheDiskStaticUtils.put("userInfo", userBean);
设置以后 过一天信息全没了是怎么回事?
急!!!!!!!!!!!!!!!!!!!!!

**Comment by Blankj** [comment]
这跟手机 rom 有关系，有些手机 cache 里面的东西自己过段时间就会清除，你要是想长时间用，那就自定义用 file 的目录，不要用默认的 cache 目录。

**Comment by zzl313703419** [comment]
解决了 万分感谢
CacheDiskStaticUtils.setDefaultCacheDiskUtils(CacheDiskUtils.getInstance(new File(CommonConstant.getCacheDiskName())));
