### ISSUE TITLE
Unknown constant type [105] in constant pool error when building Release configuration of application that utilizes this library

### ISSUE THREAD

**Issue by c0state** [Blankj/AndroidUtilCode#117]
I'm getting the following error when building a "Release" configuration for my application:
<code>java.io.IOException: Can't read [<project_dir>/app/build/intermediates/transforms/proguard/release/jars/3/1f/main.jar] (Can't process class [com/blankj/utilcode/utils/PinyinUtils.class] (Unknown constant type [105] in constant pool))</code>

Does this mean that the .jar in bintray is corrupt?

**Comment by wrightakencom** [comment]
think 3 ijar_ )serie(correct)eine/injar>
<Open_Access_report l

**Comment by Blankj** [comment]
http://stackoverflow.com/questions/26729189/android-proguard-with-multidex-unknown-constant-type-100-in-constant-pool-fa

**Comment by c0state** [comment]
@Blankj I did see that post but I don't think it was my issue.
Also, reverting to version 1.3.4 worked fine.

**Comment by Blankj** [comment]
The PinyinUtils updated on version of 1.3.5.

**Comment by abeemukthees** [comment]
I'm also facing the same issue? how to resolve it ?

**Comment by kam520c** [comment]
@abeemukthees Do you occured this problem while signing the apk?

**Comment by abeemukthees** [comment]
@kam520c  yes

**Comment by kam520c** [comment]
@abeemukthees me too,and i still looking for the answer

**Comment by kam520c** [comment]
@abeemukthees 
Find build.gradle and set zipAlignEnabled false ,minifyEnabled false,it worked for me.
```java
buildTypes {
        release {
            zipAlignEnabled false
            minifyEnabled false
            ...
            }
        }
    }
```

**Comment by gshcherb** [comment]
Try to specify 
-optimizations !code/simplification/string
in your proguard config
