### ISSUE TITLE
手机号的正则表达式错误，中括号内不应该有逗号

### ISSUE THREAD

**Issue by Rays15** [Blankj/AndroidUtilCode#1181]
## 正则表达式错误

手机号的正则表达式错误，中括号内不应该有逗号，会导致输入的逗号是合法的。

- The version of utilcode: 1.26.0

## 错误代码

```java
public final class RegexConstants {
    public static final String REGEX_MOBILE_EXACT  = "^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(16[6])|(17[0,1,3,5-8])|(18[0-9])|(19[1,8,9]))\\d{8}$";
}
```

**Comment by Rays15** [comment]
![图片](https://user-images.githubusercontent.com/17613135/74920944-efa08480-5407-11ea-8626-ac3a8a47083b.png)

**Comment by Blankj** [comment]
好的，收到，下版本会修复

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布
