### ISSUE TITLE
PermissionUtils 的rationale 

### ISSUE THREAD

**Issue by charmeleon2** [Blankj/AndroidUtilCode#1183]
权限申请配置了rationale会出现如下问题：第一次申请权限正常，这时候如果我从设置里把对应权限从允许改成询问，重新打开app，此时不会出现申请权限的弹窗，而是会直接走到rationale方法里

**Comment by charmeleon2** [comment]
看了下在不勾选禁止后不再提示的情况下，权限依旧是属于询问状态。
但是从使用角度来讲，rationale这个应该是点了拒绝权限之后走的逻辑，不应该影响下次重新打开app后的请求逻辑。

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/issues/1144

**Comment by Blankj** [comment]
目前最新的是 1.26.1-alpha1

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布
