### ISSUE TITLE
FileUtils.isFileExists() 在安卓10的机子总是返回false，已经确保文件是存在的。

### ISSUE THREAD

**Issue by lan2000** [Blankj/AndroidUtilCode#1184]
## Describe the bug
在安卓10的机子上上，调用FileUtils.isFileExists()总是返回false。
 是否安卓10的适配问题，恳请大佬进行修复。
- The version of utilcode: v1.26.0

- The version of device: API29

## The code of bug

FileUtils.isFileExists()

**Comment by Wanchen7** [comment]
用华为p30 Pro  调试这个方法，在 `AssetFileDescriptor afd = cr.openAssetFileDescriptor(uri, "r");  ` 这行报 FileNotFoundException 。

**Comment by lan2000** [comment]
> 用华为p30 Pro 调试这个方法，在 `AssetFileDescriptor afd = cr.openAssetFileDescriptor(uri, "r"); ` 这行报 FileNotFoundException 。

我的也是，你有解决方法吗？

**Comment by mao19951015** [comment]
将compileSdkVersion改为28 以下，安卓版本最新版本不让用File类的api了

**Comment by lan2000** [comment]
只能是目标版本降低到28了，关于这个android q的文件读取文件，找了相关资料说得都不是很清楚啊，难下手。关键引用的第三方项目也没进行适配。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "江柯"<notifications@github.com&gt;; 
发送时间: 2020年2月26日(星期三) 下午2:40
收件人: "Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com&gt;; 
抄送: "若即若离若迷离"<122775467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Blankj/AndroidUtilCode] FileUtils.isFileExists() 在安卓10的机子总是返回false，已经确保文件是存在的。 (#1184)




将compileSdkVersion改为28 以下，安卓版本最新版本不让用File类的api了

**Comment by LucasXu01** [comment]
遇到同样的问题，恳请大佬进行修复，大佬辛苦！

**Comment by yxyaxng** [comment]
public static boolean isAndroidQFileExists(Context context, String path){
        AssetFileDescriptor afd = null;
        ContentResolver cr = context.getContentResolver();
        try {
            Uri uri = Uri.parse(path);
            afd = cr.openAssetFileDescriptor(uri, "r");
            if (afd == null) {
                return false;
            } else {
                close(afd);
            }
        } catch (FileNotFoundException e) {
            return false;
        }finally {
            close(afd);
        }
        return true;
}

**Comment by Blankj** [comment]
FileUtils#isFileExists() 已适配，Android 10 有问题可以转到 https://github.com/Blankj/AndroidUtilCode/issues/1211
