### ISSUE TITLE
AppUtils Demo权限弹窗问题

### ISSUE THREAD

**Issue by JankingWon** [Blankj/AndroidUtilCode#1185]
进入AppUtils Demo
弹出权限申请框，如果勾选拒绝后不再询问，并且拒绝
本来应该弹出一个引导去权限设置的页面的对话框，但这个对话框闪退

**Comment by Blankj** [comment]
1.26.0 的权限有点问题，1.26.1-aplha0 已经修复了 可以看 https://github.com/Blankj/AndroidUtilCode/issues/1144 ，最新版本是 1.26.1-aplha3

**Comment by JankingWon** [comment]
好的，谢谢
