### ISSUE TITLE
遇到了transformClassesWithDexBuilderForDebug

### ISSUE THREAD

**Issue by pipiqiu** [Blankj/AndroidUtilCode#1189]
error processing C:\Users\caiqi\.gradle\caches\transforms-1\files-1.1\gson-2.8.6.jar\2dba7dabfa7159f75c9dbe2189c4486f\jetified-gson-2.8.6.jar

以下是我的gradle配置
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.hz.hkrt.crm"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.2.0-alpha02'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta4'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0-alpha04'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0-alpha04'
    implementation 'com.github.ithedan:TextViewDrawable:v1.0'
    //导航栏
//    implementation 'com.flyco.tablayout:FlycoTabLayout_Lib:2.1.2@aar'
    //design控件
    implementation 'com.google.android.material:material:1.0.0'
    //常用工具类
    implementation 'com.blankj:utilcodex:1.26.0'
    //网络请求
    implementation 'com.squareup.retrofit2:retrofit:2.7.1'
    implementation 'com.squareup.retrofit2:converter-gson:2.7.1'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.10.0'

    implementation 'com.zhy:okhttputils:2.6.2'
//    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

试了很多方法还是没解决,麻烦大神帮忙看下,不胜感激

**Comment by Blankj** [comment]
应该是 gson 版本的问题，用 2.8.5 版本的 gson

**Comment by pipiqiu** [comment]
后来我剔除了gson依赖只剩 implementation 'com.squareup.retrofit2:converter-gson:2.3.0'这条依赖使用implementation 'com.blankj:utilcodex:1.26.0'还是报我上面提的错误

//常用工具类
    implementation 'com.blankj:utilcode:1.25.9'
    //    implementation 'com.blankj:utilcodex:1.26.0'
    //网络请求
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.4.0'

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/tag/1.27.0
1.27.0 版本已发布
