### ISSUE TITLE
APP来回切换语言混乱

### ISSUE THREAD

**Issue by zqlq4ever** [Blankj/AndroidUtilCode#1190]
第一次切换中文，一切正常，再切换为英文，界面就乱了，显示中英文随机组合
或者
第一次切换英文，一切正常，再切换为中文，界面就乱了，显示中英文随机组合
除非手动杀掉App，再重启，才会正常。

全部2出用到代码

第一处application的oncreate：
 Utils.init(context);

第二处是切换的时候：

![image](https://user-images.githubusercontent.com/37474811/75755162-0f6d6c00-5d69-11ea-9a23-cbef75980139.png)

**Comment by Blankj** [comment]
目前有解决吗，可以跟我 qq 或者 微信 联系

**Comment by zqlq4ever** [comment]
> 目前有解决吗，可以跟我 qq 或者 微信 联系
![QQ截图20200309110214](https://user-images.githubusercontent.com/37474811/76179321-7e2d4800-61f5-11ea-8a04-ef28c1953262.png)
我在你代码里加了强制重启App代码，目前这样解决的。但是感觉不是很好，App强制重启了一遍

**Comment by Blankj** [comment]
加我 qq 细聊吧，625不783482

**Comment by zqlq4ever** [comment]
> 目前有解决吗，可以跟我 qq 或者 微信 联系

已解决：问题找到了，项目里很多地方用的是静态常量，切换语言后，不会改变，所以需要重启App，我把所有静态常量去掉了，就正常了

**Comment by Blankj** [comment]
好的，看来不是我的问题哈

**Comment by zqlq4ever** [comment]
> 好的，看来不是我的问题哈，想找你确认的就是那些没变化的是什么东西。

嗯，是我项目里的问题。
public static final String AAA = context.getString(R.string.aaa);
有很多这样的常量，引用的地方很多，所以看起来全乱了
