### ISSUE TITLE
文本错误

### ISSUE THREAD

**Issue by aowoWolf** [Blankj/AndroidUtilCode#1191]
栏相关 -> BarUtils.java -> Demo
getStatusBarHeight                   : 获取状态栏高度（px）
setStatusBarVisibility               : 设置状态栏是否可见
isStatusBarVisible                   : 判断状态栏是否可见
setStatusBarLightMode                : **设置状态栏是否为浅色模式**
isStatusBarLightMode                 : **判断状态栏是否为浅色模式**
addMarginTopEqualStatusBarHeight     : 为 view 增加 MarginTop 为状态栏高度
subtractMarginTopEqualStatusBarHeight: 为 view 减少 MarginTop 为状态栏高度
setStatusBarColor                    : 设置状态栏颜色
setStatusBarColor4Drawer             : 为 DrawerLayout 设置状态栏颜色
transparentStatusBar                 : 透明状态栏
getActionBarHeight                   : 获取 ActionBar 高度
setNotificationBarVisibility         : 设置通知栏是否可见
getNavBarHeight                      : 获取导航栏高度
setNavBarVisibility                  : 设置导航栏是否可见
isNavBarVisible                      : 判断导航栏是否可见
setNavBarColor                       : 设置导航栏颜色
getNavBarColor                       : 获取导航栏颜色
isSupportNavBar                      : 判断是否支持导航栏
setNavBarLightMode                   : **设置状态栏是否为浅色模式**
isNavBarLightMode                    : **判断状态栏是否为浅色模式**

**Comment by Blankj** [comment]
已更正
