### ISSUE TITLE
SpanUtils 最大行数限制问题

### ISSUE THREAD

**Issue by zcychinese** [Blankj/AndroidUtilCode#1194]
作者大大你好，
我使用setSpans这个方法添加完一个圆角背景样式后，因为这个TextView设置最大显示2行，超出部分省略，导致后面append的文字直接换了一行。 这有什么方法可以避免这种情况么？

**Comment by zcychinese** [comment]
[http://m.qpic.cn/psc?/V140QMU01V3PEM/umnC*3EstktJA9fyqNwGf0ww567EYqyGqZcyH7VHo5sytIVdjj6mL4NR.hrp.EMuz.BTKEK*HQSL8cVOyJnj9g!!/b&bo=QQK0AAAAAAADB9U!&rf=viewer_4](url)

图片在这里

**Comment by tanranran** [comment]
推荐使用padding left解决
