### ISSUE TITLE
SpanUtils 在dialogFragment里面使用，设置文字颜色没有效果

### ISSUE THREAD

**Issue by zhjun2016** [Blankj/AndroidUtilCode#1196]
SpanUtils.with(stvAttention)
                .append(getString(R.string.account_rule_content_agree))
                .append("《用户协议》")
                .setForegroundColor(Color.parseColor("#00D4BF"))
                .setClickSpan(xieYiClickSpan)
                .append("与")
                .append("《隐私政策》")
                .setForegroundColor(Color.parseColor("#00D4BF"))
                .setClickSpan(yinsiClickSpan)
                .append("。")
                .create();
用户协议 设置的绿色，显示的是蓝色，代码放在activity里面显示正常。请问什么原因

**Comment by Blankj** [comment]
你的 xieYiClickSpan 中可以设置字体颜色的，没必要用 setForegroundColor
