### ISSUE TITLE
isAvailableByPing 假的？

### ISSUE THREAD

**Issue by Sabirjan** [Blankj/AndroidUtilCode#120]
看了里面的代码，修改了IP，不管设置什么样的IP 都返回SUCCESS

**Comment by Blankj** [comment]
那说明ping通了啊

**Comment by Sabirjan** [comment]
没有，随便写一个IP 测试，CMD命令行不通，但是这个方法返回true

**Comment by Blankj** [comment]
没道理啊，你设备断网的？

**Comment by Sabirjan** [comment]
你自己测试一下，然后说没道理也来得及....

**Comment by Blankj** [comment]
我早就测试过了的，今天试也是可以的，断网是false，有网是true

**Comment by jp1017** [comment]
@Sabirjan 测试正常的,,,

默认的这个ip哪里的？ @Blankj 我喜欢用阿里的223.5.5.5 :smile:

**Comment by Blankj** [comment]
@jp1017 百度的
