### ISSUE TITLE
Android 8.1 shutdown() compatibility problem

### ISSUE THREAD

**Issue by dtboy1995** [Blankj/AndroidUtilCode#1203]
An update: for newer Android version, in my case is Android 8.1, they changed the action name. See below:
```java
Intent i = new Intent("com.android.internal.intent.action.REQUEST_SHUTDOWN");
i.putExtra("android.intent.extra.KEY_CONFIRM", false);
i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
startActivity(i);
```

[Reference](https://stackoverflow.com/questions/24693682/turn-off-device-programmatically)

**Comment by Blankj** [comment]
说中文就行，我下版本修复

**Comment by nxnyk** [comment]
> 说中文就行，我下版本修复

哈哈哈，真实

**Comment by Blankj** [comment]
1.27.0 已发布
