### ISSUE TITLE
gson转换对象为json字符串时对特殊字符编码的问题

### ISSUE THREAD

**Issue by cloudmist** [Blankj/AndroidUtilCode#1204]
把对象转json字符串时，特殊符号会被转义，比如url中的=会变成unicode编码，然后看Gson类中
static final boolean DEFAULT_ESCAPE_HTML = true; 就是说gson默认会转义，所以需要把html转义
关闭GsonBuilder中提供了如下方法：

  /**
   * By default, Gson escapes HTML characters such as &lt; &gt; etc. Use this option to configure
   * Gson to pass-through HTML characters as is.
   *
   * @return a reference to this {@code GsonBuilder} object to fulfill the "Builder" pattern
   * @since 1.3
   */
  public GsonBuilder disableHtmlEscaping() {
    this.escapeHtmlChars = false;
    return this;
  }

然后修改一下就可以了，希望工具类中可以添加一下这个方法

![微信图片_20200323142229](https://user-images.githubusercontent.com/26298774/77288193-3f79b080-6d12-11ea-869e-5df4f50a560d.png)

**Comment by Blankj** [comment]
好的，下版本支持哈
