### ISSUE TITLE
Some potential NullPointerException bugs

### ISSUE THREAD

**Issue by JulyChen728** [Blankj/AndroidUtilCode#1206]
Hi all,
Our bug scanner has reported some NPE bugs.

1.The first one is at [ShellUtils.java#L139](https://github.com/Blankj/AndroidUtilCode/blob/master/buildSrc/src/main/groovy/ShellUtils.java#L139), since the parameter `process` is checked for whether being `not null` at [ShellUtils.java#L196](https://github.com/Blankj/AndroidUtilCode/blob/master/buildSrc/src/main/groovy/ShellUtils.java#L196), a NPE bug may take place when parameter `precess` invokes its method `getOutputStream()`. 

2.Familiar with the first one, the second one is at [HttpsUtil.java#L73](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/subutil/src/main/java/com/blankj/subutil/util/HttpsUtil.java#L73), and the parameter that could be `null` is `connection`.

3.The third one is at [FileIOUtils.java#L845](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/FileIOUtils.java#L845), since the parameter `fc` is checked for whether being `not null` at [FileIOUtils.java#L855](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/FileIOUtils.java#L855), a NPE bug may take place when the parameter `fc` invokes its method `size()`. Some familiar situations are at [FileIOUtils.java#L457](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/FileIOUtils.java#L457), [FileIOUtils.java#L378](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/FileIOUtils.java#L378) and [FileIOUtils.java#L885](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/FileIOUtils.java#L885).

4.The forth bug is at [ReflectUtils.java#L205](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L205). A possible call chain is [ReflectUtils.java#L205](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L205)=>[ReflectUtils.java#L204](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L204)=>[ReflectUtils.java#L240](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L240)=>[ReflectUtils.java#L229](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L229)=>[ReflectUtils.java#L246](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L246)=>[ReflectUtils.java#L408](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L408). Since the method `accessible()` may return `null`, a NPE bug may take place. Some familiar situations are at [ReflectUtils.java#L221](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L221) and [ReflectUtils.java#L230](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L230).

5.The fifth bug is at [ReflectUtils.java#L185](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L185) when the method `newInstance()` is invoked, since the method `accessible()` may return `null` at [ReflectUtils.java#L409](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/ReflectUtils.java#L409).

6.The sixth bug is at [ZipUtils.java#L194](https://github.com/Blankj/AndroidUtilCode/blob/master/plugin/api-gradle-plugin/src/main/java/com/blankj/api/util/ZipUtils.java#L194). A NPE bug may take place when the parameter `srcFile` invokes its method `getName()` since `srcFile` may be `null`. A possible call chain is [ZipUtils.java#L67](https://github.com/Blankj/AndroidUtilCode/blob/master/plugin/api-gradle-plugin/src/main/java/com/blankj/api/util/ZipUtils.java#L67)=>[ZipUtils.java#L441](https://github.com/Blankj/AndroidUtilCode/blob/master/plugin/api-gradle-plugin/src/main/java/com/blankj/api/util/ZipUtils.java#L441).

Thanks.

**Comment by Blankj** [comment]
I check those NPE bugs, and I think the code is safe.
