### ISSUE TITLE
报错u should init first

### ISSUE THREAD

**Issue by wimvogt** [Blankj/AndroidUtilCode#121]
但是我在自定义的application中已经调用过Utils.init(context)方法，也在xml中引用了该application，但是还是会报这个错误

**Comment by Blankj** [comment]
那就鬼了，要不在activity中？

**Comment by addappcn** [comment]
会不会加入先在Utils.init(context)方法 前调用了初始化crashutils的初始化造成的

**Comment by wimvogt** [comment]
activity中也试过，没有用，crashutils没有调用 ，在application中，我只有Utils.init(this)这一行代码

**Comment by addappcn** [comment]
clean 重新编译 我好像也遇到过  第二次就好了

**Comment by wimvogt** [comment]
试过了，卸载，clean，重装，sync，重装，都不行

**Comment by Blankj** [comment]
新建个项目呢，或者直接跑我这个的app现象呢

**Comment by wimvogt** [comment]
新建项目没试过，跑demo是可以的，我现在正在尝试把源码库导入后再试下

**Comment by wimvogt** [comment]
找出问题了，我新建的项目的targetSdkVersion都是24的，但是这个util库的targetSdkVersion需要25，否则就会报这个错误，改成25就可以了。
还有就是好像没有获取手机deviceId的方法，希望可以加下，这个还是比较常用的

**Comment by Blankj** [comment]
有啊，在Phone里的IMEI

**Comment by Blankj** [comment]
@jp1017 targetSdkVersion还会影响context？

**Comment by jp1017** [comment]
版本兼容问题吧，着实蛋疼

**Comment by Blankj** [comment]
@jp1017 难不成都需要改成targetSdkVersion为25才能用我的初始化？没道理吧

**Comment by jp1017** [comment]
这个库不指定咯，哈哈

**Comment by wimvogt** [comment]
呃，不好意思，搜getDeviceId了，看漏了，关于版本的问题，我这边就3个值和demo不一样
buildToolsVersion "24.0.3"
minSdkVersion 14
targetSdkVersion 24

**Comment by Blankj** [comment]
那我指定了，不可能就这个初始化不能用吧，其他工具类跟它无关的怎么都可以用

**Comment by Blankj** [comment]
@wimvogt 你把我那句targetSdkVersion 25去掉之后用呢

**Comment by wimvogt** [comment]
这是必须有的吧，不过你的demo改成24后好像没影响，正常运行
