### ISSUE TITLE
 PermissionUtils.permission().rationale UtilsTransActivity 

### ISSUE THREAD

**Issue by protectedMan** [Blankj/AndroidUtilCode#1212]
rationale 
![image](https://user-images.githubusercontent.com/17565737/78204433-14d6e700-74cc-11ea-8c9c-399ec505bec9.png)
升级到1.27.0  新增的UtilsTransActivity参数是什么作用，我原有的写法要不要做兼容。

**Comment by Blankj** [comment]
权限请求启动的 透明 Activity
