### ISSUE TITLE
[BUG] AdaptScreenUtils 错误日志

### ISSUE THREAD

**Issue by WarriorYu** [Blankj/AndroidUtilCode#1214]
## 描述 Bug

E/AdaptScreenUtils: getMetricsFromField: java.lang.ClassCastException: java.lang.Object cannot be cast to android.util.DisplayMetrics

简洁地描述下 Bug。

- AndroidUtilCode 的版本：1.27.1
- 出现 Bug 的设备型号：HUAWEI Mate 30 Pro 
- 设备的 Android 版本： Android 10

## 相关代码
没有堆栈信息，日志没有看到相关代码的调用

从报错可以看出是在AdaptScreenUtils类的这个方法里报的错
private static DisplayMetrics getMetricsFromField(final Resources resources, final Field field) {
        try {
            return (DisplayMetrics) field.get(resources);
        } catch (Exception e) {
            Log.e("AdaptScreenUtils", "getMetricsFromField: " + e);
            return null;
        }
    }

**Comment by Blankj** [comment]
这个只是输出了日志吧，并没有 crash 吧？

**Comment by xuejiawang** [comment]
UtilsTransActivity页面被销毁了会抛出上面的异常，但是没有搞明白怎么会被销毁

**Comment by Achenglove** [comment]
@WarriorYu 这个问题最后解决了吗？
