### ISSUE TITLE
升级1.27.3后CleanUtils.cleanInternalCache()失效

### ISSUE THREAD

**Issue by huwencheng** [Blankj/AndroidUtilCode#1216]
之前如果清除缓存的话，我这边是先通过FileUtils.getSize(cacheDir)获取缓存文件大小，当确定清除缓存后就调用CleanUtils.cleanInternalCache()，然后再调用FileUtils.getSize(cacheDir)此时缓存被清除显示缓存大小为0，升级1.27.3后，调用CleanUtils.cleanInternalCache()后FileUtils.getSize(cacheDir)缓存值还是原来的，没被清除

**Comment by Blankj** [comment]
试试 1.27.4 版本
