### ISSUE TITLE
FileUtils.isFileExists() Android 10 判断 App-specific 文件是否存在时，结果有误

### ISSUE THREAD

**Issue by lhhseraph** [Blankj/AndroidUtilCode#1217]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：
- 出现 Bug 的设备型号：
- 设备的 Android 版本：

## 相关代码
String ERROR_LOG_FILE = App.getInstance().getExternalCacheDir() + "/error.txt"

创建文件写入数据后
FileUtils.isFileExists(ERROR_LOG_FILE) 
结果始终为false

直接 使用FileUtils.isFileExists(FileUtils.getFileByPath(ERROR_LOG_FILE)) 
结果判断为true

因为是应用自身，App-specific  目录，期间未获取 WRITE_EXTERNAL_STORAGE

**Comment by Blankj** [comment]
试试 1.27.4 版本

**Comment by lhhseraph** [comment]
谢谢回复
升级后还是这样，判断的私有目录文件
[.(ErrorLog.java:310)UploadError] ERROR_LOG_FILE = /storage/emulated/0/Android/data/com.test/cache/error.txt
[.(ErrorLog.java:312)UploadError] FileUtils.isFileExists(FileUtils.getFileByPath(ERROR_LOG_FILE)) = true
[.(ErrorLog.java:314)UploadError] FileUtils.isFileExists(ERROR_LOG_FILE) = false
