### ISSUE TITLE
PermissionConstants增加权限

### ISSUE THREAD

**Issue by neabea** [Blankj/AndroidUtilCode#1218]
PermissionConstants 里面的权限不够，我想增加有什么方法嘛？必须得lib这个类重写吗

**Comment by Blankj** [comment]
直接往 permission 后加权限就行了

**Comment by Blankj** [comment]
再说为啥会有不够？android 新加权限了吗？

**Comment by neabea** [comment]
比如判断位置服务，可能是不是权限，这个相关的有支持嘛

**Comment by Blankj** [comment]
属于动态权限才需要请求的，不是动态权限为何需要请求？定位的请求权限不是已经有了么。

**Comment by neabea** [comment]
申请了动态位置权限，如果没开位置服务也是定位不了的，所以我还要判断位置服务开没开，我是想加这个

**Comment by Blankj** [comment]
这又不属于动态权限了，为何要加到这里来？

**Comment by neabea** [comment]
我开始以为位置服务也是动态权限，查了下通过setting可以查询
