### ISSUE TITLE
关于UriUtils 的建议

### ISSUE THREAD

**Issue by prczhb** [Blankj/AndroidUtilCode#1222]
## 描述需求

简洁地描述下需求。
1.该类只能uri和file的互转, 但是还有应用asset及raw 下的资源转uri的需求, 
比如播放音频的API, 里面的参数都是需要uri , 这里就用到了吧raw 或 asset下的资源转成uri ,再使用
建议加入此类的转换
2.部分三方文件浏览器 返回的uri, 有些无法识别, 比如万恶的qq浏览器,通过代码吊起QQ浏览器返回指定的文件uri, 它返回的uri 有些是系统本来就定义好的, 还有一些uri 是他自己的uri,如 
` content://com.tencent.mtt.fileprovider/QQBrowser/asdf.jpg`
然而这种uri ,uriutil工具类就无法解析了. 总是解析失败, 转换成的file 当然也为空.
建议加入此类的转换 扩大uriutil 的支持面

## 可借鉴的

如果有的话，可以给出一些参考文章、链接、代码
[https://www.jianshu.com/p/df60c12d27b6](url)
[https://github.com/DB-BOY/FileChoose/blob/master/app/src/main/java/cn/dbboy/filechoose/FileUtil.java](url)
[https://www.cnblogs.com/lee0oo0/articles/2557537.html](url)

## 请删除当前行及以下内容

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
1.27.6 已支持
