### ISSUE TITLE
FileUtils.isFileExists(FilePath) 判断有问题

### ISSUE THREAD

**Issue by pipspx** [Blankj/AndroidUtilCode#1230]
## FileUtils.isFileExists(path)判断有问题

文件实际存在，isFileExists()判断是False不存在,New File(path).exists()判断true存在是正确的

使用版本：com.blankj:utilcodex:1.26.0
手机：小米10 Pro Android 10

**Comment by Blankj** [comment]
有问题首先要考虑升级版本看是否能解决哈
