### ISSUE TITLE
希望GsonUtils 去掉非空注解

### ISSUE THREAD

**Issue by mctshen** [Blankj/AndroidUtilCode#1231]
## 描述需求

希望GsonUtils 去掉非空注解，gson里面没有加，希望保持原样，不然使用的时候要加很多非空判断

## 可借鉴的
public static <T> T fromJson(@NonNull final String json, @NonNull final Type type)
改回
public static <T> T fromJson(final String json, final Type type)

public static String toJson(@NonNull final Object object)
改回
public static String toJson(final Object object)

**Comment by Blankj** [comment]
GsonUtils.setGsonDelegate(urGson); 这样就可以代理我默认的 Gson，如果还有其他类型的，可以使用setGson(final String key, final Gson gson) 来设置你自己需要的 gson，通过 getGson(key) 来获取。

**Comment by mctshen** [comment]
上面的方案是可以避开这个问题。
只是我只用一个类型的时候，这样的GsonUtils.getGson().fromJson()的方式调用不够简洁

**Comment by Blankj** [comment]
你用了那么多不同的 gson，那我也没辙啊，每个人都不一样的需求，能用就行了，你有更好的方案那你可以提出来。

**Comment by mctshen** [comment]
GsonUtils.fromJson这样的话不是又回到了我最开始提问的非空注解问题了么……
因为业务里有时候json不需要保证他非空，需要非空判断也是转换出来的对象非空判断下就好了

**Comment by Blankj** [comment]
最新版本已经去掉注解了

**Comment by mctshen** [comment]
好的，谢谢
