### ISSUE TITLE
Tinker和utils的冲突（1.28.1）

### ISSUE THREAD

**Issue by Freedomhxb** [Blankj/AndroidUtilCode#1233]
## 描述需求

简洁地描述下需求。
原来一直使用的是1.24版本，昨天升级到1.28.1后发现app不能正常运行，经过研究，项目中使用了tinker，原来的1.24版本，utils的初始化是手动调用，而1.28版本是在UtilsFileProvider自动调用的。
utils的init方法会调用application的registerActivityLifecycleCallbacks，此时的application是tinkerApplication，在tinkerApplication的onCreate方法中会将"android.app.ActivityThread""android.app.LoadedApk"中的application替换为我自定义的myApplication，所以utils中的ActivityLifecycleCallback将不会调用，导致ActivityUtils中的方法出错。

## 可借鉴的

如果有的话，可以给出一些参考文章、链接、代码
[tinker](http://tinkerpatch.com/Docs/SDK)

**Comment by Blankj** [comment]
？？我 24 之前早就有 Provider 了，应该不是这个问题导致的吧。

**Comment by Freedomhxb** [comment]
> ？？我 24 之前早就有 Provider 了，应该不是这个问题导致的吧。

额，我更新了下问题，大佬看下

**Comment by Blankj** [comment]
那就是需要判断下 class 是吗？

**Comment by Freedomhxb** [comment]
> 那就是需要判断下 class 是吗？然后还是需要你自己 init 才行

1.24我自己调用init就正常了，而在1.28中，手动init不行，因为sApp有值会被返回

**Comment by Blankj** [comment]
所以我说需要判断下 class。

**Comment by Blankj** [comment]
你试下 1.28.3 吧
