### ISSUE TITLE
LanguageUtils.applyLanguage(locale)方法未生效

### ISSUE THREAD

**Issue by vi1zen** [Blankj/AndroidUtilCode#1234]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：1.27.5
- 出现 Bug 的设备型号：
- 设备的 Android 版本：

## 相关代码

```
LanguageUtils.applyLanguage(locale)
```

为什么LanguageUtils.applyLanguage(locale)方法会调用isAppliedLanguage()方法?这样的话会造成切换语言不生效的问题(例如中文切到英文，英文再切回中文)，去除掉就好了

## 截图

如果有的话请添加屏幕截图以帮助解释问题。

**Comment by Blankj** [comment]
最新版本已修复
