### ISSUE TITLE
Security Flaws raised in the AndroidUtilcode library 

### ISSUE THREAD

**Issue by Hemavathi-DM** [Blankj/AndroidUtilCode#1238]
## Hi Blankj team, 

We are using the Androidutilcode thirdparty library in our code and when the application is scanned for vulnerability, we found below issues, can you please help us in resolving these flaws.

1) com/.../util/AppUtils.java 
Log.d("AppUtils", "isAppRoot() called" + result.errorMsg);
2) com/.../util/NetworkUtils.java 97
 Log.d("NetworkUtils", "isAvailableByPing() called" + result.errorMsg);
3) com/.../util/NetworkUtils.java 100
Log.d("NetworkUtils", "isAvailableByPing() called" + result.successMsg);

### Recommendations
Avoid directly embedding user input in log files when possible. Sanitize untrusted data used to construct log entries by
using a safe logging mechanism such as the OWASP ESAPI Logger, which will automatically remove unexpected
carriage returns and line feeds and can be configured to use HTML entity encoding for non-alphanumeric data. Only
write custom blacklisting code when absolutely necessary. Always validate untrusted input to ensure that it conforms
to the expected format, using centralized data validation routines when possible.

4)  com/.../util/EncryptUtils.java 166
MessageDigest md = MessageDigest.getInstance("MD5");
5) com/.../util/FileUtils.java 925
MessageDigest md = MessageDigest.getInstance("MD5");

### Description
The use of a broken or risky cryptographic algorithm is an unnecessary risk that may result in the disclosure of
sensitive information.

6) com/.../util/ZipUtils.java 234

### Recommendations
Validate all untrusted input to ensure that it conforms to the expected format, using centralized data validation routines
when possible. When using black lists, be sure that the sanitizing routine performs a sufficient number of iterations to
remove all instances of disallowed characters.

7) com/.../util/LogUtils.java 316
### Recommendations
Configure the XML parser to disable external entity resolution.

- The version of AndroidUtilCode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Please delete the current line and the following.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
Try to update to the version of 1.28.4.

**Comment by Hemavathi-DM** [comment]
Hi Blankj team, 

Thank you for the quick response, can you please confirm me whether upgrading to 1.28.4 resolve the above mentioned security flaws.

Regards
Hemavathi DM

**Comment by Blankj** [comment]
If the latest version didn't work. I think u should set minifyEnabled true to solve the problem.

**Comment by Hemavathi-DM** [comment]
Hi Blankj team,
Enablind minifyEnabled to true is not accepted by veracode security team, Are there any plans of fixing above mentioned security issues.
