### ISSUE TITLE
IntentUtils 获取跳转的intent不应该默认添加isNewTask

### ISSUE THREAD

**Issue by LLQQHH** [Blankj/AndroidUtilCode#1239]
例如这个方法：getLaunchAppDetailsSettingsIntent
场景：
跳到设置，让用户去授权，客户返回app后，在onActivityResult重新判断客户有没有授权，做一些操作
bug:
因为你自动Intent.FLAG_ACTIVITY_NEW_TASK，导致onActivityResult无法获取回调，所以客户回到app界面就什么反应都没有!
建议：要吗去掉添加isNewTask，或者增加重载方法暴露boolean参数，表示是否要isNewTask这个flag！

**Comment by Blankj** [comment]
你试过 onActivityResult 会有结果吗，我记得我当时直接 start 就返回结果了？

**Comment by Blankj** [comment]
1.28.5 已支持
