### ISSUE TITLE
AppUtils.installApp(file); 的问题

### ISSUE THREAD

**Issue by Easy10010** [Blankj/AndroidUtilCode#1242]
## 描述 Bug

使用 com.blankj.utilcode.util.AppUtils#installApp(java.io.File) 传入apk文件的File对象，然后就空指针异常闪退。只有某个客户的手机发生这个问题，我自己的模拟器都没法重现
看不出来是哪里的问题导致的

- AndroidUtilCode 的版本：utilcode:1.23.7
- 出现 Bug 的设备型号：三星 SM N9600也就是三星NOTE9
- 设备的 Android 版本：Android 10,level 29

## 相关代码

AppUtils.installApp(file);

## 异常堆栈

# main(2)
java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
1 android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:584)
2 android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
3 android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
4 com.blankj.utilcode.util.AppUtils.getInstallAppIntent(AppUtils.java:975)
5 com.blankj.utilcode.util.AppUtils.installApp(AppUtils.java:84)
6 com.xxx.yyy.UpdateService$3.run(UpdateService.java:266)
7 android.app.Activity.runOnUiThread(Activity.java:6972)
8 com.xxx.yyy.UpdateService.installApp(UpdateService.java:214)
9 com.xxx.yyy.UpdateService.downloadApk(UpdateService.java:139)
10 com.xxx.yyy.UpdateService.access$100(UpdateService.java:46)
11 com.xxx.yyy.UpdateService$1$1.okClick(UpdateService.java:80)
12 com.weilai.framework.ui.DialogConfirm$3.onClick(DialogConfirm.java:79)
13 android.view.View.performClick(View.java:7870)
14 android.widget.TextView.performClick(TextView.java:14966)
15 android.view.View.performClickInternal(View.java:7839)
16 android.view.View.access$3600(View.java:886)
17 android.view.View$PerformClick.run(View.java:29363)
18 android.os.Handler.handleCallback(Handler.java:883)
19 android.os.Handler.dispatchMessage(Handler.java:100)
20 android.os.Looper.loop(Looper.java:237)
21 android.app.ActivityThread.main(ActivityThread.java:7811)
22 java.lang.reflect.Method.invoke(Native Method)
23 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
24 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

## 截图

无

**Comment by Blankj** [comment]
崩溃率是多少，应该很少吧？还有你的版本太老啦。

**Comment by guominfang** [comment]
@Easy10010 你解决了吗，我目前也发产生这个Bug，使用 1.29.0版本
![image](https://user-images.githubusercontent.com/24568042/134647263-15f0a2e3-ea46-41d8-9eeb-ec67f7ce71ae.png)
