### ISSUE TITLE
BarUtil 设置0透明度的颜色

### ISSUE THREAD

**Issue by zhangqifan1** [Blankj/AndroidUtilCode#1245]
版本  'com.blankj:utilcode:1.28.4'
        

        BarUtils.setStatusBarColor(this, getResources().getColor(R.color.white));//#FFFFFF
        BarUtils.setStatusBarColor(this, 0xFFFFFFFF);
        BarUtils.setStatusBarColor(this, 0x00FFFFFF);
        BarUtils.setStatusBarColor(this, getResources().getColor(R.color.white_0));//00FFFFFF
        BarUtils.setStatusBarColor(this, getResources().getColor(R.color.white_f));//#FFFFFFFF

我试了这几种都没有纯色的效果,需要怎么写呢?

**Comment by Blankj** [comment]
玩一玩我的 demo 就知道了

**Comment by zhangqifan1** [comment]
我补一下...手机型号小米9
![图片](https://user-images.githubusercontent.com/29973474/82414052-06a74f00-9aa9-11ea-9199-70b6e127ddee.png)

**Comment by zhangqifan1** [comment]
![图片](https://user-images.githubusercontent.com/29973474/82414119-2474b400-9aa9-11ea-80ba-5a945a5107ae.png)

**Comment by zhangqifan1** [comment]
找到问题了,我写的位置不对,需要在setContentView()之后写!
