### ISSUE TITLE
Environment.getDownloadCacheDirectory()

### ISSUE THREAD

**Issue by isyikuan** [Blankj/AndroidUtilCode#1246]
Environment.getDownloadCacheDirectory() 路径测试时为 /data/cache
测试的设备 NEXUS 5 API 29

**Comment by Blankj** [comment]
有啥问题么？这就是系统 api 啊

**Comment by isyikuan** [comment]
方法注释是 /cache


 
---Original---

**Comment by Blankj** [comment]
这不同的 rom 不一样的，最终都是 cache 结尾，这没必要纠结吧，再说也没必要知道具体的目录吧。
