### ISSUE TITLE
关于NetworkUtils的问题

### ISSUE THREAD

**Issue by gaoyl87** [Blankj/AndroidUtilCode#1248]
## 描述需求

高版本网络监听

库中的网络监听还是用的动态广播，把 cm.registerNetworkCallback(new NetworkRequest.Builder().build(), networkCallback)高版本的api给注释了，请问是出于什么考虑？

**Comment by Blankj** [comment]
你看得还挺细哈，我没测试过呀，再说老的又不是不能用。

**Comment by gaoyl87** [comment]
最近在写网络状态监听，用新的registerNetworkCallback碰到一个问题。在wifi和蜂窝都连接的状态下，关闭wifi，但是蜂窝还是开着，api还是会回调onLost方法，我就想看看你这边有没有用新的api，然后发现注释掉了

**Comment by Blankj** [comment]
具体细节我没测试过，当时只是写了一下而已

**Comment by xuhaoyang** [comment]
> 最近在写网络状态监听，用新的registerNetworkCallback碰到一个问题。在wifi和蜂窝都连接的状态下，关闭wifi，但是蜂窝还是开着，api还是会回调onLost方法，我就想看看你这边有没有用新的api，然后发现注释掉了

会调用onLost 但是马上又会调用onAvailable。以NetworkCallback 判断网络是否可以用，会比较麻烦。

最近看了下官方文档，通过广播获得状态早就标记deprecated，https://developer.android.com/reference/android/net/NetworkInfo 上个版本也标记deprecated，希望 @Blankj 也可以封装一下。哈哈哈
