### ISSUE TITLE
com.blankj.utilcode.util.IntentUtil类，getInstallAppIntent()返回null问题

### ISSUE THREAD

**Issue by tydqcjj** [Blankj/AndroidUtilCode#1249]
![image](https://user-images.githubusercontent.com/21003314/83092006-09b8c580-a0cf-11ea-9c0c-1156927e99c0.png)
小问题，看图就明白。
版本implementation 'com.blankj:utilcodex:1.28.0'

**Comment by Blankj** [comment]
1.29.0 已发布
