### ISSUE TITLE
spanutils，forgroundColor和verticalAlign不能同时生效

### ISSUE THREAD

**Issue by conghuahuadan** [Blankj/AndroidUtilCode#1251]
你好，spanutils，forgroundColor和verticalAlign不能同时生效

![image](https://user-images.githubusercontent.com/20864280/83374411-25d5a300-a3fe-11ea-9983-0c3ac1327cd4.png)

**Comment by Blankj** [comment]
verticalAlign 这个 api 我 readme 并没有写，是有问题的存在，这个因为继承的是 ReplacementSpan，设置了之后样式会被覆盖掉，太复杂的 span 的话还是不推荐都用 span

**Comment by RunRunAllen** [comment]
这个问题 有处理么？

**Comment by weizhizhu** [comment]
有规避方法吗

**Comment by W-quan** [comment]
@weizhizhu 我直接在VerticalAlignSpan的draw() 里 paint.setColor()

**Comment by nchuloukh** [comment]
> @weizhizhu 我直接在VerticalAlignSpan的draw() 里 paint.setColor()

这个暴力方法确实好用
