### ISSUE TITLE
1.29.0版本中 ClickUtils.OnMultiClickListener onBeforeTriggerClick()中ToastUtils.showShort()不显示   

### ISSUE THREAD

**Issue by Jasperben** [Blankj/AndroidUtilCode#1252]
utilcodex:1.29.0版本中 ClickUtils.OnMultiClickListener onBeforeTriggerClick()中ToastUtils.showShort()不显示   
utilcodex:1.28.4版本没问题

- AndroidUtilCode 的版本： utilcodex:1.29.0
- 出现 Bug 的设备型号：
- 设备的 Android 版本：API29

## 相关代码

ClickUtils.OnMultiClickListener onBeforeTriggerClick()中进行ToastUtils.showShort()

**Comment by Blankj** [comment]
正常调用 ToastUtils.showShort() 呢

**Comment by Jasperben** [comment]
正常调用 ToastUtils.showShort() 可以     貌似还是ToastUtils得问题

**Comment by mao19951015** [comment]
仅仅是ToastUtils.showShort()不显示，还是其它代码都不执行？本职都是方法调用，没理由是ToastUtils的问题啊？ @Jasperben

**Comment by open9527** [comment]
小米note 4x android7.0 也是不显示,地下有个系统报错:W/WindowManager: Attempted to add a toast window with bad token null.  Aborting.

**Comment by open9527** [comment]
我在app权限中开启了悬浮窗权限ToastUtils.showShort()  就不能显示了,关闭这个权限就可以了

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
