### ISSUE TITLE
可以新增一个判断当前设备是否支持深色(暗黑)模式的函数

### ISSUE THREAD

**Issue by yibaimishenlan** [Blankj/AndroidUtilCode#1253]
## 是否可以新增一个 判断当前设备是否支持深色模式的方法函数？

可根据改函数方法处理一些 UI 需求

**Comment by Blankj** [comment]
上代码？

**Comment by yibaimishenlan** [comment]
惭愧， 我不会啊，更没有代码了[囧😶]。 这个需求是我在看微信的时候  发现微信做了判断的。微信-我的-设置-通用 中 “深色模式” item 会根据当前设备是否支持深色模式来设置显示和隐藏。

**Comment by Blankj** [comment]
你说的深色模式是哪里深色？状态栏还是什么？
