### ISSUE TITLE
BusUtils: The bus of tag <updateSwitch> is not exists.

### ISSUE THREAD

**Issue by liqiangCoding** [Blankj/AndroidUtilCode#1254]
报错误BusUtils: The bus of tag <updateSwitch> is not exists.

接受的函数
A界面 @BusUtils.Bus(tag = "updateSwitch")
    public void onEventMassage() {
}
B界面 BusUtils.post("updateSwitch");

**Comment by Blankj** [comment]
bus 插件依赖了么

**Comment by liqiangCoding** [comment]
我是直接用的AndroidCodeUtils工具没有单独依赖




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoxiaohaozai"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 晚上6:58
收件人: "Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com&gt;; 
抄送: "李强"<446528285@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Blankj/AndroidUtilCode] BusUtils: The bus of tag <updateSwitch&gt; is not exists. (#1254)





 
bus 插件依赖了么

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/tree/master/plugin/bus-gradle-plugin
