### ISSUE TITLE
建议PermissionUtils类的isGranted方法支持PermissionConstants作为参数

### ISSUE THREAD

**Issue by zjhcode** [Blankj/AndroidUtilCode#1256]
## 描述需求

PermissionUtils的permission方法是支持PermissionConstants作为参数的。
一般来说会认为isGranted方法也是支持的，容易造成错误的使用。
事实上我是发现判断出现问题，看了源码才知道是不支持的。
建议isGranted方法支持PermissionConstants作为参数。

**Comment by Blankj** [comment]
下版本支持吧

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
