### ISSUE TITLE
华为9.0、10.0系统，安全键盘下toast无法正常提示

### ISSUE THREAD

**Issue by buhuiming** [Blankj/AndroidUtilCode#1257]
## 描述 Bug

华为9.0、10.0系统，安全键盘下toast无法正常提示

**Comment by Blankj** [comment]
调用系统 toast 表现呢？

**Comment by buhuiming** [comment]
1、toast在下方显示，会被安全键盘挡住看不到。
2、改成toast在上方显示，表象：登录失败后输入框获取到焦点安全键盘弹出，同时toast提示失败的信息，但是toast刚出现，安全键盘弹出的时候toast就瞬间被隐藏了。

**Comment by Blankj** [comment]
@buhuiming 我问的是系统 toast 的表现是怎么样的，你回答的是系统 toast 吗？

**Comment by buhuiming** [comment]
系统toast就是出现以上描述问题，用了你的库的toast也是一样的

**Comment by Blankj** [comment]
那就不是我的问题了哈，我也解决不了的
