### ISSUE TITLE
ServiceUtils. startForegroundService

### ISSUE THREAD

**Issue by Jasperben** [Blankj/AndroidUtilCode#1258]
private void startService(Class<?> cls) {
        try {
            Intent intent = new Intent(Utils.getApp(), cls);
            intent.setFlags(Intent.FLAG_INCLUDE_STOPPED_PACKAGES);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                Utils.getApp().startForegroundService(intent);
            } else {
                Utils.getApp().startService(intent);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

**Comment by Blankj** [comment]
说清楚点？？

**Comment by Liberations** [comment]
8.0以上启动服务会报错。必须开启前台服务

**Comment by Blankj** [comment]
新版本 1.30.0 已发布

**Comment by xmlxin** [comment]
也遇到这个问题了，1.29.0版本没有问题，更新到1.30.0出现这个问题

**Comment by Jasperben** [comment]
> 也遇到这个问题了，1.29.0版本没有问题，更新到1.30.0出现这个问题

这是你service写的有问题
