### ISSUE TITLE
getMeid返回值错误

### ISSUE THREAD

**Issue by zou-xian-liang** [Blankj/AndroidUtilCode#1259]
## 描述 Bug

PhoneUtils.getMEID()方法获取的MEID与设备的实际值不一致；
获取到的是IMEI2的值

- AndroidUtilCode 的版本：utilcodex:1.28.6
- 出现 Bug 的设备型号：oppoA83
- 设备的 Android 版本：7.1.1

## 相关代码
PhoneUtils.getMEID()
获取到的meid与通过拨号盘的*#06#获取的imei2一致

> 我代码逻辑是只返回小的那个，并不是返回 1 还是 2

我的意思是获取到的MEID与真实的值不一样

**Comment by Blankj** [comment]
我代码逻辑是只返回小的那个，并不是返回 1 还是 2

**Comment by zou-xian-liang** [comment]
PhoneUtils.getMEID()获取的值是错的 @Blankj

**Comment by Blankj** [comment]
返回了啥

**Comment by zou-xian-liang** [comment]
@Blankj 
获取到的是IMEI2的值
AndroidUtilCode 的版本：utilcodex:1.28.6
出现 Bug 的设备型号：oppoA83
设备的 Android 版本：7.1.1

**Comment by Blankj** [comment]
我只返回小的那个而已，没说一定返回1，具体你要那么细的话自己写一个吧。

**Comment by zou-xian-liang** [comment]
我自己需求处理了，我只是提出我遇到的问题，帮助项目改进没别的意思。。。
我通过拨号键盘获取的meid、imei1、imei2是三个不同的值
然后通过PhoneUtils.getMEID()获取到的并不是meid值，是不是机型兼容有问题。
但是测试的小米8还有魅族MX6都是正确的

**Comment by Blankj** [comment]
这个同设备的不同手机表现也可能不一样吧，你有代码那可以放上来参考，我这边会放进去的。不过高版本 imei 都是没有的了。
