### ISSUE TITLE
BusUtils crash

### ISSUE THREAD

**Issue by mdtuyen** [Blankj/AndroidUtilCode#1261]
- The version of AndroidUtilCode: 1.29.0
- The device:  Xiaomi Redmi 4A
- The version of device: 7.1.2
I post a event from activity to Service and see crash
`BusUtils.post(Event.RequestVideoPlaybackStateAndDataMessage);
`
> 
> Caused by: java.lang.IllegalArgumentException: Wrong number of arguments; expected 1, got 0
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.blankj.utilcode.util.BusUtils.realInvokeMethod(BusUtils.java:279)
>         at com.blankj.utilcode.util.BusUtils.access$100(BusUtils.java:29)
>         at com.blankj.utilcode.util.BusUtils$1.run(BusUtils.java:236)
>         at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(ThreadUtils.java:70)
>         at com.blankj.utilcode.util.BusUtils.invokeMethod(BusUtils.java:241)
>         at com.blankj.utilcode.util.BusUtils.invokeBus(BusUtils.java:191)
>         at com.blankj.utilcode.util.BusUtils.postInner(BusUtils.java:179)
>         at com.blankj.utilcode.util.BusUtils.postInner(BusUtils.java:169)
>         at com.blankj.utilcode.util.BusUtils.post(BusUtils.java:80)
>         at com.blankj.utilcode.util.BusUtils.post(BusUtils.java:76)

**Comment by Blankj** [comment]
你 post 的参数不对吧

**Comment by mdtuyen** [comment]
Sorry, I convert from eventbus to your lib. There are some difference between two lib
