### ISSUE TITLE
1.2.9demo apk跑起来，locationutil页面 值都为unknown

### ISSUE THREAD

**Issue by dawsonjiang** [Blankj/AndroidUtilCode#1267]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本： utilcode:1.29.0
- 出现 Bug 的设备型号：mi 9
- 设备的 Android 版本：api 29

1.29.0 demo apk跑起来，locationutil页面 值都为unknown
## 截图 
![image](https://user-images.githubusercontent.com/17867071/85968406-a258a300-b9f7-11ea-9aad-8ee6b3806b38.png)
权限、位置都是打开了的

**Comment by dawsonjiang** [comment]
![image](https://user-images.githubusercontent.com/17867071/85968437-b8666380-b9f7-11ea-849e-9011e98f0afe.png)

**Comment by dawsonjiang** [comment]
![Screenshot_2020-06-29-10-59-19-782_com blankj and](https://user-images.githubusercontent.com/17867071/85968551-f9f70e80-b9f7-11ea-938a-96fa9f27021c.jpg)

**Comment by Blankj** [comment]
自带的定位在某些手机上不支持的哈
