### ISSUE TITLE
SnackbarUtils 内存泄露

### ISSUE THREAD

**Issue by me-xg** [Blankj/AndroidUtilCode#1268]
SnackbarUtils 在demo里面快速点击多次，然后结束当前页面，就提示内存泄露了。

**Comment by me-xg** [comment]
更新到1.29发现还是存在内存泄露。

**Comment by Blankj** [comment]
support 的 bug，https://github.com/GC-Xi/SnackbarBug

**Comment by me-xg** [comment]
> 支持的错误，https://github.com/GC-Xi/SnackbarBug

谢谢了。
