### ISSUE TITLE
CacheDiskUtils

### ISSUE THREAD

**Issue by dawnhope** [Blankj/AndroidUtilCode#1271]
请问下作者我这样获取的大小为什么总是0，cacheUtils文件夹里确定放入了图片文件CacheDiskUtils.getInstance("cacheUtils").getCacheSize()

**Comment by AndyRenJie** [comment]
同样追问，解决了么

**Comment by aheven** [comment]
@Blankj 发现一个问题，Cache文件夹在部分手机上运行系统手机管家清理内存的时候会删除Cache文件夹。所以存储的东西会丢失

**Comment by dawnhope** [comment]
> 同样追问，解决了么

一开始就搞错了，作者的CacheDiskUtils.getInstance("cacheUtils").getCacheSize()是内置目录缓存，就是路径/data/data/package/cache/cacheUtils这个。
