### ISSUE TITLE
屏幕适配的方法去掉了吗?

### ISSUE THREAD

**Issue by clbDream** [Blankj/AndroidUtilCode#1273]
adaptWidth : 适配宽度
adaptHeight: 适配高度
closeAdapt : 关闭适配（pt 等同于 dp）
pt2Px      : pt 转 px
px2Pt      : px 转 pt

屏幕适配的这个方法去掉了吗?我是用的   implementation 'com.blankj:utilcodex:1.29.0,找不到这些方法了

**Comment by Blankj** [comment]
没去掉啊，可以查看 https://github.com/Blankj/AndroidUtilCode/issues/758

**Comment by clbDream** [comment]
![image](https://user-images.githubusercontent.com/28987014/86785354-1d275b00-c095-11ea-81b5-faa892030bb6.png)
我使用适配宽度的方法,但是好像没效果啊
![image](https://user-images.githubusercontent.com/28987014/86785421-30d2c180-c095-11ea-9ec4-0584bc276d47.png)

**Comment by Blankj** [comment]
布局里写得 pt 吗

**Comment by clbDream** [comment]
必须使用PT吗

**Comment by Blankj** [comment]
仔细地好好看下文章吧，https://github.com/Blankj/AndroidUtilCode/issues/758
