### ISSUE TITLE
SpanUtils.setClickSpan()内存泄露

### ISSUE THREAD

**Issue by Sigasiiiiii** [Blankj/AndroidUtilCode#1277]
## 描述 Bug

SpanUtils.setClickSpan()会内存泄露。导致内存泄漏的原因：
https://stackoverflow.com/questions/28539216/android-textview-leaks-with-setmovementmethod

## 请删除当前行及以下内容

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
这就是系统 API 的问题了哈，不是我工具类导致的了。

**Comment by luoxiong94** [comment]
现在还有这个问题

**Comment by luoxiong94** [comment]
> 这就是系统 API 的问题了哈，不是我工具类导致的了。

大佬  ， 我不用SpanUtils就正常， 用了就会被检测到内存泄漏
