### ISSUE TITLE
BarUtils从1.25.8升级到androidx 1.29.0后兼容刘海屏出错

### ISSUE THREAD

**Issue by zeplee** [Blankj/AndroidUtilCode#1279]
1.25.8时获取状态栏高度getStatusBarHeight 是对的，升级后出错，认为是Resources.getSystem()的问题，希望排查一下

**Comment by Blankj** [comment]
参考老的 issue 吧  https://github.com/Blankj/AndroidUtilCode/issues/1063

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
