### ISSUE TITLE
可否降低下耦合性

### ISSUE THREAD

**Issue by Reginer** [Blankj/AndroidUtilCode#1280]
能否不把一个工具类依赖一堆

**Comment by Blankj** [comment]
能否不要单独拷一个类出去用？

**Comment by Reginer** [comment]
@Blankj   是的呀。
以前经常在这里拷贝工具类(ToastUtils   FileUtils .. )，放到工程里基本都能用。

刚看有些代码更新了，再一拷贝就很多错。

之前那样是有哪不好么

**Comment by Blankj** [comment]
换了设计方案，通过 UtilsBridge 来做桥接，以前那样因为存在代码的冗余，一个地方修复了，有的地方就漏了，不推荐拷贝，有的拷贝就会隐性存在问题。

**Comment by Reginer** [comment]
代码有重复，露改确实是个问题。

一个依赖全部放进去感觉又太多了 。

**Comment by Blankj** [comment]
项目都开启混淆的么？开了混淆就不用顾虑了呀

**Comment by Reginer** [comment]
有些没有，哈哈哈
