### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by z244370114** [Blankj/AndroidUtilCode#1282]
## 描述需求

我想了解一下 ActivityUtils这个管理类为什么要使用 该类 Application.ActivityLifecycleCallbacks 
一直没搞明白？楼主是否可以讲解一下吗？

**Comment by Blankj** [comment]
监听所有 activity 生命周期变化难道你有更好的方式吗？

**Comment by z244370114** [comment]
嗯嗯，我只是有这个疑问！想了解一下API具体还有哪些使用场景！没有别的意思
[https://mp.weixin.qq.com/s?__biz=MzAxMTI4MTkwNQ==&mid=2650822889&idx=1&sn=56d40fba0a7d4a62d75f98ca71a22ae9&chksm=80b78c77b7c005614fdc24fec9e8133e7ec583357aff5a7b5c66402b58ca7fe61db428c3d497&scene=38#wechat_redirect](url)

**Comment by Blankj** [comment]
前后台切换啊，获取栈顶 activity，工具类都有的，你好好看看

**Comment by z244370114** [comment]
嗯嗯，已经看了的！  我是在BaseActivity的onCreate里面去使用这个方法addActivityLifecycleCallbacks(this, Utils.ActivityLifecycleCallbacks()) —— onDestory 使用removeActivityLifecycleCallbacks(this)
