### ISSUE TITLE
AppUtils.isAppInstalled在部分OPPO手机上始终返回false

### ISSUE THREAD

**Issue by wankey** [Blankj/AndroidUtilCode#1284]
## 描述 Bug

使用AppUtils中的isAppInstalled方法判断指定包名是否已安装，在部分OPPO手机上始终返回false，其他品牌手机无此问题。

- AndroidUtilCode 的版本：com.blankj:utilcodex:1.29.0
- 出现 Bug 的设备型号：OPPO PBDM00
- 设备的 Android 版本：API 29

## 截图
<img width="723" alt="截屏2020-07-26 15 02 14" src="https://user-images.githubusercontent.com/1932886/88473548-2b102380-cf51-11ea-953b-de5adf83c88a.png">

**Comment by Blankj** [comment]
这应该就是 rom 的问题了，需要你自己兼容处理一下
