### ISSUE TITLE
调用截屏screenShot方法，apk崩溃

### ISSUE THREAD

**Issue by zhumeng1582** [Blankj/AndroidUtilCode#1286]
java.lang.IllegalArgumentException
cannot use a recycled source in createBitmap

com.blankj.utilcode.util.ScreenUtils.screenShot(ScreenUtils.java:268)

**Comment by mao19951015** [comment]
我调的没问题，希望能给给更多信息

**Comment by zhumeng1582** [comment]
![image](https://user-images.githubusercontent.com/5193944/89502392-84047500-d7f7-11ea-9c8e-387353df4e5b.png)

**Comment by mao19951015** [comment]
看不出来，我就这样调用的，一些OK，就一个文件读写权限
Bitmap bitmap = ScreenUtils.screenShot(activity);
String filePath = getShotFilePath();
ImageUtils.save(bitmap, filePath, Bitmap.CompressFormat.JPEG, true);
ToastUtils.showShort("截图已保存到" + filePath);

**Comment by zhumeng1582** [comment]
也不是必现

**Comment by zhumeng1582** [comment]
https://codeleading.com/article/45702509807/

**Comment by mao19951015** [comment]
看你是在获取权限后调用的，试试去掉动态权限获取再调用。实在不行你去看看ScreenUtils的源码，原理很简单，就是更具View的canvas生成位图

**Comment by Blankj** [comment]
这我无能为力

**Comment by hailongren** [comment]
> 可能知道原因了，下版本修复

大佬，啥原因呀？

**Comment by Blankj** [comment]
判空的时候再加个判断是否 recycled

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
