### ISSUE TITLE
SpanUtils.setClickSpan设置图片点击后背景颜色异常，如何设置

### ISSUE THREAD

**Issue by dawnhope** [Blankj/AndroidUtilCode#1293]
## Describe the bug

- The version of AndroidUtilCode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Please delete the current line and the following.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
textview highlight 的问题吧
