### ISSUE TITLE
172号段希望支持下

### ISSUE THREAD

**Issue by wlingf** [Blankj/AndroidUtilCode#1294]
## 描述需求

简洁地描述下需求。

## 可借鉴的

如果有的话，可以给出一些参考文章、链接、代码

## 请删除当前行及以下内容

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
先用 isMobileExact(final CharSequence input, List newSegments) 这个函数来支持新号段吧，下个版本我会新增

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
