### ISSUE TITLE
Android 11(Api 30+) 没有通知权限时ToastUtils将无法展示Toast

### ISSUE THREAD

**Issue by hanjx-dut** [Blankj/AndroidUtilCode#1295]
## 描述 Bug
Android 11 在没有通知权限的情况下，ToastUtils.showShort() 等方法没有展示Toast。

开发者文档：https://developer.android.google.cn/preview/features/toasts

**Comment by Blankj** [comment]
下版本修复

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
