### ISSUE TITLE
努比亚手机屏幕适配失效

### ISSUE THREAD

**Issue by wangzhanxian** [Blankj/AndroidUtilCode#1297]
努比亚手机屏幕适配失效

- AndroidUtilCode 的版本：1.25.7
- 出现 Bug 的设备型号：NX563J
- 设备的 Android 版本：7.1.1

**Comment by Blankj** [comment]
上个图看看？机器 debug 进去看下哪里出错了？我这边没设备测不了哈

**Comment by wangzhanxian** [comment]
> 上个图看看？机器 debug 进去看下哪里出错了？我这边没设备测不了哈
报错信息，因该是努比亚系统自定义了DisplayMetrics类：
AdaptScreenUtils: getMetricsFromField: java.lang.ClassCastException: java.lang.Object cannot be cast to android

**Comment by wangzhanxian** [comment]
class1.isAssignableFrom(class2) 判定此 Class1 对象所表示的类或接口与指定的 Class2 参数所表示的类或接口是否相同，或是否是其超类或超接口，这个地方if (field.getType().isAssignableFrom(DisplayMetrics.class))这么判断是不是会有问题呢

**Comment by wangzhanxian** [comment]
![image](https://user-images.githubusercontent.com/24356511/89756200-65aeba00-db14-11ea-95ce-6986a4d10e14.png)

**Comment by Blankj** [comment]
我这边云测试了下，好像没问题
![image](https://user-images.githubusercontent.com/17978187/89756953-7e1fd400-db16-11ea-890d-2727008b275c.png)
不过版本是 Android9 的

**Comment by Blankj** [comment]
可以参考 applyOtherDisplayMetrics 这个函数，看怎么能把他封装的真正值替换掉

**Comment by wangzhanxian** [comment]
我找到问题了，这个场景出现在横竖屏切换的时候，
![image](https://user-images.githubusercontent.com/24356511/89757643-68131300-db18-11ea-8fbb-08a67a0e61dd.png)
当第一次横竖屏切换正常，在切换就出现问题了，
![image](https://user-images.githubusercontent.com/24356511/89757705-9264d080-db18-11ea-8b0c-80960f84b7cf.png)
这个屏幕高度两个获取出来的值不一样，第一次是1920，第二次变成了1845，
![image](https://user-images.githubusercontent.com/24356511/89757770-c9d37d00-db18-11ea-9780-d0a84dea97a2.png)

**Comment by Blankj** [comment]
所以解决方案是？

**Comment by YuDongZhang** [comment]
不能识别限定符  , sb 努比亚
