### ISSUE TITLE
snackbar的问题

### ISSUE THREAD

**Issue by ruhaly** [Blankj/AndroidUtilCode#130]
我只要加了这个库，用snackbar就会报下面的错误
![image](https://cloud.githubusercontent.com/assets/4638754/22239898/64d40a94-e253-11e6-977d-3bf8a00445b2.png)

不知道是不是什么冲突了

**Comment by Blankj** [comment]
我等下发个版本，修正下，因为最新版的不是merge了是view，所以会报错

**Comment by ruhaly** [comment]
能告诉我具体的错误在哪儿么，我是一个个库排查的，但是具体不知道是哪个地方错了

**Comment by Blankj** [comment]
snackbar那个xml，最新版的是<view>，之前是<merge>，所以我曾经那样写会报错

**Comment by ruhaly** [comment]
但是snackbar，我没有用你吧，

**Comment by Blankj** [comment]
更新了  你试试1.3.6

**Comment by Blankj** [comment]
@ruhaly 现在有报错吗

**Comment by ruhaly** [comment]
ok了，请问你改了什么啊

**Comment by Blankj** [comment]
因为snackbar布局文件有变更
