### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference

### ISSUE THREAD

**Issue by aixi2494** [Blankj/AndroidUtilCode#1301]
1 java.lang.RuntimeException:Unable to stop activity {com.snmi.class/com.snmi.smclass.ui.main.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference
2 android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5359)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to read from field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference
6 com.android.internal.policy.DecorView.updateColorViewInt(DecorView.java:1614)
7 com.android.internal.policy.DecorView.updateColorViews(DecorView.java:1385)
8 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged(PhoneWindow.java:3234)
9 android.view.Window.setSoftInputMode(Window.java:1072)
10 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.processHideSoftInputOnActivityDestroy(UtilsActivityLifecycleImpl.java:258)
11 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.onActivityStopped(UtilsActivityLifecycleImpl.java:231)
12 android.app.Application.dispatchActivityStopped(Application.java:503)
13 android.app.Activity.dispatchActivityStopped(Activity.java:1380)
14 android.app.Activity.onStop(Activity.java:2560)
15 androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:558)
16 androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:207)
17 android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1494)
18 android.app.Activity.performStop(Activity.java:8318)
19 android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5351)
20 android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5329)
21 android.app.ActivityThread.handleStopActivity(ActivityThread.java:5404)
22 android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
23 android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
24 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
25 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
26 android.os.Handler.dispatchMessage(Handler.java:110)
27 android.os.Looper.loop(Looper.java:219)
28 android.app.ActivityThread.main(ActivityThread.java:8347)
29 java.lang.reflect.Method.invoke(Native Method)
30 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
31 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by mohdarif8299** [comment]
Can I work on this bug?

**Comment by Blankj** [comment]
@mohdarif8299 Of course.

**Comment by mohdarif8299** [comment]
Can you help me with cloning the project to the local system?

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
