### ISSUE TITLE
项目添加版本1.27.0    1.28.0  1.29.0   无法引用google gson 注解  @SerializedName    @Expose    annotations类无法引用

### ISSUE THREAD

**Issue by aglszz** [Blankj/AndroidUtilCode#1302]
项目添加版本1.27.0    1.28.0  1.29.0   无法引用google gson 注解  @SerializedName    @Expose    annotations类无法引用
![image](https://user-images.githubusercontent.com/27655065/90110145-5d0dec00-dd7f-11ea-89e2-6c22977be83f.png)
![image](https://user-images.githubusercontent.com/27655065/90110179-67c88100-dd7f-11ea-903f-4a0079d60893.png)
![image](https://user-images.githubusercontent.com/27655065/90110218-73b44300-dd7f-11ea-873c-6ab4b007690f.png)

**Comment by aglszz** [comment]
1.27.0 以后 需要自己 引用 gson？

**Comment by Blankj** [comment]
是的，因为我只是 implementation，并不是 api

**Comment by aglszz** [comment]
好的  之前我这边引用的1.24.6   并没有 引用 gson  就可以使用 annotations  升级之后不能用了  还以为有bug呢    嘿嘿   谢啦大婶

**Comment by Blankj** [comment]
我中间貌似有用过 compileOnly 导致需要你们自己依赖，27 版本以后貌似可以访问到的

**Comment by aglszz** [comment]
应该是用了compileOnly    我就刚试了试  27 28 29  在之前 用的24   27 28 29  必须自己引用google的gson 才可以 使用
