### ISSUE TITLE
使用了该库，华为审核报有病毒

### ISSUE THREAD

**Issue by EthanChenccc** [Blankj/AndroidUtilCode#1307]
![Snipaste_2020-08-21_14-33-25](https://user-images.githubusercontent.com/65217924/90860951-87822980-e3bd-11ea-878c-22006d13f085.png)

**Comment by Blankj** [comment]
版本是不太老了

**Comment by EthanChenccc** [comment]
> 版本是不太老了

我用的1.23.0

**Comment by EthanChenccc** [comment]
华为用的这个检测工具，国外的 https://www.virustotal.com/gui/，我之前没有混淆utilcode，现在我混淆了，我再测测

**Comment by Blankj** [comment]
升级版本呀

**Comment by EthanChenccc** [comment]
嗯，已经好了，升级到了最新版，谢谢大佬及时解答，感谢感谢
