### ISSUE TITLE
计算机检测报病毒

### ISSUE THREAD

**Issue by clbDream** [Blankj/AndroidUtilCode#1308]
火绒检测下,项目报病毒
![image](https://user-images.githubusercontent.com/28987014/90995122-94855f80-e5ed-11ea-94ee-55404d71876a.png)

**Comment by Blankj** [comment]
遇到问题首先升级到最新版本看是否还有问题

**Comment by clbDream** [comment]
> 遇到问题首先升级到最新版本看是否还有问题

这是官网拉取的最新的

**Comment by Blankj** [comment]
你检测我的 demo 干啥，我 demo 里 subutil 里有些危险权限的，你这是要干嘛？
