### ISSUE TITLE
FragmentUtils.replace 方法展示空白

### ISSUE THREAD

**Issue by ruansu2015** [Blankj/AndroidUtilCode#1309]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：1.29.0
- 出现 Bug 的设备型号：Xiaomi MINOTELTE
- 设备的 Android 版本：9

## 相关代码

```
FragmentUtils.replace(getSupportFragmentManager(), fragment, R.id.frameLayout, true);
```

## showHide正常显示

```
FragmentUtils.showHide(fragment, fragments);
```

**Comment by Blankj** [comment]
正常 replace 可以展示？

**Comment by ruansu2015** [comment]
> 正常 replace 可以展示？

不行，replace就是空白的

**Comment by Blankj** [comment]
那就是你使用的问题吧。

**Comment by ruansu2015** [comment]
> 那就是你使用的问题吧。

我是这样使用的
FragmentUtils.add(getSupportFragmentManager(), fragments, R.id.frameLayout, 0);
FragmentUtils.replace(getSupportFragmentManager(), fragments.get(position), R.id.frameLayout);

**Comment by Blankj** [comment]
我的意思是别用我的工具类，你自己调用原生的 api 试试看可以不。

**Comment by ruansu2015** [comment]
原生是可以的，现在替换了实现的方式
