### ISSUE TITLE
KeyboardUtils.hideSoftInput无法隐藏输入法

### ISSUE THREAD

**Issue by qq764215676** [Blankj/AndroidUtilCode#1310]
## 描述 Bug

简洁地描述下 Bug。
调用KeyboardUtils.showSoftInput弹出的键盘，按home键后不消失，调用KeyboardUtils.hideSoftInput也无法隐藏

- AndroidUtilCode 的版本：utilcodex:1.28.0
- 出现 Bug 的设备型号：小米5
- 设备的 Android 版本：Android8.0

## 相关代码

```
put your code here

KeyboardUtils.showSoftInput();
KeyboardUtils.showSoftInput(et_content);
KeyboardUtils.hideSoftInput(et_content);
KeyboardUtils.hideSoftInput(getActivity());
上面几个方法换着试了还是不行
```

## 异常堆栈

```
put the stack of crash here
```

## 截图

如果有的话请添加屏幕截图以帮助解释问题。

## 请删除当前行及以下内容

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by ITAnt** [comment]
不要在onResume里直接调，找到界面的一个View，如textView，post后调，如：
``` Kotlin
textView.post {
  KeyboardUtils.hideSoftInput(this)
}
```
