### ISSUE TITLE
希望能增加一个限流工具类

### ISSUE THREAD

**Issue by mao19951015** [Blankj/AndroidUtilCode#1313]
## 描述需求

简洁地描述下需求。
       点击事件或者监听推送时，偶尔会出现短时间内重复执行多次任务的情景，
可以用这个类来判断。一般大家都是在全局变量里记录一下上次运行的时间，这样不太干净。

## 可借鉴的
我简单封装的
/**
 * 限流工具类，可用于防止短时间内重复执行同一任务
 * （暂未考虑多线程下情景）
 */
public class FastUtil {

    private static Map<String, Long> lastTimeMap = new HashMap<>();

    public static boolean isFast(String key, long interval) {
        if (lastTimeMap.get(key) == null) {
            lastTimeMap.put(key, 0L);
        }
        long time = System.currentTimeMillis();
        long timeD = time - lastTimeMap.get(key);
        if (0 < timeD && timeD < interval) {
            return true;
        }
        lastTimeMap.put(key, time);
        return false;
    }

    public static void isFast(String key, long interval, Runnable callback) {
        if (lastTimeMap.get(key) == null) {
            lastTimeMap.put(key, 0L);
        }
        long time = System.currentTimeMillis();
        long timeD = time - lastTimeMap.get(key);
        if (0 < timeD && timeD < interval) {
            callback.run();
        }
        lastTimeMap.put(key, time);
    }

    public static boolean isNotFast(String key, long interval) {
        return !isFast(key, interval);
    }

    public static void isNotFast(String key, long interval, Runnable callback) {
        if (!isFast(key, interval)) {
            callback.run();
        }
    }
}

**Comment by Blankj** [comment]
点击事件去重有 ClickUtils，推送为啥要重复推送一样的？

**Comment by mao19951015** [comment]
本质都是收到消息执行一段代码，外接系统都是不可信任的。 就比如我们公司，用MQ推送消息，每5分钟让终端设备签到一次，一些新人不会配置，经常会导致在一秒内连续推十几次相同的消息。

**Comment by Blankj** [comment]
新版本 1.30.0 已发布，DebouncingUtils#isValid
