### ISSUE TITLE
Utils.getApp() 报错

### ISSUE THREAD

**Issue by aixi2494** [Blankj/AndroidUtilCode#1315]
1 java.lang.Throwable.<init>(Throwable.java:66)
--
2 java.lang.Throwable.<init>(Throwable.java:108)
3 java.lang.Exception.<init>(Exception.java:60)
4 java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:50)
5 com.android.qihooSandbox.QihooBridge.invokeOriginalMethodNative(Native Method)
6 com.android.qihooSandbox.QihooBridge.handleHookedMethod(QihooBridge.java:776)
7 java.lang.StringBuilder.toString(Native Method)
8 java.lang.StackTraceElement.toString(StackTraceElement.java:229)
9 com.android.qihooSandbox.QihooBridge.stackArrayToString(QihooBridge.java:744)
10 com.android.qihooSandbox.QihooBridge.outputErrorMessage(QihooBridge.java:708)
11 com.android.qihooSandbox.QihooBridge.handleHookedMethod(QihooBridge.java:821)
12 java.lang.Class.forName(Native Method)
13 java.lang.Class.forName(Class.java:172)
14 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInActivityThreadStaticField(UtilsActivityLifecycleImpl.java:345)
15 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:336)
16 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
17 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
18 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
19 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
20 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
21 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
22 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
23 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
24 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
25 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
26 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
27 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
28 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
29 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
30 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
31 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
32 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
33 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
34 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
35 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
36 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
37 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
38 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
39 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
40 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
41 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
42 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
43 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
44 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
45 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
46 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
47 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
48 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
49 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
50 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
51 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
52 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
53 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
54 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
55 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
56 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
57 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
58 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
59 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
60 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
61 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
62 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
63 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
64 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
65 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
66 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
67 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
68 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
69 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
70 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
71 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
72 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
73 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
74 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
75 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
76 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
77 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
78 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
79 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
80 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
81 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
82 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
83 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
84 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
85 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
86 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
87 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
88 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
89 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
90 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
91 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
92 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
93 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
94 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
95 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
96 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
97 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
98 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
99 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
100 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
101 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
102 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
103 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
104 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
105 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
106 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
107 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
108 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
109 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
110 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
111 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
112 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
113 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
114 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
115 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
116 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
117 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
118 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
119 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
120 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
121 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
122 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
123 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
124 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
125 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
126 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
127 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
128 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
129 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
130 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
131 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
132 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
133 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
134 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
135 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
136 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
137 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
138 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
139 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
140 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
141 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
142 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
143 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
144 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
145 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
146 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
147 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
148 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
149 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
150 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
151 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
152 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
153 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
154 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
155 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
156 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
157 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
158 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
159 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
160 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
161 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
162 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
163 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
164 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
165 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
166 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
167 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
168 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
169 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
170 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
171 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
172 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
173 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
174 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
175 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
176 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
177 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
178 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
179 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
180 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
181 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
182 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
183 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
184 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
185 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
186 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
187 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
188 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
189 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
190 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
191 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
192 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
193 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
194 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
195 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
196 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
197 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
198 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
199 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
200 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
201 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
202 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
203 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
204 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
205 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
206 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
207 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
208 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
209 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
210 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
211 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
212 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
213 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
214 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifecycleImpl.java:369)
215 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThread(UtilsActivityLifecycleImpl.java:340)
216 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getApplicationByReflect(UtilsActivityLifecycleImpl.java:94)
217 com.blankj.utilcode.util.UtilsBridge.getApplicationByReflect(UtilsBridge.java:87)
218 com.blankj.utilcode.util.Utils.getApp(Utils.java:70)
219 com.blankj.utilcode.util.UtilsActivityLifecycleImpl.getActivityThreadInLoadedApkField(UtilsActivityLifec...too long be cutted!

**Comment by aixi2494** [comment]
A23:3.14;A24:Android+4.1.2,level+16;A25:f8630c020b572f04;F09:42;C04_G10:1.4.5;C04_APP_ID:bd85e1afe0;

**Comment by aixi2494** [comment]
rom 

google/occam/mako:4.4/KRT16S/920375:user/release-keys/fail
--

**Comment by Blankj** [comment]
应该是非主进程报的错，你判断非主进程初始化下 Utils 就行。

**Comment by aixi2494** [comment]
好的，，谢谢，我试试

**Comment by MZCretin** [comment]
1.30.0版本 好像在子进程初始化 Utils.init也不行是怎么回事呢？
