### ISSUE TITLE
BarUtils.setStatusBarColor 在华为手机上不兼容

### ISSUE THREAD

**Issue by lindabang** [Blankj/AndroidUtilCode#1319]
## 描述 Bug
我的 CustomDialog extends Dialog, 然后在CustomDialog使用BarUtils.setStatusBarColor 设置系统状态栏颜色，发现在华为手机上不兼容，所设置的颜色未生效，并且挡住了我APP的其他内容了。

- AndroidUtilCode 的版本：utilcodex:1.29.0
- 出现 Bug 的设备型号：HUAWEI Mate 30 5G
- 设备的 Android 版本：API 29

## 相关代码

        Window window = this.getWindow();
        WindowManager.LayoutParams lp = window.getAttributes();
        lp.width = WindowManager.LayoutParams.MATCH_PARENT;
        lp.height = WindowManager.LayoutParams.MATCH_PARENT;
        window.setAttributes(lp);

        BarUtils.setStatusBarColor(window, ColorUtils.getColor(R.color.colorPrimary));
        BarUtils.setStatusBarLightMode(window, false);

## 异常堆栈

无

## 截图
![image](https://user-images.githubusercontent.com/23623339/92297439-d7dab900-ef71-11ea-9765-819f9f15bbef.png)

**Comment by Blankj** [comment]
dialog 不也是 window 么，size 为啥会延伸不到状态栏，你试着解决这个就行
