### ISSUE TITLE
验证身份证号码 18 位 台湾是83不是71

### ISSUE THREAD

**Issue by G10516011** [Blankj/AndroidUtilCode#1321]
## 描述 Bug

http://www.gov.cn/zhengce/content/2018-08/19/content_5314865.htm
第三条　港澳台居民居住证登载的内容包括：姓名、性别、出生日期、居住地住址、公民身份号码、本人相片、指纹信息、证件有效期限、签发机关、签发次数、港澳台居民出入境证件号码。

公民身份号码由公安机关按照公民身份号码国家标准编制。香港居民公民身份号码地址码使用810000，澳门居民公民身份号码地址码使用820000，台湾居民公民身份号码地址码使用830000。

## 相关代码
https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/src/main/java/com/blankj/utilcode/util/RegexUtils.java

**Comment by Blankj** [comment]
好的

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
