### ISSUE TITLE
希望CrashUtils可以增加自定义数据

### ISSUE THREAD

**Issue by xmt328** [Blankj/AndroidUtilCode#1322]
## Describe the feature

希望CrashUtils在输出crash日志时可以自定义部分头部数据
比如渠道号之类的

## Reference

CrashUtils#getUncaughtExceptionHandler()

**Comment by Blankj** [comment]
已经写好了，明天发版支持

**Comment by xmt328** [comment]
十分感谢

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
