### ISSUE TITLE
权限申请不够灵活，申请的权限中包含了一下不需要的权限，导致用户体验较差

### ISSUE THREAD

**Issue by hardlove** [Blankj/AndroidUtilCode#1325]
## 描述 Bug

权限申请能否提供API 自由配置申请哪些权限，比如：
在申请 PHONE权限时，由于用户对权限敏感，申请了一些不需要的权限，如 permission.CALL_PHONE在我的APP
中是多余的权限，因去掉
    private static final String[] GROUP_PHONE         = {
            permission.READ_PHONE_STATE, permission.READ_PHONE_NUMBERS, permission.CALL_PHONE,
            permission.READ_CALL_LOG, permission.WRITE_CALL_LOG, permission.ADD_VOICEMAIL,
            permission.USE_SIP, permission.PROCESS_OUTGOING_CALLS, permission.ANSWER_PHONE_CALLS
    };

## 相关代码

```
put your code here
```
![image](https://user-images.githubusercontent.com/11812893/92877569-dd3a7680-f43d-11ea-9553-a3dd2ae7fd1e.png)
能否去掉这个注解，或是提供其它API灵活配置要申请的权限

**Comment by Blankj** [comment]
你不在 xml 里声明就行啊，我这里会找出你 xml 里声明的权限去请求权限组，高版本是和权限组走的

**Comment by hardlove** [comment]
> 你不在 xml 里声明就行啊，我这里会找出你 xml 里声明的权限去请求权限组，高版本是和权限组走的

 private static final String[] GROUP_PHONE         = {
            permission.READ_PHONE_STATE, permission.READ_PHONE_NUMBERS, permission.CALL_PHONE,
            permission.READ_CALL_LOG, permission.WRITE_CALL_LOG, permission.ADD_VOICEMAIL,
            permission.USE_SIP, permission.PROCESS_OUTGOING_CALLS, permission.ANSWER_PHONE_CALLS
    };
这里面申请的权限，只有在xml中也配置了才有效果吗？是否意味着，即使我动态申请了GROUP_PHONE中所有的权限，但是如果我没有在xml中申请 permission.CALL_PHONE这个权限，那么 permission.CALL_PHONE这个也是不会被动态申请的吗？

**Comment by Blankj** [comment]
那肯定啊，你 xml 里没写肯定申请不到啊

**Comment by hardlove** [comment]
好的，谢谢。
检查了下代码，xml中确实也申请了不需要的权限<uses-permission android:name="android.permission.CALL_PHONE" />，
所以，导致动态申请的时候也多出了这个权限。
非常感谢！

**Comment by hanxiaomeme** [comment]
> 那肯定啊，你 xml 里没写肯定申请不到啊

请问在低版本中会出现未在xml申请 从而申请权限的情况吗,在谷歌市场上架的app最近因为CALLLOG权限被下架了,但是我反复查了代码中并没有出现申请calllog权限的相关操作

**Comment by Deaful** [comment]
@Blankj 大佬你好，我集成的版本是1.30.6，在release里面找不到，是被废弃了吗？另外隐私合规检测中，查出CALL_PHONE未申请（xml中没申请）已使用（SDK中已使用），请问怎么在SDK中去掉CALL_PHONE权限申请呢？

**Comment by Deaful** [comment]
> > 那肯定啊，你 xml 里没写肯定申请不到啊
> 
> 请问在低版本中会出现未在xml申请 从而申请权限的情况吗,在谷歌市场上架的app最近因为CALLLOG权限被下架了,但是我反复查了代码中并没有出现申请calllog权限的相关操作

同问
