### ISSUE TITLE
ImageUtils view2Bitmapt图片变形了

### ISSUE THREAD

**Issue by 1825492258** [Blankj/AndroidUtilCode#1326]
![image](https://user-images.githubusercontent.com/16134482/92888691-21327900-f448-11ea-9cc8-19c5ba0a4d50.png)
我传一个LinearLayout的View进去，展示的图片变形

**Comment by Blankj** [comment]
既然你可以复现那你可以帮我 debug 看下哪里有问题呀

**Comment by Blankj** [comment]
加个 delay？你是不是布局还没加载完就调用了

**Comment by 1825492258** [comment]
没有，布局加载完了。我换成之前的view2Bitmap就可以了，暂时用之前的代码。
我的LinearLayout是在ScrollView下面，如果布局超出屏幕了就变形，没有超出屏幕不变形。
是这个方法不支持长布局？

**Comment by Blankj** [comment]
可以把你的代码贡献上来哈

**Comment by CPC-Coder** [comment]
我也发生一样的问题
