### ISSUE TITLE
使用ToastUtils无法展示Toast

### ISSUE THREAD

**Issue by YeGuli** [Blankj/AndroidUtilCode#1329]
## 描述 Bug
使用ToastUtils.showShort() 等方法无法展示Toast。

- AndroidUtilCode 的版本：com.blankj:utilcodex:1.29.0
- 出现 Bug 的设备型号：Google pixel2、Xiaomi10、Xiaomi6
- 设备的 Android 版本：Android11

## 相关代码
```kotlin
ToastUtils.showShort() 
```

## 异常堆栈
```
I/NotificationService: cancelToast token=android.os.BinderProxy@32a3315
W/NotificationService: Toast already cancelled. token=android.os.BinderProxy@32a3315
```

**Comment by Blankj** [comment]
新版本 1.30.0 已发布，ToastUtils 无敌
