### ISSUE TITLE
PermissionUtils的一些疑问?

### ISSUE THREAD

**Issue by lydlovezjr** [Blankj/AndroidUtilCode#1334]
Android9以上获取运动步数需要动态申请ACTIVITY_RECOGNITION权限.
PermissionUtils好像不支持动态获取这个权限.

https://stackoverflow.com/questions/58017585/android-activity-recognition-permission-sdk-28-running-on-android-10-q-sdk-29

**Comment by lydlovezjr** [comment]
![360截图20200924183149155](https://user-images.githubusercontent.com/19246347/94134229-543b2a80-fe94-11ea-956d-021560793a9e.jpg)
可以这样用,但是AS会提示错误.
但是确实可以调用成功

**Comment by Blankj** [comment]
嗯，这个只是我没加入到注解里，但也是可以兼容你自己传入非注解的

**Comment by lydlovezjr** [comment]
狗哥牛逼
