### ISSUE TITLE
关于ToastUtils的一点建议

### ISSUE THREAD

**Issue by jingzz1** [Blankj/AndroidUtilCode#1335]
关闭通知后系统toast无法弹出，悬浮窗权限也没有打开，这时弹出弹出toast依赖的是最顶层的activity，但是这样有个问题，当activity被销毁或转到后台时，toast也会跟着消失
转到后台目前没有好的处理方案，但activity被销毁，这里可以使用美团提供的一个方案：在activity栈的最上层三个activity同时弹出toast，这样即使最上层的activity被finish()，toast依然在第二个activity 里显示

**Comment by Blankj** [comment]
可以安排

**Comment by jingzz1** [comment]
不会吧，我用Snackbar可以，等我下午用Toast试试

**Comment by Blankj** [comment]
snackbar 其实就是 add view 应该是可以的呀

**Comment by jingzz1** [comment]
我试了一下，windowManager.addView() 可以show出来，所以依赖windowManager的toast应该也可以show才对
demo
https://jingzz.lanzous.com/imuyihb5chc

**Comment by Blankj** [comment]
![device-2020-10-10-185427](https://user-images.githubusercontent.com/17978187/95653393-0af10900-0b2b-11eb-904d-45fcc2c70547.gif)
我手机 Android 10 的表现哈

**Comment by jingzz1** [comment]
用真机云测了一下，三星和魅族不可以，华为，小米,vivo,oppo可以，看来这方法行不通了

**Comment by Blankj** [comment]
新版本 1.30.0 已发布，ToastUtils 无敌

**Comment by TeemoDong** [comment]
作者你好，这样改完之后，如果是【这里可以使用美团提供的一个方案：在activity栈的最上层三个activity同时弹出toast，这样即使最上层的activity被finish()，toast依然在第二个activity 里显示】这样的改法（我看了您的代码，大概也是这么改的，ToastUtils的636行开始，活着的activity就加个view显示toast，这样其实也有个缺点，我有两个activity是大小不一样的，特殊的需求导致一个activity不是完整铺满屏幕，这时候关闭通知权限然后调用到activityToast，会出现两个toast，其中一个就是不规则大小的toast）

**Comment by Blankj** [comment]
@TeemoDong activity 不一样大那里面的内容不也就缩放了么，这有问题吗？或者截个图我看看？

**Comment by TeemoDong** [comment]
![image](https://user-images.githubusercontent.com/19491042/101571255-a959f780-3a12-11eb-87ae-55a159408719.png)
emm这也是有年份的项目了，一个activity套4个activity。。现在就是一个大的activity套着这个登录activity，登录界面不带标题栏。然后关闭通知权限就这样了，正常开权限没问题。刚刚试了https://github.com/getActivity/ToastUtils，就没问题了，他主要是对TopActivity进行处理（https://github.com/getActivity/ToastUtils/blob/master/library/src/main/java/com/hjq/toast/ToastHelper.java  58行）
