### ISSUE TITLE
getMetaDataInApp

### ISSUE THREAD

**Issue by cowoboy007** [Blankj/AndroidUtilCode#1336]
如何在manifest声明push的配置信息。因为有些平台的id是数字。直接用这个方法取出来的是很大的数字，而不是字符串

**Comment by Blankj** [comment]
你自己转啊。。。

**Comment by cowoboy007** [comment]
。。。。不确定是什么呢。有的push配置是很大的纯数字，有的是字符串。manifest写的是数字的字符串。但是取出来就是已经转成科学计数了。。没法转

**Comment by Blankj** [comment]
这不归我管吧

**Comment by cowoboy007** [comment]
最好能把类型暴露出来。要不现在这种方式没太大意义了。直接取的obj.然后转的string,不知道取出来是什么东东

**Comment by Blankj** [comment]
你取到 obj 那能干嘛，之所以 String 已经转成科学计数了那是因为 obj 识别出来的是浮点数，给你 obj 为浮点数你不还是取不到原来的纯数字么

**Comment by cowoboy007** [comment]
内部进行类型判断。或者在get的时候。把类型穿进去。按给的类型进行转换。而不是统一都string。。。是什么类型的返回什么类型

**Comment by Blankj** [comment]
你自己先试试吧，你好像没懂我说的意思，比如里面写的是 `12345678901234567890123456789012345678901234567890123456789012345678901234567890` 这种，你试一下怎么才能取到？

**Comment by Blankj** [comment]
推荐解决方案就是在大数字符串前面加个字母作为前缀，比如 `D`，然后或取到 String 后 substring 即可
