### ISSUE TITLE
关于ThreadUtils定时任务的bug

### ISSUE THREAD

**Issue by SenchunHuang** [Blankj/AndroidUtilCode#1339]
ThreadUtils开启定时任务后，调用cancel()方法后，需要重新创建对象才能再次开启定时任务
public void cancel(boolean mayInterruptIfRunning) {
            synchronized (state) {
                if (state.get() > RUNNING) return;
                state.set(CANCELLED);
            }
            if (mayInterruptIfRunning) {
                if (runner != null) {
                    runner.interrupt();
                }
            }

            getDeliver().execute(new Runnable() {
                @Override
                public void run() {
                    onCancel();
                    onDone();
                }
            });
        }
建议在return方法之前调用onDone方法，这样可以移除TASK_POOL_MAP的对象，再次开启相同的定时任务就不会有问题

**Comment by Blankj** [comment]
任务本来就不能复用，一个任务只在一个线程中执行，可以复用的话那多个线程执行一个任务对象就会出现各种问题，可以参考源码 FutureTask

**Comment by SenchunHuang** [comment]
你好，多谢你的回复。比如我现在有个需求，在A界面有个定时任务，每隔10秒执行一个任务请求，然后我回到桌面，或者开启B界面，这时cancel这个任务。再回到A界面，如果用类似于executeBySingleAtFixRate()这样的方法，那如何能重新开启这个定时任务呢，只能通过创建新的Task的方式来完成吗，但是TASK_POOL_MAP中旧的不就一直没移除了。
synchronized (TASK_POOL_MAP) {
            if (TASK_POOL_MAP.get(task) != null) {
                Log.e("ThreadUtils", "Task can only be executed once.");
                return;
            }
            TASK_POOL_MAP.put(task, pool);
        }
你这个是不是已经规定同个Task没remove之前只能执行一次。
