### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by DanteAndroid** [Blankj/AndroidUtilCode#134]
有空的话，可以添加[这个功能](https://github.com/TheFinestArtist/AndroidBaseUtils#extrasbinder)，可以很方便的传递bundle。

> Code：
https://github.com/TheFinestArtist/AndroidBaseUtils/blob/master/utils/src/main/java/com/thefinestartist/binders/ExtrasBinder.java

因为不太懂注解和反射，所以就没PR

**Comment by Blankj** [comment]
我不太认同这个做法，何必非要用反射去做这操作呢，比如对fragment的的操作，getArgument之后set进去就好了，我不太喜欢用反射，毕竟不友善

**Comment by DanteAndroid** [comment]
反射对性能有一定影响，但是其实没那么大。这样操作可以避免写模板代码啊（与这个库的思想也是一致的）。不过不认同，也无所谓啦。

**Comment by Blankj** [comment]
fragment里直接写newInstance传进去不是很适合么，规范都是这么写的
