### ISSUE TITLE
java.lang.NullPointerException: Argument 'activity' of type Activity (#0 out of 2, zero-based) is marked by @androidx.annotation.NonNull but got null for it

### ISSUE THREAD

**Issue by fearlesstrek** [Blankj/AndroidUtilCode#1343]
## 描述 Bug
调用ScreenUtils.screenShot(ActivityUtils.getTopActivity(), false);报错

java.lang.NullPointerException: Argument 'activity' of type Activity (#0 out of 2, zero-based) is marked by @androidx.annotation.NonNull but got null for it

- AndroidUtilCode 的版本：1.26.0

**Comment by Blankj** [comment]
这个是你传入的 ActivityUtils.getTopActivity() 维空导致的，需要你自己做下判空处理，或者自己传入 Activity
