### ISSUE TITLE
请求权限前弹窗

### ISSUE THREAD

**Issue by midFang** [Blankj/AndroidUtilCode#1345]
## 希望增加请求权限前的弹窗

用户请求权限前，先弹出应用本身自定义的弹窗，允许之后再弹系统的弹窗

**Comment by Blankj** [comment]
那你就判断是否有权限呀，没的话弹你自己的就行，然后再申请，跟我没什么关系吧

**Comment by midFang** [comment]
我的意思是在你的工具类里面处理，有点类似这个  https://blog.csdn.net/guolin_blog/article/details/106181780  里面的explainReasonBeforeRequest 方法

**Comment by Blankj** [comment]
了解了 好的

**Comment by midFang** [comment]
需要

**Comment by Blankj** [comment]
那我就把列表状态返回参数给你就好了

**Comment by midFang** [comment]
我这里的目前的需求大概是这样的，假如说我请求两个权限
1. 首次请求，先弹出了请求权限前弹窗，这个弹窗里面我还有允许和拒绝两个按钮，拒绝是不再做任何处理，允许时继续弹出系统的权限请求弹窗，假如这个过程中我拒绝了某一个权限，我要知道是哪一个被拒绝了
2. 假如我第二次进行请求，其中一个权限已经申请了，继续弹出请求权限前弹窗，此时我要知道那个那个权限还没有申请
3. 如果都拒绝了，点了系统弹窗的不再询问，则直接弹出需要去系统设置申请的弹窗

**Comment by Blankj** [comment]
我就类似把 callback 中的 deniedForever 和 denied 都返回给你就行了应该

**Comment by Blankj** [comment]
貌似 deniedForever 这个在某些机型第一次会判断不准

**Comment by Blankj** [comment]
情况还分部分不再询问，部分首次拒绝，我这边就统一返回 denied 吧，具体情况再到 callback 里去判断吧

**Comment by Blankj** [comment]
新版本 1.30.0 已发布
