### ISSUE TITLE
DeviceUtils类   获取设备唯一ID SharePreference保存UUID，他喵的连SP的名字都错的，导致无法获取保存的UUID

### ISSUE THREAD

**Issue by luozhanming** [Blankj/AndroidUtilCode#1347]
![image](https://user-images.githubusercontent.com/17785617/95937936-682ada00-0e0b-11eb-8e5e-8d1ac3ff1549.png)
![image](https://user-images.githubusercontent.com/17785617/95937962-74af3280-0e0b-11eb-82c8-fbd713c46cd9.png)
![image](https://user-images.githubusercontent.com/17785617/95937981-7f69c780-0e0b-11eb-9f5f-123515584eca.png)

够牛逼的，这个坑死不少人吧

**Comment by Blankj** [comment]
你这版本有点老吧？

**Comment by luozhanming** [comment]
亏我这么信这个框架。服务器拿手机的唯一id做业务，结果用户开关wifi就直接换了个id。直接造成经济损失，被骂惨了。而且wifi开启后不能立刻拿到mac地址，需要延时延时延时。

**Comment by Blankj** [comment]
你用的版本是那会 Android 的 mac 地址还不会变所设计的啊，之后谷歌在 Android9 上面做了变更呀，那但凡老版本的库都会有问题吧，这能怪我么？
