### ISSUE TITLE
一些小建议，还望采纳

### ISSUE THREAD

**Issue by hujiaweibujidao** [Blankj/AndroidUtilCode#135]
1.`IntentUtils`中的`getInstallAppIntent(File file)`方法，其中"com.your.package.fileProvider"里面的package是可以拿到的吧，所以这里是不是还没有改过来？

```java
Uri contentUri = FileProvider.getUriForFile(Utils.getContext(), "com.your.package.fileProvider", file);
```

2.`SDCardUtils`中的`getSDCardPath`方法，个人感觉在sd卡不在的时候返回null比返回"sdcard unable!"好些，否则调用方拿到一个非null非空的字符串可能会以为路径存在，同理这个类中的其他方法也建议返回null。

```java
public static String getSDCardPath() {
        if (!isSDCardEnable()) return null;//"sdcard unable!"
        //...
}
```

3.`PhoneUtils`中`getPhoneStatus`方法里面`PhoneType`拼写有笔误，漏了`P`

4.`SizeUtils`中`mListener`成员变量可以不用定义，也就是下面几句可以不用，`forceGetViewSize`方法调用的时候会传入listener

```java
public static void setListener(onGetSizeListener listener) {
  mListener = listener;
}

private static onGetSizeListener mListener;
```

最后，再次感谢你的分享。

**Comment by Blankj** [comment]
感谢你的建议哈，下版本会更新哈

**Comment by wrightakencom** [comment]
Have a good look forward to install 
a translator for safety and security 
reasons  , I will be signing off to 
reflect the views expressed in any 
capacity of my review  , disclosure or distribution of this repository  ?

**Comment by Blankj** [comment]
:writing_hand: welcome
