### ISSUE TITLE
SP存储是否可以考虑加入mmkv

### ISSUE THREAD

**Issue by cowoboy007** [Blankj/AndroidUtilCode#1350]
## 描述需求

简洁地描述下需求。
现在sp存储是否可以加入mmkv存储。效果更高，也支持跨进程

## 可借鉴的

如果有的话，可以给出一些参考文章、链接、代码

## 请删除当前行及以下内容

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
mmkv 肯定是不会引入的，推荐自己设计接口，然后进行不同的实现，这样就可以灵活切换了
