### ISSUE TITLE
Android 10存储适配

### ISSUE THREAD

**Issue by GXSZone** [Blankj/AndroidUtilCode#1352]

**Comment by dalong982242260** [comment]
CleanUtils、CrashUtils、LogUtils、PathUtils、SDCardUtils 这里都需要适配下

**Comment by oopyoung** [comment]
> CleanUtils、CrashUtils、LogUtils、PathUtils、SDCardUtils 这里都需要适配下

你在教作者做事？

**Comment by GXSZone** [comment]
我自己的就一点，写好了，我还是希望能用上库的，依赖都依赖了，干脆都用上，哈哈

**Comment by Blankj** [comment]
怎么适配？不是你们自己换到应用目录不就好了吗？

**Comment by wangtb** [comment]
ImageUtils中的getBitmap(final String filePath)方法，如果在Android 10以上的系统运行应该会有问题吧
