### ISSUE TITLE
请大神考虑添加二维码工具类

### ISSUE THREAD

**Issue by candyguy242** [Blankj/AndroidUtilCode#1353]
## 描述需求

如题，目前二维码应用挺广泛的，一些基础功能，如生成二维码在很多场景，尤其是分享中会用到，请大神考虑加入QRCodeUtil~

## 可借鉴的

如果有的话，可以给出一些参考文章、链接、代码

## 请删除当前行及以下内容

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
那我就要引入其他三方库了呀，类似这样的三方库挺多的吧
