### ISSUE TITLE
NumberUtils一个bug

### ISSUE THREAD

**Issue by shanhai1992** [Blankj/AndroidUtilCode#1356]
用代码 `` NumberUtils.format(str.toDouble(), 4, false)``
`50.6720000000` 保留4位小数变成 `50.6719`

**Comment by Blankj** [comment]
你看看你的 str.toDouble() 是啥

**Comment by Blankj** [comment]
你这都已经是字符串了还不好处理吗，干嘛还要绕远路呢

**Comment by shanhai1992** [comment]
&nbsp;是toDouble的问题&nbsp; 关闭issue




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Blankj/AndroidUtilCode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 下午3:05
收件人:&nbsp;"Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com&gt;;
抄送:&nbsp;"山海"<1925488467@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Blankj/AndroidUtilCode] NumberUtils一个bug (#1356)





 
你看看你的 str.toDouble() 是啥
