### ISSUE TITLE
isDeveloperOptionsEnabled in DeviceUtils

### ISSUE THREAD

**Issue by NotNotMarshall** [Blankj/AndroidUtilCode#1357]
Please add this method to the DeviceUtils module as it is required and 

A simple check would be like this:

`return Settings.Global.getInt(context.contentResolver, Settings.Global.DEVELOPMENT_SETTINGS_ENABLED,0) == 1`

Thank you for your awesome library, this really saved a lot of time for me! And every time I discover something new and useful in it... Glad that people like you exist! ❤

**Comment by Blankj** [comment]
Next version will support it.

**Comment by Blankj** [comment]
1.30.2 has published.
