### ISSUE TITLE
ObjectUtils isEmpty(final Object obj)

### ISSUE THREAD

**Issue by dawsonjiang** [Blankj/AndroidUtilCode#1358]
## 描述 Bug

ObjectUtils isEmpty(final Object obj)方法，如果
ObjectUtils.isEmpty(EditText.text) 方法内部没有判断 EditText.text（Editable）类型的
建议添加

utilcode:1.30.0
- AndroidUtilCode 的版本：
- 出现 Bug 的设备型号：
- 设备的 Android 版本：

**Comment by dawsonjiang** [comment]
![Uploading image.png…]()

**Comment by Blankj** [comment]
Editable 不是继承了 CharSequence 么，ObjectUtils.isEmpty 会直接走 CharSequence 的啊

**Comment by dawsonjiang** [comment]
我写错了，写成ObjectUtils.isEmpty(EditText)了
抱歉
