### ISSUE TITLE
SpannableStringUtils设置字体大小单位

### ISSUE THREAD

**Issue by hxxxxxxxk** [Blankj/AndroidUtilCode#136]
大神怎么没有设置字体大小单位的API？有时一行文字大小会各不同，如此：
spannableString.setSpan(new AbsoluteSizeSpan(textSize, true), start, end, Spanned.SPAN_INCLUSIVE_EXCLUSIVE);

**Comment by Blankj** [comment]
setProportion，你说的那我也下版本也加进去哈

**Comment by hxxxxxxxk** [comment]
@Blankj 有看到，setProportion使用的是RelativeSizeSpan，我觉得AbsoluteSizeSpan自由度更好些，期待新版本~~~
