### ISSUE TITLE
TimeUtils功能增加建议

### ISSUE THREAD

**Issue by Dboy233** [Blankj/AndroidUtilCode#1360]
## 描述需求

TimeUtils 中 只能格式化 完整的时间戳，

在我的开发中经常会使用到一些倒计时或者 时间是固定的 50分钟.

而我会直接给一个50分钟的毫秒值，将50分钟的毫秒值（3000000毫秒）格式化成 50:00 然而当前的工具库并不能实现这个功能。

我都是自己再写方法去计算这个毫秒当前是多少时长。

比如有时候获取的是一个视频的时长，将这个时长进行格式化成 (HH:mm:ss)

我希望有这样的功能：

fun(3000000,"HH:mm:ss")-> "00:50:00"

fun("00:50:00","HH:mm:ss",TimeUnit.HOURS) -> 0.5 

fun("00:50:00","HH:mm:ss",TimeUnit.MINUTES) -> 50

fun("00:50:00","HH:mm:ss",TimeUnit.SECONDS) -> 3000

**Comment by Blankj** [comment]
这个自己封装实现下就好了，取整、取余而已，不通用哈
