### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() 

### ISSUE THREAD

**Issue by Jasperben** [Blankj/AndroidUtilCode#1361]
10-30 14:26:43.370  1122  1122 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2c255eb u0 }

上述异常出现在1.29.0之后的版本

包括最新的1.30.4也存在这个问题

**Comment by Blankj** [comment]
是使用 MessengerUtils 出现的吗，这个新版本修复了，不是的话那需要你自己修改你的 Service
