### ISSUE TITLE
isEmulator 判断错误

### ISSUE THREAD

**Issue by runnchild** [Blankj/AndroidUtilCode#1365]
## 描述 Bug

Android 11， 
![image](https://user-images.githubusercontent.com/13394690/98530926-896fd080-22ba-11eb-8926-1eb032a05284.png)

- AndroidUtilCode 的版本：1.30.0
- 出现 Bug 的设备型号：小米 10
- 设备的 Android 版本：30

## 相关代码

```
put your code here
```

## 异常堆栈

```
put the stack of crash here
```

## 截图

如果有的话请添加屏幕截图以帮助解释问题。

## 请删除当前行及以下内容

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by runnchild** [comment]
需要加quries

**Comment by crazywenza** [comment]
这个bug还有问题呀，为啥closed了？
