### ISSUE TITLE
PermissionUtils.isGranted(PermissionConstants.STORAGE)总是返回false

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#1366]
## Describe the bug
PermissionUtils.isGranted(PermissionConstants.STORAGE)总是返回false，但存储权限是确认申请成功的，都可以成功发图片下载文件，请求权限的成功回调都在初始界面执行了。

- The version of AndroidUtilCode:  1.29.0
- The device: 华为mate20
- The version of device: Android10

## The code of bug

```
PermissionUtils.isGranted(PermissionConstants.STORAGE)
```

**Comment by Blankj** [comment]
申请也是用的 PermissionUtils 吗？

**Comment by li-xiaojun** [comment]
1.30.4没问题了，申请也是用的整个权限套餐。
