### ISSUE TITLE
MessengerUtils发生ANR

### ISSUE THREAD

**Issue by liangrk** [Blankj/AndroidUtilCode#1367]
## 描述 Bug

亲爱的柯基, 之前跟你反应过来的跨进程通讯问题, 根据你上次的帮助我更改了代码, 后面发现其在部分手机上会触发 ANR .

- AndroidUtilCode 的版本：utilcodex:1.30.4
- 出现 Bug 的设备型号：RedMi note 8
- 设备的 Android 版本：API 28

## 相关代码

2020-11-10 14:23:04.329 1380-1491/? E/ActivityManager: ANR in com.test.mypackage
    PID: 22047
    Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2cd3de0 u0 com.test.mypackage/com.blankj.utilcode.util.MessengerUtils$ServerService}
  

## 异常堆栈

2020-11-10 14:23:04.329 1380-1491/? E/ActivityManager: ANR in com.test.mypackage
    PID: 22047
    Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2cd3de0 u0 com.test.mypackage/com.blankj.utilcode.util.MessengerUtils$ServerService}
    Load: 0.55 / 0.34 / 0.65
    CPU usage from 72820ms to 0ms ago (2020-11-10 14:21:47.017 to 2020-11-10 14:22:59.837):
      15% 673/surfaceflinger: 8.3% user + 7.5% kernel / faults: 120 minor
      11% 7151/com.miui.weather2: 7.6% user + 3.6% kernel / faults: 308 minor
      5.4% 1380/system_server: 3.1% user + 2.2% kernel / faults: 17793 minor 1 major
      3.9% 2052/com.android.systemui: 3.3% user + 0.6% kernel / faults: 7591 minor
      2.6% 9318/adbd: 0.5% user + 2.1% kernel / faults: 215262 minor
      2% 3006/cnss_diag: 1.5% user + 0.4% kernel
      1.4% 16747/kworker/u16:1: 0% user + 1.4% kernel
      1.4% 601/android.hardware.graphics.composer@2.2-service: 0.9% user + 0.5% kernel / faults: 94 minor
      1.2% 489/logd: 0.5% user + 0.7% kernel / faults: 40 minor
      1% 449/ueventd: 0.9% user + 0% kernel / faults: 116 minor
      1% 609/android.hardware.sensors@1.0-service: 0.4% user + 0.5% kernel / faults: 280 minor
      0.8% 7942/kworker/u16:5: 0% user + 0.8% kernel
      0.8% 21860/kworker/u16:0: 0% user + 0.8% kernel
      0.6% 2805/irq/85-1b8e200.: 0% user + 0.6% kernel
      0.5% 2461/com.android.phone: 0.3% user + 0.2% kernel / faults: 290 minor
      0.5% 1854/cds_ol_rx_threa: 0% user + 0.5% kernel
      0.4% 242/crtc_commit:90: 0% user + 0.4% kernel
      0% 591/android.hardware.audio@2.0-service: 0% user + 0% kernel / faults: 75 minor
      0% 668/audioserver: 0% user + 0% kernel / faults: 155 minor
      0.4% 490/servicemanager: 0.1% user + 0.2% kernel
      0.4% 614/android.hardware.wifi@1.0-service: 0.2% user + 0.1% kernel / faults: 117 minor
      0.3% 31269/com.miui.systemAdSolution: 0.2% user + 0% kernel / faults: 608 minor 2 major
      0.2% 31043/com.miui.securitycenter.remote: 0.2% user + 0% kernel / faults: 1110 minor
      0.2% 249/kgsl_worker_thr: 0% user + 0.2% kernel
      0.2% 340/mmc-cmdqd/0: 0% user + 0.2% kernel
      0.2% 524/netd: 0.1% user + 0.1% kernel / faults: 568 minor
      0.2% 9830/transport: 0% user + 0.1% kernel
      0.2% 529/kworker/u17:2: 0% user + 0.2% kernel
      0.2% 35/ksoftirqd/3: 0% user + 0.2% kernel
      0.2% 9/rcu_preempt: 0% user + 0.2% kernel
      0.1% 6644/com.miui.home: 0.1% user + 0% kernel / faults: 1534 minor
      0.1% 27/ksoftirqd/2: 0% user + 0.1% kernel
      0.1% 468/android.hardware.keymaster@4.0-service-qti: 0% user + 0.1% kernel
      0.1% 1853/scheduler_threa: 0% user + 0.1% kernel
      0.1% 9302/kworker/3:3: 0% user + 0.1% kernel
      0.1% 19/ksoftirqd/1: 0% user + 0.1% kernel
      0.1% 1004/msm_irqbalance: 0% user + 0% kernel
      0.1% 6756/com.android.quicksearchbox: 0.1% user + 0% kernel / faults: 975 minor
      0% 16748/kworker/u16:3: 0% user + 0% kernel
      0.1% 8/ksoftirqd/0: 0% user + 0.1% kernel
      0.1% 1002/qcrild: 0.1% user + 0% kernel / faults: 47 minor
      0.1% 2740/mcd: 0% user + 0.1% kernel
      0% 501/android.hardware.gatekeeper@1.0-service-qti: 0% user + 0% kernel / faults: 2 minor
      0% 581/qrtr_rx: 0% user + 0% kernel
      0.1% 21914/com.miui.securityadd: 0% user + 0% kernel / faults: 76 minor
      0.1% 12/rcuop/0: 0% user + 0.1% kernel
      0.1% 30/rcuop/2: 0% user + 0.1% kernel
      0% 243/crtc_event:90: 0% user + 0% kernel
      0% 15385/kworker/u16:9: 0% user + 0% kernel
      0% 83/kcompactd0: 0% user + 0% kernel
      0% 670/lmkd: 0% user + 0% kernel
      0% 810/wificond: 0% user + 0% kernel / faults: 4 minor
      0% 3786/com.xiaomi.mi_connect_service: 0% user + 0% kernel / faults: 62 minor 5 major
      0% 21911/kworker/1:3: 0% user + 0% kernel
      0% 46/rcuop/4: 0% user + 0% kernel
      0% 88/system: 0% user + 0% kernel
      0% 525/zygote64: 0% user + 0% kernel / faults: 315 minor
      0% 546/kworker/u17:16: 0% user + 0% kernel
      0% 762/wlan_logging_th: 0% user + 0% kernel
      0% 1744/com.sohu.inputmethod.sogou.xiaomi: 0% user + 0% kernel / faults: 249 minor
      0% 3319/com.miui.powerkeeper: 0% user + 0% kernel / faults: 132 minor
      0% 3828/mdnsd: 0% user + 0% kernel
      0% 18738/kworker/2:1: 0% user + 0% kernel

## 截图
![image](https://user-images.githubusercontent.com/39788948/98636167-4a488a80-2361-11eb-96e3-573bf8898c52.png)

**Comment by Blankj** [comment]
已修复，可以试试
