### ISSUE TITLE
camerautils abandon?

### ISSUE THREAD

**Issue by TedWithAHammer** [Blankj/AndroidUtilCode#137]
有个动态权限检测的好像是wifimanager的 好像是你因为直接disable insepect了 好像要加try catch

**Comment by Blankj** [comment]
camerautils还没写呢，所以你说的暂时不考虑哈

**Comment by TedWithAHammer** [comment]
没有 报错那个不在camerautils里在networkutils里面 但是我看camera里面都是写完了 然后注释掉了 我还以为 是其它utils覆盖功能了 哈哈哈 总之谢谢啦 省却很多重复早轮子的时间

**Comment by Blankj** [comment]
network哪里报错了？

**Comment by TedWithAHammer** [comment]
network会有个wifimanager的使用需要动态检测权限 不过disabale检测就好了 刚复制进去会有问题
