### ISSUE TITLE
佬,保存照片到相册的一点小疑问.

### ISSUE THREAD

**Issue by lydlovezjr** [Blankj/AndroidUtilCode#1371]
可否增加一个可配置项.
现在保存后路径直接应用的包名.
可以自定义这个路径.
![360截图20201116132500852](https://user-images.githubusercontent.com/19246347/99215906-46a87e00-280f-11eb-84e3-ab0442ba54b7.jpg)

**Comment by lydlovezjr** [comment]
其它的可以不改.就图中那个应用包名一般都是一堆字母.
产品嫌弃这个用户找不到.

**Comment by lydlovezjr** [comment]
![Uploading 360截图20201116164739310.jpg…]()

**Comment by lydlovezjr** [comment]
佬,可否给个这样的自定义配置

**Comment by lydlovezjr** [comment]
微信就是用的WeiXin的拼音

**Comment by Blankj** [comment]
1.30.6 版本已支持
