### ISSUE TITLE
避免FragmentUtil 添加Fragment的时候出现 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by 1wayticket** [Blankj/AndroidUtilCode#1373]
## Describe the feature

当fragment 的add事件被短时间同时出发的时候，极易出现 
java.lang.IllegalStateException
Fragment already added；
比如在点击事件中使用FragmentUtils.add() 调用两次add Fragment就会稳定出现这个crash 异常。
应该是FragemntManager缓存FragemntTransaction导致Fragment 是否add判断失效.

## Reference

http://www.hellojava.com/a/73422.html
https://stackoverflow.com/questions/55613314/fragment-already-added-dialogfragment
https://stackoverflow.com/questions/55376472/android-java-lang-illegalstateexception-fragment-already-added

## Please delete the current line and the following

```
ft.commitAllowingStateLoss();
executePendingTransactions();
```

**Comment by Blankj** [comment]
1.30.6 版本已修复
