### ISSUE TITLE
ThreadUtils设置超时崩溃

### ISSUE THREAD

**Issue by haianhsing** [Blankj/AndroidUtilCode#1379]
## 描述 Bug

ThreadUtils设置超时崩溃

- AndroidUtilCode 的版本：1.30.5
- 出现 Bug 的设备型号：Google Pixel 
- 设备的 Android 版本：API 26

## 相关代码

```
task.setTimeout(1000) { LogUtils.e("timeout") }
ThreadUtils.executeByIo(task)
```

## 异常堆栈

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.blankj.utilcode.util.ThreadUtils$Task$OnTimeoutListener.onTimeout()' on a null object reference
        at com.blankj.utilcode.util.ThreadUtils$Task$1.run(ThreadUtils.java:1218)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

## 截图

如果有的话请添加屏幕截图以帮助解释问题。

![微信截图_20201127145515](https://user-images.githubusercontent.com/37507408/100420431-6b2f1080-30c1-11eb-84f1-0e2f3e033c39.png)
![微信截图_20201127145539](https://user-images.githubusercontent.com/37507408/100420437-6ec29780-30c1-11eb-8a15-26da629dfa95.png)
![微信截图_20201127145601](https://user-images.githubusercontent.com/37507408/100420442-7124f180-30c1-11eb-99f1-b0cce6a59d54.png)

**Comment by Blankj** [comment]
好的 下版本修复

**Comment by Blankj** [comment]
1.30.6 版本已修复
