### ISSUE TITLE
耦合太高了

### ISSUE THREAD

**Issue by BinarySatan** [Blankj/AndroidUtilCode#138]
基本上类和类之间都有关联， 想单用的话 无法直接单拿出来用,

**Comment by Blankj** [comment]
比如？我很多都已经独立出来了，你哪些还看不过去，我看能不能改

**Comment by BinarySatan** [comment]
比如加密的文件 = =， EncryptUtils。

**Comment by BinarySatan** [comment]
如加密工具,EncryptUtils,  如果能改的话 是非常好的,  感谢。  =3=

**Comment by Blankj** [comment]
谢谢提出，是我疏漏了这个

**Comment by ljf1172361058** [comment]
还要 CacheUtils 耦合也高,无法直接拿出来用

**Comment by Blankj** [comment]
@ljf1172361058 CacheUtils 耦合高？你开玩笑吧

**Comment by ljf1172361058** [comment]
部分代码不符合规范

> 在if/else/for/while/do语句中必须使用大括号，即使只有一行代码

**Comment by ljf1172361058** [comment]
@Blankj 感谢解惑,另外我用的是 Android Studio 的阿里编码规范插件,系统自动提示的额,有些出入应该是正常的,不必太在意

**Comment by Blankj** [comment]
阿里的是 java 规范，Android 应该有安卓自己的

**Comment by jp1017** [comment]
666

**Comment by ljf1172361058** [comment]
@Blankj 这话题终结掉它,还是讨论代码有趣 []~(￣▽￣)~*
