### ISSUE TITLE
 可不可以在ActivityUtils.startActivity传extras数据

### ISSUE THREAD

**Issue by kamike** [Blankj/AndroidUtilCode#1382]
ActivityUtils.startActivity有很多重载的方法，可以传基本数据类型的值，但是传putSerializable就不可以。可不可以加一个方法，这样就方便多了，不用传context就随便启动其他界面并传任意值。

 Bundle bundle = new Bundle();
 bundle.putSerializable("extras", infoBean);
 ActivityUtils.startActivity(CoinDetailsActivity.class, bundle);
我看到源码有提供传extras，只是没放出来
![image](https://user-images.githubusercontent.com/3920019/100694436-0e39a000-33ca-11eb-9a6c-cb2d5a0aea19.png)

**Comment by Blankj** [comment]
你再好好看看，有可以传 bundle 的，bundle 是第一个参数
