### ISSUE TITLE
1.3.0 ToastUtils在RTL环境下问题

### ISSUE THREAD

**Issue by linmomo** [Blankj/AndroidUtilCode#1386]
1.3.0的ToastUtils在RTL环境下，Toast会有很多空白，显示不全文本，1.2.9没有这个问题
简洁地描述下 Bug。

- AndroidUtilCode 的版本：utilcode:1.3.0
- 出现 Bug 的设备型号：任意机型
- 设备的 Android 版本：Android 9 、10

**Comment by Blankj** [comment]
1.3.0？

**Comment by linmomo** [comment]
129版本的LTR和RTL的Toast截图
![129LTR](https://user-images.githubusercontent.com/13284924/101976867-79198f80-3c84-11eb-8c57-a55ca6a79c72.png)
![129RTL](https://user-images.githubusercontent.com/13284924/101976869-7ae35300-3c84-11eb-801f-23713aa19e4a.png)
130版本的LTR和RTL的Toast截图
![1 3 0RTL](https://user-images.githubusercontent.com/13284924/101976877-8a629c00-3c84-11eb-8353-c66d1897ba1b.png)
![1 3 0LTR](https://user-images.githubusercontent.com/13284924/101976878-8c2c5f80-3c84-11eb-8fa8-8f3f200f6e3d.png)
英语文本：You need to choose a user first
阿语文本：يجب أن تختار مستخدم أولاً

**Comment by linmomo** [comment]
具体测试版本是1.30.5

**Comment by Blankj** [comment]
1.30.6 版本已修复
