### ISSUE TITLE
ToastUtils  在5.0 Android  小米 redmi note2 上不会显示

### ISSUE THREAD

**Issue by jswn0203** [Blankj/AndroidUtilCode#1389]
## Describe the bug

- The version of AndroidUtilCode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Please delete the current line and the following.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
调用系统的 toast 可以展示吗？

**Comment by jswn0203** [comment]
可以的，我现在升级1.30.5 就没事了，之前时1.29.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Blankj"<notifications@github.com&gt;; 
发送时间: 2020年12月8日(星期二) 下午2:37
收件人: "Blankj/AndroidUtilCode"<AndroidUtilCode@noreply.github.com&gt;; 
抄送: "1016032936"<1016032936@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Blankj/AndroidUtilCode] ToastUtils  在5.0 Android  小米 redmi note2 上不会显示 (#1389)





 
调用系统的 toast 可以展示吗？

**Comment by Blankj** [comment]
好的
