### ISSUE TITLE
拼音测试,"这"  转换出来是"zhei"

### ISSUE THREAD

**Issue by SauceZQ** [Blankj/AndroidUtilCode#139]
好尴尬...

**Comment by Blankj** [comment]
恭喜你，找到bug，这我只能做个判断来解决了

**Comment by jasoncheng911** [comment]
恭喜你，又可以再次强壮你的代码了，在掘金说好要给你pull request的。等着啊 @Blankj

**Comment by Blankj** [comment]
其实这有zhei这个发音，所以这是多音字的问题，我这个pinyinUtils并不包括平常字的多音字转拼音，只包含姓氏的哈 @SauceZQ

**Comment by Blankj** [comment]
@jasoncheng911 come on baby
