### ISSUE TITLE
ToastUtils显示在dialog后面

### ISSUE THREAD

**Issue by SheepYang1993** [Blankj/AndroidUtilCode#1390]
还是会出现被dialog遮挡的问题。
步骤：先弹出了dialog，再显示Toast。
版本：1.30.5
#773

**Comment by flyzend** [comment]
我和你一样的问题，dialog挡住toast
使用 Toast.makeText 不会被dialog挡住。以前用的1.18.6 版本的AUC也不会被挡住。 @Blankj

**Comment by zhoujia456888** [comment]
同样遇到了这个情况，弹出虚拟键盘也会挡住ToastUtils。但是系统的Toast.makeText 不会被挡住。 @Blankj

**Comment by FunTc** [comment]
private static IToast newToast(ToastUtils toastUtils) {
        if (!toastUtils.isNotUseSystemToast) {
            if (NotificationManagerCompat.from(Utils.getApp()).areNotificationsEnabled()) {
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
                    return new SystemToast(toastUtils);
                }
                if (!UtilsBridge.isGrantedDrawOverlays()) {
                    return new SystemToast(toastUtils);
                }
            }
        }

        // not use system or notification disable
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N_MR1) {
            return new WindowManagerToast(toastUtils, WindowManager.LayoutParams.TYPE_TOAST);
        } else if (UtilsBridge.isGrantedDrawOverlays()) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                new WindowManagerToast(toastUtils, WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY);
            } else {
                new WindowManagerToast(toastUtils, WindowManager.LayoutParams.TYPE_PHONE);
            }
        }
        return new ActivityToast(toastUtils);
    }


这段代码是ToastUtils中的478--501行，其中存在一些问题，如果toastUtils.isNotUseSystemToast  = false，就表明我要使用系统自带的Toast显示，但是却还要受能否通知的限制，接着还要受应用上层显示权限是否开启的限制，我觉得这种逻辑是有问题的；
还有495和497行只是new了而没有return

**Comment by wenfengtou** [comment]
遇到同样的问题

**Comment by TmRobust** [comment]
遇到同样的问题.

**Comment by Blankj** [comment]
1.30.6 版本已修复
