### ISSUE TITLE
关于ToastUtils的一点建议

### ISSUE THREAD

**Issue by jingzz1** [Blankj/AndroidUtilCode#1394]
试了公司几部测试机 ，包括原生系统，android10之后即使通知被关闭，toast依然可以正常弹出，所以我想android10之后这个bug应该已经被修补好了
另外关于toast被弹窗挡住的问题，建议topActivity使用windowManager，其他activity使用decorView的方式，这样至少能保证栈顶的toast正常显示，如果刚好出现第二个activity有弹窗挡住toast的情况，只能建议用户finish之后再showToast，或者改变toast的显示位置

**Comment by Blankj** [comment]
这个建议不错

**Comment by Blankj** [comment]
1.30.6 版本已支持
