### ISSUE TITLE
希望可以增加一个在根布局动态添加视图的工具类，如下:

### ISSUE THREAD

**Issue by mao19951015** [Blankj/AndroidUtilCode#1397]
## 可借鉴的

/**
 * 根布局添加视图工具类
 */
public class RootLayoutUtil {
    /**
     * 添加一个视图到屏幕最顶层
     */
    public static void addViewOnWindow(View view, int w, int h, int x, int y) {
        Activity activity = (Activity) view.getContext();
        ViewGroup root = activity.findViewById(android.R.id.content);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(w, h);
        layoutParams.leftMargin = x;
        layoutParams.topMargin = y;
        root.addView(view, -1, layoutParams);
    }

    /**
     * 添加隐藏按钮到当前活动窗口最顶层。隐藏按钮：人眼看不到且得连续点击四次才会触发事件
     */
    public static void addHideButtonOnWindow(Context context, int w, int h, int x, int y, Runnable runnable) {
        Activity activity = (Activity) context;
        ViewGroup root = activity.findViewById(android.R.id.content);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(w, h);
        layoutParams.leftMargin = x;
        layoutParams.topMargin = y;
        View view = new View(activity);
        view.setOnClickListener(new OnMultiClickListener(4) {
            @Override
            public void onTriggerClick(View v) {
                runnable.run();
            }
        });
        root.addView(view, -1, layoutParams);
    }
}

/**
 * 连续点击监听器
 */
public abstract class OnMultiClickListener implements View.OnClickListener {

    private static final long DEFAULT_INTERVAL = 666;

    private final int mTriggerClickCount;
    private final long mClickInterval;

    private long mLastClickTime;
    private int mClickCount;

    public OnMultiClickListener(int triggerClickCount) {
        this(triggerClickCount, DEFAULT_INTERVAL);
    }

    public OnMultiClickListener(int triggerClickCount, long clickInterval) {
        this.mTriggerClickCount = triggerClickCount;
        this.mClickInterval = clickInterval;
    }

    public abstract void onTriggerClick(View v);

    public void onBeforeTriggerClick(View v, int count) {
    }

    @Override
    final public void onClick(View v) {
        if (mTriggerClickCount <= 1) {
            onTriggerClick(v);
            return;
        }
        long curTime = System.currentTimeMillis();

        if (curTime - mLastClickTime < mClickInterval) {
            mClickCount++;
            if (mClickCount == mTriggerClickCount) {
                onTriggerClick(v);
            } else if (mClickCount < mTriggerClickCount) {
                onBeforeTriggerClick(v, mClickCount);
            } else {
                mClickCount = 1;
                onBeforeTriggerClick(v, mClickCount);
            }
        } else {
            mClickCount = 1;
            onBeforeTriggerClick(v, mClickCount);
        }
        mLastClickTime = curTime;
    }
}

**Comment by Blankj** [comment]
增加视图这个自己写一个吧，连续点击这个 ClickUtils 里就有
