### ISSUE TITLE
强烈希望在ToastUtils中，加入一个方法，能手动将全局的showShort()和showLong()变为以前的黑色背景，因为黑色比白色好看!!!

### ISSUE THREAD

**Issue by NightMoonCat** [Blankj/AndroidUtilCode#1399]
如题，黑色比白色好看!!!
但是代码太漂亮了，不想自己重写玷污了它(QAQ，其实是懒)，所以希望作者增加方法

**Comment by zhoujia456888** [comment]
可以自己定义一个ToastUtils1,调用utilcode.ToastUtils的make.setBgColor、make.setBgResource 、make.setTextColor等方法

**Comment by FunTc** [comment]
ToastUtils中带有方法可以设置，ToastUtils.getDefaultMaker().setMode(ToastUtils.MODE.DARK)就可以是黑色的背景了，如果颜色达不到你的预期，可以调用ToastUtils.getDefaultMaker().setBgColor()和ToastUtils.getDefaultMaker().setTextColor()来自定义，不过最新版的ToastUtils还存在Bug，请注意

**Comment by kangdawei** [comment]
> ToastUtils中带有方法可以设置，ToastUtils.getDefaultMaker().setMode(ToastUtils.MODE.DARK)就可以是黑色的背景了，如果颜色达不到你的预期，可以调用ToastUtils.getDefaultMaker().setBgColor()和ToastUtils.getDefaultMaker().setTextColor()来自定义，不过最新版的ToastUtils还存在Bug，请注意

implementation 'com.blankj:utilcodex:1.30.5'  里面有

**Comment by NightMoonCat** [comment]
非常感谢大家的回复，确实已经各位提供的方式处理了
