### ISSUE TITLE
1.30.0 ImageUtils.getBitmap(int resId)方法获取R.mipmap.ic_launcher返回null

### ISSUE THREAD

**Issue by qq549631030** [Blankj/AndroidUtilCode#1402]
## 描述 Bug

ImageUtils.getBitmap(@DrawableRes final int resId)方法1.30.0后改成了BitmapFactory.decodeResource()方法来实现，会导致获取应用logo(R.mipmap.ic_launcher)这样的AdaptiveIconDrawable返回null

- AndroidUtilCode 的版本：utilcode:1.30.0
- 出现 Bug 的设备型号：Mate30 5G
- 设备的 Android 版本：API 29

## 相关代码

```
ic_ic_launcher.xml

<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>

ImageUtils.getBitmap(R.mipmap.ic_launcher)
```

**Comment by Blankj** [comment]
1.30.6 版本已修复
