### ISSUE TITLE
ToastUtils.showLong 内存泄露

### ISSUE THREAD

**Issue by qiushui95** [Blankj/AndroidUtilCode#1410]
## 描述 Bug

rt

- AndroidUtilCode 的版本：1.30.5
- 出现 Bug 的设备型号：小米Mix 2s
- 设备的 Android 版本：API 29
- LeakCanary 版本:2.6

直接运行的本项目

## 截图

![QQ图片20201228171008](https://user-images.githubusercontent.com/22932494/103203343-a37b7600-492f-11eb-888c-ea9ae1151daa.jpg)

**Comment by Blankj** [comment]
1.30.6 版本已修复
