### ISSUE TITLE
AppUtils.registerAppStatusChangedListener在冷启动的时候，不会调用onForeground

### ISSUE THREAD

**Issue by gentlemansolo** [Blankj/AndroidUtilCode#1411]
在UtilsActivityLifecycleImpl内部代码中mIsBackground初始状态为false，我建议是改为true，让冷启动能够调用onForeground

**Comment by Blankj** [comment]
1.30.6 版本已修复

**Comment by qweenhool** [comment]
现在测试发现，冷启动会调用onForeground，但是应用第一次进入分屏模式的时候会调用两次onForeground
