### ISSUE TITLE
PhoneUtils.dial() URI parse problem

### ISSUE THREAD

**Issue by NotNotMarshall** [Blankj/AndroidUtilCode#1412]
Hello there! The dial() function cannot handle USSD codes properly and this is due to the hash # character not being encoded in the URI string that gets passed to the Dialer intent. So whenever you dial for example *123# it calls *123 instead of dialing the USSD code *123#.. It strips out the hash (pound sign) at the end due to not encoding it.

This fault is present since the first version until Utilcode v1.30.0 and it happens in most devices (personally tested on SAMSUNG and OnePlus).

Just to make clear this is not a bug that crashes anything, its just a mistake in the code.

This is your code:
```
public static Intent getCallIntent(final String phoneNumber) {
        Intent intent = new Intent("android.intent.action.CALL", Uri.parse("tel:" + phoneNumber));
        return getIntent(intent, true);
}
```

And this is how it should be done:
```
public static Intent getCallIntent(final String phoneNumber) {
    String finalUriString = "";
    for(char c : phoneNumber.toCharArray()) {
        if(c == '#')
            finalUriString += Uri.encode("#");
        else
            finalUriString += c;
    }
        Intent intent = new Intent("android.intent.action.CALL", Uri.parse("tel:" + finalUriString));
        return getIntent(intent, true);
}
```

Once again thanks for this great library, and good luck.

**Comment by NotNotMarshall** [comment]
@Blankj and by the way for now the only way to handle this is to hardcode a string at the end like so:
`PhoneUtils.call("*123${Uri.encode("#")}")`

**Comment by NotNotMarshall** [comment]
@Blankj  yo!

**Comment by Blankj** [comment]
the version of 1.30.6 fix it.
