### ISSUE TITLE
BarUtils.setNavBarVisibility的Bug

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#1414]
## Describe the bug

设置隐藏导航栏之后，TabLayout被遮挡一部分:
```
BarUtils.setNavBarVisibility(this, false);
```
版本是1.30.5, 机型是华为mate20， Android10
![image](https://user-images.githubusercontent.com/4426715/103333264-51119500-4aa8-11eb-9eb3-c13733c8a289.png)

**Comment by Blankj** [comment]
布局重新 layout 一下，这就不是我这的 bug 了已经
