### ISSUE TITLE
1.30.5 版本LogUtils打印时字符串过长显示不全，用系统的log打印可以全部显示

### ISSUE THREAD

**Issue by MrXiaoLiu** [Blankj/AndroidUtilCode#1416]
LogUtils.e("test","https://wepozt-oss.oss-ap-southeast-1.aliyuncs.com/goods_pic/414508937927296_1609380644574.png?Expires=1609385086&OSSAccessKeyId=STS.NUE6g5znKtwxnVKXN6XaGBy1U&Signature=mk2rukxQs7HADCphRWjD1UDKSTQ%3D&security-token=CAISiwJ1q6Ft5B2yfSjIr5bwfd2Bl7Fqw7WTbHD6vE5jVO5rrbyatzz2IHhLeXRtCOgcv/U2mG1Z6vgSlrh%2BW4NIX0rNaY5t9ZlN9wqkbtIoallrbvpW5qe%2BEE2/VjTZvqaLEcibIfrZfvCyESOm8gZ43br9cxi7QlWhKufnoJV7b9MRLGLaBHg8c7UwHAZ5r9IAPnb8LOukNgWQ4lDdF011oAFx%2BwgdgOadupTBtUWD3QOmlrdM/tSvcsCeApMybMslYbCcx/drc6fN6ilU5iVR%2Bb1%2B5K4%2Bom%2BY44zAUgELskTfb7eFroM/NnxwYqkrBqhDt%2BPgkv51vOPekYntwgpKJ/tSVynPtGNucy92lokagAGYuZkmm7dCtVcPLpkYUSFEFzOA4uJDFPUDJu3C4D4CEFVyREOx%2Bw5W7Fwjw0kwLEBfk4PR5rJCaM/uHb7URe8gXUTH3yjvklaXVdua0NIrmXwGa7IkaR3hFDadUFcCoXg8aGayVjA9%2BugmzZzHhXcA1dsMJ3TBKs4qeDBxwyBQfA%3D%3D");
        Log.e("test","https://wepozt-oss.oss-ap-southeast-1.aliyuncs.com/goods_pic/414508937927296_1609380644574.png?Expires=1609385086&OSSAccessKeyId=STS.NUE6g5znKtwxnVKXN6XaGBy1U&Signature=mk2rukxQs7HADCphRWjD1UDKSTQ%3D&security-token=CAISiwJ1q6Ft5B2yfSjIr5bwfd2Bl7Fqw7WTbHD6vE5jVO5rrbyatzz2IHhLeXRtCOgcv/U2mG1Z6vgSlrh%2BW4NIX0rNaY5t9ZlN9wqkbtIoallrbvpW5qe%2BEE2/VjTZvqaLEcibIfrZfvCyESOm8gZ43br9cxi7QlWhKufnoJV7b9MRLGLaBHg8c7UwHAZ5r9IAPnb8LOukNgWQ4lDdF011oAFx%2BwgdgOadupTBtUWD3QOmlrdM/tSvcsCeApMybMslYbCcx/drc6fN6ilU5iVR%2Bb1%2B5K4%2Bom%2BY44zAUgELskTfb7eFroM/NnxwYqkrBqhDt%2BPgkv51vOPekYntwgpKJ/tSVynPtGNucy92lokagAGYuZkmm7dCtVcPLpkYUSFEFzOA4uJDFPUDJu3C4D4CEFVyREOx%2Bw5W7Fwjw0kwLEBfk4PR5rJCaM/uHb7URe8gXUTH3yjvklaXVdua0NIrmXwGa7IkaR3hFDadUFcCoXg8aGayVjA9%2BugmzZzHhXcA1dsMJ3TBKs4qeDBxwyBQfA%3D%3D");

**Comment by Blankj** [comment]
我的 LogUtils.e 第一个参数不是 tag，此时 tag 默认是类名在你不设置 globalTag 时，你要用 tag 需要使用 LogUtils.eTag。
![image](https://user-images.githubusercontent.com/17978187/103433450-fa34c880-4c2b-11eb-958a-3e78cf9fa5cc.png)
