### ISSUE TITLE
ToastUtils 内存泄漏

### ISSUE THREAD

**Issue by boboqun** [Blankj/AndroidUtilCode#1425]
## 描述 Bug

简洁地描述下 Bug。

- AndroidUtilCode 的版本：例如 utilcode:1.30.5 
- 出现 Bug 的设备型号：OnePlus 7Pro
- 设备的 Android 版本：API 29

## 截图
![Screenshot_20210113-101104](https://user-images.githubusercontent.com/20718624/104397651-33542d80-5588-11eb-972a-e7cac88b2bf0.jpg)
![Screenshot_20210113-101111](https://user-images.githubusercontent.com/20718624/104397657-37804b00-5588-11eb-92fd-0a6de61040a3.jpg)

**Comment by Blankj** [comment]
1.30.6 版本已修复
