### ISSUE TITLE
1.30.5版本的依赖和AndroidAutoSize的最新版在6.0的机器上有冲突

### ISSUE THREAD

**Issue by mengzhidaren** [Blankj/AndroidUtilCode#1427]
## Bug描述 
新版本似乎和其它项目有冲突
同时引用以下两个库文件
····
//屏幕适配方案 https://github.com/JessYanCoding/AndroidAutoSize
api 'me.jessyan:autosize:1.2.1'
api 'com.blankj:utilcodex:1.30.5'
····
AndroidAutoSize在6.0的平板上(瑞芯微RK3288平台)的自适应布局失效了，
但是在模拟器上确是正常的 测试了下三星和华为也是正常的
但是就在瑞芯微RK3288平台的平板上就无效了，
很神奇的bug我尝试捕获问题但没有结果
如果把版本回退到 utilcode:1.26.0 平板就又正常了，
重新升到utilcodex:1.30.5 之后自适应布局又失效了。
连续试了几次都是这样，现在只能用低版本适配了

- AndroidUtilCode 的版本：utilcodex:1.30.5  
- 出现 Bug 的设备型号：瑞芯微RK3288
- 设备的 Android 版本： API 22

**Comment by Blankj** [comment]
这应该跟我的库没关系
