### ISSUE TITLE
ToastUtils.showShort这个方法无法显示阿拉伯语

### ISSUE THREAD

**Issue by ToFigting** [Blankj/AndroidUtilCode#1428]
能够弹窗,但是无法显示阿拉伯语的文本.

**Comment by ToFigting** [comment]
补充一下暂时在手机SDK版本28发现这个问题

**Comment by Liangwenb** [comment]
+1  无法显示阿拉伯文.

**Comment by Blankj** [comment]
1.30.6 版本已修复

**Comment by ToFigting** [comment]
你好 抱歉我想问一下之前无法显示阿拉伯语的原因是什么呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Blankj/AndroidUtilCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 凌晨3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Blankj/AndroidUtilCode] ToastUtils.showShort这个方法无法显示阿拉伯语 (#1428)





 
1.30.6 版本已修复

**Comment by Blankj** [comment]
rtl 写的布局 wrapcontent 文本支持有问题
