### ISSUE TITLE
ActivityUtils.getTopActivity()不准确的问题

### ISSUE THREAD

**Issue by gentlemansolo** [Blankj/AndroidUtilCode#1429]
ActivityUtils.getTopActivity()在特殊条件下会不准确

例子，共有2个Activity在堆栈中，分别为A和B，B是**全透明**的Activity，当A启动B，然后启动分屏时，B会重新创建，A也跟着重新创建，这个时候TopActivity变成了A，但是实际上TopActivity应该为B

**Comment by Blankj** [comment]
那你是否有解决方案？

**Comment by gentlemansolo** [comment]
没有，我这边禁止重新创建Activity来避免以上的bug
