### ISSUE TITLE
AppUtils类下;installApp(Context context, File file)这个安装函数在7.0失效，4.0好使，请您检测下代码

### ISSUE THREAD

**Issue by SpringRiverLee** [Blankj/AndroidUtilCode#143]

**Comment by Blankj** [comment]
7.0本来就没支持呢，相关参考可以看之前的issue，只支持到6，7的话还要在清单文件里添加

**Comment by SpringRiverLee** [comment]
IntentUtils.getInstallAppIntent(file)这个函数里面代码
    /**
     * 获取安装App(支持6.0)的意图
     *
     * @param file 文件
     * @return intent
     */
    public static Intent getInstallAppIntent(File file) {
        if (file == null) return null;
        Intent intent = new Intent(Intent.ACTION_VIEW);
        String type;

        if (Build.VERSION.SDK_INT < 23) {
            type = "application/vnd.android.package-archive";
        } else {
            type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(FileUtils.getFileExtension(file));
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(Utils.getContext(), "com.your.package.fileProvider", file);
            intent.setDataAndType(contentUri, type);
        }
        intent.setDataAndType(Uri.fromFile(file), type);
        return intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    }
我疑问其中的if 语句:如下        
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(Utils.getContext(), "com.your.package.fileProvider", file);
            intent.setDataAndType(contentUri, type);
        }
这个if语句什么时候用到的，因为下面intent又重新设置了setDataAndType。
希望您指导解疑下

**Comment by Blankj** [comment]
根据条件就可以看出最后那个是7.0的，因为7.0比较麻烦，我还没写，所以就先放着的

**Comment by 11621546** [comment]
你好  这个7.0的  什么时候能完善呀   期待

**Comment by Blankj** [comment]
7.0的你们暂时先自己写吧，我手头也没机子，我暂时也没空写

**Comment by IsMrWu** [comment]
7.0要在清单文件里制定FileProvider

**Comment by Blankj** [comment]
嗯，你可以看我现在的demo，已经支持了

**Comment by Blankj** [comment]
@11621546 已完善，今天发布版本

**Comment by Blankj** [comment]
1.5.1已发布，试试吧
