### ISSUE TITLE
PermissionUtils bug反馈

### ISSUE THREAD

**Issue by weileifrank** [Blankj/AndroidUtilCode#1431]
## 描述 Bug

PermissionUtils.isGrantedDrawOverlays()在部分机型上一直返回true

- AndroidUtilCode 的版本：1.30.1
- 出现 Bug 的设备型号：vivo X9i
- 设备的 Android 版本：android 7.1.2   (27)

## 相关代码
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M){
            if (PermissionUtils.isGrantedDrawOverlays()) {
                 println(true)
            }else{
                 println(false)
            }
        }else{
            println(true)
        }

**Comment by Blankj** [comment]
我只是按照官方给的来封装 国产机器那可能需要自己适配吧
