### ISSUE TITLE
ToastUtils调用areNotificationsEnabled出现android.os.DeadSystemException

### ISSUE THREAD

**Issue by caiyoufei** [Blankj/AndroidUtilCode#1442]
使用版本 "com.blankj:utilcodex:1.30.5"
异常信息如下
![image](https://user-images.githubusercontent.com/11989916/106087339-5e2cad00-6156-11eb-9633-9ce778e37769.png)

**Comment by caiyoufei** [comment]
手机信息如下
![image](https://user-images.githubusercontent.com/11989916/106087521-c54a6180-6156-11eb-9f1e-3a9a63dc035c.png)

**Comment by caiyoufei** [comment]
疑似模拟器导致

**Comment by tackleboz** [comment]
That's the situations that I'm running into I think that it's a dead end
file thanks fir the help
