### ISSUE TITLE
ToastUtils 在未开启通知栏权限的时候，toast显示到顶部适配问题

### ISSUE THREAD

**Issue by Muwl** [Blankj/AndroidUtilCode#1455]
## 描述 Bug

ToastUtils 在为开启通知栏权限的时候，我看最后源码会走到 showWithActivity方法，在这个方法中，bottomMargin 和leftMargin，但是比如说我设置的Gravity是 top的时候。然后这是YOffset因为是依据顶部的偏移量+状态栏的高度，但是目前看到好像没有适配，导致设置Gravity的时候，如果通知栏没有开启，显示就会和状态栏重叠，下面的代码是源码有问题的位置

## 代码

 private void showWithActivity(final Activity activity, final int index, boolean useAnim) {
            final Window window = activity.getWindow();
            if (window != null) {
                final ViewGroup decorView = (ViewGroup) window.getDecorView();
                FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(
                        ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT
                );
              ！！！  lp.gravity = mToast.getGravity();
              ！！！lp.bottomMargin = mToast.getYOffset() + UtilsBridge.getNavBarHeight();
              ！！！  lp.leftMargin = mToast.getXOffset();
                View toastViewSnapshot = getToastViewSnapshot(index);
                if (useAnim) {
                    toastViewSnapshot.setAlpha(0);
                    toastViewSnapshot.animate().alpha(1).setDuration(200).start();
                }
                decorView.addView(toastViewSnapshot, lp);
            }
        }

**Comment by klzhong69** [comment]
这个影响挺大的，什么时候解决啊

**Comment by Blankj** [comment]
1.30.6 版本已修复
