### ISSUE TITLE
ToastUtil在App获取了SYSTEM_ALERT_WINDOW权限之后会被Dialog盖住，导致看不到吐司信息

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#1460]
## 描述 Bug
应用申请了下面的权限后就出现问题了，吐司会对话框盖住，只要Dialog显示时，吐司就看不到了。
```
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
```

- AndroidUtilCode 的版本：1.30.5
- 出现 Bug 的设备型号：华为Mate20等多个手机
- 设备的 Android 版本：Android10

**Comment by Blankj** [comment]
升级到最新版本试试
