### ISSUE TITLE
TimeUtils bug

### ISSUE THREAD

**Issue by unengchen** [Blankj/AndroidUtilCode#1462]
TimeUtils.millis2String() 有问题，把50_000 毫秒（也就是50秒）转换为时间显示（HH:mm:ss)时，结果是08：00：50，显然这个结果是不正确的，应该是00：00：50

**Comment by unengchen** [comment]
换了十几个毫秒数，无论大小也是不对的，应该是所有毫秒数转换为（HH:mm:ss)这个格式的时候都是不正确的

**Comment by unengchen** [comment]
是不是时区设置的问题

**Comment by Blankj** [comment]
看官方注释呀，HH:mm:ss 传入的时间戳是以 1970年1月1日 00:00 开始计算，我们在东八区就是 08:00 开始算，你这么简单的计算直接整除取余不就好了么

**Comment by unengchen** [comment]
好的，谢谢
