### ISSUE TITLE
代码渲染的问题

### ISSUE THREAD

**Issue by ice1000** [Blankj/AndroidUtilCode#15]
[屏幕相关](https://github.com/Blankj/AndroidUtilCode/blob/master/about_screen.md)的**设置屏幕为横屏**那一栏的代码渲染有问题，没渲染出Java高亮。 :joy:

**Comment by Blankj** [comment]
这位施主心细可嘉，不知道怎么就冲突了不给高亮了，它任性

**Comment by ice1000** [comment]
不是冲突了啊，是没指定高亮啊，需要pull request吗？
