### ISSUE TITLE
Kotlin codebase

### ISSUE THREAD

**Issue by NotNotMarshall** [Blankj/AndroidUtilCode#1501]
Hello!
Any plans to move the codebase to Kotlin? Besides making significant performance improvements, it will also reduce the library size, and as you know will have much less boilerplate code. Even though down under they're both getting executed in JVM.
Knowing how busy you are, but still I'm asking if you have any plans to move the codebase to Kotlin or at least assign a team of people to do it? 

Thank you and keep up the good work!

**Comment by NotNotMarshall** [comment]
@Blankj 他妈的，兄弟！？

**Comment by Blankj** [comment]
没有这个必要哈

**Comment by NotNotMarshall** [comment]
> 没有这个必要哈

OK
