### ISSUE TITLE
AppUtils.getAppVersionName()返回null 

### ISSUE THREAD

**Issue by sceneren** [Blankj/AndroidUtilCode#1517]
## 描述 Bug
AppUtils.getAppVersionName()返回null 、AppUtils.getAppVersionCode()返回0

- AndroidUtilCode 的版本：1.30.6
- 出现 Bug 的设备型号：一加6T
- 设备的 Android 版本：30

## 相关代码
AppUtils.getAppVersionName()
AppUtils.getAppVersionCode()

```
put your code here
```

## 异常堆栈

```
put the stack of crash here
```

## 截图

![image](https://user-images.githubusercontent.com/6612998/124858097-06854e00-dfe0-11eb-89fc-b0374c19f7bc.png)
![image](https://user-images.githubusercontent.com/6612998/124858596-f6ba3980-dfe0-11eb-8930-04dff79a29fc.png)

**Comment by Reginer** [comment]
是对应的应用没有设置版本号

**Comment by sceneren** [comment]
我自己也发现了
