### ISSUE TITLE
使用 LanguageUtils 设置成功后打开新Activity 就出问题了

### ISSUE THREAD

**Issue by chapliny** [Blankj/AndroidUtilCode#1523]
如题
1. 在设置页面 比如设置了英文,然后已经打开的所有页面都正常,
2. 打开一个新的页面后,新的页面 就显示了中文,
3.然后再返回到 mainActivity 里面的fragment 也显示中文.
4,当重新设置语言后,又好了

**Comment by scsfwgy** [comment]
> 是因为加了firebase sdk 导致的问题，

我也遇到了，怎么处理？直接升级firebase sdk 就OK吗？
