### ISSUE TITLE
minSdkVersion 19....

### ISSUE THREAD

**Issue by xiang473535976** [Blankj/AndroidUtilCode#156]
minSdkVersion 19....   这样会让很多低版本的手机没法用 兼容性降低了   希望改进哈 谢谢     期待你 的6.0动态授权哈

**Comment by Blankj** [comment]
等我几天后的大版本吧

**Comment by xiang473535976** [comment]
谢谢大婶    新项目刚开始 正在用      毕竟19兼容性低了

**Comment by Blankj** [comment]
我推荐你还是用到什么就拷贝什么，不要一次性导入

**Comment by Xanthuim** [comment]
`
<?xml version="1.0" encoding="utf-8"?>
<manifest
    package="com.blankj.utilcode"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:versionCode="16"
    android:versionName="1.3.7" >

    <uses-sdk android:minSdkVersion="19" />

</manifest>
`
这让低版本的情何以堪啊？没法用1.3.7

**Comment by Blankj** [comment]
今天就更新
