### ISSUE TITLE
期待总结相关代码的Kotlin+anko版本

### ISSUE THREAD

**Issue by ice1000** [Blankj/AndroidUtilCode#16]
毕竟现在Kotlin也是Android开发的生力军了不是吗

先咨询一下，你们觉得什么样的排版合适（两门语言的当然要分开啦），然后我发个pull request给你们。 :+1:

**Comment by Blankj** [comment]
这个我是还没用Kotlin开发过，只知道些语法方面的，毕竟谷歌还没收录Kotlin，至于之后会不会，那就之后再说了，对这方面的兴趣可以有，但运用到时机开发的话还是风险有风险的，我还是一枚菜鸟，Java都没啃完呢，23333
