### ISSUE TITLE
Android 原生系统NetWorkUtils.isAvailableByPing()工作异常

### ISSUE THREAD

**Issue by walkthehorizon** [Blankj/AndroidUtilCode#161]
NetWorkUtils的isAvailableByPing()方法在Ping的时候successMsg如下，PING 223.5.5.5 (223.5.5.5) 56(84) bytes of data.--- 223.5.5.5 ping statistics ---1 packets transmitted, 0 received, 100% packet loss, time 0ms，测试手机网络正常，也能联网，系统是Google原生7.1，

**Comment by Blankj** [comment]
这不就是对的么？有什么错

**Comment by walkthehorizon** [comment]
对该命令我不是太熟悉，具体的表现是我分别在多个手机上测试，比如华为手机这个命令在表现正常，但在摩托罗拉的原生Android上发生上面的100% packet loss，我确认网络是可以连通的，但不知是什么原因导致的无法ping通阿里云

**Comment by jp1017** [comment]
多换几个dns测试咯，ping 8.8.8.8, ping 114.114.114.114....

**Comment by walkthehorizon** [comment]
刚刚再次测试了下，发现除了阿里云的223.5.5.5，114.114.114.114和119.29.29.29等公用DNS也可以ping通了，可能是网络的问题吧
