### ISSUE TITLE
AppUtils.getInstallAppIntent() 方法有错误

### ISSUE THREAD

**Issue by KnifeStone** [Blankj/AndroidUtilCode#163]
`public static Intent getInstallAppIntent(File file) {
        if (file == null) return null;
        Intent intent = new Intent(Intent.ACTION_VIEW);
        String type;

        if (Build.VERSION.SDK_INT < 23) {
            type = "application/vnd.android.package-archive";
        } else {
            type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(FileUtils.getFileExtension(file));
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(Utils.getContext(), "com.your.package.fileProvider", file);
            intent.setDataAndType(contentUri, type);//这里应该直接 return intent;
        }
        intent.setDataAndType(Uri.fromFile(file), type);
        return intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    }`

**Comment by Blankj** [comment]
嗯，这个7.0安装还没适配

**Comment by Blankj** [comment]
已适配7.0
