### ISSUE TITLE
Git Clone 最新的项目跑不起来,狗哥

### ISSUE THREAD

**Issue by lydlovezjr** [Blankj/AndroidUtilCode#1631]
Caused by: groovy.lang.MissingPropertyException: Cannot get property 'ossrhUsername' on extra properties extension as it does not exist

**Comment by liubiaoren** [comment]
我也是这个提示，怎么解决的？

**Comment by Blankj** [comment]
全局搜索下把使用到的这个脚本的地方注视掉就好了吧，这是发布 mavenCentral 用的，你们应该用不到

**Comment by lydlovezjr** [comment]
AndroidUtilCode\config\publish.gradle

**Comment by huanshangliuying** [comment]
![image](https://github.com/Blankj/AndroidUtilCode/assets/114646504/6ebdb720-5c85-4119-be37-a47c466fd91b)
![image](https://github.com/Blankj/AndroidUtilCode/assets/114646504/b37b5e12-1acc-42c9-be86-caf940619136)
注释掉确实就好使了

**Comment by wanghuasheng** [comment]
你这个截图简单明了
