### ISSUE TITLE
LanguageUtils.applyLanguage(),上传Google play后失效问题

### ISSUE THREAD

**Issue by kimljx** [Blankj/AndroidUtilCode#1633]
## Describe the bug

LanguageUtils.applyLanguage(),debug+release打包的apk没问题。但是打包aab上传Google play下载下来后无法实现切换语言

- The version of AndroidUtilCode: 1.30.0
- The device: 红米k40
- The version of device: api 30

## The code of bug

  val spanish = Locale("es", "ES")
 LanguageUtils.applyLanguage(spanish, true)

**Comment by kimljx** [comment]
Google aab 分发问题

**Comment by renhe2020** [comment]
aab分发问题，动态加载，在app下build.gradle加上这段就好了
bundle {
        language {
            enableSplit = false
        }
    }
