### ISSUE TITLE
什么辣鸡工具类啊，不行就别弄了

### ISSUE THREAD

**Issue by lwl456789** [Blankj/AndroidUtilCode#1642]
要弄就好好弄啊，要是不维护了就把库关了。一堆问题也不修改，就在这坑人。。。。。

**Comment by fighterwk** [comment]
有问题你说出来啊！

**Comment by rgdzh1** [comment]
你可以自己解决遇到的问题, 为什么要苛责作者, 他开源出来没有问你要一分钱, 怎么就成作者坑你了. 这个库已经非常优秀了.
