### ISSUE TITLE
球球了，把库关了吧

### ISSUE THREAD

**Issue by lwl456789** [Blankj/AndroidUtilCode#1643]
RT

**Comment by zhtoo** [comment]
话说你是不是不会用啊，不会用可以提啊，没人笑话你。库里面的工具类都是可以单独拿出来用的。因为作者做了封装，部分类需要自己改下代码的。嗯，估计你是不会自己改代码才会提这样的问题吧。

**Comment by Huazhiling** [comment]
有些人自己本事不够，怪别人太强，然后也不肯学，还要别人停下脚步。

**Comment by southsala** [comment]
有些人自己本事不够，怪别人太强，然后也不肯学，还要别人停下脚步。

**Comment by lwl456789** [comment]
无语，能别再舔了吗。有问题不修改一直在这里误导别人，给别人挖坑。技术好就不能接受批评与提问了？

**Comment by chshp1234** [comment]
什么几把标题,害我没找到,心虚?

**Comment by lwl456789** [comment]
只是不想取闹而已，对于听不进话的人没必要争吵

**Comment by chshp1234** [comment]
> 只是不想取闹而已，对于听不进话的人没必要争吵

去掉"而已",可组成歌词.兄弟文采不错,可惜是个喷子.

**Comment by zhtoo** [comment]
> 无语，能别再舔了吗。有问题不修改一直在这里误导别人，给别人挖坑。技术好就不能接受批评与提问了？

你用这个库给作者钱了么？有问题你提问题，作者没改，自己不会看源码改么？用开源库这点觉悟都没有么？

**Comment by lwl456789** [comment]
对这个库我并没有任何不敬，确实很全，我自己也star,fork了。遇到的问题已经修改完了，遇到的问题早在之前就已经提了。一直不修改难道不是在给别人挖坑吗。

我喷啥了。。。。有问题还不能提了？一直不修改在这不是误导别人

**Comment by lwl456789** [comment]
不回了，dddd

**Comment by chshp1234** [comment]
> 对这个库我并没有任何不敬，确实很全，我自己也star,fork了。遇到的问题已经修改完了，遇到的问题早在之前就已经提了。一直不修改难道不是在给别人挖坑吗。
> 
> 我喷啥了。。。。有问题还不能提了？一直不修改在这不是误导别人

有啥问题提出来甩作者脸上,或者我帮你甩作者脸上.u1s1市面上莫名死亡的库太多了,作者这个库算是很良心了,而且只是个工具类,自己改也方便.所以只是好奇你到底在怨啥?
