### ISSUE TITLE
FileUtils中getFileLines()方法获取的文件行数比目测的大1？

### ISSUE THREAD

**Issue by zwping** [Blankj/AndroidUtilCode#165]
获取的行数大于目测的行数，是知识点问题吗？

**Comment by Blankj** [comment]
你拿AS打开是多少行？代码跑出来是多少行？

**Comment by zwping** [comment]
真机测试。使用writeFileFromString("123123\r\n")写入，readFile2String().size 和实际行数一致，

仅仅只有getFileLines()获取的行数大于实际行数

**Comment by Blankj** [comment]
readFile2String().size获取的不是行数吧，你这个写完应该是2行啊
