### ISSUE TITLE
BarUtils中的bug

### ISSUE THREAD

**Issue by wimvogt** [Blankj/AndroidUtilCode#167]
setColor(Activity activity, int color, int statusBarAlpha) 
当满足第二个条件>4.4 && <5.0时需要添加
       decorView.getChildAt(0).setFitsSystemWindows(false);
这段代码，否则会出现布局内容顶到了状态栏的情况

**Comment by Blankj** [comment]
这个我没具体测过，那我先把你的加进来好了

**Comment by wimvogt** [comment]
嗯，添加前后你那可以先测下，大概什么时候会有新版本？
