### ISSUE TITLE
反射获取复杂结构属性值

### ISSUE THREAD

**Issue by CGreen11** [Blankj/AndroidUtilCode#1681]
## 描述需求

拥有一个类实例对象，该类包含一个接口的实现类，但是不知道是哪个实现类。以这样的方式嵌套n次，最后拿到最后一个节点的成员变量string值。实际场景类似代码监控当前Activity请求的url链接。

## 可借鉴的

依据是否包含孙子对象来确定子对象的具体实现类吗？

**Comment by CGreen11** [comment]
DActivity  {
    AInterface a;
}
debug 模式能看到DActivity  
                                         --》a
                                                 --》b
                                                        --》c  
                                                                 ...... 
                                                                       --》string="www.www.www"

**Comment by shouzhong** [comment]
首先网络请求是否属于自己的业务代码，如果是的话，我觉得不如自己弄个拦截器之类的东西，这样更好维护，感觉更重要的是代码要规范化，类似这种需求实现起来就更简单

**Comment by CGreen11** [comment]
万物可用穷举法
