### ISSUE TITLE
 内存泄漏

### ISSUE THREAD

**Issue by vizoss** [Blankj/AndroidUtilCode#1688]
随便新开一个工程，app的build.gradle文件中添加依赖 ```implementation 'com.blankj:utilcodex:1.31.0'```，然后用不调用lib代码，启动程序，用 ```adb shell dumpsys meminfo 包名```, 显示2个activity，退出程序，在使用adb shell 命令，显示残留一个activity；去掉依赖则正常

**Comment by majunm** [comment]
我也发现了,但是不知道是哪个activity在内存中? 我称之为影子activity, 奇怪的是leakcanary也没提示有泄漏,反正查内存就是2个activity

**Comment by majunm** [comment]
![image](https://user-images.githubusercontent.com/5853418/186049277-f734ab5a-e9dd-434e-a2b4-ae5d287716dc.png)

**Comment by adffice** [comment]
首先该库会通过`com.blankj.utilcode.util.UtilsFileProvider` 对自己进行初始化。如下图：
![image](https://user-images.githubusercontent.com/2122729/186385025-e2c62780-f191-4666-a255-6d82eddd8eb0.png)
然后在初始化过程中会注册`Activity`生命周期回调的实现类`UtilsActivityLifecycleImpl`，在这里就会一个`Activity`静态对象。
![image](https://user-images.githubusercontent.com/2122729/186384293-7ed3fae9-586b-46fa-a7b0-a3de3758f26e.png)

**Comment by majunm** [comment]
666

> 首先该库会通过`com.blankj.utilcode.util.UtilsFileProvider` 对自己进行初始化。如下图： ![image](https://user-images.githubusercontent.com/2122729/186385025-e2c62780-f191-4666-a255-6d82eddd8eb0.png) 然后在初始化过程中会注册`Activity`生命周期回调的实现类`UtilsActivityLifecycleImpl`，在这里就会一个`Activity`静态对象。 ![image](https://user-images.githubusercontent.com/2122729/186384293-7ed3fae9-586b-46fa-a7b0-a3de3758f26e.png)

666

**Comment by Blankj** [comment]
Activity 没挂载到生命周期里怎么可能会内存泄漏呢，你试试看随便 new static Activity 看会不会内存泄漏，我这个只是用来占位的而已

**Comment by majunm** [comment]
> 
我没说这个泄漏啊

**Comment by vizoss** [comment]
> 首先该库会通过`com.blankj.utilcode.util.UtilsFileProvider` 对自己进行初始化。如下图： ![image](https://user-images.githubusercontent.com/2122729/186385025-e2c62780-f191-4666-a255-6d82eddd8eb0.png) 然后在初始化过程中会注册`Activity`生命周期回调的实现类`UtilsActivityLifecycleImpl`，在这里就会一个`Activity`静态对象。 ![image](https://user-images.githubusercontent.com/2122729/186384293-7ed3fae9-586b-46fa-a7b0-a3de3758f26e.png)
