### ISSUE TITLE
现在使用就这样

### ISSUE THREAD

**Issue by zhuzhushang** [Blankj/AndroidUtilCode#169]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.blankj:utilcode:1.4.0] C:\Users\noah\.android\build-cache\42e0e836fe3cbeba042f97a93816628828102496\output\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.blankj.utilcode" to force usage

**Comment by Blankj** [comment]
你把你工程minSdkVersion改到16
