### ISSUE TITLE
建议修改BarUtils.getNavBarHeight()和BarUtils.getStatusBarHeight()实现

### ISSUE THREAD

**Issue by liuyuttkx** [Blankj/AndroidUtilCode#1704]
## 描述需求
修改BarUtils.getNavBarHeight()和BarUtils.getStatusBarHeight()实现。
因为贵库实现是使用application的resources来获取高度，如果 application的resources.getDisplayMetrics().density 字段值被修改，那么就会出现通过上述API获取的状态栏和导航栏高度与实际的高度不相符。

是否考虑如下代码获取 状态栏高度了？
将resources对象用Resources.getSystem() 来赋值。
    public static int getStatusBarHeight(Context context) {
        // 获得状态栏高度
        Resources resources = Resources.getSystem();
        int resourceId = resources.getIdentifier("status_bar_height", "dimen", "android");
        return resources.getDimensionPixelSize(resourceId);
    }

为什么要修改Density ? 
修改density是为了进行UI适配。
如果项目中修改了application对应的Density值，那么就没法使用贵库中获取 状态栏、导航栏高度及相关工具类方法了。

感谢支持 [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by YoungBill** [comment]
兄弟，BarUtils由我维护，
你说的我明天看一下，你可以加我V详聊，13733594471

**Comment by Blankj** [comment]
已发布版本

**Comment by ijoncc** [comment]
1.31.1和1.31.0两个版本获取在**异形屏**上状态栏高度不一样，
我在设置BarUtils.addMarginTopEqualStatusBarHeight的时候发现，
Resources.getSystem()获取的是**63**，标题栏显示不全，如图
<img width="88" alt="image" src="https://user-images.githubusercontent.com/13847079/223042832-3ee61c5e-bc98-4f5a-a597-c2f223a668db.png">

Utils.getApp().getResources()获取的是**136**，
标题栏正常显示，如图
<img width="81" alt="image" src="https://user-images.githubusercontent.com/13847079/223043169-1c0b34d5-0095-486f-8bc7-3116d08736ec.png">


并且项目中并没有修改application的resources.getDisplayMetrics().density ，所以直接修改为Resources.getSystem()没有兼容异形屏

**Comment by liuyuttkx** [comment]
Hi:    
        大神，你的意思是说 使用  Resources.getSystem()获取的Resource对象，去获取状态栏高度，在异形屏上有问题，是吗？

        请问会在哪些异形屏出现毛病？我已经使用这种方式在生产上应用了[流泪]
        多谢指教！



| |
liuyu195
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年03月6日 15:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Blankj/AndroidUtilCode] 建议修改BarUtils.getNavBarHeight()和BarUtils.getStatusBarHeight()实现 (Issue #1704) |

描述需求

修改BarUtils.getNavBarHeight()和BarUtils.getStatusBarHeight()实现。 因为贵库实现是使用application的resources来获取高度，如果 application的resources.getDisplayMetrics().density 字段值被修改，那么就会出现通过上述API获取的状态栏和导航栏高度与实际的高度不相符。

是否考虑如下代码获取 状态栏高度了？ 将resources对象用Resources.getSystem() 来赋值。 public static int getStatusBarHeight(Context context) { // 获得状态栏高度 Resources resources = Resources.getSystem(); int resourceId = resources.getIdentifier("status_bar_height", "dimen", "android"); return resources.getDimensionPixelSize(resourceId); }

为什么要修改Density ? 修改density是为了进行UI适配。 如果项目中修改了application对应的Density值，那么就没法使用贵库中获取 状态栏、导航栏高度及相关工具类方法了。

感谢支持 AndroidUtilCode.

你这样的改法在获取异形屏的状态栏目高度是存在问题的
