### ISSUE TITLE
android studio 使用新版，引用不进来

### ISSUE THREAD

**Issue by dazhiyu** [Blankj/AndroidUtilCode#1707]
## 

使用了 maven { url 'https://jitpack.io' }
但是引用 implementation 'com.blankj:utilcodex:1.31.1'，还是报错：

Failed to resolve: com.blankj:utilcodex:1.31.1
Show in Project Structure dialog
Affected Modules: app

Android Studio 2021.1.1版本
项目环境在 java 11上
compileSdk 31
buildToolsVersion ’31.0.0‘

**Comment by tunghsingw** [comment]
同样的问题，请问如何解决呢，低一个版本的可以
