### ISSUE TITLE
接口不规范

### ISSUE THREAD

**Issue by XieEDeHeiShou** [Blankj/AndroidUtilCode#171]
[HandlerUtils.java#L45](https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/util/HandlerUtils.java#L45)
这个接口在Handler内部有原生实现, [Handler.Callback](https://developer.android.com/reference/android/os/Handler.Callback.html)(叫你不好好看源码)

[CSDN上的这篇帖子](http://bbs.csdn.net/topics/391075032?page=1)也提供了另一种解决方案.

**Comment by Blankj** [comment]
已改
