### ISSUE TITLE
重复造轮子

### ISSUE THREAD

**Issue by FrankKwok** [Blankj/AndroidUtilCode#172]
[StringUtils](https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/util/StringUtils.java)中的isEmpty与equals方法在TextUtils类里都有实现，不如直接调用

**Comment by Blankj** [comment]
我尽量可以一步到位的东西为何还要借助下中介？我这样是可以做到纯java代码，如果加入TextUtils，如果java的人要用，那不就GG了么

**Comment by gdky005** [comment]
项目很强大哦。

**Comment by FrankKwok** [comment]
但是项目叫AndroidUtilCode

**Comment by Blankj** [comment]
@FrankKwok 🤣  能不用中介就不用哈，这也同时少import了哈

**Comment by FrankKwok** [comment]
Ok,明白了

**Comment by Blankj** [comment]
@FrankKwok 我就喜欢你这种怼一波的 😆

**Comment by FrankKwok** [comment]
@Blankj 我困惑好几天了，看到[#171](https://github.com/Blankj/AndroidUtilCode/issues/171)才怼的
