### ISSUE TITLE
项目中的工具类很多，为何没加上单元测试和自动化编译呢？

### ISSUE THREAD

**Issue by gdky005** [Blankj/AndroidUtilCode#173]
自动化编译例如： Travis CI or Circle CI。
单元测试覆盖： codecov
自动发包： jitpack

一些建议哈，有兴趣可以搞搞，会方便很多。

**Comment by Blankj** [comment]
可以可以，搞搞搞搞，应该就是像你TestJitpack一样吧

**Comment by gdky005** [comment]
哈哈，看来都在一个群里哈。最近看过一些比较好的开源项目，都用徽章表示，看起来更有信服力，感觉很专业的样子。  细细研究后，发觉有很多东西可以拓展

**Comment by FrankKwok** [comment]
求群号，我也学习一下

**Comment by Blankj** [comment]
徽章？shields吧？

**Comment by gdky005** [comment]
一个意思

**Comment by Blankj** [comment]
@gdky005 我写的[Alog](https://github.com/Blankj/ALog)用到了
