### ISSUE TITLE
app打包时出现以下错误，希望改善下

### ISSUE THREAD

**Issue by Fitem** [Blankj/AndroidUtilCode#175]
The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing Utils.getContext() to Utils.getContext().getApplicationContext() more... (Ctrl+F1)

**Comment by Blankj** [comment]
你工具类初始化用的是applicationContext吗

**Comment by Fitem** [comment]
public class BaseApplication extends Application {

    private static BaseApplication baseApplication;

    @Override
    public void onCreate() {
        super.onCreate();
        baseApplication = this;
    }

    public static Context getAppContext() {
        return baseApplication;
    }
    public static Resources getAppResources() {
        return baseApplication.getResources();
    }
    @Override
    public void onTerminate() {
        super.onTerminate();
    }
}

 //工具初始化
 Utils.init(getAppContext());

**Comment by Fitem** [comment]
我跟新到最新版本，然后初始化改成Utils.init(this);就没问题了

**Comment by Fitem** [comment]
更新库到最新版本

**Comment by Blankj** [comment]
好的
