### ISSUE TITLE
java.lang.NullPointerException,BarUtils.java,538]

### ISSUE THREAD

**Issue by xuminmin0405** [Blankj/AndroidUtilCode#176]
调试没问题。上传到商店，反馈报错

**Comment by Blankj** [comment]
设备版本号太低了？

**Comment by xuminmin0405** [comment]
应该不会百度和小米同时反馈的。我测试的机子不会有这个异常，他们的有，小米测试的机子是小米3

**Comment by Blankj** [comment]
应该是兼容问题，具体你可以拿测试机再测测，你看看538行为什么会报空，不行的话先ctach一下调用那个方法的代码处理下

**Comment by xuminmin0405** [comment]
![image](https://cloud.githubusercontent.com/assets/20292619/25707739/1094eb70-3117-11e7-97d8-3b849cac4619.png)
这是小米官方，测试反馈的Log

**Comment by Blankj** [comment]
你这是activity空指针了吧，是你调用的地方应该不对从而空指针了

**Comment by xuminmin0405** [comment]
LoadingActivity报错，错误是BaseActivity的20行 调用了您的BarUtils工具类的setColor方法。
里面的 setRootView方法的ViewGroup rootView = (ViewGroup) ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0);  rootView对象空指针。

**Comment by xuminmin0405** [comment]
自己公司的测试安卓机运行时没有异常和crash的，小米百度应用市场同时反馈的。

**Comment by xuminmin0405** [comment]
方便QQ交流下么，我的895458380。

**Comment by Blankj** [comment]
1.5.0试试？

**Comment by Blankj** [comment]
用最新版的BarUtils，结合这篇文章 http://www.jianshu.com/p/068fb77ebe17
