### ISSUE TITLE
Separation of gradle modules

### ISSUE THREAD

**Issue by MartinNemec** [Blankj/AndroidUtilCode#177]
Hi,

it would be awesome to have single gradle modules for the different aspects. So if I want to include only lets say NetworkUtils into a project I dont need to include all (method count!!)

just an idea ;)
cheers and thanks for your library

**Comment by Blankj** [comment]
One util one module? I think it is inadvisable. If I want 10 utils, I should depend 10 utils. I think the best way to use it is copy the functions what u want in your project, other than compile it.
