### ISSUE TITLE
LogUtils能否添加一个回调?

### ISSUE THREAD

**Issue by phcbest** [Blankj/AndroidUtilCode#1793]
## 描述需求
如下面代码所示,我需要记录崩溃信息,之后再手动结束进程,但是有时没有记录完就被杀了,看到log写入文件是由一个Runnable来完成的,是否可以添加一个Callback来解决该问题呢?
```kotlin
private fun handleException(ex: Throwable?): Boolean {
        ex?.printStackTrace()
        if (ex == null) {
            return false
        }
        LogUtils.e(ex)
        Process.killProcess(Process.myPid())
        exitProcess(1)
    }
```

**Comment by AdminQQZ** [comment]
提 pr 上来

**Comment by phcbest** [comment]
> 提 pr 上来

pr会合吗,我看很多PR很久都没响应了,我明天提一个吧虽然不知是否会合

**Comment by phcbest** [comment]
> 提 pr 上来

看了一下代码,改回调确实对代码侵入性比较大,而且不太符合LogUtils这种打完日志就不管的场景,我权衡考虑之下还是用FilteIOUtils直接写了个新的崩溃日志文件
