### ISSUE TITLE
NetworkUtil有个方法会报空指针

### ISSUE THREAD

**Issue by kinkenrin** [Blankj/AndroidUtilCode#185]
/**
     * 判断wifi是否连接状态
     * <p>需添加权限 {@code <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>}</p>
     *
     * @return {@code true}: 连接<br>{@code false}: 未连接
     */
    public static boolean isWifiConnected() {
        ConnectivityManager cm = (ConnectivityManager) Utils.getContext()
                .getSystemService(Context.CONNECTIVITY_SERVICE);
        return cm != null && cm.getActiveNetworkInfo() != null
                && cm.getActiveNetworkInfo().getType() == ConnectivityManager.TYPE_WIFI;
    }

网络不稳定的情况下 cm.getActiveNetworkInfo().getType()  这句话会报空指针

**Comment by Blankj** [comment]
我这写法还会报空吗？ 错误日志发上来看看
