### ISSUE TITLE
android 6.0使用DeviceUtil.getMacAddress会返回02:00:00:00:00:00

### ISSUE THREAD

**Issue by vikingden8** [Blankj/AndroidUtilCode#19]
android 6.0使用DeviceUtil.getMacAddress会返回02:00:00:00:00:00，期待更新，网上有具体的实现方法。
地址：http://www.yrom.net/blog/2015/10/28/android-m-getting-wifi-macaddress-1/?utm_source=tuicool&utm_medium=referral

**Comment by Blankj** [comment]
已加wlan0获取方式
