### ISSUE TITLE
dp2px, px2dp sp2px, px2sp 方法重复

### ISSUE THREAD

**Issue by ChineseLincoln** [Blankj/AndroidUtilCode#190]
ConvertUtils 和 SizeUtils  工具类中都包含了 dp2px, px2dp，sp2px, px2sp 这四个方法，方法代码相同，是否可以合并到一起？

**Comment by Blankj** [comment]
不合并的，为了解耦所以都是各自用各自的，尽量不互相调用，推荐不要一次性导入全部工具类，用什么拷贝什么
