### ISSUE TITLE
Kotlin中引用LogUtils，打印log显示错误

### ISSUE THREAD

**Issue by 791180116** [Blankj/AndroidUtilCode#192]
Kotlin 中调用 LogUtils.d("lcc") 其实是引用的
public static void d(String tag, Object... contents) {
        log(D, tag, contents);
    }

打印出来为：
05-19 11:20:53.974 23037-23037/com.free.lcc D/lcc: ╔══════════════════════════════
05-19 11:20:53.974 23037-23037/com.free.lcc D/lcc: ║ Thread: main, dofor(Main2Activity.java:67)
05-19 11:20:53.974 23037-23037/com.free.lcc D/lcc: ╚══════════════════════════════

建议添加方法：

public static void d(String contents) {
        log(D, sGlobalTag, contents);
}

**Comment by Blankj** [comment]
Kotlin暂不支持哈，你那样的话string类型太狭隘了，我这不是Kotlin库，到时候想设计的话我会再设计一套。建议你可以新建一个MyLogUtils来把LogUtils.d("lcc")来封装成LogUtils.d(“”, "lcc")
