### ISSUE TITLE
MD5 32位加密算法没有？

### ISSUE THREAD

**Issue by shingohu** [Blankj/AndroidUtilCode#193]
RT

**Comment by Blankj** [comment]
有啊，EncryptUtils.encryptMD5

**Comment by shingohu** [comment]
@Blankj 这个我加密出来的结果 跟使用32位加密算法出来的结果不一样

**Comment by shingohu** [comment]
@`public static String md5(String inStr) {
        MessageDigest md5 = null;
        try {
            md5 = MessageDigest.getInstance("MD5");
        } catch (Exception e) {
            e.printStackTrace();
            return "";
        }
        char[] charArray = inStr.toCharArray();
        byte[] byteArray = new byte[charArray.length];

        for (int i = 0; i < charArray.length; i++)
            byteArray[i] = (byte) charArray[i];
        byte[] md5Bytes = md5.digest(byteArray);


        StringBuilder hexValue = new StringBuilder();
        for (byte md5Byte : md5Bytes) {
            int val = ((int) md5Byte) & 0xff;

            if (val < 16)
                hexValue.append("0");
            hexValue.append(Integer.toHexString(val));
        }
        return hexValue.toString();

    }`

**Comment by Blankj** [comment]
32位指的是最后长度是几位吧，我的和[md5](http://tool.chinaz.com/tools/md5.aspx)一样的

**Comment by liyanfei250** [comment]
获取当前app的安装路径有没有？

**Comment by Blankj** [comment]
@liyanfei250 在AppUtils里有
