### ISSUE TITLE
建议对工具的功能进行模块化并发布成一个个小的子模块

### ISSUE THREAD

**Issue by MarkChan7** [Blankj/AndroidUtilCode#200]

**Comment by JerrryLiu** [comment]
支持+1 
只需要库中一部分功能，就得集成所有，有些浪费资源

**Comment by Jocoo2015** [comment]
需要哪个功能就使用对应的工具类不就行了

**Comment by Blankj** [comment]
如果那样的话建议复制粘贴，你用类中的也只是用部分代码，那其他代码不就浪费了么也，而且每个使用者使用的相关类可能都不同，不是很好处理，aar200k不到很占你空间吗
