### ISSUE TITLE
最小版本变成19了？

### ISSUE THREAD

**Issue by wimvogt** [Blankj/AndroidUtilCode#202]
刚想更新版本时运行出错
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 19 declared in library [com.blankj:utilcode:1.3.7] /Users/wim/.gradle/caches/transforms-1/files-1.1/utilcode-1.3.7.aar/6b28699061d825422e436d42efcba14d/AndroidManifest.xml as the library might be using APIs not available in 15
  	Suggestion: use a compatible library with a minSdk of at most 15,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.blankj.utilcode" to force usage (may lead to runtime failures)
要把项目的最低版本改成19？有其它解决办法吗？

**Comment by Blankj** [comment]
现在都1.6.4了哦，更新版本即可

**Comment by wimvogt** [comment]
尴尬了，我写了1.3.+
