### ISSUE TITLE
Toast Utils 问题

### ISSUE THREAD

**Issue by ErebusHu** [Blankj/AndroidUtilCode#206]
1.7.0依赖后的 ToastUtils  中的方法与wiki上的不同 
public static void setBackgroundResource(@IdRes int backgroundResource) {
        ToastUtils.backgroundResource = backgroundResource;
    }
这叫我如何设置drawable

**Comment by ErebusHu** [comment]
这里真的是1.7.0吗？ 我删除缓存重新下载 还是这样的方法。。看这里是已经更新了的 为啥我依赖下载下来的还是老的方法。

**Comment by Blankj** [comment]
已发布
