### ISSUE TITLE
关于HandlerUtils

### ISSUE THREAD

**Issue by FrankKwok** [Blankj/AndroidUtilCode#207]
HandlerUtils.HandlerHolder类并不能防止内存泄漏，因为Message对象会持有Handler对象的引用，正确的方式应该是在退出Activity时调用Handler.removeMessages(),而且系统自带的Handler已经实现了对Handler.Callback逻辑的调用，所以HandlerUtils这个类已经没有必要了

**Comment by Blankj** [comment]
🆗
