### ISSUE TITLE
图片压缩会oom

### ISSUE THREAD

**Issue by xicong** [Blankj/AndroidUtilCode#208]
同时压缩多张图片在低端机上会出现oom，还有能不能建议把最低sdk调成android4.0，现在还有一部分应用需要支持4.0的低端机

**Comment by Blankj** [comment]
同时压缩其实也是一张张操作吧，你压缩完那张图片回收下，或者用其他第三方图片库，4.0和4.0.3有差吗，我貌似是minSdk是15吧，那我下版本到14

**Comment by xicong** [comment]
这个压缩完要手动回收吗？，建议压缩完能自动回收

**Comment by Blankj** [comment]
最后面不是有个参数属否回收吗

**Comment by xicong** [comment]
嗯嗯，我试试，对了，你的群74721490怎么加不了，或者有新的微信群之类的，平时有问题可以相互交流，会方便一点

**Comment by Blankj** [comment]
在README里不是有群号么
