### ISSUE TITLE
希望加入 kotlin支持 LogUtils

### ISSUE THREAD

**Issue by xiang473535976** [Blankj/AndroidUtilCode#209]
06-23 09:26:50.161 13102-13102/aichen.stopcar E/11: ╔═══════════════════════════════════════════════════════════════════════════════════════════════════
06-23 09:26:50.161 13102-13102/aichen.stopcar E/11: ║ main, accept(MainActivity.java:29)
06-23 09:26:50.161 13102-13102/aichen.stopcar E/11: ╚═══════════════════════════════════════════════════════════════════════════════════════════════════
                 无法打印里面的内容  谢谢   只能打印出页面信息

**Comment by xiang473535976** [comment]
06-23 09:28:22.911 14143-14143/aichen.stopcar E/11打印的内容放在了页面信息里面  没有包含在括号里  例如我这里打印的是11   结果显示在了前面

**Comment by Blankj** [comment]
那是tag，kotlin里调用的是e(String tag, Object... contents)，所以11就成了tag，而内容无，想解决的话你再自己封装一层
