### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by Fitem** [Blankj/AndroidUtilCode#210]
作者你好，感谢你开源的这个项目，对我的工作效率非常大，但我也有一些建议希望采纳：
由于工作需要用到cacheutils 我从之前的版本升级到1.7.1，发现其中有许多变动的地方：
1. SpUtils 获取方式变化 ,导致我整个项目的SpUtils都需要变化。
2. sputils.get(String , String ),以前没有值则是获取的null，现在却是“”。导致我代码许多判断都失效。
3.  SpannableStringUtils改名为SpanUtils，并且其中的一些方法名也修改

1.3点提示报错还好，第2点没有任何提示，看了源码才发现，希望作者对于第2点这样的情况考虑变动的影响，或者在文档中提示，同时考虑一下方法修改形式对于以前集成开发者的影响，谢谢！

**Comment by YunlongYang** [comment]
1.作者把null改成""就是不想返回空指针出异常
2.判断字符串为空最好用TextUtils.isEmpty来判断
3.当你的代码有很多地方在判断同一个值，怎么不统一成一个方法呢

**Comment by Blankj** [comment]
不好意思哈，给你带来了不便，有些东西都是在不断优化的，当你修改版本号了，或多或少是会出现这种错误，而且我用新函数替代了老函数一般都不加过时注解，不过一般都是朝好的方面发展的，而且改动一般也不是很大。

根据你的问题我可以给你提几个你可以吸取的建议，SpUtils你用的时候自己可以再封装一层，那样只需要修改你自己封装的那一层即可，而且SP操作都应该放在同一个地方一般，第二点的话 @YunlongYang 已经帮我回答了，或者你可以用我的StringUtils解决，第三点的话函数名改了的话全剧替换一下吧只能。

不过，你升级版本只是要用到CacheUtils，那么为何不把这个类拷出来即可呢，哈哈。

**Comment by Fitem** [comment]
首先感觉楼上两位周末花时间的解答！在此感谢两位！！！

想一想确实是自己的问题：
第一，太依赖了第三方库，没有考虑到第三方库版本更新或者替换第三方库的情况
第二，没有对可能会经常出现的代码进行一个统一的管理，这些问题自己以后都要注意。

对于函数名的变更我也是用的全局替换（顺带一提AS的全局查找预览真的很赞！），至于TextUtils我还是经常用的(QAQ)。

最后，祝作者的utils库越来越火，我是从简书到Github，从开始的6K到11K Star的见证者(ZZZ)

**Comment by jp1017** [comment]
:+1:
