### ISSUE TITLE
获取缓存大小怎么总是要第二次才能获取到

### ISSUE THREAD

**Issue by xicong** [Blankj/AndroidUtilCode#211]
![default](https://user-images.githubusercontent.com/11675597/27681035-68d83170-5cf0-11e7-84d9-c02f6063e555.png)

**Comment by Blankj** [comment]
??还有问题吗

**Comment by xicong** [comment]
还存在，第一次获取不到，无奈我只有进界面时候获取一次，到界面后再获取就没问题了

**Comment by xicong** [comment]
还有在使用fragmentutils的时候发现切换好生硬，要是能支持加动画就更好了

**Comment by Blankj** [comment]
后面会加，现在只支持共享元素

**Comment by xicong** [comment]
共享元素？  fragment的复用吗？

**Comment by Blankj** [comment]
不是，你去看看fragment切换动画，有一种就是共享元素

**Comment by xicong** [comment]
好的

**Comment by xicong** [comment]
![image](https://user-images.githubusercontent.com/11675597/28205788-19e1a688-68b6-11e7-8b5c-e7685cf7b8dd.png)这个好像有问题啊，明明可用的网络竟然返回false

**Comment by Blankj** [comment]
你ping不通那个ip而已，你把ip换成你们自己服务器

**Comment by xicong** [comment]
哦，这样啊，知道了，谢谢

**Comment by Blankj** [comment]
这个bug修复了，之前new的时候会异步去计算缓存大小，所以你立马获取得到的是0，现在你异步去获取就行。

**Comment by xicong** [comment]
好的，谢了
