### ISSUE TITLE
一行含有两张图片的时候，图片和文字居中的属性没有用了

### ISSUE THREAD

**Issue by littlezan** [Blankj/AndroidUtilCode#212]
![image](https://user-images.githubusercontent.com/5358278/27761923-7218f40e-5e99-11e7-9154-c7e1807d20c4.png)

```
     .append("测试大图字体居中对齐").setBackgroundColor(Color.LTGRAY).setAlign(Layout.Alignment.ALIGN_CENTER)
                .appendImage(R.drawable.shape_spannable_block_low, SpanUtils.ALIGN_CENTER).setAlign(Layout.Alignment.ALIGN_CENTER)
                .appendImage(R.drawable.shape_spannable_block_high, SpanUtils.ALIGN_CENTER).setAlign(Layout.Alignment.ALIGN_CENTER)
                .appendImage(R.drawable.shape_spannable_block_low, SpanUtils.ALIGN_CENTER).setAlign(Layout.Alignment.ALIGN_CENTER)
                .appendLine()
```
显示效果如下

![image](https://user-images.githubusercontent.com/5358278/27761939-cf8df602-5e99-11e7-8875-b0a430038e09.png)

**Comment by littlezan** [comment]
[Android 解决图文混排，图片和文字居中对齐问题(ImageSpan) ](http://www.jianshu.com/p/add321678859)

**Comment by Blankj** [comment]
你这只是适合图片小于文字才适合，如果图片长于文字，行高并不会改变，图片会跑到上一行。一般安卓中图文混排图片都是统一尺寸，所以不会有你上面的情况发生，所以我写的demo中也不会这么写，这种问题我是知道的，所以都规避了

**Comment by Blankj** [comment]
你所发的链接其实就是我所谓的小图对齐，但我比他做得还要完善罢了

**Comment by littlezan** [comment]
可不可以，提供一个api设置预定义高度，MaxHeight，所有的高度计算，按照MaxHeight计算

**Comment by littlezan** [comment]
这样就不会出现错乱的问题了

**Comment by Blankj** [comment]
没那么简单，我设置当前span怎么会考虑到前后span的问题呢，而且还不知道他们是否同一行，我当前这样是做不了。

**Comment by Blankj** [comment]
统一图片大小即可，这种尺寸不同的现象那就另寻别路吧
