### ISSUE TITLE
关于ToastUtils#setBgResource方法问题

### ISSUE THREAD

**Issue by keenoor** [Blankj/AndroidUtilCode#215]
demo里面的
`
    ToastUtils.setBgResource(R.drawable.shape_round_rect);
    ToastUtils.showLong(R.string.toast_custom_bg);
`
即可正常显示带背景的toast，然而，在自己的项目里面使用ToastUtils时候（未做删改），字体与背景显得比较拥挤，不知道demo项目有什么特别之处？
我自己重新设置了背景图的padding才行。
`
    <solid android:color="@color/colorAccent"/>
    <corners android:radius="16dp"/>
    <padding android:left="8dp"/>
    <padding android:right="8dp"/>
    <padding android:top="8dp"/>
    <padding android:bottom="8dp"/>
`

**Comment by Blankj** [comment]
targetSdkVersion的问题吧，或者手机问题

**Comment by keenoor** [comment]
targetSdkVersion compileSdkVersion 都一样，同一部手机，结果不同。
![image](https://user-images.githubusercontent.com/12131613/27942472-cbee70f2-6309-11e7-8507-82323ea646f9.png)
![image](https://user-images.githubusercontent.com/12131613/27942475-d09198a0-6309-11e7-821c-072276924b2c.png)

**Comment by Blankj** [comment]
不知道，我demo啥也没写。

**Comment by 386534312** [comment]
我遇到了同样的问题，请问解决了吗

**Comment by Blankj** [comment]
Toast.setView来解决

**Comment by Yanqilong** [comment]
我也遇到了这个问题，这个问题重新打开吧 @Blankj 

ToastUtils.setBgResource() 之后文字和 Toast 左右边框都贴在了一块，我测试了两款小米机型都会

**Comment by Blankj** [comment]
国产的不同手机对 Toast 的 view 底层都做了修改，所以里面的 TextView 的 sytle 都会不太一样所造成的，你如果想样式都统一，那就自定义就可以了，可以参考 [CustomToast](https://github.com/Blankj/AndroidUtilCode/blob/a5fe7c03e5bdd46b0d31df1dc01cfb6b91a87f9a/app/src/main/java/com/blankj/androidutilcode/feature/core/toast/CustomToast.java)
