### ISSUE TITLE
方法返回值一定为null

### ISSUE THREAD

**Issue by Blizzard-liu** [Blankj/AndroidUtilCode#217]
流只能被读取一次  下次在获取返回值就是null

![image](https://user-images.githubusercontent.com/20244432/28049566-ce216338-662a-11e7-9313-d1b684bd522a.png)

**Comment by Blankj** [comment]
既然能获取一次，那为何第二次不行了，你打断点看看，我觉得是你流为空了吧才返回空

**Comment by ZhanXuzhaoYYD** [comment]
Blizzard-liu 反映的问题确实存在，我之前也遇到过。InputStream用过一次后，第二次使用就无效了，上面的方法返回的bitmap是null；

        AssetManager assetManager = getAssets();
        String tag = ImageActivity.class.getName();
        try {
            InputStream inputStream = assetManager.open("lena.png");
            Bitmap bm1 = ImageUtils.getBitmap(inputStream, 100, 100);
            LogUtils.i(tag, "bm1 width: " + bm1.getWidth());
        } catch (IOException e) {
            e.printStackTrace();
        }

以上测试代码会在打日志那行抛出空指针异常；
下面是另一个例子，会在第二处log抛出空指针异常，取消注释行就不会。

        AssetManager assetManager = getAssets();
        String tag = ImageActivity.class.getName();
        try {
            InputStream inputStream = assetManager.open("lena.png");
            Bitmap bm1 = BitmapFactory.decodeStream(inputStream);
            LogUtils.i(tag, "bm1 width: " + bm1.getWidth());
            //inputStream = assetManager.open("lena.png");
            Bitmap bm2 = BitmapFactory.decodeStream(inputStream);
            LogUtils.i(tag, "bm2 width: " + bm2.getWidth());
        } catch (IOException e) {
            e.printStackTrace();
        }

**Comment by Blizzard-liu** [comment]
这是java基础的问题 记忆都模糊了  网络流只能被读取一次 取出来就没了    //inputStream = assetManager.open("lena.png");  你在这里又给它重新赋值了 所以不是null ,我是这么解决的

   /**
+     * 获取bitmap
+     *
+     * @param is        输入流
+     * @param maxWidth  最大宽度
+     * @param maxHeight 最大高度
+     * @return bitmap
+     */
+    public static Bitmap getBitmap(final InputStream is, final int maxWidth, final int maxHeight) throws IOException {
+        if (is == null) return null;
+        BitmapFactory.Options options = new BitmapFactory.Options();
+        options.inJustDecodeBounds = true;
+        byte[] data = inputStream2ByteArr(is);//将InputStream转为byte数组，可以多次读取
+        Bitmap bitmap = BitmapFactory.decodeByteArray(data, 0, data.length, options);
+        options.inSampleSize = calculateInSampleSize(options, maxWidth, maxHeight);
+        options.inJustDecodeBounds = false;
+        bitmap = BitmapFactory.decodeByteArray(data, 0, data.length, options);
+        return bitmap;
+    }

  private static byte[] inputStream2ByteArr(InputStream inputStream) throws IOException {
+        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
+        byte[] buff = new byte[1024*2];
+        int len = 0;
+        while ( (len = inputStream.read(buff)) != -1) {
+            outputStream.write(buff, 0, len);
+        }
+        inputStream.close();
+        outputStream.close();
+        return outputStream.toByteArray();
+    }
+
 }

**Comment by Blankj** [comment]
那就用public static Bitmap getBitmap(final byte[] data, final int offset) 这个函数，你把流转为字节数组就好了，这不是我工具类的问题吧 🤣
