### ISSUE TITLE
SPUtils

### ISSUE THREAD

**Issue by zhuzhao404** [Blankj/AndroidUtilCode#219]
第一次保存数据SPUtils对象会保存到Map里面，这个时候可以保存成功，但是如果开启页面其他页面获取值则获取不到，好像获取时持有的sputils对象是刚才保存数据之前的对象，然后会造成获取的时候既不存在这个key也获取不到这个值，望关注一下这个bug

**Comment by Blankj** [comment]
把你代码发上来看看，按道理不会发生你所说的吧，你可以看源码调试

**Comment by sunshinewei** [comment]
我也遇到了这个问题。

**Comment by zhuzhao404** [comment]
/***
 * SP工具
 */
public class SPDao {

    private static final String SP_NAME = "pd_cache";
    private static final String USER_ID = "userId";
    private static final String USER_CODE = "empNo";
    private static final String USER_NAME = "cName";
    private static final String IS_LOGIN = "isLogin";

    /**
     * 获取userId
     *
     * @return
     */
    public static String getUserId() {
        if (SPUtils.getInstance(SP_NAME).contains(USER_ID)) {
            return SPUtils.getInstance().getString(USER_ID);
        } else {
            return "";
        }

    }

    /**
     * 获取用户登录代码
     *
     * @return
     */
    public static String getUserLoginCode() {
        if (SPUtils.getInstance(SP_NAME).contains(USER_CODE)) {
            return SPUtils.getInstance().getString(USER_CODE);
        } else {
            return "";
        }
    }

    /**
     * 获取用户名
     *
     * @return
     */
    public static String getUserName() {
        if (SPUtils.getInstance(SP_NAME).contains(USER_NAME)) {
            return SPUtils.getInstance().getString(USER_NAME);
        } else {
            return "";
        }
    }

    /**
     * 获取是否保持登录
     *
     * @return
     */
    public static boolean getStayLogin() {
        if (SPUtils.getInstance(SP_NAME).contains(IS_LOGIN)) {
            return SPUtils.getInstance().getBoolean(IS_LOGIN);
        } else {
            return false;
        }
    }

    /**
     * 保存用户id
     *
     * @param userId
     */
    public static void setUserId(String userId) {
        SPUtils.getInstance(SP_NAME).put(USER_ID, userId);
    }

    /**
     * 保存用户登录代码
     *
     * @param loginCode
     */
    public static void setUserLoginCode(String loginCode) {
        SPUtils.getInstance(SP_NAME).put(USER_CODE, loginCode);
    }

    /**
     * 保存用户登录密码
     *
     * @param userName
     */
    public static void setUserName(String userName) {
        SPUtils.getInstance(SP_NAME).put(USER_NAME, userName);
    }

    /**
     * 清除所有
     */
    public static void clearAll() {
        SPUtils.getInstance(SP_NAME).clear();
    }

    /**
     * 清除用户登录代码
     */
    public static void clearUserCode() {
        SPUtils.getInstance(SP_NAME).remove(USER_CODE);
    }

    /**
     * 清除用户id
     */
    public static void clearUserId() {
        SPUtils.getInstance(SP_NAME).remove(USER_ID);
    }

    /**
     * 清除用户名
     */
    public static void clearUserName() {
        SPUtils.getInstance(SP_NAME).remove(USER_NAME);
    }

    /**
     * 是否保持登录状态
     * 入口处获取该值 加以判断 如果获取是false  就清除用户相关sp配置数据
     *
     * @param isLogin true 保持  false不保持
     */
    public static void setStayLogin(boolean isLogin) {
        SPUtils.getInstance(SP_NAME).put(IS_LOGIN, isLogin);
    }
}

**Comment by Blankj** [comment]
是你使用方式有问题，你if里getInstance是带SP_NAME的，get的时候不带SP_NAME，这都不是一个对象，而且你获取的时候不用写contains，多此一举，getXXX后面的第二个参数就是不存在返回的默认值

**Comment by zhuzhao404** [comment]
难怪。。。我当时也没看出来，写多了就犯糊涂了，谢谢，太麻烦你了！

**Comment by Blankj** [comment]
```
public class SPDao {

    private static final String SP_NAME = "pd_cache";
    private static final String USER_ID = "userId";
    private static final String USER_CODE = "empNo";
    private static final String USER_NAME = "cName";
    private static final String IS_LOGIN = "isLogin";

    private static SPUtils sSPUtils = SPUtils.getInstance(SP_NAME);

    /**
     * 获取userId
     *
     * @return
     */
    public static String getUserId() {
//        return SPUtils.getInstance(SP_NAME).getString(USER_ID, "");// 默认就是""，所以等同于下面
        return sSPUtils.getString(USER_ID);// 默认就是""
    }

    /**
     * 获取用户登录代码
     *
     * @return
     */
    public static String getUserLoginCode() {
        return sSPUtils.getString(USER_CODE);
    }

    /**
     * 获取用户名
     *
     * @return
     */
    public static String getUserName() {
        return sSPUtils.getString(USER_NAME);
    }

    /**
     * 获取是否保持登录
     *
     * @return
     */
    public static boolean getStayLogin() {
        return sSPUtils.getBoolean(IS_LOGIN);
    }

    /**
     * 保存用户id
     *
     * @param userId
     */
    public static void setUserId(String userId) {
        sSPUtils.put(USER_ID, userId);
    }

    /**
     * 保存用户登录代码
     *
     * @param loginCode
     */
    public static void setUserLoginCode(String loginCode) {
        sSPUtils.put(USER_CODE, loginCode);
    }

    /**
     * 保存用户登录密码
     *
     * @param userName
     */
    public static void setUserName(String userName) {
        sSPUtils.put(USER_NAME, userName);
    }

    /**
     * 清除所有
     */
    public static void clearAll() {
        sSPUtils.clear();
    }

    /**
     * 清除用户登录代码
     */
    public static void clearUserCode() {
        sSPUtils.remove(USER_CODE);
    }

    /**
     * 清除用户id
     */
    public static void clearUserId() {
        sSPUtils.remove(USER_ID);
    }

    /**
     * 清除用户名
     */
    public static void clearUserName() {
        sSPUtils.remove(USER_NAME);
    }

    /**
     * 是否保持登录状态
     * 入口处获取该值 加以判断 如果获取是false  就清除用户相关sp配置数据
     *
     * @param isLogin true 保持  false不保持
     */
    public static void setStayLogin(boolean isLogin) {
        sSPUtils.put(IS_LOGIN, isLogin);
    }
}
```
这样用才是最完美的

**Comment by zhuzhao404** [comment]
恩恩 我已经清楚了  谢谢！
