### ISSUE TITLE
json解析的可以加上

### ISSUE THREAD

**Issue by MaXiuQiang** [Blankj/AndroidUtilCode#22]
json解析的可以加上

**Comment by ssyijiu** [comment]
@Blankj  自己常用的Gson解析工具类，经得起实战检验
https://github.com/ssyijiu/android-helper/blob/master/utils/GsonUtil.java

**Comment by Blankj** [comment]
这加了第三方库了，我这个不引入第三方库的，不然图片什么的都用第三方的那还得了？他的意思是封装原生解析

**Comment by ssyijiu** [comment]
哦哦，原生解析感觉没有很大的意义，毕竟这么多优秀的json工具

**Comment by Blankj** [comment]
所以用户想用就自己加第三方的，一般开发sdk用的都是原生的，不会引入第三方的
