### ISSUE TITLE
Manifest中的allowbackup属性

### ISSUE THREAD

**Issue by StevenYou** [Blankj/AndroidUtilCode#220]
该属性设置为true，会跟其他第三方库冲突，有些第三方库会校验这个属性导致编译不通过。可否设为false。

**Comment by Blankj** [comment]
这只是app下的manifest，这也会冲突？

**Comment by jp1017** [comment]
直接去了行了

**Comment by Blankj** [comment]
这个属性默认为true哦

**Comment by StevenYou** [comment]
对，但是确实会冲突，我现在没办法只能手动改了先。是某宝的内部sdk

**Comment by Blankj** [comment]
嗯？你用我的工具类和我app下的代码没关系的吧，我app写了allowbackup，会影响到utils的？

**Comment by cervy** [comment]
主model下的会覆盖其它的

**Comment by StevenYou** [comment]
我在manifest下面加了tools:replace="android:allowBackup"已经解决了

**Comment by Blankj** [comment]
@cervy 明白了
