### ISSUE TITLE
IntentUtils.getInstallAppIntent(final File file, final String authority)方法我的会报错

### ISSUE THREAD

**Issue by JGWCoding** [Blankj/AndroidUtilCode#223]
IntentUtils.getInstallAppIntent(final File file, final String authority)方法里的
Build.VERSION.SDK_INT < Build.VERSION_CODES.N  我的  Build.VERSION_CODES.N 不行 会报错,只能写成  
Build.VERSION_CODES.M  ,请问下是我个人的问题还是别的什么问题

**Comment by Blankj** [comment]
错误信息呢，发上来

**Comment by Blankj** [comment]
6.0还不需要FileProvider的，7.0才需要的

**Comment by JGWCoding** [comment]
![image](https://user-images.githubusercontent.com/20368200/28511415-b7ab81ec-707f-11e7-9372-f1cf9519918e.png)

**Comment by JGWCoding** [comment]
说不能解析,N改成M就可以了

**Comment by Blankj** [comment]
那是你没下7.0的sdk，你把你sdk更到最新就有了

**Comment by Blankj** [comment]
我还以为是运行时错误呢。。

**Comment by JGWCoding** [comment]
是不是  Build.VERSION.SDK_INT < 23 就可以了,另外我的依赖的是23的sdk

**Comment by Blankj** [comment]
嗯，你把sdk更新到最新就有了
