### ISSUE TITLE
SpanUtils中的setIconMargin的align不生效

### ISSUE THREAD

**Issue by chengzhijun0706** [Blankj/AndroidUtilCode#224]
有俩个问题
1.setIconMargin并不会替换区间内的字,容易造成误解
2.当行数超过图片的高度是align熟悉并没有生效
![image](https://user-images.githubusercontent.com/13751034/28604095-f82913ac-71fa-11e7-9460-995f7feea469.png)
![image](https://user-images.githubusercontent.com/13751034/28604115-1ee71098-71fb-11e7-8917-829fa24fb732.png)

**Comment by Blankj** [comment]
icon是放在行首的，你要用image的话就用appendImage

**Comment by Blankj** [comment]
* setIconMargin本来就不是用来替换文字的
* setIconMargin之后的文字你写在前面，你写在后面就不会生效了，是你用法问题

**Comment by chengzhijun0706** [comment]
icon在行首会占据多行,那align属性不应该是在整体行高中的位置么

**Comment by chengzhijun0706** [comment]
icon在行首会占据多行,那align属性不应该是在整体行高中的位置么

**Comment by Blankj** [comment]
那你把整行内容写在前面，不要在setIconMargin之后再加文字，具体看我demo怎么写的

**Comment by Blankj** [comment]
或者你自己研究下IconMargin

**Comment by chengzhijun0706** [comment]
谢谢,受教了,明白了
