### ISSUE TITLE
大佬遇见过spUtils存了过后，取不出来的情况吗

### ISSUE THREAD

**Issue by HeJingWei** [Blankj/AndroidUtilCode#227]
我在做开发，现在设想会不会存在手机适配的问题，某些手机通过spUtils会不会存不了呢？希望大佬看到能为我解惑

**Comment by Blankj** [comment]
用不了sp的手机？那不是安卓机吧

**Comment by HeJingWei** [comment]
是啊，之前的项目用SP存了用户的ID，结果反馈回来某些手机每次都取出来为空

**Comment by Blankj** [comment]
那跟我这工具类没啥关系吧，是手机的问题。

**Comment by HeJingWei** [comment]
对，没啥关系。我主要是想请教一下，如果遇见这种情况怎么办，因为我就只用存几个简单的字段在本地来请求下用户数据

**Comment by Blankj** [comment]
那就用CacheUtils存本地

**Comment by HeJingWei** [comment]
我再试试，谢谢~
