### ISSUE TITLE
Strman

### ISSUE THREAD

**Issue by jp1017** [Blankj/AndroidUtilCode#23]
https://github.com/shekhargulati/strman-java

**Comment by RweiSyin** [comment]
这个字符串的工具类不错，不过更偏向Java吧，虽然Android也是Java。

建议整理一份图片处理的工具类，挺常用的。

**Comment by jp1017** [comment]
@RweiSyin 是的，更偏向底层一些，还有大名鼎鼎的 `apache` :smile: 

https://github.com/apache/commons-lang

图片处理没怎么玩过，听着不错哦
