### ISSUE TITLE
Prevent LogUtils show log in release version

### ISSUE THREAD

**Issue by duongnv1996** [Blankj/AndroidUtilCode#235]
Thank for your supporting. I got the error about LogUtils. I hit the log in my project and I wanna only show log when build version debug and when I release version It should be hidden.
I don't know how to config or prevent it from showing in the release version.

Thank you!

**Comment by Blankj** [comment]
``` java
LogUtils.Builder builder = new LogUtils.Builder()
                .setLogSwitch(BuildConfig.DEBUG);
```
U can read more in [UtilsApp.java](https://github.com/Blankj/AndroidUtilCode/blob/dd949671302f66ae47a152a5e646307a82ca6d76/app/src/main/java/com/blankj/androidutilcode/UtilsApp.java)

**Comment by duongnv1996** [comment]
Thank you, sir!
