### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by r17171709** [Blankj/AndroidUtilCode#238]
感谢作者的辛勤付出，但是我还是想提及一下使用过程中的困扰。作者更新框架比较积极，但是在更新过程中经常更换方法名或者变量类型，以至于使用者在更新该框架之后必须要检查一遍代码，特别是那些通过反射调用的方法还不太容易排查出来，比较折腾。希望作者能够尽量兼容老版本，谢谢

**Comment by Blankj** [comment]
如果老版本的代码就能解决你业务上的需求，建议不要更新，更新的话看我日志，我一般都会写变动了什么类，更新的话一般都做了相应优化或者解决了bug，如果不涉及到自己需求的话就没必要更哈。

**Comment by r17171709** [comment]
好的
