### ISSUE TITLE
FileUtils的一个建议

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#240]
你好,我看你FileUtils里面deleteFilesInDir()方法会删除目录下的所有文件,包括子目录,是否能扩展一个只删除文件不删除目录的方法,
我自己是用你的listFilesInDir()方法遍历出来,然后再判断是否是目录,是的话保留

**Comment by Blankj** [comment]
listFilesInDir，然后判断是否文件，调用deleteFile

**Comment by sweet2o09** [comment]
@Blankj 你好,顺便问个MD5加密的问题
![Uploading image.png…]()这个是网上看到的一个MD5加密方式,与你的bytes2HexString(final byte[] bytes)方法算出来的貌似有区别,请问这是为什么呢,

**Comment by Blankj** [comment]
对不对那个网址比较下就知道了，http://tool.chinaz.com/Tools/md5.aspx
我的和网上是一样的，32位
