### ISSUE TITLE
FileUtils 和 FileIOUtils 的 isSpace 方法疑问

### ISSUE THREAD

**Issue by ChenJunXu** [Blankj/AndroidUtilCode#242]
大神，那个 for 循环的用意是什么呢？总觉得很奇怪 ~O.o~

public static boolean isSpace(final String s) {
        if (s == null) return true;
        for (int i = 0, len = s.length(); i < len; ++i) {
            if (!Character.isWhitespace(s.charAt(i))) {
                return false;
            }
        }
        return true;
    }

**Comment by Blankj** [comment]
判空字符，/t什么的都是空

**Comment by ChenJunXu** [comment]
那如果第一个不为空字符，然后就返回false。会不会出现中间或者最后有空字符的情况呢？

**Comment by Blankj** [comment]
都有不为空的那就是不为空的了，还管后面干嘛

**Comment by ChenJunXu** [comment]
soga，懂了。之前转牛角尖了，3Q
