### ISSUE TITLE
关于加密类EncryptUtils的建议

### ISSUE THREAD

**Issue by chunca** [Blankj/AndroidUtilCode#245]
private static final char hexDigits[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};
有时项目加密需要hexDigits中的字母需要是小写的，建议最好可以更换大小写字母！辛苦了

**Comment by Blankj** [comment]
得到的结果不会String.toLowerCase()吗，我这么多函数都加个你说的标志何必呢
