### ISSUE TITLE
使用Robolectric进行单元测试时报错

### ISSUE THREAD

**Issue by spd-heshuip** [Blankj/AndroidUtilCode#247]
java.lang.VerifyError: Expecting a stackmap frame at branch target 10
Exception Details:
  Location:
    com/blankj/utilcode/util/Utils.getContext()Landroid/content/Context; @3: ifnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b200 08c6 0007 b200 08b0 bb00 0559 1202
    0x0000010: b700 0abf 

报错log，如果去掉初始化的操作后，测试通过。。。

**Comment by Blankj** [comment]
自动化构建单元测试是过的哦

**Comment by pitatensai** [comment]
确实使用Robolectric 会出现这个错误
