### ISSUE TITLE
LeakCanary监测到SpanUtils有内存泄漏

### ISSUE THREAD

**Issue by PeterJiung** [Blankj/AndroidUtilCode#253]
In com.dapang.svip:1.104:20170823.
* com.dapang.svip.v2.ui.order.ConfirmOrderActivity has leaked:
* GC ROOT static com.dapang.base.utils.SpanUtils.mBuilder
* references android.text.SpannableStringBuilder.mSpans
* references array java.lang.Object[].[2]
* references com.dapang.base.utils.SpanUtils$SpaceSpan.this$0
* references com.dapang.base.utils.SpanUtils.mContext
* leaks com.dapang.svip.v2.ui.order.ConfirmOrderActivity instance

* Retaining: 4.2 KB.
* Reference Key: d13ee5c7-ac53-4870-8bcf-9f945825dffb
* Device: Xiaomi Xiaomi MI 3 pisces
* Android Version: 4.4.4 API: 19 LeakCanary: 1.5.1 1be44b3
* Durations: watch=5015ms, gc=181ms, heap dump=1666ms, analysis=24810ms

* Details:
* Class com.dapang.base.utils.SpanUtils
|   static ALIGN_BASELINE = 1
|   static mBuilder = android.text.SpannableStringBuilder@1155184752 (0x44dab870)
|   static $staticOverhead = byte[168]@1128604801 (0x43452481)
|   static LINE_SEPARATOR = java.lang.String@1105558568 (0x41e57c28)
|   static ALIGN_TOP = 3
|   static ALIGN_CENTER = 2
|   static ALIGN_BOTTOM = 0
|   static DEFAULT_COLOR = 301989888
* Instance of android.text.SpannableStringBuilder
|   static SPAN_END_AT_START = 16384
|   static MARK = 1
|   static SPAN_START_AT_START = 4096
|   static POINT = 2
|   static NO_FILTERS = android.text.InputFilter[0]@1106694024 (0x41f6cf88)
|   static END_MASK = 15
|   static SPAN_START_AT_END = 8192
|   static $staticOverhead = byte[288]@1105917793 (0x41eaf761)
|   static START_MASK = 240
|   static PARAGRAPH = 3
|   static START_SHIFT = 4
|   static SPAN_END_AT_END = 32768
|   static SPAN_START_END_MASK = 61440
|   mFilters = android.text.InputFilter[0]@1106694024 (0x41f6cf88)
|   mText = char[26]@1155185600 (0x44dabbc0)
|   mSpans = java.lang.Object[13]@1155185888 (0x44dabce0)
|   mSpanStarts = int[13]@1155185960 (0x44dabd28)
|   mSpanFlags = int[13]@1155186104 (0x44dabdb8)
|   mSpanEnds = int[13]@1155186032 (0x44dabd70)
|   mSpanCountBeforeAdd = 3
|   mSpanCount = 6
|   mGapStart = 11
|   mGapLength = 15
* Array of java.lang.Object[]
|   [0] = android.text.style.ForegroundColorSpan@1155185136 (0x44dab9f0)
|   [1] = android.text.style.AbsoluteSizeSpan@1155185248 (0x44daba60)
|   [2] = com.dapang.base.utils.SpanUtils$SpaceSpan@1155185544 (0x44dabb88)
|   [3] = android.text.style.ForegroundColorSpan@1155185672 (0x44dabc08)
|   [4] = android.text.style.AbsoluteSizeSpan@1155185688 (0x44dabc18)
|   [5] = android.text.style.StrikethroughSpan@1155185872 (0x44dabcd0)
|   [6] = null
|   [7] = null
|   [8] = null
|   [9] = null
|   [10] = null
|   [11] = null
|   [12] = null
* Instance of com.dapang.base.utils.SpanUtils$SpaceSpan
|   this$0 = com.dapang.base.utils.SpanUtils@1155184512 (0x44dab780)
|   color = 0
|   width = 20
* Instance of com.dapang.base.utils.SpanUtils
|   static ALIGN_BASELINE = 1
|   static mBuilder = android.text.SpannableStringBuilder@1155184752 (0x44dab870)
|   static $staticOverhead = byte[168]@1128604801 (0x43452481)
|   static LINE_SEPARATOR = java.lang.String@1105558568 (0x41e57c28)
|   static ALIGN_TOP = 3
|   static ALIGN_CENTER = 2
|   static ALIGN_BOTTOM = 0
|   static DEFAULT_COLOR = 301989888
|   url = null
|   typeface = null
|   style = null
|   alignment = null
|   spans = null
|   shader = null
|   mText = java.lang.String@1155185512 (0x44dabb68)
|   mContext = com.dapang.svip.v2.ui.order.ConfirmOrderActivity@1152185984 (0x44acf680)
|   imageUri = null
|   clickSpan = null
|   imageDrawable = null
|   imageBitmap = null
|   fontFamily = null
|   iconMarginUri = null
|   iconMarginDrawable = null
|   iconMarginBitmap = null
|   foregroundColor = 301989888
|   fontSizeIsDp = true
|   iconMarginGapWidth = -1
|   iconMarginResourceId = -1
|   fontSize = -1
|   flag = 33
|   first = -1
|   imageResourceId = -1
|   bulletRadius = 0
|   isBold = false
|   isBoldItalic = false
|   isItalic = false
|   isStrikethrough = false
|   isSubscript = false
|   isSuperscript = false
|   isUnderline = false
|   lineHeight = -1
|   bulletGapWidth = 0
|   bulletColor = 301989888
|   mType = 0
|   mTypeCharSequence = 0
|   mTypeImage = 1
|   mTypeSpace = 2
|   proportion = -1.0
|   quoteColor = 301989888
|   quoteGapWidth = 0
|   rest = 0
|   blurRadius = -1.0
|   shadowColor = 0
|   shadowDx = 0.0
|   shadowDy = 0.0
|   shadowRadius = -1.0
|   spaceColor = 0
|   spaceSize = -1
|   backgroundColor = 301989888
|   stripeWidth = 0
|   alignLine = 0
|   alignImage = 0
|   alignIconMargin = 0
|   xProportion = -1.0
* Instance of com.dapang.svip.v2.ui.order.ConfirmOrderActivity
|   static REQUEST_CODE_ADDRESS = 0
|   static BUNDLE_TAG_TYPE = java.lang.String@1106257568 (0x41f026a0)
|   static BUNDLE_TAG_COUPON = java.lang.String@1152207616 (0x44ad4b00)
|   static BUNDLE_TAG_BEAN = java.lang.String@1152207552 (0x44ad4ac0)
|   static REQUEST_TAG_ORDER = 1
|   static REQUEST_TAG_SUBMIT = 2
|   static BUNDLE_TAG_LIST = java.lang.String@1152207832 (0x44ad4bd8)
|   static BUNDLE_TAG_DISCOUNT_ID = java.lang.String@1152207752 (0x44ad4b88)
|   static BUNDLE_TAG_TIME = java.lang.String@1106328224 (0x41f13aa0)
|   static $staticOverhead = byte[288]@1150248953 (0x448f67f9)
|   static BUNDLE_TAG_SHOP = java.lang.String@1153461104 (0x44c06b70)
|   static REQUEST_TAG_SUBMIT_DROP_GAME = 3
|   static BUNDLE_TAG_DISCOUNT = java.lang.String@1152207680 (0x44ad4b40)
|   tv = android.support.v7.widget.AppCompatTextView@1152359664 (0x44af9cf0)
|   rv = android.support.v7.widget.RecyclerView@1156369728 (0x44eccd40)
|   mTvTel = android.support.v7.widget.AppCompatTextView@1153517968 (0x44c14990)
|   mAdapter = com.dapang.svip.v2.ui.order.adapter.ConfirmOrderAdapter@1148932264 (0x447b50a8)
|   mAddressId = null
|   mBean = com.dapang.svip.v2.ui.order.bean.ConfirmOrderBean@1157090144 (0x44f7cb60)
|   mChooseAddressId = null
|   mTvRight = android.support.v7.widget.AppCompatTextView@1150189960 (0x448e8188)
|   mCouponId = null
|   mDiscount = null
|   mDiscountId = null
|   mEt = android.support.v7.widget.AppCompatEditText@1153348368 (0x44beb310)
|   mFlEditAddress = android.widget.FrameLayout@1153343344 (0x44be9f70)
|   mFromShop = null
|   mIvLeft = android.support.v7.widget.AppCompatImageView@1150186032 (0x448e7230)
|   mIvRight = android.support.v7.widget.AppCompatImageView@1150189056 (0x448e7e00)
|   mLLChooseRight = android.support.v7.widget.LinearLayoutCompat@1157052848 (0x44f739b0)
|   mLLLeft = android.support.v7.widget.LinearLayoutCompat@1150185456 (0x448e6ff0)
|   mLLRight = android.support.v7.widget.LinearLayoutCompat@1150188248 (0x448e7ad8)
|   mList = null
|   mLv = com.dapang.svip.v2.view.MaxListView@1157049832 (0x44f72de8)
|   mOrderNum = java.lang.String@1153703424 (0x44c41e00)
|   mPostBean = com.dapang.svip.v2.ui.order.bean.PostConfirmOrderBean@1152364128 (0x44afae60)
|   mRemark = java.lang.String@1151733616 (0x44a60f70)
|   mTime = java.lang.String@1152365256 (0x44afb2c8)
|   mTvAddressRight = android.support.v7.widget.AppCompatTextView@1153342264 (0x44be9b38)
|   mTvDeliveryMoney = android.support.v7.widget.AppCompatTextView@1148797608 (0x447942a8)
|   mTvLeft = android.support.v7.widget.AppCompatTextView@1150186864 (0x448e7570)
|   mTvMoney = android.support.v7.widget.AppCompatTextView@1148793984 (0x44793480)
|   mTvName = android.support.v7.widget.AppCompatTextView@1153514760 (0x44c13d08)
|   mChooseType = 1
|   leftColor = -1485549
|   mType = 0
|   red = -439763
|   rightColor = -879104
|   defaultColor = -3618358
|   black = -9342863
|   toolbar = android.support.v7.widget.Toolbar@1152691928 (0x44b4aed8)
|   mDelegate = android.support.v7.app.AppCompatDelegateImplV14@1150435232 (0x44923fa0)
|   mResources = null
|   mEatKeyUpEvent = false
|   mThemeId = 2131427508
|   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@1152165872 (0x44aca7f0)
|   mFragments = android.support.v4.app.FragmentController@1150432472 (0x449234d8)
|   mHandler = android.support.v4.app.FragmentActivity$1@1150432232 (0x449233e8)
|   mNextCandidateRequestIndex = 0
|   mOptionsMenuInvalidated = false
|   mCreated = true
|   mReallyStopped = true
|   mRequestedPermissionsFromFragment = false
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mStartedActivityFromFragment = false
|   mStartedIntentSenderFromFragment = false
|   mExtraDataMap = android.support.v4.util.SimpleArrayMap@1150432208 (0x449233d0)
|   mActionBar = null
|   mActivityInfo = android.content.pm 

.ActivityInfo@1152183424 (0x44acec80)
|   mAllLoaderManagers = android.util.ArrayMap@1149679072 (0x4486b5e0)
|   mApplication = com.dapang.svip.supervip.AppContext@1122990296 (0x42ef78d8)
|   mWindowManager = android.view.WindowManagerImpl@1150435080 (0x44923f08)
|   mWindow = com.android.internal.policy.impl.MiuiPhoneWindow@1150433200 (0x449237b0)
|   mUiThread = java.lang.Thread@1105530024 (0x41e50ca8)
|   mTranslucentCallback = null
|   mComponent = android.content.ComponentName@1152183112 (0x44aceb48)
|   mToken = android.os.BinderProxy@1152183328 (0x44acec20)
|   mContainer = android.app.Activity$1@1150432048 (0x44923330)
|   mCurrentConfig = android.content.res.Configuration@1150433032 (0x44923708)
|   mDecor = null
|   mTitle = java.lang.String@1123987976 (0x42feb208)
|   mDefaultKeySsb = null
|   mSearchManager = null
|   mResultData = null
|   mEmbeddedID = null
|   mParent = null
|   mMenuInflater = null
|   mFragments = android.app.FragmentManagerImpl@1152186456 (0x44acf858)
|   mHandler = android.os.Handler@1150432176 (0x449233b0)
|   mManagedDialogs = null
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@1150432088 (0x44923358)
|   mInstrumentation = android.app.Instrumentation@1122985752 (0x42ef6718)
|   mIntent = android.content.Intent@1152182960 (0x44aceab0)
|   mLastNonConfigurationInstances = null
|   mLoaderManager = null
|   mManagedCursors = java.util.ArrayList@1150432064 (0x44923340)
|   mMainThread = android.app.ActivityThread@1122949968 (0x42eedb50)
|   mLoadersStarted = false
|   mIdent = 1128038456
|   mFinished = true
|   mEnableDefaultActionBarUp = false
|   mResultCode = 0
|   mDoReportFullyDrawn = false
|   mResumed = false
|   mDestroyed = true
|   mStartedActivity = false
|   mStopped = true
|   mTemporaryPause = false
|   mDefaultKeyMode = 0
|   mTitleColor = 0
|   mTitleReady = true
|   mConfigChangeFlags = 0
|   mCheckedForLoaderManager = true
|   mChangingConfigurations = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mChangeCanvasToTranslucent = false
|   mWindowAdded = true
|   mCalled = true
|   mBase = android.app.ContextImpl@1150432488 (0x449234e8)
|   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater@1150434712 (0x44923d98)
|   mOverrideConfiguration = null
|   mResources = android.content.res.MiuiResources@1122976424 (0x42ef42a8)
|   mTheme = android.content.res.Resources$Theme@1150435104 (0x44923f20)
|   mThemeResource = 2131427508
|   mBase = android.app.ContextImpl@1150432488 (0x449234e8)
* Excluded Refs:
| Field: android.app.ActivityThread$ActivityClientRecord.nextIdle
| Field: android.widget.Editor$EasyEditSpanController.this$0
| Field: android.widget.Editor$SpanController.this$0
| Field: android.os.Message.obj
| Field: android.os.Message.next
| Field: android.os.Message.target
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.inputmethod.InputMethodManager.mCurRootView
| Field: android.animation.LayoutTransition$1.val$parent
| Field: android.view.textservice.SpellCheckerSession$1.this$0
| Field: android.support.v7.internal.widget.ActivityChooserModel.mActivityChoserModelPolicy
| Field: android.widget.ActivityChooserModel.mActivityChoserModelPolicy
| Field: android.speech.SpeechRecognizer$InternalListener.this$0
| Field: android.accounts.AccountManager$AmsTask$Response.this$1
| Field: android.media.MediaScannerConnection.mContext
| Field: android.os.UserManager.mContext
| Field: android.appwidget.AppWidgetHost$Callbacks.this$0
| Field: android.media.AudioManager$1.this$0
| Field: android.widget.Editor$Blink.this$0
| Field: android.net 

.ConnectivityManager.sInstance
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Static field: android.text.TextLine.sCached
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by Blankj** [comment]
这我看不出来啊，你咋用的就泄漏了呢

**Comment by Blankj** [comment]
@PeterJiung 使用不当么是你

**Comment by ms03001620** [comment]
public static SpanUtils with(final TextView textView) {
        return new SpanUtils(textView);
    }
这个静态然后持有TextView。是不是有风险？

**Comment by luoxiong94** [comment]
现在还有这个问题
