### ISSUE TITLE
ToastUtils显示的字体没法被改变

### ISSUE THREAD

**Issue by flztsj** [Blankj/AndroidUtilCode#258]
使用反射更改App的默认字体，发现ToastUtils弹出的字体不会被改变

**Comment by Blankj** [comment]
你setCustomView或者用spannable都可以修改字体

**Comment by flztsj** [comment]
没理解

**Comment by Blankj** [comment]
Toast可以自定义视图，你自己传个已经设置字体的layout进去，spannable的话自己查吧

**Comment by flztsj** [comment]
不是单个换字体，现在是App全局换字体，而且只是简单的Toast 每次还得set layout。。

**Comment by flztsj** [comment]
@Blankj 为什么不能debug？

**Comment by sooner0493** [comment]
自定义视图我看源码里并没有给text赋值的地方。。。

**Comment by Blankj** [comment]
你自定义View里不会自己放个TextView吗
