### ISSUE TITLE
请问我的缓存文件为何获取到总是0

### ISSUE THREAD

**Issue by HeJingWei** [Blankj/AndroidUtilCode#262]
请问cacheUtils.getInstance()是获取android/data/包名/cache中所有的缓存包括文件夹里的吗？
我用这个方法获取到的缓存一直都为0
我在cache文件里有一个叫xBitmapCache的文件夹，里面有3个文件，我用cacheUtils.getInstance("xBitmapCache")获取到的缓存依然是0
不是很理解，求解

**Comment by HeJingWei** [comment]
我怎么才能每次都获取到android/data/包名/cache下的缓存  然后实现清理缓存的功能呢？

**Comment by Blankj** [comment]
因为是异步计算吧，你延迟会去获取就不是0了，之后我搞个回调吧。

**Comment by HeJingWei** [comment]
那我用cacheUtils.getInstance()获取到的是android/data/包名/cache中所有的缓存吗，包括所有文件夹下的吗？

**Comment by Blankj** [comment]
你用我的CacheUtils存缓存怎么会存文件夹？只能获取文件，你要获取文件大小那就用FileUtils

**Comment by HeJingWei** [comment]
好的

**Comment by Blankj** [comment]
已修复此bug，现在异步获取size就可以了，同步的话会卡哦

**Comment by HeJingWei** [comment]
好的哈！辛苦了

**Comment by candrwow** [comment]
@Blankj 你好，CacheUtils.getInstance().getCacheSize()方法仍然获取到的是0，是需要其他配置吗，在主线程或是rxjava的异步里结果都是0，设置里获取到的cache是有几兆的，设备是模拟器

**Comment by Blankj** [comment]
用最新版本

**Comment by candrwow** [comment]
@Blankj 这边之前使用的1.9.10,现在替换了1.9.12，实体机和模拟器仍然是0，实体机上在系统设置里看到的缓存大小是304k，

**Comment by Blankj** [comment]
设置里的缓存和我这个缓存不是一个东西啊  大哥

**Comment by candrwow** [comment]
我看到cache就以为是系统缓存，理解错了。3Q
