### ISSUE TITLE
关于自定义toast view

### ISSUE THREAD

**Issue by sooner0493** [Blankj/AndroidUtilCode#264]
private static void show(CharSequence text, int duration) {
        cancel();
        if (customView != null) {
            sToast = new Toast(Utils.getContext());
            sToast.setView(customView);
            sToast.setDuration(duration);
        } else {
            sToast = Toast.makeText(Utils.getContext(), text, duration);
        }
        sToast.setGravity(gravity, xOffset, yOffset);
        sToast.show();
    }
请问这个如何设置显示的text内容？谢谢

**Comment by Blankj** [comment]
？

**Comment by sooner0493** [comment]
抱歉 没表达清 我是说自定义view时传入的layout里面有TextView,如何给这个TextView赋值呢 ？

**Comment by Blankj** [comment]
getView().findViewById(id)

**Comment by sooner0493** [comment]
是这样？ ((TextView) ToastUtils.getView().findViewById(R.id.message)).setText(words);
        ToastUtils.showShort(words);

**Comment by Blankj** [comment]
``` java
ToastUtils.showCustomLong(R.layout.toast_custom);
TextView tvMessage = (TextView) ToastUtils.getView().findViewById(R.id.tv_toast_message);
tvMessage.setText(getString(R.string.toast_custom_view));
```

**Comment by sooner0493** [comment]
好吧 谢谢。。。
