### ISSUE TITLE
ToastUtils.setBgColor设置后只有上下的边距，没有左右的边距，

### ISSUE THREAD

**Issue by xicong** [Blankj/AndroidUtilCode#265]

**Comment by Blankj** [comment]
那你就设置BgResource呗

**Comment by xicong** [comment]
恩恩，就是建议你可以优化一下，我测试了直接给文字设置setPadding就可以了
![image](https://user-images.githubusercontent.com/11675597/29955506-c7ca123a-8f12-11e7-8224-71b2c901818b.png)

**Comment by Blankj** [comment]
android:background="?android:attr/toastFrameBackground"

**Comment by xicong** [comment]
ok

**Comment by Blankj** [comment]
@xicong 更新了哦
