### ISSUE TITLE
APP审核不通过（3.2.9 包含厌恶信息检测）

### ISSUE THREAD

**Issue by zhuozuoying** [Blankj/AndroidUtilCode#266]
我在一个POS机项目中使用这个工具库，提交对方审核提示有两处没有通过审核要求：

建议：希望能避免敏感词会出现

敏感词：u can\'t fuck me...(出现次数:3)
文件：com/blankj/utilcode/utils/IntentUtils.smali

该应用中存在私自拨打电话或者发送短信等行为【1】处。
--
1敏感词：android.intent.action.CALL文件：com/blankj/utilcode/utils/IntentUtils.smali

**Comment by Blankj** [comment]
ok，之前疏漏了

**Comment by jp1017** [comment]
:cry:
