### ISSUE TITLE
Logutils过滤好像有问题，直接Logutils.json(data)没有打印

### ISSUE THREAD

**Issue by yuzhiqiang1993** [Blankj/AndroidUtilCode#267]
LogUtils.Config config = LogUtils.getConfig()
                .setLogSwitch(BuildConfig.DEBUG)// 设置log总开关，包括输出到控制台和文件，默认开
                .setConsoleSwitch(BuildConfig.DEBUG)// 设置是否输出到控制台开关，默认开
                .setGlobalTag(null)// 设置log全局标签，默认为空
                // 当全局标签不为空时，我们输出的log全部为该tag，
                // 为空时，如果传入的tag为空那就显示类名，否则显示tag
                .setLogHeadSwitch(true)// 设置log头信息开关，默认为开
                .setLog2FileSwitch(false)// 打印log时是否存到文件的开关，默认关
                .setDir("")// 当自定义路径为空时，写入应用的/cache/log/目录中
                .setFilePrefix("")// 当文件前缀为空时，默认为"util"，即写入文件为"util-MM-dd.txt"
                .setBorderSwitch(true)// 输出日志是否带边框开关，默认开
                .setConsoleFilter(LogUtils.V)// log的控制台过滤器，和logcat过滤器同理，默认Verbose
                .setFileFilter(LogUtils.V)// log文件过滤器，和logcat过滤器同理，默认Verbose
                .setStackDeep(1);// log栈深度，默认为1
        LogUtils.d(config.toString());
---------------------------------------------------------------------------------------------------
LogUtils.json(json);//这个没有打印
LogUtils.json(LogUtils.I, json);//这个有打印

**Comment by Blankj** [comment]
那是你设备问题，不支持打印Log.d哈，否则不会没有的，不信你可以试试自己打印Log.d

**Comment by yuzhiqiang1993** [comment]
确实是
