### ISSUE TITLE
把sActivityList暴露出来吧

### ISSUE THREAD

**Issue by flztsj** [Blankj/AndroidUtilCode#270]
Utils里面的sActivityList是否可以暴露出来，因为这边会有对Activity堆栈进行一些特殊的管理，既然有了就不先再重复了。

**Comment by flztsj** [comment]
// Activity堆栈管理
public class ActivityManager {
    private static volatile ActivityManager mInstance;

    public List<Activity> getActivityLists() {
        return mActivityList;
    }

    private static List<Activity> mActivityList;

    private ActivityManager() {
        mActivityList = ActivityUtils.getActivityList();
    }

    public static ActivityManager getInstance() {
        if (mInstance == null) {
            synchronized (ActivityManager.class) {
                if (mInstance == null) {
                    mInstance = new ActivityManager();
                }
            }
        }
        return mInstance;
    }

    // 入栈
    public void addActivity(Activity activity) {
        mActivityList.add(activity);
    }

    // 出栈
    public void removeActivity(Activity activity) {
        mActivityList.remove(activity);
    }

    //  彻底退出
    public void finishAllActivity() {
        ActivityUtils.finishAllActivities();
    }

    // 结束指定类名的Activity
    public void finishActivity(Class<? extends Activity> cls) {
        for (Activity activity : mActivityList) {
            if (activity.getClass().equals(cls)) {
                finishActivity(activity);
            }
        }
    }

    // 查找栈中是否存在指定的activity
    public boolean checkActivity(Class<?> cls) {
        for (Activity activity : mActivityList) {
            if (activity.getClass().equals(cls)) {
                return true;
            }
        }
        return false;
    }

    // 结束指定的Activity
    public void finishActivity(Activity activity) {
        if (activity != null) {
            activity.finish();
            activity.overridePendingTransition(0, 0);
        }
    }

    // finish指定的activity之上所有的activity
    public boolean finishToActivity(Class<? extends Activity> actCls, boolean isIncludeSelf) {
        List<Activity> buf = new ArrayList<>();
        int size = mActivityList.size();
        Activity activity;
        for (int i = size - 1; i >= 0; i--) {
            activity = mActivityList.get(i);
            if (activity.getClass().isAssignableFrom(actCls)) {
                for (Activity a : buf) {
                    finishActivity(a);
                }
                return true;
            } else if (i == size - 1 && isIncludeSelf) {
                buf.add(activity);
            } else if (i != size - 1) {
                buf.add(activity);
            }
        }
        return false;
    }

    // finish除最新activity之外所有的同类型activity
    public void finishOthersActivity(Class<? extends Activity> cls) {
        boolean findCur = false;
        int size = mActivityList.size();
        for (int i = size - 1; i >= 0; i--) {
            Activity activity = mActivityList.get(i);
            if (activity.getClass().equals(cls)) {
                if (!findCur) {
                    findCur = true;
                } else {
                    finishActivity(activity);
                }
            }
        }
    }
}

**Comment by flztsj** [comment]
// 结束指定的Activity
public void finishActivity(Activity activity) {
    if (activity != null) {
        activity.finish();
        activity.overridePendingTransition(0, 0);
    }
}

不需要自己主动remove，以为ActivityLifecycleCallbacks会在onActivityDestroyed回调中remove

**Comment by Blankj** [comment]
@flztsj 1.9.1已可使用
