### ISSUE TITLE
ToastUtils实现方式无法更改字体问题

### ISSUE THREAD

**Issue by flztsj** [Blankj/AndroidUtilCode#271]
[FontChange.zip](https://github.com/Blankj/AndroidUtilCode/files/1283666/FontChange.zip)
我这边写了一个换字体的demo，你那边check下，使用ApplicationContext字体无法更换，改用ActvityContext就没有问题

**Comment by Blankj** [comment]
加群了吗你，没的话加我q: 625783482

**Comment by Blankj** [comment]
调用的默认的一直都是sans-serif-condensed这个字体，我工具类里的是跟着系统字体走的，如果你只是要在你的应用里用的话那就把我ToastUtils里的上下文改成Activity，或者自定义以下，参照[CustomToast](https://github.com/Blankj/AndroidUtilCode/blob/master/app/src/main/java/com/blankj/androidutilcode/core/toast/CustomToast.java)

**Comment by flztsj** [comment]
库里换成Activity应该更通用一些吧

**Comment by Blankj** [comment]
不依赖Activity的应用呢，那要咋办，原生toast字体一直都是sans-serif-condensed，不会根据你系统字体的改变而改变，你要想改变字体为何一定要用原生的？为何不自定义下更为简单？
