### ISSUE TITLE
关于NetWorkUtils的问题

### ISSUE THREAD

**Issue by wimvogt** [Blankj/AndroidUtilCode#272]
NetWorkUtils中的isAvailableByPing方法不适用于判断是否有网络，因为可能会出现一直在ping不返回的情况，那么结果为true的处理会一直在等待状态，在这过程中不会执行

**Comment by fenghebaiyang** [comment]
我遇到的问题是ping 223.5.5.5会超时，PC和手机都试过了，公司网络和联通数据流量都试过了。

**Comment by Blankj** [comment]
@wimvogt `-c 1`就是执行一次的意思，怎么会一直在ping。

**Comment by Blankj** [comment]
@fenghebaiyang 超时是因为你网络吧223.5.5.5屏蔽了？可以调用后面自己传入ip地址，比如你公司服务器地址。

**Comment by zhaolewei** [comment]
我也遇到这个问题，这个可以ping 通 ， NetworkUtils.isAvailableByPing("www.yahoo.com");

**Comment by fifa0329** [comment]
主线程中谨慎调用，会引起ANR

**Comment by fifa0329** [comment]
不同设备 ping的实现不同 不会有默认的timeout
