### ISSUE TITLE
FragmentUtils的addFragment再hideAllShowFragment之后,实测切换fragment会跳闪，切换不顺滑。

### ISSUE THREAD

**Issue by pcxjsl** [Blankj/AndroidUtilCode#274]

**Comment by Blankj** [comment]
先隐藏再显示呢

**Comment by pcxjsl** [comment]
都试过了，最后自己写开启同一个FragmentTransaction切换是没问题的，我看了源码，猜测哦，源码里是开启了不同FragmentTransaction导致的吧。

**Comment by Blankj** [comment]
你调用两个函数的话那就是启动两个事务

**Comment by pcxjsl** [comment]
那这样不就有问题吗？切换跳闪很明显，应该要让它们这些函数在一个事务里操作就切换顺滑，肉眼没感觉。

**Comment by Blankj** [comment]
你是要实现什么？

**Comment by pcxjsl** [comment]
就是简单的一个activity上面点击底部radiobutton， show，hide ，Fragment哦~

**Comment by Blankj** [comment]
不是有个hideShowFragment么

**Comment by pcxjsl** [comment]
我好像试过这个方法的，都不行~ 一般都是先hideAll再show点击那个fragment，hideShowFragment要传一个oldFragment? 你去试验一下吧，我再去试试看。

**Comment by Blankj** [comment]
可以试试新版本啦，已修改
