### ISSUE TITLE
CrashUtils自定义路径

### ISSUE THREAD

**Issue by zhuzhao404** [Blankj/AndroidUtilCode#275]
CrashUtils自定义路径遇到崩溃没有退出app，程序一直卡着，而且文件没有写入自定义的路径，默认可以；
CrashUtils.init(ConstantsValue.CRASH_DIR);//自定义的不可用
CrashUtils.init();//可以使用

**Comment by Blankj** [comment]
有个地方写错了变量，下个版本就好

**Comment by flyjin** [comment]
没有什么友好的提示

**Comment by Blankj** [comment]
@zhuzhao404 1.9.1已解决
