### ISSUE TITLE
隐藏状态栏方法无效

### ISSUE THREAD

**Issue by OvenCroc** [Blankj/AndroidUtilCode#276]
隐藏状态栏方法无效 , 权限也添加了 , 但是状态栏还是存在 , 代码我直接在activity的oncreate里面执行的 , `public static void hideNotificationBar(@NonNull final Context context) {
        String methodName = (Build.VERSION.SDK_INT <= 16) ? "collapse" : "collapsePanels";
        invokePanels(context, methodName);
    }`执行的是这个方法 , 求大神帮助

**Comment by Blankj** [comment]
hideNotificationBar不是隐藏状态栏，你仔细看看README文档再看看Demo
