### ISSUE TITLE
ActivityUtils中的finishAllActivities()方法有错

### ISSUE THREAD

**Issue by LJW123** [Blankj/AndroidUtilCode#278]
/**
     * 结束所有activity
     */
    public static void finishAllActivities() {
        List<Activity> activityList = Utils.sActivityList;
        for (int i = activityList.size() - 1; i >= 0; --i) {
            activityList.get(i).finish();
            **activityList.remove(i);**
        }
    }

集合在遍历时不能修改 会报错：ConcurrentModificationException

**Comment by Blankj** [comment]
怎么复现？我测试没事

**Comment by Blankj** [comment]
1.9.1已解决
