### ISSUE TITLE
SpanUtils mBuilder申明为静态的导致内存泄漏

### ISSUE THREAD

**Issue by LambdaV5** [Blankj/AndroidUtilCode#281]
![test](https://user-images.githubusercontent.com/17512402/30847839-88efad88-a2cf-11e7-91b2-72208a354416.png)

**Comment by Blankj** [comment]
忘记把static去掉了，下版本修复，你现在onDestroy里调用下`new SpanUtils()`即可解决

**Comment by Blankj** [comment]
1.9.1已可以使用
