### ISSUE TITLE
设置log写入文件级别有误

### ISSUE THREAD

**Issue by Likarl** [Blankj/AndroidUtilCode#283]
LogUtils.Config config = LogUtils.getConfig();
config.setFileFilter(LogUtils.W)// log文件过滤器，和logcat过滤器同理，默认Verbose

设置LogUtils.D的情况，LogUtils.I级别的日志也写入文件中了。

**Comment by Blankj** [comment]
大佬，你Logcat设置D会没有I？

**Comment by Likarl** [comment]
十分抱歉，常识问题给您添麻烦了，请见谅
