### ISSUE TITLE
(建议)关于判断App是否已经安装的局限性

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#285]
首先 , 感谢大神提供了这个工具, 使用起来非常方便, 其中, 我在使用过程中发现了一些局限, 注意,只是说局限,不是缺陷什么的, 因为像我这样的需求还是比较少的;
源码中,判断应用是否已经安装主要是通过是否有启动的Intent去判断的
`!isSpace(packageName) && IntentUtils.getLaunchAppIntent(packageName) != null;`
但是, 我现在有一个项目, 需求是判断一个服务框架是否已经安装, 由于这个服务框架只有一个NoDisplay的Activity和一些Service组成,不需要桌面图标, 所以没有
`<category android:name="android.intent.category.LAUNCHER"/>`属性
(我的项目是把LAUNCHER改为DEFAULT了,Action也改了)
那么问题就在这里, 我这样肯定是获取不到LaunchIntent的, 最终结果就是我的App已经安装了,但是工具的判断为false,导致了一些问题;

所以,我建议是否考虑添加一个根据action和Category字符串得到ResolveInfo 是否非空的方法去判断App是否安装
下面贴上我自己的相关代码:
`Intent intent = new Intent(ACTION_STRING);`
`intent.addCategory(Intent.CATEGORY_DEFAULT);`
`PackageManager pm = getPackageManager();`
`ResolveInfo info = pm.resolveActivity(intent, 0);`
`if (info != null) {`
`// 软件已安装`
`} else {`
`//软件未安装`

**Comment by Blankj** [comment]
ok，下版本会有

**Comment by Blankj** [comment]
已更新
