### ISSUE TITLE
FileUtils.moveFile方法监听器的问题

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#288]
如题, 建议添加一个监听器的非空判断, 如果监听器为null, 则强制覆盖移动, 我看源码并没有做null判断啊,由于我以前写功能的时候不是用最新版, 现在整合的时候我用了最新版本, 提示方法报错才知道要添加一个监听器,然后跟踪源码发现最后并没有做监听器的null判断,这里会不会有问题
 我现在有个需求, 移动文件不需要判断有没有, 直接强制覆盖移动, 这个看大神有没有空优化一下.

**Comment by Blankj** [comment]
你加个监听器就好了哦
``` java
private FileUtils.OnReplaceListener mListener = new FileUtils.OnReplaceListener() {
    @Override
    public boolean onReplace() {
        return true;
    }
};
```
升级未免多多少少会带来一些代价，你所说的这点也是我没考虑到的，没能兼容旧版本，sorry，但我这样做是为了让开发者有更大的选择余地，代码也是更为健壮、优化、完善，而不是停留在老版本留有的局限性上，希望你也可以更近一下代码哈。

**Comment by xiexin52k** [comment]
代码我已经修正过来了, 使用起来倒是没什么问题, 只是跟踪源码时发现有这个可能导致NPE的问题, 我这人有个习惯哈, 使用开源库喜欢去看看源码, 看看大神的思路和实现, 学习学习一下, 毕竟我自己水平也不高,..

**Comment by Blankj** [comment]
不过还好，这个函数新版本和老版本的参数不一样，所以旧版本肯定是需要修改相关代码，所以也就可以在修改版本号之后再次编译即可发现。
