### ISSUE TITLE
完善工具类

### ISSUE THREAD

**Issue by zhaoxiuyu** [Blankj/AndroidUtilCode#29]
单位转换，比如dp转px . .. . . . .
文件操作，文件创建 删除  压缩等等....
Bitmap处理工具类，毛玻璃  圆角  转byte[]之类的.....
MD5 . Base64 工具类......

**Comment by Blankj** [comment]
单位在SizeUtils，文件和图片操作这两天会加，MD，Base64都在Encode和Encrypt里
