### ISSUE TITLE
ToastUtils在小米手机上字体特别大

### ISSUE THREAD

**Issue by q996467794** [Blankj/AndroidUtilCode#290]
`TextViewCompat.setTextAppearance(tvMessage, android.R.style.TextAppearance);`
中`<item name="textSize">16sp</item>`导致Toast看起来特别奇怪，建议增加全局设置Toast的方法

**Comment by Blankj** [comment]
原生比这个就多了个字体而已，大小我并没有改变，想自定义那就参照我写的CustomToast自己写一个，具体看Demo
