### ISSUE TITLE
建议添加获取软键盘高度的工具

### ISSUE THREAD

**Issue by wapchief** [Blankj/AndroidUtilCode#292]

**Comment by Blankj** [comment]
那么问题来了，你怎么获取。

**Comment by dxsdyhm** [comment]
用尺量啊-_-

**Comment by genius158** [comment]
也是可以做的，软键盘会在相对布局的时候，把布局顶起来，利用这个原理来实现。

**Comment by Blankj** [comment]
在应用里我知道怎么获取，那么你怎么封装个api来获取呢

**Comment by genius158** [comment]
在window里插入透明的相对布局，测量完毕后移除，当然还得考虑sindowSoftInptMode，就是判断两个：window在屏幕的底边的位置和相对布局的高度来共同判断软键盘的高度

**Comment by Blankj** [comment]
@genius158 show me ur code. :rofl:

**Comment by genius158** [comment]
@Blankj 我只是说明一下思路，理论上是可以实现的😁
根据windowSoftInputMode来做，当然真的实现起来大概会很麻烦很麻烦，情况很多
要对获取焦点的控件的父控件做各种判断，再判断要不要考虑这个父控件的父控件，
再决定要不要插入相对布局或怎么插入.etc,
做不到软键盘弹起之前就得到高度，本身使用这个高度的情况就很少，再加上这个条件，
就更少了，花大力气去做这个，基本上是没有意义🤓

**Comment by Blankj** [comment]
你说的考虑这么多都是在有界面的条件下，所以在没有界面单纯封装出一个api可供调用来获取高度，基本是实现不了哈，而且你说的这种还需要显示键盘后方可获取，那要是想直接获取那是更加没戏哦，理论和现实还是有很大差距的哈。
