### ISSUE TITLE
Activity从链表当中移除

### ISSUE THREAD

**Issue by zhaoxiuyu** [Blankj/AndroidUtilCode#293]
在 Application 中初始化工具类 Utils.init(this)  看里面的代码 
会自动把启动的Activity都添加一个sActivityList链表里面，
当我关闭某一个Activity的时候如何把当前Activity从链表当中移除掉。。。

**Comment by Blankj** [comment]
好好看源码吧，ActivityLifeCycleCallback这个回调利用的是

**Comment by zhaoxiuyu** [comment]
谢谢，是我没看清楚
