### ISSUE TITLE
ImageUtils.save always return false

### ISSUE THREAD

**Issue by RanKKI** [Blankj/AndroidUtilCode#300]
public static boolean save(final Bitmap src, final File file, final CompressFormat format, final boolean recycle) {
        if (isEmptyBitmap(src) || !createFileByDeleteOldFile(file)) return false;
        OutputStream os = null;
        boolean ret = false;
        try {
            os = new BufferedOutputStream(new FileOutputStream(file));
            ret = src.compress(format, 100, os);
            if (recycle && !src.isRecycled()) src.recycle();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            CloseUtils.closeIO(os);
        }
        return ret;
    }

It is a bug or feature ?

**Comment by Blankj** [comment]
有什么问题？

**Comment by RanKKI** [comment]
按常理来讲如果成功了不应该return true么. 但这个似乎并不会return true.

**Comment by Blankj** [comment]
ret = src.compress(format, 100, os); 压缩成功ret就变成true了哦

**Comment by RanKKI** [comment]
我的我的... 没注意到....
