### ISSUE TITLE
PermissionUtils.requestPermissions

### ISSUE THREAD

**Issue by OoadaioO** [Blankj/AndroidUtilCode#305]
系统 5.1.1
AppCompatActivity 没有requestPermissions这个方法

java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
                                                                            at com.blankj.utilcode.util.PermissionUtils.requestPermissions(PermissionUtils.java:73)

可以通过下面方式解决

    public static boolean checkPermission(final Activity context, final int requestPermissionCode, final String... permissions) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            return true;
        }

        List<String> permissionsNeeded = new ArrayList<>();
        final List<String> permissionsList = new ArrayList<>();
        for (String permission : permissions) {
            if (!addPermission(context, permissionsList, permission)) {
                permissionsNeeded.add(permission);
            }
        }
        if (permissionsList.size() > 0) {
            if (permissionsNeeded.size() > 0) {
                DialogHelper.dialogBuilder(context, R.string.dialog_title_notice, R.string.toast_permission_failure)
                        .setPositiveButton(R.string.dialog_ok, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                                    ActivityCompat.requestPermissions(context,permissionsList.toArray(new String[permissionsList.size()]), requestPermissionCode);
                                }
                            }
                        }).show();
                return false;
            }
            ActivityCompat.requestPermissions(context,permissionsList.toArray(new String[permissionsList.size()]), requestPermissionCode);
            return false;
        }
        return true;
    }

**Comment by Plainlazy01** [comment]
Do I send you my code info

**Comment by Blankj** [comment]
这个类我还没写入到README里 还没搞好 好了会加入到README里的

**Comment by Blankj** [comment]
@OoadaioO @Plainlazy01 @MapleDev PermissionUtils 已在 1.11.0 问世
