### ISSUE TITLE
EmptyUtils.isEmpty

### ISSUE THREAD

**Issue by OoadaioO** [Blankj/AndroidUtilCode#306]
这个方法是否能拆分成多个isEmpty方法，而不是内部isInstanceOf 不然很多if 比较耗性能

**Comment by Blankj** [comment]
只是单纯地if else 判断而已，常用的都靠前放了，不常用的放在后面，这个函数本来就是为了统一判断而省去类型判断，你把它单个拆开来判断的话，我觉得那你还不如直接在代码里写if else判断得了。
