### ISSUE TITLE
android6.0以后的敏感权限怎么控制的？

### ISSUE THREAD

**Issue by CH-Augustine** [Blankj/AndroidUtilCode#309]

**Comment by Blankj** [comment]
PermissionUtils还没做呢，第三方库很多，可以选一个暂时

**Comment by nzsdyun** [comment]
写的不错，6.0动态权限，我写了个库，在[permissionutil](https://github.com/nzsdyun/PermissionDemo/tree/master/permissionutil),你们可以看下。

**Comment by Blankj** [comment]
@nzsdyun 好的

**Comment by Blankj** [comment]
@CH-Augustine 1.11.0 PermissionUtils 已发布

**Comment by CH-Augustine** [comment]
Thank you, I have received your letter and have already visited GitHub!
发自银河系火星


在2018年01月11日 10:41，布兰柯基<notifications@github.com> 写道：

Closed #309.
