### ISSUE TITLE
建议使用阿里规约插件规范一下工具类相关代码。

### ISSUE THREAD

**Issue by yangyiRunning** [Blankj/AndroidUtilCode#313]
RT

**Comment by Blankj** [comment]
规范只是一个约定俗成，每个大公司都有这种style，我也有我总结的规范：https://github.com/Blankj/AndroidStandardDevelop   我为何一定要去迎合阿里的规范呢，我觉得AS自带的lint检查这方面做得足够好了，最重要的还是代码的可读性高。

**Comment by yangyiRunning** [comment]
@Blankj    之所以有这个issue是因为是平常将这个类当中的util类拷入项目代码中时，由于彼此之间的规约标准不匹配，导致需要做大量的修改（诸如修改常量、注释方式、命名规则等等诸如此类）。所以才想到有没有统一规约标准的可能。当然了，规约这东西大家也见仁见智，我只是提出一个想法。

**Comment by Blankj** [comment]
即便我改成了阿里的规约，那么其他不用阿里规约的人呢，既然都是用AS的，那么为何不用AS自带的规则呢，如果AS之后自带了阿里规约，那我肯定也遵守其规约，众口难调，为何不接受默认的，默认的也就是大部分人所能接受的

**Comment by yangyiRunning** [comment]
@Blankj  阿里规约相对AS默认更严格点，不过你说的对，标准这个东西，确实众口难调，作为开源项目，统一标准确实很难。看来还是平常引用的时候多细心吧~
