### ISSUE TITLE
MultiDex Error

### ISSUE THREAD

**Issue by Mehran-Abghari** [Blankj/AndroidUtilCode#317]
When i updated UtilCode to v1.9.8 I got this error:

`Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/blankj/utilcode/util/LogUtils;`

**Comment by Blankj** [comment]
u can try it.
```
dexOptions {
    preDexLibraries = false
}
```
clean and build ur project.

**Comment by Mehran-Abghari** [comment]
Thanks for reply, I deleted .gradle cache folder and rebuild my project. It fixed my issue.
