### ISSUE TITLE
SPUtils.java 's name is confusing

### ISSUE THREAD

**Issue by beshoy-samy** [Blankj/AndroidUtilCode#319]
this issue is dummy but the shared prefs Util class name is confusing I think you should rename it I was about to use another library or use my own class.

**Comment by Blankj** [comment]
SharedPreferences getPreferences (int mode)
Retrieve a SharedPreferences object for accessing preferences that are private to this activity. This simply calls the underlying getSharedPreferences(String, int) method by passing in this activity's class name as the preferences name.
U can read the [document](https://developer.android.com/guide/topics/data/data-storage.html#pref)
