### ISSUE TITLE
线程

### ISSUE THREAD

**Issue by newObjectOne** [Blankj/AndroidUtilCode#32]
能不能做一些线程相关的工具类

**Comment by Blankj** [comment]
线程池吗还是什么

**Comment by newObjectOne** [comment]
是的，多线程之类的

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/utils/ThreadPoolUtils.java
