### ISSUE TITLE
SPUtil改成静态方法更方便

### ISSUE THREAD

**Issue by DanteAndroid** [Blankj/AndroidUtilCode#324]
SP 一般以包名命名即可，即使用：`PreferenceManager.getDefaultSharedPreferences(App.context)`更为方便。
如果想自定义名称，可以加个构造函数，重新赋值给静态的sp对象

参考代码：[SpUtil.java.zip](https://github.com/Blankj/AndroidUtilCode/files/1512520/SpUtil.java.zip)

**Comment by Blankj** [comment]
那么如果我在 Login 模块中操作 SP 是 Login 名称的 SP，在 Setting 模块中操作 SP 是 Setting 名称的 SP，而在操作 SP 的时候都要来回重新设置 SP 的名称吗，这样就不方便了啊。我如今这样的多重单例同样使用在 CacheUtils 中，我推荐的做法是对数据的操作一般都是放在一个 data 包下的，比如可以在 DataManager 里面声明多个 SPUtils 单例对象操作 SP 即可，而不是在业务层直接使用 SPUtils，即便需要在 业务层直接使用 SPUtils 的话，可以在 Application 中放一个全局静态的 SPUtils 对象即可。

**Comment by DanteAndroid** [comment]
按照我的说法，提供一个默认的sp，然后提供构造函数不就好了~两全其美

**Comment by Blankj** [comment]
那怕是不行哦，静态函数和对象的函数不能是同名的，而且这样设计反而臃肿，我觉得这种需要多个名称的用多重单例就好了，直接全静态就不适用多名称的了，这也是我很早之前就发现的，我最初就是像你说的那样设计的，然后碰到多名称的就满足不了了，所以改成如今这样。

**Comment by DanteAndroid** [comment]
好，感谢回复！
