### ISSUE TITLE
ImageUtils.compressBySampleSize throws OutOfMemoryError

### ISSUE THREAD

**Issue by AbduazizKayumov** [Blankj/AndroidUtilCode#326]
Here is a code I am using:

`  private final static int GOOD_WIDTH = 480;
    private final static int GOOD_HEIGHT = 640;
    public static Bitmap getResizedBitmap(Bitmap bm) {
        if (bm == null)
            return bm;
        return ImageUtils.compressBySampleSize(bm, GOOD_WIDTH, GOOD_HEIGHT);
    }
`

**Comment by Blankj** [comment]
@AbduazizKayumov Do you solve it?

**Comment by AbduazizKayumov** [comment]
@Blankj yes, I have solved it by increasing heapSize, those who have the same issue should refer first [this](https://plumbr.io/outofmemoryerror/java-heap-space), then [this](https://stackoverflow.com/questions/25719620/how-to-solve-java-lang-outofmemoryerror-trouble-in-android). This issue is not related to the library, that's why I closed it.
