### ISSUE TITLE
LogUtils能否添加全局TAG后还能显示当前类名的功能

### ISSUE THREAD

**Issue by baiyulinlin** [Blankj/AndroidUtilCode#327]
比如：全局TAG-MainActivity:---------

**Comment by baiyulinlin** [comment]
还有log头部显示的位置，能否点击追踪到当前代码

**Comment by Blankj** [comment]
@baiyulinlin 
不明白 “还有log头部显示的位置，能否点击追踪到当前代码” 什么意思

**Comment by baiyulinlin** [comment]
D/芯芯卡管家: ║ main, initParms(MainActivity.java:71)
上面这个能不能做成点击MainActivity.java:71就跳转到该类

**Comment by Blankj** [comment]
可以的啊，你的不能跳转？

**Comment by Blankj** [comment]
卧槽，貌似现在咋不行了，我看看咋回事

**Comment by baiyulinlin** [comment]
不可以啊

**Comment by baiyulinlin** [comment]
需要做什么配置么

**Comment by Blankj** [comment]
吓我一跳，可以的是，Logcat 里就可以哦 
![image](https://user-images.githubusercontent.com/17978187/33540796-93d37d56-d907-11e7-9c1b-8123abeb4373.png)

**Comment by baiyulinlin** [comment]
![image](https://user-images.githubusercontent.com/15973309/33540861-cb5d5468-d907-11e7-9a44-1532d07a7bdc.png)

**Comment by Blankj** [comment]
你确定你是在Logcat里？不是在run里？

**Comment by baiyulinlin** [comment]
卧槽，还是在run里面，只支持logcat是吧

**Comment by baiyulinlin** [comment]
卧槽，还真是在run里面，只支持logcat是吧

**Comment by Blankj** [comment]
还有你说的那个全局 TAG 一般是什么？是根据应用分的吗，那就选择 
![image](https://user-images.githubusercontent.com/17978187/33540988-5095c4bc-d908-11e7-955e-3b12b2662a6c.png) 就好了吧，不然那个前缀 TAG 还有什么用？

**Comment by Blankj** [comment]
是的，也就只有 logcat 支持点击跳转啊，其他不都是不带链接的么。

**Comment by baiyulinlin** [comment]
![image](https://user-images.githubusercontent.com/15973309/33541077-bcf90d44-d908-11e7-89d4-ddea0c3b892a.png)

**Comment by baiyulinlin** [comment]
为啥系统的run可以直接跳

**Comment by baiyulinlin** [comment]
![image](https://user-images.githubusercontent.com/15973309/33541227-48fdb9ca-d909-11e7-8606-89dc48c87067.png)

**Comment by baiyulinlin** [comment]
我想起来了，logger的可以哦

**Comment by Blankj** [comment]
我去看看比较下有啥不同

**Comment by Blankj** [comment]
run 里面跳转的话需要该行有 `.` 才能
![image](https://user-images.githubusercontent.com/17978187/33546111-1cb04b6e-d91b-11e7-903b-2d1c6d2ce261.png)

我觉得没必要在 run 里支持跳转，看 logcat 就好了，Logger 做的前面显示 类名.方法名(文件名:行数) 类名和文件名重复了，没必要。

**Comment by baiyulinlin** [comment]
好吧
