### ISSUE TITLE
努比亚Z11mini,BarUtils 下的hideNotificationBar方法无效

### ISSUE THREAD

**Issue by aijiao0624** [Blankj/AndroidUtilCode#328]
测试真机：
荣耀9全网通尊享版，系统Android7.0（EMUI5.1），B190
努比亚Z11mini（NX529J），系统Android5.1.1（Nubia UI 3.9.6.1）

**Comment by Blankj** [comment]
有解决方案吗

**Comment by aijiao0624** [comment]
参照这个：http://blog.csdn.net/guolin_blog/article/details/51763825

**Comment by aijiao0624** [comment]
这个不能@XXX？？？

**Comment by Blankj** [comment]
可以 @ 的，我可以看到的只要你回我

**Comment by Blankj** [comment]
你这个发的是状态栏，notificationbar 是通知栏，不是一个东西。
