### ISSUE TITLE
数学运算的工具类

### ISSUE THREAD

**Issue by smallfishfizz** [Blankj/AndroidUtilCode#329]
虽然网上有很多现成的代码，但是作为一个强迫症，希望大神你考虑考虑下，能不能加到你的神作里⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by Blankj** [comment]
运算？比如呢

**Comment by smallfishfizz** [comment]
@Blankj 比如int、float、double、long各种类型的数据加减乘除，要考虑到精度缺失问题。

**Comment by Blankj** [comment]
这还用封装？考虑高精度那就使用 Java 的高精度类，系统 API 已经很完善啦，平时浮点型转整型四舍五入加个 0.5 即可吧。

**Comment by smallfishfizz** [comment]
@Blankj 我估计大神你会这么回复我😂....懒癌庅，传两个数字进去拿结果就行🙈

**Comment by Blankj** [comment]
懒不死你哈，这种就是过度封装了。

**Comment by smallfishfizz** [comment]
@Blankj 🙈🙈🙈好吧，谢谢大神的回复

**Comment by xiexin52k** [comment]
大柯基佬, 建议增加一个输入APP名字和需求就可以一键生成apk的工具类...
