### ISSUE TITLE
有系统签名的APK,但不是系统APK静默安装会失败

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#334]
如题, 被静默安装坑了三个钟, 我有系统的签名文件, 但是程序并不是系统程序, 另外系统也没有root权限,当运行静默安装的时候, 始终安装不上, 
源代码采用这样的判断
```java
ShellUtils.CommandResult commandResult = ShellUtils.execCmd(command, !isSystemApp(), true);
```
导致程序始终调用su, 由于我系统su不存在, 就会一直报错,[su] Environment : null这样的, 后来经过我导入修改成
```java
ShellUtils.CommandResult commandResult = ShellUtils.execCmd(command, isSystemApp(), true);
```
这样后, 就可以使用sh用户执行, 然后就可以静默安装了;

我觉得大神是不是没有考虑到这种情况, 就是系统没有root(没有su), 然后软件也不是系统级别的APP, 但是有系统签名这样的情况...

**Comment by Blankj** [comment]
你这样的情况我没碰到过，所以不了解哈，那我加个参数来传入是否使用 root 吧。
