### ISSUE TITLE
Parcelable 和 Serializable 在CacheUtils 时存储不考虑持久化,到底哪个内存开销更小

### ISSUE THREAD

**Issue by bzn1120** [Blankj/AndroidUtilCode#335]
http://www.jianshu.com/p/287acb9e396f
这个帖子做个试验说Serializable  被冤,Serializable快,
其他帖子都说Parcelable  内存开销小,不能持久化保存,Serializable  容易造成gc,求正解

**Comment by bzn1120** [comment]
http://www.developerphil.com/parcelable-vs-serializable/

![default](https://user-images.githubusercontent.com/4623275/33817275-a284dd8c-de79-11e7-88c4-d7c032ab6e4b.png)
![Uploading 图片.png…]()

**Comment by bzn1120** [comment]
![default](https://user-images.githubusercontent.com/4623275/33817305-d8034d90-de79-11e7-97b1-7fa740ad8fc5.png)

**Comment by Blankj** [comment]
自己取舍，我觉得简单的就用 parcelable，复杂的就用 serializable。

以后这种不关于库的问题不要在这提 issue
