### ISSUE TITLE
正则更新

### ISSUE THREAD

**Issue by kidochen** [Blankj/AndroidUtilCode#338]
柯基好，
中国移动新增了198开头的号码选择，中国联通则是166开头，中国电信是199开头。
`RegexConstants` 中的 `REGEX_MOBILE_EXACT` 正则要更新一下。 
`^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,1,3,5-8])|(18[0-9])|(166)|(199)|(198)|(147))\\d{8}$`
/**
     * 正则：手机号（精确）
     * <p>移动：134(0-8)、135、136、137、138、139、147、150、151、152、157、158、159、178、182、183、184、187、188</p>
     * <p>联通：130、131、132、145、155、156、171、175、176、185、186</p>
     * <p>电信：133、153、173、177、180、181、189</p>
     * <p>全球星：1349</p>
     * <p>虚拟运营商：170</p>
     */
    public static final String REGEX_MOBILE_EXACT  = "^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,1,3,5-8])|(18[0-9])|(147))\\d{8}$";

**Comment by Blankj** [comment]
已更新 1.9.12 版本
