### ISSUE TITLE
手机相关:PhonekUtils.java的网址写错了

### ISSUE THREAD

**Issue by zjfsdnu** [Blankj/AndroidUtilCode#34]
现在是
https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/utils/PhonekUtils.java
应该是
https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/utils/PhoneUtils.java
多了个k

**Comment by Blankj** [comment]
哈哈，又是个有心人
