### ISSUE TITLE
有没有获取存储设备空间大小的API?

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#340]
如题, 我在工具里面没有找到相关API, 是没有提供还是我没找到呢?
目前我使用自己的方法获取总空间以及可用空间
```java
//获取总空间大小
StatFs statFs = new StatFs(path);
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            return  statFs.getTotalBytes();
        } else {
            return statFs.getBlockCount() * statFs.getBlockSize();
        }

//获取可用空间大小
StatFs statFs = new StatFs(path);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            return statFs.getAvailableBytes();
        } else {
            return statFs.getAvailableBlocks() * statFs.getBlockSize();
        }
```

如果柯基大神没有添加这个API并且觉得我这个方法没什么问题的话, 可考虑是否添加?

**Comment by Blankj** [comment]
``` java
File file = new File(path);
file.getTotalSpace();
file.getFreeSpace();
file.getUsableSpace();
```

**Comment by xiexin52k** [comment]
啥? 还有这操作, 我怎么不知道..哈哈哈哈

**Comment by Blankj** [comment]
你可以试试看，看结果是不是一样的，然后对比下 adb shell 得到的结果，看哪个准确。

**Comment by xiexin52k** [comment]
OK我去试试

**Comment by xiexin52k** [comment]
getFreeSpace和getUsableSpace获得的值不一样, 经过测试发现getUsableSpace更加符合实际大小,getFreeSpace获取的要大一点点 @Blankj

**Comment by Blankj** [comment]
看下源代码的解释吧
     * Returns the number of bytes available to this virtual machine on the
     * partition <a href="#partName">named</a> by this abstract pathname.  When
     * possible, this method checks for write permissions and other operating
     * system restrictions and will therefore usually provide a more accurate
     * estimate of how much new data can actually be written than {@link
     * #getFreeSpace}.
里面说了的哦。
