### ISSUE TITLE
IntentUtils类下的相机getCaptureIntent方法获取的相机意图，跳转相机还没拍照，onActivityResult就回调。

### ISSUE THREAD

**Issue by chenyiyao** [Blankj/AndroidUtilCode#341]
在onActivityResult回调无法获取到图片

**Comment by Blankj** [comment]
你 Activity 是 singleTask 模式？

**Comment by chenyiyao** [comment]
不是的，是获取的Intent中添加了Intent.FLAG_ACTIVITY_NEW_TASK这个标签。去掉这个就没问题了

**Comment by chenyiyao** [comment]
@Blankj 不是的，是获取的意向中添加了Intent.FLAG_ACTIVITY_NEW_TASK这个标签。去掉这个就没问题了

**Comment by Blankj** [comment]
嗯，5.0 以下的机器会这样，5.0 以后的就没事，我写个是否 new task 的参数吧。

**Comment by chenyiyao** [comment]
@Blankj 我用的是魅族pro6 是7.0的

**Comment by Blankj** [comment]
机器不一样吧，哈哈，下个版本会改。

**Comment by Blankj** [comment]
新版本已发布，已修复哈
