### ISSUE TITLE
横屏状态，获取屏幕宽度getScreenWidth方法和虚拟导航栏getNavBarHeight方法不准确

### ISSUE THREAD

**Issue by edifangyi** [Blankj/AndroidUtilCode#342]
测试设备：坚果pro2，测出宽度是不包含导航条，此时需要加入虚拟导航栏按钮宽度才是正确值。
测试设备：三星平板，测出宽度为实际值，屏幕上是没有虚拟导航栏按钮的，但是也把虚拟导航栏测出来了96

**Comment by Blankj** [comment]
呵，国产机，都被玩坏了，那你有什么能统一下的吗

**Comment by Blankj** [comment]
新版本已发布，欢迎使用
