### ISSUE TITLE
BarUtils优化

### ISSUE THREAD

**Issue by wimvogt** [Blankj/AndroidUtilCode#344]
可以添加根据状态栏的颜色深浅来设置状态栏文字的模式（如设置状态样为白色后，其改为暗色模式）

**Comment by Blankj** [comment]
你这是有点业务化了，状态栏图标文字颜色 6.0 以后才正式支持，之后我会新增相关 api，至于国内给大厂家低版本乱七八糟的修改字体颜色，我是不会去适配的哈。

**Comment by Blankj** [comment]
6.0 以后的可以调用 [BarUtils#setStatusBarLightMode](https://github.com/Blankj/AndroidUtilCode/blob/08f27a0a8edf51366ec376e93831cec39036d257/utilcode/src/main/java/com/blankj/utilcode/util/BarUtils.java#L104-L104)
