### ISSUE TITLE
有点小疑问，有人能解答的吗

### ISSUE THREAD

**Issue by huzipiaopiao** [Blankj/AndroidUtilCode#348]
请问下，如果app只需要其中的几个方法，如果添加了这个库，是不是会增加app的方法数和体积

**Comment by zuolongxiang** [comment]
如果使用了Proguard，没有使用到的方法会自动删除。

**Comment by huzipiaopiao** [comment]
如果不用混淆，是会出现我说的问题的是么？看来还是得学会混淆，我现在都是加固了直接上架的，不怎么会混淆
