### ISSUE TITLE
Snackbar 添加顶部显示实现

### ISSUE THREAD

**Issue by azMallco** [Blankj/AndroidUtilCode#349]

**Comment by Blankj** [comment]
顶部实现动画需要从上往下，系统的无法实现吧。

**Comment by azMallco** [comment]
是需要重写布局好像

**Comment by Blankj** [comment]
我说的是显示动画就不一样，布局不是问题。

**Comment by BobEve** [comment]
https://stackoverflow.com/questions/31746300/how-to-show-snackbar-at-top-of-the-screen/36768267
这样可以处理顶部弹出
