### ISSUE TITLE
encryptAES返回null

### ISSUE THREAD

**Issue by Johnny-Chou** [Blankj/AndroidUtilCode#351]
EncyptUtils.encryptAES(),传入两个字节数组，一直返回null。。。

**Comment by Blankj** [comment]
看 [Test](https://github.com/Blankj/AndroidUtilCode/blob/2847e5a342d28e0a8404b161152f47a4df3482e0/utilcode/src/test/java/com/blankj/utilcode/util/EncryptUtilsTest.java#L396-L396)，你的模式不对，默认是
![image](https://user-images.githubusercontent.com/17978187/34246380-53262ba4-e669-11e7-98a6-6490525e3197.png)
你自己改成你的

**Comment by Johnny-Chou** [comment]
改过了的。看了下实现方式，cipher.init(Cipher.DECRYPT_MODE, keySpec, ivspec);好像缺个IvParameterSpec参数

**Comment by Blankj** [comment]
那是 SecureRandom 吧，有什么关系吗

**Comment by Johnny-Chou** [comment]
因为之前会抛一个异常，java.security.InvalidKeyException: Parameters missing。
然后参考[https://stackoverflow.com/questions/6669181/why-does-my-aes-encryption-throws-an-invalidkeyexception](url)解决了。。。

**Comment by Blankj** [comment]
不同模式需要不同的 init 吧

**Comment by Blankj** [comment]
新版本函数最后加了个向量参数

**Comment by iielse** [comment]
@Blankj 测试用例是不是没有更新哇。 encryptAES方法现在有4个入参，但是单元测试只有2个。

**Comment by Blankj** [comment]
你看的是最新代码吗

**Comment by iielse** [comment]
我点的第二条回复的    `看 Test，你的模式不对，默认是`

**Comment by Blankj** [comment]
那个是当时的代码，所以是那样的

**Comment by iielse** [comment]
@Blankj 那函数新加的2个参数不会传，能不能补一下。谢谢。

**Comment by Blankj** [comment]
去了解一下 AES 加密，第三个和第四个需要看你们服务端怎么配制的
