### ISSUE TITLE
继承郭霖的LitePalApplication不能初始化的冲突怎么解决?

### ISSUE THREAD

**Issue by canglen** [Blankj/AndroidUtilCode#354]
集成郭霖的LitePalApplication后 application需要继承LitePalApplication,
并把清单文件中的name指为 android:name="org.litepal.LitePalApplication"
造成 init失败
请教如何解决
logger也存在这个问题.
klog没有这个问题.

**Comment by Blankj** [comment]
什么错误啊返回？

**Comment by canglen** [comment]
就提示没有init
传入 this 及(Application)LitePalApplication.getContext() 均不可以.

**Comment by canglen** [comment]
把 android:name="MyApplication"  并修改 MyApplication extends Application 后  

可以init成功并正常使用.

**Comment by Blankj** [comment]
你自己写个 BaseApplication，然后在 BaseApplication 中初始化我的工具类，然后再写个 AppApplication，让它继承 LitePalApplication

**Comment by canglen** [comment]
清单文件里的  android:name="org.litepal.LitePalApplication"  呢?

**Comment by Blankj** [comment]
你有没有初始化我的工具类？`Utils.init(this);`

**Comment by canglen** [comment]
汗..肯定初始化的哦,
我意思是 MyApplication继承LitePalApplication,
这个litepal是需要修改清单文件中的name指为 android:name="org.litepal.LitePalApplication"
的
然后 在  MyApplication 里 Utils.init(this);  是无效的. 报错提示 没有init
同样的在MyApplication继承LitePalApplication的情况下.
logger也存在这个问题.
但是 klog没有这个问题.

**Comment by Blankj** [comment]
你自己写一个 MyApplication 继承了LitePalApplication，那清单文件就用 MyApplication 就好了啊。

**Comment by canglen** [comment]
又去看了下  LitePalApplication 确实可以... 
我好像太久没注意了.抱歉...
感谢百忙之中回复.
建议可否增加个 Decimal 类 用于精确计算. 加减乘除计算.
