### ISSUE TITLE
一键重启，使用ShellUtils下的方法无法被记住

### ISSUE THREAD

**Issue by 1130381752** [Blankj/AndroidUtilCode#355]
如题，使用的是ShellUtils.execCmd("reboot",true,true)，但是貌似这个动作是一点击同意root申请就执行了，无法被记住root申请（勾选了 记住我的选择 也没用），下次再用又会申请一遍，自己也想不到延迟重启的方法，我也尝试过一进去就调用ShellUtils.execCmd("su",true,true)并勾选 记住我的选择，重启系统后还是没被root管理程序记住，求解决方法

**Comment by Blankj** [comment]
这我也帮不了，你要是知道有个参数能解决欢迎反馈。

**Comment by 1130381752** [comment]
你是说把返回的结果打印出来是吗，点重启并拒绝是这样的：
result:1,successMsg:,errorMsg:Permission denied
允许的话就直接重启了，打印不出返回结果

**Comment by Blankj** [comment]
root 的还是不靠谱的哈

**Comment by 1130381752** [comment]
好吧，市场上一些一键关机重启都能被supersu这种root管理程序记住，想做个这样的App，但是找不到好方法.虽然我用的不是supersu而是安卓原生系统自带的root权限管理
