### ISSUE TITLE
AppUtils工具类引起崩溃

### ISSUE THREAD

**Issue by samuelhuahui** [Blankj/AndroidUtilCode#356]
java.lang.RuntimeException:Unable to create application s.h.e.l.l.S: java.lang.RuntimeException: Package manager has died
--
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4881)
3 ......
4 android.os.DeadObjectException:
5 android.os.BinderProxy.transactNative(Native Method)
6 android.os.BinderProxy.transact(Binder.java:503)
7 android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:2408)
8 android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:309)
9 com.ody.library.utils.util.AppUtils.boolean isAppDebug(java.lang.String)(AppUtils.java:400)
10 com.ody.library.utils.util.AppUtils.boolean isAppDebug()(AppUtils.java:387)

**Comment by Blankj** [comment]
必现还是怎么？

**Comment by samuelhuahui** [comment]
偶发

**Comment by samuelhuahui** [comment]
@Blankj   偶发的

**Comment by Blankj** [comment]
偶发的话应该是应用当时环境有关，函数本身应该没问题，看报错的话就是当时 Package manager 被杀死了，所以函数里获取 Package manager 相关的都会有问题了。
