### ISSUE TITLE
因为AppUtils里的静默安装和静默卸载的代码 ，被某数字公司监测出apk有病毒

### ISSUE THREAD

**Issue by yinyiliang** [Blankj/AndroidUtilCode#358]
这几天真是要哭了，折腾好久才最终发现是这个引用里的代码问题......

**Comment by hehui0123** [comment]
深圳南山科技园招聘android开发，有需求的可以联系我。






------------------




best regards!

贺辉


北京康力优蓝机器人科技有限公司
深圳市杰思谷科技有限公司
手机：18664330912

QQ： 81553652  

网址：http://www.uurobot.com/


地址：深圳市南山区科技园北区同方信息港A5



 

 
 
 
------------------ Original ------------------

**Comment by Blankj** [comment]
🤣  这你把防混淆去掉试试

**Comment by jp1017** [comment]
:cry:
