### ISSUE TITLE
SpanUtil设置字体空一行

### ISSUE THREAD

**Issue by AlexZwh1995** [Blankj/AndroidUtilCode#363]
public SpanUtils() {
        mBuilder = new SpannableStringBuilder();
        mText = "";
        setDefault();
        **appendLine().setFontSize(0);// it's important for span start with icon**
    }
这一行去不掉吗，这样的话单行的TextView不是没办法适用了

**Comment by Blankj** [comment]
好吧，我下版本放 icon 里

**Comment by AlexZwh1995** [comment]
thx

**Comment by Blankj** [comment]
你设置 lines = 2 就行了

**Comment by AlexZwh1995** [comment]
不行啊  顶上还是空了一行，先不用这个了，等更新✧(≖ ◡ ≖✿)

**Comment by Blankj** [comment]
我的没问题啊 设置为 android:lines="2"

**Comment by Blankj** [comment]
我测了，不同版本出现的效果不一样，4.几的就会有空行 6.0 7.0 没问题 我修复下吧

**Comment by AlexZwh1995** [comment]
哦哦，我测试机5.0的；另外
`public SpanUtils setForegroundColor(@ColorInt final int color) {
        this.foregroundColor = color;
        return this;
    }`
这里是不是没法传入自定义的color资源值

**Comment by Blankj** [comment]
已更新 1.11.0
