### ISSUE TITLE
没有获取activity的icon的吗？

### ISSUE THREAD

**Issue by zhuzhushang** [Blankj/AndroidUtilCode#365]
如题，没有获取activity的icon的吗？

**Comment by Blankj** [comment]
activity 还有 icon？ AppUtils 中有 getAppIcon

**Comment by WanghongLin** [comment]
manifest可以可以指定activity的icon或者logo属性，这种icon一般用于处理explicit intent的场合，有intent filter的时候，比如接受图片分享。

**Comment by GWYloved** [comment]
用packagemanager获取activityinfo可以拿到
http://www.cnblogs.com/lee0oo0/archive/2012/08/08/2628458.html

**Comment by Blankj** [comment]
已更新 1.11.0
