### ISSUE TITLE
CrashUtils能不能添加动态申请文件操权限

### ISSUE THREAD

**Issue by xubo5200** [Blankj/AndroidUtilCode#366]
由于项目还没有执行到动态申请文件操作权限那一步，就crash了，然后应用直接卡死，检查原因是crashutils写入错误日志时，没有权限

`01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err: java.io.IOException: Permission denied
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at java.io.File.createNewFile(File.java:948)
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at com.blankj.utilcode.util.CrashUtils.createOrExistsFile(CrashUtils.java:160)
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at com.blankj.utilcode.util.CrashUtils.access$300(CrashUtils.java:29)
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at com.blankj.utilcode.util.CrashUtils$1.uncaughtException(CrashUtils.java:79)
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
01-02 11:44:53.455 10179-10179/com.tjx.tingdao W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)`

**Comment by Blankj** [comment]
类功能要单一 申请权限你自己外部申请一下 不然我其他涉及到权限的都要加上？ 这不合理

**Comment by xubo5200** [comment]
好吧，那只能自己处理了
