### ISSUE TITLE
1.10.0 中BarUtils替换原来hideNavBar的新方法在语义上是不是有歧义

### ISSUE THREAD

**Issue by ChiLogNNS** [Blankj/AndroidUtilCode#372]
新的方法是        
BarUtils.setNavBarVisibility(this, 
BarUtils.setNavBarImmersive(this);

我觉得在一般情况下会认为是用setNavBarVisibility代替原来的hideNavBar
实际上只是把布局延伸到NavBar的位置

而setNavBarImmersive(注释是:隐藏导航栏) 却才是把NavBar隐藏收起来的实现

不知道是不是我个人理解错了

**Comment by Blankj** [comment]
setNavBarImmersive 是设置导航栏沉浸式

**Comment by ChiLogNNS** [comment]
明白了  BarUtils.setNavBarVisibility 只把NavBar设为可见或不可见, 但实际上点击对应按钮的位置还是会有效果; BarUtils.setNavBarImmersive 是把NavBar收缩起来.
我误解了, 功能没问题的, 十分感谢
