### ISSUE TITLE
CrashUtils有些机型不打印e.printStackTrace(pw);

### ISSUE THREAD

**Issue by binbin594738977** [Blankj/AndroidUtilCode#374]
CrashUtils有些机型不打印e.printStackTrace(pw);
是否可以直接加成Log.e("xxx", "xxx", e);

**Comment by Blankj** [comment]
`Log.e("xxx", "xxx", e);` 中也是调用 `e.printStackTrace();` 的哦

**Comment by Blankj** [comment]
最新版初始化的时候有个 OnCrashListener 回调供你使用
