### ISSUE TITLE
 RegexUtils 的规则有问题

### ISSUE THREAD

**Issue by jingzz1** [Blankj/AndroidUtilCode#377]
判断url的，只要是“字母”+"://"+"任意字符"就能通过,比如 acbd://a 会判断为true
建议把url的规则改成：“^((http|https)://)?([\w-]+\.)+[\w-]+(/[\w-./?%&=]*)?$ ”;
把邮箱规则改成"^[a-zA-Z_]{1,}[0-9]{0,}@(([a-zA-z0-9]-*){1,}\.){1,3}[a-zA-z\-]{1,}$"

还有，简单的手机号码判断也建议去掉，他的规则是 判断开头为1，后面10位是否数字，这种判断其实没什么意义。

**Comment by Blankj** [comment]
url 只有 http 和 https ? 你想的也太少了吧，你要判断 http 类型那你自己传入正则调用 isMatch 判断即可
邮箱正则是写得不对还是怎么？
手机号码粗略判断对你没什么意义不代表对别人需要简单校验的没什么意义，话干嘛说那么决绝？
你要是觉得不妥可以调用 RegexUtils#isMatch 即可
