### ISSUE TITLE
1.11.0版本没有EmptyUtils这个类

### ISSUE THREAD

**Issue by xubo5200** [Blankj/AndroidUtilCode#379]
今天更新了1.11.0，EmptyUtils这个类不见了
![image](https://user-images.githubusercontent.com/13805827/34759182-443aeea2-f615-11e7-83bd-3db07b48469b.png)

**Comment by Blankj** [comment]
全局替换成 ObjectUtils 即可

**Comment by xubo5200** [comment]
OK

**Comment by Blankj** [comment]
我之前 1.10.0 有加 @deprecated
![image](https://user-images.githubusercontent.com/17978187/34759271-9bdbc2ee-f615-11e7-96bc-1e6ca8eedb0d.png)

**Comment by xubo5200** [comment]
好吧，我直接从1.9直接升级1.11的
