### ISSUE TITLE
android:windowSoftInputMode="stateVisible|adjustResize" is not useful

### ISSUE THREAD

**Issue by BigSea001** [Blankj/AndroidUtilCode#38]
# android:windowSoftInputMode="stateVisible|adjustResize" is not uesful.
楼主，android:fitsSystemWindows="true"，在EditText的上一层布局中加入这个属性就可以了，但是有点问题，就是我用透明状态栏的时候，上一层的布局中会有一个和状态栏一样的高度的白色的条子，那是因为透明状态栏引起的，希望你能把这个加在这里，谢谢，如果可以的话帮我解决一下那个透明状态栏的问题吧。

**Comment by Blankj** [comment]
android:clipToPadding="true"
android:fitsSystemWindows="true"
把这两个属性都加在最外层，如果不能解决，你的布局文件让我看下
