### ISSUE TITLE
反馈AndroidUtilCode问题

### ISSUE THREAD

**Issue by tcqq** [Blankj/AndroidUtilCode#384]
希望可以添加一个基于LruCache实现的内存缓存的功能，这个功能很常用，谢谢

**Comment by Blankj** [comment]
LruCache 本身就很简单了，还封装个啥子，不过现在一点都不常用了哦，图片加载不都用第三方的了么，还用那干啥。

**Comment by TCQQ** [comment]
“LruCache本身就很简单了，还封装个啥子”
-LruCache现在只支持传入对象，但是不支持像pref那样可以传入指定类型，例如：getString、getInt...等，所以现在使用的时候如果想单独获取指定类型的数据需要二次转换。

“不过现在一点都不常用了哦，图片加载不都用第三方的了么，还用那干啥。”
-不，LruCache很常用，加载图片我们可以用Glide等框架，但是如果我们要进行三级缓存从服务器Api获取到的数据，或者缓存应用本地设置的数据，就需要用到LruCache，因为内存缓存速度最快，磁盘缓存第二快，数据库缓存最慢，所以LruCache很有用。

**Comment by Blankj** [comment]
基础数据有什么好缓存的，本来就有那个变量指着它的，你还存内存里干嘛，再说基础数据想做缓存直接存文件读取不就好了么，小数据文件读取本来就很快，LruCache 最常用的不就是在图片上么，因为图片内存开销大，用内存缓存起来加载更快，存文件的话次之，而我们平时用的图片加载框架里都是有缓存配置，还需要所谓的 LruCache？你可以去看一波源码解析，看是否是我说的这样的。

**Comment by TCQQ** [comment]
“基础数据有什么好缓存的，本来就有那个变量指着它的，你还存内存里干嘛，再说基础数据想做缓存直接存文件读取不就好了么，小数据文件读取本来就很快”
-基础数据可能有多个变量，例如多个设置选项，所以当读取数据时，使用LruCache进行读取的速度一定比磁盘读取的速度更快，并且文件越大，差异越大。

“LruCache 最常用的不就是在图片上么”
不，LruCache不止在图片上被应用，我在进行一次解释，支持三级缓存的应用几乎所有的缓存都使用了LruCache，因为内存缓存的速度比磁盘快很多，并且随着文件越大，内存缓存的速度和磁盘缓存的速度差异就越大，所以优先级最高的一定是LruCache。

“因为图片内存开销大，用内存缓存起来加载更快，存文件的话次之”
-但是当一组数据越来越多的时候，它的开销不次于图片的开销，例如聊天记录。

“而我们平时用的图片加载框架里都是有缓存配置，还需要所谓的 LruCache？”
-上面已经解释过了，LruCache的使用场景不限于图片。

**Comment by Blankj** [comment]
我是觉得没必要，需求量暂时也就你一个这么认为的，况且我见到的应用我也没见过 LruCache 随处用的，可是是我我看的应用不够高端把。

**Comment by TCQQ** [comment]
“我是觉得没必要，需求量暂时也就你一个这么认为的”
-不，你可以google搜索一下“android三级缓存”，里面的第一级的内存缓存就是LruCache，所以LruCache很有用。看看这个链接：https://www.jianshu.com/p/b49a111147ee

**Comment by carozhu** [comment]
LruCacheUtils 要写的话其实可以直接借鉴 Glide。
该文中（http://blog.csdn.net/qq_39238370/article/details/78067023）作者也分享了Glide的缓存策略。
