### ISSUE TITLE
trouble via NetworkUtils

### ISSUE THREAD

**Issue by amirjun32** [Blankj/AndroidUtilCode#389]
hello.
i used this code in my project.but has an error.why?tanx
code:

 if (NetworkUtils.isConnected()){
                    Toast.makeText(MainActivity.this,"connected",Toast.LENGTH_SHORT).show();

                }else{
                    Toast.makeText(MainActivity.this,"not connected",Toast.LENGTH_SHORT).show();
                }

error:

                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

**Comment by Blankj** [comment]
Do u init util in ur project?

**Comment by amirjun32** [comment]
i used this code for init util.
`   Application    application=new Application();
     Utils.init(application);`


wrong?

**Comment by Blankj** [comment]
u can see [UtilsApp.java](https://github.com/Blankj/AndroidUtilCode/blob/6f864ec8fee627b0959918ee94793d27875c6590/app/src/main/java/com/blankj/androidutilcode/UtilsApp.java)

**Comment by amirjun32** [comment]
i see this.but i didn't understand,because i begginer.please give code.tanx

**Comment by Blankj** [comment]
Step by step. Don't worry.

**Comment by amirjun32** [comment]
u say true.but i import this to my project,and used from other methodes in this library.but i just trouble via this section.please help

**Comment by Blankj** [comment]
If u don't know Application, u can init it in ur MainActivity
```java
Utils.init(getApplication());
```
