### ISSUE TITLE
  SpanUtils   Drawable d = getCachedDrawable();报空

### ISSUE THREAD

**Issue by i2863CookieZJ** [Blankj/AndroidUtilCode#393]

**Comment by Blankj** [comment]
用法和异常栈都发上来哈

**Comment by yuger** [comment]
我插播一条消息，不再另开issue了。
获取型号 Build.Model https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/src/main/java/com/blankj/utilcode/util/DeviceUtils.java#L180 在三星手机出现一个奇怪的现象：
返回的是SM-<一个字母><3-4位数字> 这个格式（有的在数字后还有字母），比如 Galaxy s8是返回SM-G9500， 而我需要的是Galaxy s8，毕竟三星型号太多，谁也不认识这些代号，而像Galaxy s8是认识的。我查了很多资料都没有找到该怎么返回类似Galaxy s8而不是SM-G9500，所以来此求助。

**Comment by Blankj** [comment]
@yuger 这种特殊机型不适配的那你就只能自己建个 hashmap 来映射了，或者你能找个字段能替代它

**Comment by yuger** [comment]
@Blankj 这个问题已经有人实现了 https://github.com/jaredrummler/AndroidDeviceNames

**Comment by Blankj** [comment]
那你拷贝那个类过来用就好了
