### ISSUE TITLE
获取设备系统版本号，不太符合要求

### ISSUE THREAD

**Issue by baiyulinlin** [Blankj/AndroidUtilCode#394]
DeviceUtils.getSDKVersion    : 获取设备系统版本号，这个显示的是24，不太符合需求，应该再添加一个显示具体android版本号，比如：7.0，
    /** 
     * 获取当前手机系统版本号 
     * 
     * @return  系统版本号 
     */  
    public static String getSystemVersion() {  
        return android.os.Build.VERSION.RELEASE;  
    }

**Comment by Blankj** [comment]
DeviceUtils. getSDKVersionName 已加入最新版本 1.12.3，之前的 getSDKVersion 替换为 getSDKVersionCode
