### ISSUE TITLE
想要在AndroidTest中使用工具类？

### ISSUE THREAD

**Issue by kigkrazy** [Blankj/AndroidUtilCode#395]
想要在AndroidTest中使用工具类？怎么初始化？
![image](https://user-images.githubusercontent.com/11622206/35263933-b90b379c-0055-11e8-9896-ca3c5f410a21.png)
上面的代码都不能很好的初始化。
能不能将
```
public static void init(@NonNull final Application app) 
```
的参数改成Context？

还有谈下个人看法：感觉`Utils.init`这个初始化是个很累赘的东西，为什么不在工具类接口使用的时候多传入一个`Context`？这样感觉可以减少整个库中类与类的耦合程度！
上面只是个人看法。

**Comment by Blankj** [comment]
用 Robolectric，具体可以看 [TestUtils.java](https://github.com/Blankj/AndroidUtilCode/blob/e485ef9d01026873de3aa51193a6ed4721f77052/utilcode/src/test/java/com/blankj/utilcode/util/TestUtils.java)

**Comment by kigkrazy** [comment]
我这边有特殊需求需要跑在AndroidTest框架下。这样有没有办法初始化库

**Comment by Blankj** [comment]
你 mock 下工具类的结果就好了，其实你写测试根本不需要用到我工具类返回的结果。

**Comment by Blankj** [comment]
实在想获取的话那就Start一个Activity 或者 @Rule 获取 mActivityRule..getActivity() 来获取 Activity，然后 Activity.getApplication() 即可
