### ISSUE TITLE
Toastutil为什么要改样式？

### ISSUE THREAD

**Issue by yuzhiqiang1993** [Blankj/AndroidUtilCode#397]
建议不要修改ToastUtils默认样式。看着很别扭。

**Comment by Blankj** [comment]
我哪里改样式了？改不改不都是你们自己设置么

**Comment by yuzhiqiang1993** [comment]
`    private static void show(final CharSequence text, final int duration) {
        HANDLER.post(new Runnable() {
            @Override
            public void run() {
                cancel();
                sToast = Toast.makeText(Utils.getApp(), text, duration);
                // solve the font of toast
//                TextView tvMessage = sToast.getView().findViewById(android.R.id.message);
//                TextViewCompat.setTextAppearance(tvMessage, android.R.style.TextAppearance);
//                tvMessage.setTextColor(msgColor);
                sToast.setGravity(gravity, xOffset, yOffset);
                // setBg(tvMessage);
                sToast.show();
            }
        });
    }`

show方法注释的这个地方好像是改了

**Comment by Blankj** [comment]
```java
if (msgColor != COLOR_DEFAULT) {
    tvMessage.setTextColor(msgColor);
}
```
不知道啥时候去除了这个判断 加上了已经 下版本会更新

**Comment by yuzhiqiang1993** [comment]
好的  麻烦了

**Comment by Blankj** [comment]
默认是颜色是 fffffff，我的默认是feffffff，差了一个透明度，你的机器是自己修改过的 rom? 把默认颜色改了吗？上传个图让我看看默认的和 ToastUtils 的区别，代码我已经修改了，我只是想确认下。

**Comment by yuzhiqiang1993** [comment]
[](url)
![qq 20180129105823](https://user-images.githubusercontent.com/18605757/35491750-6d077c74-04e3-11e8-99fa-b2dd549aef32.jpg)
![qq 20180129105817](https://user-images.githubusercontent.com/18605757/35491751-718bbfe4-04e3-11e8-908b-ec05f05b6c74.jpg)

**Comment by yuzhiqiang1993** [comment]
应该不是rom的问题，两个机器都是这样，把那几句代码注释掉就好了

**Comment by Blankj** [comment]
你可以试试 1.12.2 版本，已经有了

**Comment by yuzhiqiang1993** [comment]
好的

**Comment by yuzhiqiang1993** [comment]
刚试了下好像还是不行， 我是直接运行你的demo也是这样，我自己的主题是 Theme.AppCompat.Light.NoActionBar

**Comment by Blankj** [comment]
你 rom 肯定是定制过的，把原生 toast 的 textview 的 TextAppearance 修改过

**Comment by yuzhiqiang1993** [comment]
但是我直接用原生的Toast.makeText(activity,"sadsad",Toast.LENGTH_LONG).show();  是正常的，而且我把下面这几句代码注释掉也是正常的
![qq 20180129111324](https://user-images.githubusercontent.com/18605757/35492060-7460f688-04e5-11e8-8866-7e4a595c9cee.png)

**Comment by Blankj** [comment]
我知道问题是出在 `TextViewCompat.setTextAppearance(tvMessage, android.R.style.TextAppearance);` 这个上，就是因为我设置了这个的原因，你 rom 改了 toast 样式

**Comment by yuzhiqiang1993** [comment]
好吧  那就先这样吧 问题不大

**Comment by yuzhiqiang1993** [comment]
不知道别人有没有这个情况  我是在华为和努比亚的手机上遇见的

**Comment by Blankj** [comment]
你把我那句换成这个 `tvMessage.setTypeface(null);` 试试

**Comment by yuzhiqiang1993** [comment]
还是不行

**Comment by yuzhiqiang1993** [comment]
反正是只要把这句注释掉就没问题  `TextViewCompat.setTextAppearance(tvMessage, android.R.style.TextAppearance);`

**Comment by Blankj** [comment]
你 ui 不给你统一 toast 的吗，你自己设置背景和字体颜色去适配，干嘛一定要用系统的呢。

**Comment by Blankj** [comment]
尽管你手上的机器是黑色字体，但在其他很多机器就是白色的了，这就会造成不统一吧，所以还是自己设置下统一不就好了么

**Comment by yuzhiqiang1993** [comment]
没  toast直接就是原生的  先这样吧  问题不大

**Comment by Blankj** [comment]
你用的手机 rom 都是定制过的，不是谷歌原生的，所以厂家可能会修改样式，明白了吗

**Comment by Blankj** [comment]
你试试这段代码
```
int msgColor = tvMessage.getCurrentTextColor();
TextViewCompat.setTextAppearance(tvMessage, android.R.style.TextAppearance);
if (sMsgColor != COLOR_DEFAULT) {
    tvMessage.setTextColor(sMsgColor);
} else {
    tvMessage.setTextColor(msgColor);
}
```

**Comment by yuzhiqiang1993** [comment]
可以了

**Comment by Blankj** [comment]
还是 1.12.2 版本，你更新下。

**Comment by yuzhiqiang1993** [comment]
代码好像没有覆盖掉

**Comment by Blankj** [comment]
那用 1.12.3把

**Comment by yuzhiqiang1993** [comment]
1.12.3版本可以了
