### ISSUE TITLE
LogUtils.getConfig().setStackDeep(3)还是设置1，控制台都没有可以点击直接跳到代码里面的功能

### ISSUE THREAD

**Issue by kamike** [Blankj/AndroidUtilCode#399]
这个要怎么设置才出现呢

**Comment by Blankj** [comment]
你确定你在 Logcat 窗口下？

**Comment by kamike** [comment]
对呀，我是Android studio3.0
![qq 20180129135037](https://user-images.githubusercontent.com/3920019/35495366-87367812-04fb-11e8-8ef3-b83c662bfca1.jpg)

**Comment by Blankj** [comment]
你是把 head 去掉了吧，打开就行了 `.setLogHeadSwitch(true)`

**Comment by kamike** [comment]
原来如此，我还以为隐藏head是隐藏左边的呢，谢谢了，已捐款表达支持

**Comment by Blankj** [comment]
感谢大佬

**Comment by kamike** [comment]
我们的log一般都是封装了好几层，我在想，能不能做到比如设置了StackDeep为3就自动高亮的那第三层调用的地方，如果没有三层就高亮一层。没研究过log里面的源码，只是猜测下

**Comment by Blankj** [comment]
基于源码自己修改 stackDeep

**Comment by kamike** [comment]
好吧
