### ISSUE TITLE
Is error？

### ISSUE THREAD

**Issue by ZaoliangZheng** [Blankj/AndroidUtilCode#40]
Hello!
In AppUtils.java,
"boolean isSD = (ApplicationInfo.FLAG_SYSTEM & ai.flags) != ApplicationInfo.FLAG_SYSTEM;
 boolean isUser = (ApplicationInfo.FLAG_SYSTEM & ai.flags) != ApplicationInfo.FLAG_SYSTEM;"
is error?
May be I wrong?
Thanks!

**Comment by Blankj** [comment]
It‘s simple expression. It works.
