### ISSUE TITLE
ImageUtils里的getRotateDegree方法有误

### ISSUE THREAD

**Issue by zhousongchao** [Blankj/AndroidUtilCode#400]
调试了半天才发现、哎：
ExifInterface exifInterface = new ExifInterface(filePath);
            int orientation = exifInterface.getAttributeInt(
                    ExifInterface.TAG_ORIENTATION,
                    ExifInterface.ORIENTATION_NORMAL);
            switch (orientation) {
                default:
                case ExifInterface.ORIENTATION_ROTATE_90:
                    degree = 90;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_180:
                    degree = 180;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_270:
                    degree = 270;
                    break;
            }
。。。。。。。。。default位置。。。

**Comment by Blankj** [comment]
default 怎么了？有啥问题？

**Comment by zhousongchao** [comment]
1、按规范应该放在最后（这不是重点）
2、没有break呀！！！这样如果是正常未旋转的照片也会返回90！！！！！！！！！！！！！
。。。所以我把这代码拷出去了、调自己的方法。
开始太相信你了，一直搞不懂正常照片为啥会返回90把照片旋转了
