### ISSUE TITLE
发现一个图片压缩的代码

### ISSUE THREAD

**Issue by kamike** [Blankj/AndroidUtilCode#401]
![image](https://user-images.githubusercontent.com/3920019/35722407-26b7401e-0831-11e8-99f8-7c68921241f4.png)

在Imageutils的compressByQuality方法里面，按质量压缩，这样算下来第一次压缩质量就设置的就是50，bitmap.compress这里面的压缩质量，我印象中这里是和ps压缩质量一样的，范围一般60~95吧，如果低于60图片会模糊的，不能设置小于50吧，这样图片出来问题大了。我觉得还是从90开始每次减少10，最低60比较好，虽然我没试

**Comment by Blankj** [comment]
这是搜寻出最接近于 maxByteSize，和你说的没关系，你一点点减是线性时间复杂度，二分是 log(n) 时间复杂度。
