### ISSUE TITLE
spanutils添加图片不显示

### ISSUE THREAD

**Issue by i2863CookieZJ** [Blankj/AndroidUtilCode#402]
utils.appendImage(R.drawable.circle_praise_on, SpanUtils.ALIGN_CENTER);

**Comment by Blankj** [comment]
查看 demo 的用法。你这样哪里会有图片

**Comment by i2863CookieZJ** [comment]
我的意思是添加图片的方法是否这样,这不是完整的，我看了demo依然不能显示

**Comment by Blankj** [comment]
那我 demo 能显示吗？

**Comment by Blankj** [comment]
先确定是否用的最新版本，我这边测试了如下代码
```
tvAboutSpan.setText(new SpanUtils()
.appendImage(R.drawable.shape_spannable_block_low, SpanUtils.ALIGN_TOP)
.create());
```
![image](https://user-images.githubusercontent.com/17978187/35793163-768d03d8-0a8b-11e8-990a-708696795471.png)
显示无误 希望能帮到你

**Comment by i2863CookieZJ** [comment]
ok，demo是可以的 我看看是不是版本问题。

**Comment by i2863CookieZJ** [comment]
我知道原因了 是spanutils中  Rect rect = d.getBounds();空指针 我处理一下就不显示了 这个报空是我缺了什么东西么  我是直接把class文件copy到我项目中的

**Comment by Blankj** [comment]
这种问题你就自己解决吧
