### ISSUE TITLE
请问AS2.3导入完整项目,为了学习代码和Demo,导入出现问题.

### ISSUE THREAD

**Issue by zsyzsy1818** [Blankj/AndroidUtilCode#405]
有大佬试过吗,改3.3  和2.3.3  还是有很多问题,请问必须把AS升级到3.0吗?

**Comment by Blankj** [comment]
这是 gradle 问题 你 gradle 版本太低了，或者把我写的改成低版本的就行，作为开发者时刻要用最新版稳定的工具哦
