### ISSUE TITLE
关于AndroidUtilCode的PermissonUtil

### ISSUE THREAD

**Issue by BeJack** [Blankj/AndroidUtilCode#409]
你好，你的权限控制，当BuildVersion>23,但是targetversion<23时候,即便运行在android6及以上设备,但ContextWrapper.checkSelfPermission和Context.checkSelfPermission均会失效，返回值始终为，PERMISSION_GRANTED，此时应使用PermissionChecker.checkSelfPermission

**Comment by Blankj** [comment]
https://www.jianshu.com/p/65e23b618f76 你可以看这篇文章查看下 23 以下就自己处理吧
