### ISSUE TITLE
加个DialogUtils?

### ISSUE THREAD

**Issue by anpoz** [Blankj/AndroidUtilCode#41]
类似于这种 http://www.jianshu.com/p/8cb2e709891c

**Comment by jp1017** [comment]
可以使用这个：
https://github.com/orhanobut/dialogplus/
或者这个：
https://github.com/afollestad/material-dialogs/

**Comment by Blankj** [comment]
good

**Comment by hss01248** [comment]
用我这个
https://github.com/hss01248/DialogUtil
