### ISSUE TITLE
CacheUtils第二天会自动清空缓存

### ISSUE THREAD

**Issue by Chenayi** [Blankj/AndroidUtilCode#411]
CacheUtils第2天会自动清空缓存，怎么解决？

**Comment by Blankj** [comment]
那是你设置了缓存时常了吧。

**Comment by Chenayi** [comment]
没有设置

**Comment by Blankj** [comment]
那我就不知道了，你自己清理应用缓存了？年后回来再说吧 这两天不带电脑

**Comment by Chenayi** [comment]
嗯好的，没有设置，没有清理，每次第2天回来缓存就没了。我也不知道为啥，就正常使用

**Comment by Blankj** [comment]
你自定义缓存路径呢？

**Comment by KnifeStone** [comment]
我也遇到这个问题了 1.9.6 和 1.12.0 都会被清掉
1.9.1不会，这是三个不同的APP就是了，也可能其它问题，供大神参考一下。 
这个问题困扰很久了，一直在找问题，也找不出会是什么问题，调用的是CacheUtils.getInstance()

**Comment by KnifeStone** [comment]
应该和版本没有关系，比对了CacheUtils的代码都是一样的
