### ISSUE TITLE
报错，

### ISSUE THREAD

**Issue by ruanbaojun1105** [Blankj/AndroidUtilCode#414]
![29bqm6sp873q7czed8o 1 6](https://user-images.githubusercontent.com/7459297/36772542-afb406e0-1c90-11e8-8e02-5092b08fa477.png)
文件读写权限已经有了的，为啥还报错
...
![chlcso0vo j wt u sz2](https://user-images.githubusercontent.com/7459297/36772636-fe723a9a-1c90-11e8-92fc-d06195b29ad8.png)

**Comment by Blankj** [comment]
什么版本手机 6.0以上的吗？

**Comment by ruanbaojun1105** [comment]
@Blankj 都是6.0以上的

**Comment by Blankj** [comment]
6.0 动态权限听说过吗  可以看看这个 (终于等到你--权限工具类)[https://blankj.com/2018/01/10/finally-get-permissionutils/]

**Comment by ruanbaojun1105** [comment]
别逗可以吗？有申请权限，且动态判断了

**Comment by Blankj** [comment]
你有报 bug 的机器吗，有的话自己进去看看文件夹权限

**Comment by Blankj** [comment]
初始化可以传递其他地址，你换其他地方试试吧如果解决不了
