### ISSUE TITLE
验证手机号不对啊~

### ISSUE THREAD

**Issue by qzqs** [Blankj/AndroidUtilCode#424]
用到作者验证手机号是否正确方法 RegexUtils.isMobileExact();
无论输入什么数字都是返回ture...

**Comment by qzqs** [comment]
作者你好，我已经看了，意思就是对每一个数进行限制，但是我这边输入00000000000也是返回ture,所以不是很明白。

**Comment by qzqs** [comment]
作者你好，我已经看了你验证手机的源码，意思就是对每一个数进行限制，但是我这边输入00000000000也是返回ture,所以不是很明白。

**Comment by qzqs** [comment]
我傻了....

**Comment by Blankj** [comment]
不是返回 true 哈
