### ISSUE TITLE
isServiceRunning无效

### ISSUE THREAD

**Issue by 617450941** [Blankj/AndroidUtilCode#426]
isServiceRunning无效

**Comment by Blankj** [comment]
是某些设备不行还是怎么，设备版本是多少？判断的是内部应用的服务还是外部应用？

**Comment by youzhiran** [comment]
https://developer.android.google.cn/reference/android/app/ActivityManager.html#getRunningServices(int)
getRunningServices在API级别26中已弃用，现在有更好的解决办法吗。

**Comment by Blankj** [comment]
同应用的服务还是能判断的，判断其他应用是不可以了，这方面谷歌是在考虑安全问题。
