### ISSUE TITLE
请问是否能对SpanUtils进行扩展

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#428]
SpanUtils 很好用,不知道是否能提供一个反向解析的功能,就是如果我用SpanUtils 工具类生成个SpannableStringBuilder,放入TextView后,是否也能把TextView中的文本反向解析成一个类似SpanUtils的结构

**Comment by Blankj** [comment]
这个不是可逆的哦，因为同一种效果可能有多种实现，而且还有各种参数，而且如果要可逆，那就要定个标准，而且只适合我这个标准，如果别人写的，那就解析不出来。
你跟我说说你的具体需求

**Comment by sweet2o09** [comment]
![image](https://user-images.githubusercontent.com/8555893/37263464-49dc0604-25e3-11e8-9e16-afac437ab504.png)
比方说我想知道这个TextView中的文字,用的是什么字号,是否加粗,颜色多少,是否有下划线或者删除线之类的

**Comment by Blankj** [comment]
逆向那不支持哈，你正向怎么知道那就怎么做。或者你用html标签去显示也可以，那样就能顺逆了，不过html支持有限。

**Comment by sweet2o09** [comment]
了解了...那是否可以对SpanUtils扩展个输出html类型?不知道这个需求合不合理

**Comment by Blankj** [comment]
android 自身就支持 html 类型输入和输出，自己查找下相关资料吧。
