### ISSUE TITLE
进入NetWorkUtilDemo报以下错误!

### ISSUE THREAD

**Issue by android-shiyan** [Blankj/AndroidUtilCode#429]
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err: java.lang.NoSuchMethodException: getDataEnabled []
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at java.lang.Class.getConstructorOrMethod(Class.java:472)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:640)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at com.blankj.utilcode.util.NetworkUtils.getMobileDataEnabled(NetworkUtils.java:119)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at com.blankj.androidutilcode.feature.core.network.NetworkActivity.updateAboutNetwork(NetworkActivity.java:121)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at com.blankj.androidutilcode.feature.core.network.NetworkActivity.onWidgetClick(NetworkActivity.java:115)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at com.blankj.androidutilcode.base.BaseActivity.onClick(BaseActivity.java:62)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at android.view.View.performClick(View.java:4438)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at android.view.View$PerformClick.run(View.java:18422)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at android.os.Looper.loop(Looper.java:136)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5001)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
03-13 13:57:24.579 2426-2426/com.blankj.androidutilcode W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by Blankj** [comment]
设备版本信息说下

**Comment by android-shiyan** [comment]
逍遥手机模拟器  
![image](http://ok2fb2she.bkt.clouddn.com/%E9%80%8D%E9%81%A5%E6%A8%A1%E6%8B%9F%E5%99%A8.png)

**Comment by android-shiyan** [comment]
设备信息截图 http://ok2fb2she.bkt.clouddn.com/%E9%80%8D%E9%81%A5%E6%A8%A1%E6%8B%9F%E5%99%A8.png

**Comment by Blankj** [comment]
具体真机试试吧，模拟器不健全，底层可能删去了手机数据流量相关的 sdk

**Comment by android-shiyan** [comment]
好的！
