### ISSUE TITLE
registerSoftInputChangedListener回调添加状态

### ISSUE THREAD

**Issue by Chenayi** [Blankj/AndroidUtilCode#430]
您好，请问registerSoftInputChangedListener这里的回调可不可以加多一个显示或者隐藏的状态参数

**Comment by Blankj** [comment]
根据 height 自己判断下哈

**Comment by Chenayi** [comment]
根据height不太好判断吧，不管隐藏还是现实都是返回一个大于0的数，而且不同手机不同键盘返回的height都不一样，或者您能说下大概的判断思路吗？

**Comment by Blankj** [comment]
你运行我 demo 看看值的变化

**Comment by Chenayi** [comment]
我有看过值的变化了，都是返回一个大于0的值

**Comment by Blankj** [comment]
之前有人给我提了个pr，我没注意看，现在我恢复回去了，你试试1.13.4
