### ISSUE TITLE
CacheUtils缓存会没掉的问题？

### ISSUE THREAD

**Issue by KnifeStone** [Blankj/AndroidUtilCode#431]
CacheUtils.getInstance().put();
用的是这样的默认保存缓存的方法，有时候几个小时，有时候十几个小时，总之就会没掉 = =
已经困扰一两个月了，之前还以为是别的地方的问题，苦苦不得解。
不知道是哪里没有设置好

**Comment by Blankj** [comment]
CacheUtils.getInstance(urFile); 
自己设置路径试试，不要放默认 cache 路径，放默认的可能其他软件清理的时候会删掉。

**Comment by KnifeStone** [comment]
好，我先试一下

**Comment by Blankj** [comment]
@KnifeStone 现在还有问题吗

**Comment by KnifeStone** [comment]
@Blankj 目前发现放在默认的cache目录下面，全部文件都会定时的被清空，Glide的缓存图片也被清了。
昨天把CacheUtils的默认路径设在files目录下，观察几天给你回复

**Comment by Blankj** [comment]
那就是你设备上有清理软件在清理吧，glide 不也被清了吗，难道你要怀疑 glide 也有问题吗，哈哈

**Comment by KnifeStone** [comment]
@Blankj 可能是系统有在做这件事情，我的是华为系统，供大家参考一下，哈哈。
