### ISSUE TITLE
有关手机号码精确验证的

### ISSUE THREAD

**Issue by Troll4it** [Blankj/AndroidUtilCode#433]
/**
     * 正则：手机号（精确）
     * <p>移动：134(0-8)、135、136、137、138、139、147、150、151、152、157、158、159、178、182、183、184、187、188</p>
     * <p>联通：130、131、132、145、155、156、175、176、185、186</p>
     * <p>电信：133、153、173、177、180、181、189</p>
     * <p>全球星：1349</p>
     * <p>虚拟运营商：170</p>
     */
最近出了166的手机号码段，希望加上，谢谢

**Comment by Blankj** [comment]
用最新版本的是有的，很久之前就加进去了
