### ISSUE TITLE
PermissionUtils.request() 方法跨进程调用问题

### ISSUE THREAD

**Issue by JasonPiao** [Blankj/AndroidUtilCode#435]
在子进程中使用 PermissionUtils.request() 不生效；
从代码判断，PermissionActivity 是默认在主进程运行；
PermissionUtils.sInstance 每个进程中都有一个，因此跨进程调用时无法获取到；
建议把权限参数通过 Intent 来传递；
        @Override
        protected void onCreate(@Nullable Bundle savedInstanceState) {
            if (sInstance.mThemeCallback != null) {
                sInstance.mThemeCallback.onActivityCreate(this);
            }
            super.onCreate(savedInstanceState);

            if (sInstance.rationale(this)) {
                finish();
                return;
            }
            if (sInstance.mPermissionsRequest != null) {
                int size = sInstance.mPermissionsRequest.size();
                if (size <= 0) return;
                requestPermissions(sInstance.mPermissionsRequest.toArray(new String[size]), 1);
            }
        }

**Comment by Blankj** [comment]
那你在子进程初始化工具类了吗？

**Comment by JasonPiao** [comment]
两个进程都初始化过工具类，在主进程调用 request() 成功，在子进程调用 request() 失败；
问题所在已经贴出来了；
在子进程调用 request() 时，由于 PermissionActivity 运行在主进程，因此 onCreate 方法里获取到的 PermissionUtils.sInstance 是主进程的，mPermissionsRequest 始终为空；
不如你动手试试；

**Comment by JasonPiao** [comment]
<activity
            android:name="com.blankj.utilcode.util.PermissionUtils$PermissionActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:process=":pbx"
            android:theme="@style/ActivityTranslucent"
            android:windowSoftInputMode="stateHidden|stateAlwaysHidden"/>
验证过手动指定 PermissionActivity 所在进程后，在子进程中申请权限是成功的；
相对地，在主进程中申请权限就无效了；
建议把权限参数通过 Intent 来传递；

**Comment by JasonPiao** [comment]
另外 1.13.4 版本测试权限为空时，PermissionActivity 会以透明界面的形式显示；
建议权限为空时把 PermissionActivity finish() 掉；

**Comment by Blankj** [comment]
我说怎么会出现 PermissionActivity 中 mPermissionsRequest 的 size 为 0 的情况。现在解决了已经，
用 1.13.5 版本即可，PermissionActivity 增加 `android:multiprocess="true"` 属性即可，你说的那种方式对于接口是无法序列化的，所以实现不了。

**Comment by JasonPiao** [comment]
ok，thanks；
android:multiprocess="true"
有这个配置，学到了；
