### ISSUE TITLE
关于Utils里面的问题

### ISSUE THREAD

**Issue by zdxiang** [Blankj/AndroidUtilCode#437]
这样写不会导致内存泄漏吗？
    @SuppressLint("StaticFieldLeak") 
    private static Application sApplication;

然后这个activity统一管理，我感觉也用不着啊，除了更好地管理activity，它能有什么特别之处吗

**Comment by Guoooooo** [comment]
从后台回来 需要弹广告页的时候 好像可以用上

**Comment by Blankj** [comment]
不会内存泄漏的
