### ISSUE TITLE
ActivityUtils.startActivity(……) 方法抛出 NoSuchElementException 异常

### ISSUE THREAD

**Issue by JasonPiao** [Blankj/AndroidUtilCode#440]
当 Utils.sActivityList 的 size 为 0 时，ActivityUtils.startActivity(……) 方法将抛出 NoSuchElementException 异常；
    public static void startActivity(@NonNull final Class<?> clz) {
        Context context = getActivityOrApp();
        startActivity(context, null, context.getPackageName(), clz.getName(), null);
    }
    private static Context getActivityOrApp() {
        Activity topActivity = getTopActivity();
        return topActivity == null ? Utils.getApp() : topActivity;
    }
    public static Activity getTopActivity() {
        final Activity topActivity = Utils.getActivityList().getLast();
        ……
    }
    public E getLast() {
        final Node<E> l = last;
        if (l == null)
            throw new NoSuchElementException();
        return l.item;
    }

**Comment by JasonPiao** [comment]
getActivityOrApp() 的逻辑可以改为，当 App 在前台运行时使用 ActivityUtils.getTopActivity()，当 App 在后台运行时使用 Utils.getApp()；
否则若 App 在后台运行，startActivity 会被系统忽略；部分设备固件对此做了兼容，但考虑到兼容性，在代码中处理更好；

**Comment by JasonPiao** [comment]
getActivityOrApp() 的逻辑可以改为，当 AppUtils.isAppForeground() == true 且 Utils.getActivityList() 不为 null、size 大于 0 时，使用 ActivityUtils.getTopActivity()，否则使用 Utils.getApp()；
否则若 App 在后台运行，startActivity 会被系统忽略；部分设备固件对此做了兼容，但考虑到兼容性，在代码中处理更好；

**Comment by Blankj** [comment]
那个异常我现在做了判断
```java
    public static Activity getTopActivity() {
        final LinkedList<Activity> activityList = Utils.getActivityList();
        if (activityList != null && activityList.size() > 0) {
            final Activity topActivity = activityList.getLast();
            if (topActivity != null) {
                return topActivity;
            }
        }
    ...
    }
```
那判断前后台是为什么要加入？

**Comment by JasonPiao** [comment]
若 App 在后台运行，通过 Activity 进行 startActivity 会被系统忽略；
部分设备固件对此做了兼容，但考虑到兼容性，在代码中处理更好；

**Comment by Blankj** [comment]
你试试最新版本 1.13.8

**Comment by hujxhed** [comment]
getActivityList 1.25.9 和最新版本，返回数据的顺序是不是变化了？
