### ISSUE TITLE
华为P9系统无法正确设置或判断导航栏

### ISSUE THREAD

**Issue by XuanJiAndroid** [Blankj/AndroidUtilCode#442]
下面两个API均无效
BarUtils.setNavBarVisibility
BarUtils.isNavBarVisible

**Comment by Blankj** [comment]
用我 demo 测试的吗

**Comment by ainiyiwan** [comment]
华为SLA-AL00 BarUtils.isNavBarVisible，一直返回true

**Comment by loshine** [comment]
三星 S9 一样的问题

无论 Navbar 是否隐藏都返回 true

**Comment by zhxcryptic** [comment]
我的想法是判断realsize和size是否相同 来判断是不是有navbar显示
```
            WindowManager wm = (WindowManager) Utils.getApp().getSystemService(Context.WINDOW_SERVICE);
            Point point = new Point();
            wm.getDefaultDisplay().getRealSize(point);
            int realSize = point.y;
            wm.getDefaultDisplay().getSize(point);
            int size = point.y;
            return realSize != size;
```

**Comment by Blankj** [comment]
用最新版本 1.20.2 试试看

**Comment by loshine** [comment]
> 用最新版本 1.20.2 试试看

三星 S9 plus 依然无效

```java
decorView.getSystemUiVisibility();
```

这个 API 总是返回 0

**Comment by loshine** [comment]
> @loshine 所以你是怎么隐藏 navBar 的？

@Blankj 三星 S9 左下角有一个小按钮，连点两下就可以隐藏 NavBar

![_20180914114709](https://user-images.githubusercontent.com/11252444/45528682-f343db00-b813-11e8-9d64-93b33e28bebd.jpg)

**Comment by Blankj** [comment]
这种三星官方没给相关 api 吗

**Comment by LeslieKoma** [comment]
我也是遇到同样的问题：通过下面的判断成功
public static int getVirtualBarHeight(Context context) {
    DisplayMetrics dm = new DisplayMetrics();
    WindowManager wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
    wm.getDefaultDisplay().getRealMetrics(dm);
    Point point = new Point();
    wm.getDefaultDisplay().getSize(point);
    return dm.heightPixels - point.y;

  }
判断高度是否为0
测试机型:小米mi-4c(无虚拟按键)，荣耀8（有虚拟按键可隐藏），官方模拟器（有虚拟按键无法隐藏）
测试通过 @Blankj

**Comment by LeslieKoma** [comment]
不好意思，上述可能表达不清楚，重新说下我的理解

1. 最开始要做的是判断此款手机有没有下面的导航栏，有的话是处于显示或者是隐藏状态，显示的时候获取高度

2. `val resources = this.resources
    val navresourceId = resources.getIdentifier("navigation_bar_height", "dimen", "android")
    val height = resources.getDimensionPixelSize(navresourceId)`
    在不用反射的情况下，在网上看到这段代码，这样判断导航栏的高度不管你有没有 
    导航栏都是大于0的( 小米)，所以不能通过此方法判断

3. 所以才有上面的代码，如果返回值大于0则说明此款手机肯定有导航栏且处于显示状态，但是等与0的情况下，就可能有但是没显示出来，也可能没有，则显然不是我们想要的结果（说这么多然并卵）


   
4. 判断是否有导航栏，那只能通过反射了(目前我发现哈)

**Comment by Blankj** [comment]
@LeslieKoma 新版本已经有 isSupportNavBar 

```
/**
 * Return whether the navigation bar visible.
 *
 * @return {@code true}: yes<br>{@code false}: no
 */
public static boolean isSupportNavBar() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
        WindowManager wm = (WindowManager) Utils.getApp().getSystemService(Context.WINDOW_SERVICE);
        //noinspection ConstantConditions
        Display display = wm.getDefaultDisplay();
        Point size = new Point();
        Point realSize = new Point();
        display.getSize(size);
        display.getRealSize(realSize);
        return realSize.y != size.y || realSize.x != size.x;
    }
    boolean menu = ViewConfiguration.get(Utils.getApp()).hasPermanentMenuKey();
    boolean back = KeyCharacterMap.deviceHasKey(KeyEvent.KEYCODE_BACK);
    return !menu && !back;
}
```

**Comment by loshine** [comment]
https://stackoverflow.com/questions/46107474/android-detect-samsung-galaxy-s8-navigation-bar-hide-or-show-programmatically

三星有一个办法可以判断是否显示

**Comment by Blankj** [comment]
@loshine 新版本都可以破了
