### ISSUE TITLE
LogUtils 1.13.5 有些可以Log台打印，有些无法打印

### ISSUE THREAD

**Issue by sangsais** [Blankj/AndroidUtilCode#443]
E/MainFragment: │ args[0] = sss
E/MainFragment: │ args[1] = 0<<<
 E/MainFragment: └────────────────────────────────────────────────────────────────
 E/MainFragment: │ args[0] = bannerModel
 E/MainFragment: │ args[1] = >>>>{"data":{"banner":[{"key":"activity","link":"wxtest.ixong.com/#/advent,wxte.ong.com/#/testlearn","url":"https://ng.b0.upyun.com/test/a2c7bd0e916c424098f23c4401b88f5b.jpg"}]},"msg":"获取成功","resultCode":0}
E/MainFragment: └────────────────────────────────────────────────────────────────
 E/InformationFragment: │ main, onSuccess(InformationFragment.java:264)
 E/InformationFragment: │ main, myRequest(InformationFragment.java:240)
 E/LessonAdapter: │ main, convert(LessonAdapter.java:141)
 E/MeFragment: │ main, onSuccess(MeFragment.java:329)
 E/MeFragment: │ main, onSuccess(MeFragment.java:331)
 E/MeFragment: │ main, onSuccess(MeFragment.java:343)

# 264 240 14 329 331 343 这些位置数据就没打印在log台，是正常现象么？

**Comment by Blankj** [comment]
你查看下日志过滤器，你是不过滤了

**Comment by sangsais** [comment]
使用的默认配置，没改动的，多个机型都这样

**Comment by Blankj** [comment]
现在都 1.13.6 版本了哈，你试试最新的

**Comment by sangsais** [comment]
我的log都是以e级别的输出显示的 1.13.5版本上e级别只能打印一部分，1.7.1的e级别是没有问题的，我现在依赖的是1.13.5的版本，把1.7.1的LogUtils工具类放在本地使用，暂时是这样处理

**Comment by Blankj** [comment]
现在的最新版本呢
