### ISSUE TITLE
consider adding NotificationUtil

### ISSUE THREAD

**Issue by Zulqurnain** [Blankj/AndroidUtilCode#445]
There are very few utils available for notifications of android why don't we add it in this library ?

**Comment by Blankj** [comment]
BarUtils has setNotificationBarVisibility

**Comment by actor20170211030627** [comment]
> There are very few utils available for notifications of android why don't we add it in this library ?

NotificationUtils(version 1.26.0)

**Comment by actor20170211030627** [comment]
哥, 要不要考虑增加一个跳转系统界面, 打开通知权限的功能.
