### ISSUE TITLE
图片保存后马上获取bitmap的问题

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#448]
使用ImageUtils.save()把bitmap保存到本地后,马上使用ImageUtils.getBitmap(final String filePath)获取刚保存的bitmap,结果获取不到,通过FileUtils.getFileLength(final File file)获取文件长度发现文件长度为0
不知道有没有什么比较好的办法解决

**Comment by Blankj** [comment]
你试试 `new FileOutputStream(file).getFD().sync()`。
