### ISSUE TITLE
可否加入判断是否全面屏手机方法

### ISSUE THREAD

**Issue by Chenayi** [Blankj/AndroidUtilCode#450]
您好，可否加入判断是否全面屏手机方法

**Comment by parcool** [comment]
很超前的想法啊~哈哈哈哈

**Comment by cervy** [comment]
宽高比？

**Comment by qinyang1018** [comment]
在小米的mix机器上  有时需要判断是否启用全面屏模式。这个判断总是不准备，不到大家有什么好的办法吗？

**Comment by jingzz1** [comment]
怎么判断？
 public boolean isFullScreen(){
        Resources resources = getResources();
        DisplayMetrics dm = resources.getDisplayMetrics();
//        float density = dm.density;
        int width = dm.widthPixels;
        int height = dm.heightPixels;
        return ((float)height/(float)width) > 1.778;
    }

这样？

**Comment by bersaty** [comment]
机子修改过分辨率后displaymetrics获取的值有时候不对

**Comment by colryzen** [comment]
> 应该获取机型，然后网上查是否是全面屏，数据放到服务器上，以便随时获取！

这种方法不是很优雅，机型那么多；初略计算可以采用 @jingzz1  上面提到的 计算宽高比； 本身全面屏的概念，也没有一个统一的界定； 是否判断是全屏，方法个人认为没有必要集成到基础库；应该交给具体到应用去计算宽高比，或者判断机型，以上仅个人意见

**Comment by Chenayi** [comment]
现在是刘海屏了，你们是怎么适配的？

**Comment by peerless2012** [comment]
> 现在是刘海屏了，你们是怎么适配的？

使用WindowInsets即可。
