### ISSUE TITLE
LogUtils 在AndroidStudio 3.1.1上格式错乱了！

### ISSUE THREAD

**Issue by blusewang** [Blankj/AndroidUtilCode#453]
`
04-15 16:12:19.477 3014-3014/com.yxggwzx.cashier I/BuyAdapter: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, onMenuItemClick(BuyAdapter.kt:38)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ args[0] = 0
    │ args[1] = 0
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
04-15 16:12:19.477 3014-3014/com.yxggwzx.cashier I/Timeline: Timeline: Activity_launch_request time:20330837
`

**Comment by blusewang** [comment]
![image](https://user-images.githubusercontent.com/1764005/38776390-3924b5f4-40c8-11e8-8845-2266462e34c0.png)

**Comment by Blankj** [comment]
1.13.8 版本以上已适配

**Comment by blusewang** [comment]
![image](https://user-images.githubusercontent.com/1764005/38778266-b1b8ee38-40e9-11e8-8c67-e7e827b327d7.png)
