### ISSUE TITLE
关于静默安装提个建议

### ISSUE THREAD

**Issue by Bter** [Blankj/AndroidUtilCode#457]
1.应该对installAppSilent(final File file, final String params)方法中的params注释时加点说明，比如-r还有-i，其中-i在7.0后会用到，不然无法完成静默安装。

2.installAppSilent(final String filePath, final String params)这个params，额。。。。。竟然没效果，去看代码才知道实际传参了也无效，哈哈哈~ @Blankj 这就有点不地道了。

3.顺便想问一下，打平台签名那个怎么弄好，现在都是打包好了后再去打的平台签名。我知道好像可以直接用平台签名文件去签名app的keystore，但我怎么弄都弄不好，这样就导致调式好麻烦啊，请赐教。（使用的keytool-importkeypair进行签名，但不成功，https://blog.csdn.net/cxq234843654/article/details/51557025）

注：试了蛮久才把静默升级的搞定。。。。。哎~~~  - _ -

**Comment by Blankj** [comment]
貌似是1.13.9 版本已做了修复，现在最新版本为 1.13.13，签名的话就是你那篇文章，不成功的话那你把错误信息搜索下，祝好运
