### ISSUE TITLE
log报错，as3.0.0 ,gradle4.1.all

### ISSUE THREAD

**Issue by linbren** [Blankj/AndroidUtilCode#461]
E/LogActivity:  
               ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
               │ main, com.blankj.androidutilcode.feature.core.log.LogActivity.onWidgetClick(LogActivity.java:157)
               │       com.blankj.androidutilcode.base.BaseActivity.onClick(BaseActivity.java:62)
               │       android.view.View.performClick(View.java:5619)
               │       android.view.View$PerformClick.run(View.java:22295)
               │       android.os.Handler.handleCallback(Handler.java:754)
               │       android.os.Handler.dispatchMessage(Handler.java:95)
               │       android.os.Looper.loop(Looper.java:163)
               │       android.app.ActivityThread.main(ActivityThread.java:6337)
               │       java.lang.reflect.Method.invoke(Method.java:-2)
               │       com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
               ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
               │ error
               └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
A/LogActivity:  
               ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
               │ main, com.blankj.androidutilcode.feature.core.log.LogActivity.onWidgetClick(LogActivity.java:158)
               │       com.blankj.androidutilcode.base.BaseActivity.onClick(BaseActivity.java:62)
               │       android.view.View.performClick(View.java:5619)
               │       android.view.View$PerformClick.run(View.java:22295)
               │       android.os.Handler.handleCallback(Handler.java:754)
               │       android.os.Handler.dispatchMessage(Handler.java:95)
               │       android.os.Looper.loop(Looper.java:163)
               │       android.app.ActivityThread.main(ActivityThread.java:6337)
               │       java.lang.reflect.Method.invoke(Method.java:-2)
               │       com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
               ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
               │ assert

**Comment by Blankj** [comment]
升级到最新版本呢
