### ISSUE TITLE
大佬考不考虑适配下7.0的FileProvider

### ISSUE THREAD

**Issue by LambertCoding** [Blankj/AndroidUtilCode#462]
拍照、裁剪、安装apk等，免去声明FileProvider的麻烦

**Comment by Blankj** [comment]
安装 apk 的已在 AppUtils 中，FileProvider 是必须申明的吧，或者你告诉我怎么不申明就可以做到的方法，我加进来

**Comment by LambertCoding** [comment]
就是在lib里提前声明好，然后项目中直接引用，可以参考鸿洋的库[FitAndroid7](https://github.com/hongyangAndroid/FitAndroid7)，提供一个获取Uri的工具就行了

**Comment by Blankj** [comment]
见 UriUtils 中
