### ISSUE TITLE
急急急 ！1.13.16 版本 xml 和别的 远程库冲突，1.13.15正常！求解！！！！

### ISSUE THREAD

**Issue by chenenqiang12345** [Blankj/AndroidUtilCode#465]
急急急 ！1.13.16 版本 xml 和别的 远程库冲突，1.13.15正常！求解！！！！

**Comment by Blankj** [comment]
应该是你工程里有个 `provider_paths.xml` 文件，我改名了，换成 `util_provider_paths.xml`了，试试 1.13.17 吧

**Comment by chenenqiang12345** [comment]
这干嘛用的

**Comment by Blankj** [comment]
自己靠搜索引擎去了解把

**Comment by chenenqiang12345** [comment]
api 'com.blankj:utilcode:+'
    api 'com.jph.takephoto:takephoto_library:+'
这 2个 冲突 你试下
