### ISSUE TITLE
ScreenUtils获取屏幕宽高, 如果屏幕内有虚拟导航键的时候

### ISSUE THREAD

**Issue by laoshuzaiwojia** [Blankj/AndroidUtilCode#467]
ScreenUtils获取屏幕宽高, 如果屏幕内有虚拟导航键的时候,获取的高不是只是整个屏幕高度, 没有减去导航栏的高度

**Comment by Blankj** [comment]
虚拟导航键不是屏幕中的吗，屏幕本来就是指整个手机屏，哪有减去导航栏的才叫屏幕？

**Comment by Blankj** [comment]
如果你要获取减去导航栏的高度，BarUtils 中有获取导航栏高度，两者减一下就可以获取你所说的屏幕高度了

**Comment by zwping** [comment]
@Blankj 借楼，关于减去导航栏高度的问题，如何有效判断导航栏是否存在，并且判断导航栏是否显示

**Comment by Blankj** [comment]
这个需要不同手机去适配了，暂时我没有统一的解决方式，我写的谷歌官方的是支持的，国内手机厂商就不一定了
