### ISSUE TITLE
1.14.0版本有点问题哦 资源文件找不到 

### ISSUE THREAD

**Issue by yulinwoniu666** [Blankj/AndroidUtilCode#468]
Error:(3, 5) No resource found that matches the given name: attr 'android:statusBarColor'.

**Comment by Blankj** [comment]
我库里面没用过这个属性吧

**Comment by yulinwoniu666** [comment]
哦 刚才试过了 写Demo依赖没问题 但是项目里面有这个问题 不知道什么鬼

**Comment by Blankj** [comment]
compileSdkVersion 太低了，没有到 21，而那个属性是 21 才有的

**Comment by yulinwoniu666** [comment]
好像是这样 3Q
