### ISSUE TITLE
getIMEI failed, Android version 4.2.2, the result is 0x0

### ISSUE THREAD

**Issue by j1406493495** [Blankj/AndroidUtilCode#472]

**Comment by Blankj** [comment]
READ_PHONE_STATE 权限加了吗

**Comment by j1406493495** [comment]
加了，我用另外一个库RxTools能成功获取IMEI

**Comment by Blankj** [comment]
你是用真机还是模拟器，模拟器是获取不到的。RxTools 是获取到 IMEI 为空返回回 ANDROID_ID，那并不是 IMEI，看看源码不就知道区别了吗

**Comment by j1406493495** [comment]
真机，但不是手机，嵌入式设备

**Comment by Blankj** [comment]
你要是想达到一样的效果，那就获取到 IMEI 为空，那么就调用 DeviceUtils.getAndroidId()

**Comment by j1406493495** [comment]
好的，多谢
