### ISSUE TITLE
SPUtils

### ISSUE THREAD

**Issue by deepfish123** [Blankj/AndroidUtilCode#478]
SPUtils工具类如果能设置mode类型就更完美了，例如可以手动设置mode指定为MODE_APPEND，检查文件是否存在，存在就往文件追加内容，否则就创建新文件。

**Comment by Blankj** [comment]
急的话就拷贝我现在 GitHub 的 SPutils，不然就等我下个版本

**Comment by Blankj** [comment]
用最新版 1.14.1 SPUtils.getInstance 传入 mode 即可
