### ISSUE TITLE
ToastUtils的字体偏大，比较难看，建议可以选择显示默认字体大小

### ISSUE THREAD

**Issue by zjhcode** [Blankj/AndroidUtilCode#480]
ToastUtils的字体偏大，比较难看，建议可以选择显示默认字体大小
目前是通过如下方式实现了默认字体大小：
Toast toast = Toast.makeText(getApplicationContext(), "", Toast.LENGTH_SHORT);
TextView textView = (TextView) toast.getView().findViewById(android.R.id.message);
ToastUtils.setMsgTextSize(SizeUtils.px2sp(textView.getTextSize()));

**Comment by Blankj** [comment]
升级 1.14.3 即可，之前设置字体样式留下来的 bug
