### ISSUE TITLE
高危漏洞

### ISSUE THREAD

**Issue by 497054711** [Blankj/AndroidUtilCode#482]
阿里云检测出高危漏洞，能不能把高危漏洞去掉啊。
![image](https://user-images.githubusercontent.com/16461163/39681705-6d262276-51de-11e8-9139-a4c268d2f016.png)

**Comment by Blankj** [comment]
使用 1.14.4 版本试试

**Comment by 497054711** [comment]
![image](https://user-images.githubusercontent.com/16461163/39734532-481f29ba-52aa-11e8-9ab5-8da860ddd1a8.png)，你好，能把这个中危漏洞也处理下吗？
