### ISSUE TITLE
log工具类的个人建议

### ISSUE THREAD

**Issue by fengchuxiaodai** [Blankj/AndroidUtilCode#483]
给log的tag添加前缀或者后缀的开关，可以并且仅可以设置一次前缀或者后缀，这样开发sdk会方便很多
例如:
设置前缀为"SDK_”,设置默认tag为"defaultTag"
LogUtils.d("我没有tag");
 日志输出：  defaultTag           :            我没有tag
LogUtils.dTag("我是后缀","我有tag");
日志输出：  SDK_我是后缀           :            我有tag

**Comment by Blankj** [comment]
这需求不行吧，奇奇怪怪的，一个 tag 而已，不用这么大费周章吧，不是都有具体行数了么，这么精准的定位了都。

**Comment by fengchuxiaodai** [comment]
sdk第三方调用的时候，调试时方便在控制台查找日志，当然，也有其他方法解决的

**Comment by Blankj** [comment]
是只要那一次 tag 的日志吗，那你可以设置一个不同的 level 不就好了么。
