### ISSUE TITLE
PermissionUtils 申请权限失败，明明没有申请到权限还是进入onGranted

### ISSUE THREAD

**Issue by protectedMan** [Blankj/AndroidUtilCode#484]
Android 5.1 魅蓝note2
![image](https://user-images.githubusercontent.com/17565737/39737409-759ea8f4-52b7-11e8-96c1-60fd51b4bb7b.png)

实测8.1的机子都可以

**Comment by Blankj** [comment]
低于 6.0 版本的我都返回了onGranted 了，对于低版本国内厂家的权限都有各厂家的适配，需要你自己处理。
