### ISSUE TITLE
installApp(final File file, final String authority)  更新应用程序安卓apk时出现解析程序包时出现问题

### ISSUE THREAD

**Issue by yang-mr** [Blankj/AndroidUtilCode#488]
installApp(final File file, final String authority)

更新应用程序安卓apk时出现解析程序包时出现问题

**Comment by Blankj** [comment]
手机什么版本，file 路径是什么

**Comment by Blankj** [comment]
data/data 目录下的是不能安装的，放到 SD 卡安装即可
