### ISSUE TITLE
文件操作的几点疑问！

### ISSUE THREAD

**Issue by HaydenHu** [Blankj/AndroidUtilCode#491]
首先判断是否是文件和判断是否是文件目录功能似乎有点重复。
其次没有getMimeType这样的文件！

**Comment by HaydenHu** [comment]
好的，谢谢！建议增加几个格式关于.lastModified();的时间戳，如.SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");这样使用起来会方便很多

**Comment by Blankj** [comment]
那就结合 DateUtils 使用即可

**Comment by HaydenHu** [comment]
好的，之前没看到，不好意思。
是在TimeUtils里，好像没有DateUtils。
这库实在是很全面，看来还是自己不仔细！

**Comment by Blankj** [comment]
我说错了哈，就是 TimeUtils
