### ISSUE TITLE
手动申请了ACTION_MANAGE_WRITE_SETTINGS权限，还是出现下面错误。

### ISSUE THREAD

**Issue by android-shiyan** [Blankj/AndroidUtilCode#492]
05-11 18:09:23.067   189   199 D gralloc : Isfb=0, [1920,1032,1920,7680], fmt=1, byte_stride=7680

05-11 18:09:23.076   694   694 D hc      :  value = 1

05-11 18:09:23.076   694   694 D hc      : i am in activity

05-11 18:09:23.079   545   562 E DatabaseUtils: Writing exception to parcel

05-11 18:09:23.079   545   562 E DatabaseUtils: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.warnOrThrowForUndesiredSecureSettingsMutationForTargetSdk(SettingsProvider.java:1175)

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.enforceRestrictedSystemSettingsMutationForCallingPackage(SettingsProvider.java:1030)

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:906)

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:874)

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:257)

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at android.content.ContentProvider$Transport.call(ContentProvider.java:398)

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)

05-11 18:09:23.079   545   562 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)

05-11 18:09:23.080   694   694 D AndroidRuntime: Shutting down VM

--------- beginning of crash

05-11 18:09:23.080   694   694 E AndroidRuntime: FATAL EXCEPTION: main

05-11 18:09:23.080   694   694 E AndroidRuntime: Process: com.kuke.kkpianoroom, PID: 694

05-11 18:09:23.080   694   694 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.kuke.kkpianoroom/com.kuke.kkpianoroom.teacher.activity.LoginActivity}: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3112)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3185)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2487)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5468)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

05-11 18:09:23.080   694   694 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1331)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.provider.Settings$System.putStringForUser(Settings.java:1661)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.provider.Settings$System.putIntForUser(Settings.java:1766)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.provider.Settings$System.putInt(Settings.java:1760)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.Activity.onResume(Activity.java:1227)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:458)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at com.kuke.kkpianoroom.teacher.activity.BaseActivity.onResume(BaseActivity.java:61)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6355)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3100)

05-11 18:09:23.080   694   694 E AndroidRuntime: 	... 10 more

05-11 18:09:23.082   545   573 V WindowManagerService: Wallpaper removing at 0: Window{f8e49ee u0 com.android.systemui.ImageWallpaper

**Comment by Blankj** [comment]
这和我工具类有啥关系？

**Comment by Kayroc** [comment]
mute the thread

At 2018-05-17 20:50:26, "布兰柯基" <notifications@github.com> wrote:


Closed #492.
