### ISSUE TITLE
建议：获取Manifest中meta_data中相关配置的数据

### ISSUE THREAD

**Issue by BlackFlagBin** [Blankj/AndroidUtilCode#495]
有时候需要获取清单文件中配置的自定义meta_data,可以定义一个方法放在AppUtil中

**Comment by Blankj** [comment]
由于不常用，所以放在了 [subutil](https://github.com/Blankj/AndroidUtilCode/blob/master/subutil/README-CN.md) 中的 [MetaDataUtils](https://github.com/Blankj/AndroidUtilCode/blob/master/subutil/src/main/java/com/blankj/subutil/util/MetaDataUtils.java)
