### ISSUE TITLE
BarUtils 在 Android P 的上的高度问题

### ISSUE THREAD

**Issue by yinxtno1** [Blankj/AndroidUtilCode#496]
Android P 模拟器打开模拟的刘海后，状态栏设置的有问题
![1526350533](https://user-images.githubusercontent.com/19941667/40033004-20fb8872-5829-11e8-877f-8c1da3673088.png)
![1526350521](https://user-images.githubusercontent.com/19941667/40033013-2b54fbfa-5829-11e8-89f4-4db5ed3821c3.png)

**Comment by Blankj** [comment]
![image](https://user-images.githubusercontent.com/17978187/40035836-49ebc0f0-5836-11e8-887e-73db7ea5c52f.png)
![image](https://user-images.githubusercontent.com/17978187/40035842-54ddc80a-5836-11e8-88bc-e757bec55525.png)
这是我模拟器的样子

**Comment by Blankj** [comment]
谷歌推荐的是刘海高度不大于状态栏高度，所以只要是动态获取状态栏的就没有什么问题。

**Comment by yinxtno1** [comment]
可以了，刚刚应该是电脑系统出问题了( ╯□╰ )
