### ISSUE TITLE
CrashUtils上报

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#498]
CrashUtils目前是把log保存在本地
是否能提供一个接口,可以把每次Crash都上报给服务器

**Comment by Blankj** [comment]
初始化的时候实现那个接口做你的业务逻辑就好了

**Comment by sweet2o09** [comment]
回复得那么快,大神果然效率
不好意思,之前没看到那个初始化方法,乌龙了
