### ISSUE TITLE
GsonUtils里面的getGson(boolean serializeNulls)方法返回的值反了。

### ISSUE THREAD

**Issue by 775311653** [Blankj/AndroidUtilCode#500]
/**
     * Gets pre-configured {@link Gson} instance.
     *
     * @param serializeNulls determines if nulls will be serialized.
     * @return {@link Gson} instance.
     */
    public static Gson getGson(final boolean serializeNulls) {
        return serializeNulls ? GSON_NO_NULLS : GSON;
    }

**Comment by 775311653** [comment]
还有threadPoolUtils的shutdown方法，建议使用Google推荐的方法；
public void shutDown() {
        exec.shutdown();
        try {
            if (!exec.awaitTermination(60,TimeUnit.SECONDS)){
                exec.shutdownNow();
            }
        } catch (InterruptedException e) {
            exec.shutdownNow();
            e.printStackTrace();
        }
    }
http://www.android-doc.com/reference/java/util/concurrent/ExecutorService.html
大佬，我只提个建议哈，如果我说的不对请多指教呀

**Comment by Blankj** [comment]
GsonUtils 返回值没有错哦，threadPoolUtils 不准备用了，过两天我会在 utilcode 中加入 ThreadUtils

**Comment by Blankj** [comment]
ThreadUtils 已加入 1.16.0 版本， ThreadPoolUtils 已删除
