### ISSUE TITLE
加上常用正则式吧

### ISSUE THREAD

**Issue by 3kqing** [Blankj/AndroidUtilCode#501]
加上常用正则式吧

**Comment by Blankj** [comment]
参考 [RegexConstants](https://github.com/Blankj/AndroidUtilCode/blob/23105feae67cf7cb9ceef55b3dfd0c84494f1ce7/utilcode/src/main/java/com/blankj/utilcode/constant/RegexConstants.java) 和 [RegexUtils](https://github.com/Blankj/AndroidUtilCode/blob/23105feae67cf7cb9ceef55b3dfd0c84494f1ce7/utilcode/src/main/java/com/blankj/utilcode/util/RegexUtils.java)
