### ISSUE TITLE
关于devicetoken

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#502]
大神,我想问下,DeviceUtils里面是否可以新增一个生成devicetoken的方法么作为机器唯一标识符(类似友盟推送的token),或者是可以用别的什么代替?

**Comment by Blankj** [comment]
这个没有一个准确的做法，你可以借用设备很多的唯一值来生成一个保存到本地即可。

**Comment by sweet2o09** [comment]
好的
