### ISSUE TITLE
SpanUtils.setClickSpan点击事件怎么没有反应

### ISSUE THREAD

**Issue by wuyang049679** [Blankj/AndroidUtilCode#504]

**Comment by Blankj** [comment]
为何不好好看下 demo 呢？

**Comment by dyguests** [comment]
天！ **movementMethod = LinkMovementMethod.getInstance()** 这句话，导致我卡了一天OTL。

大佬要不要在 setClickSpan 中实现 `if(movementMethod==null)movementMethod=LinkMovementMethod.getInstance()`的逻辑吧。

我也以为是用不了OTL
