### ISSUE TITLE
设置字体大小后再设置上标 上标效果失效

### ISSUE THREAD

**Issue by VincentYD** [Blankj/AndroidUtilCode#505]
new SpanUtils()
                        .append("99")
                        .appendLine("+")
                            // .append("+")
                        .setFontSize(15,true)
                            // .setFontSize(12,true)
                        .setSuperscript()
                            // .setFontSize(12,true)
                        .create()

版本 1.13.15

**Comment by Blankj** [comment]
![image](https://user-images.githubusercontent.com/17978187/40532789-3746da7a-6033-11e8-920f-471e156fd029.png)
```java
                new SpanUtils()
                        .append("99")
                        .appendLine("+")
                        .setFontSize(100, true)
                        .setSuperscript()
                        .create()
```
