### ISSUE TITLE
PermissionUtils请求权限不能连续调用

### ISSUE THREAD

**Issue by yoyiyi** [Blankj/AndroidUtilCode#506]
·```
 if (!PermissionUtils.isGranted(Manifest.permission.READ_PHONE_STATE)) {
            PermissionUtils.permission(Manifest.permission.READ_PHONE_STATE).request();
        }
        if (!PermissionUtils.isGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
            PermissionUtils.permission(Manifest.permission.WRITE_EXTERNAL_STORAGE).request();
        }
        if (!PermissionUtils.isGranted(Manifest.permission.READ_EXTERNAL_STORAGE)) {
            PermissionUtils.permission(Manifest.permission.READ_EXTERNAL_STORAGE).request();
        }
}
```
比如这样，不合在一起写，就自会请求第一个权限，连续请求三次，后面两个不会走。。

**Comment by Blankj** [comment]
你第一个拒绝第二个就会走，你第一个同意了，后面权限就都有了

**Comment by yoyiyi** [comment]
我们应用是必须分批申请权限的，允许之后还是只会一直跳第一个权限，后续权限请求就没了。。。

**Comment by Blankj** [comment]
我说的那样也是分批请求的啊

**Comment by yoyiyi** [comment]
是的 他只会申请第一批权限 其他批权限就没了

**Comment by Blankj** [comment]
我测试了 `PermissionUtils.permission(PermissionConstants.CALENDAR, PermissionConstants.MICROPHONE)` 会请求两个啊

**Comment by yoyiyi** [comment]
是的 这样是没问题的 但是假如我是分多次申请 多次连续调用PermissionUtils.permission 就请求不到权限 因为应用是分组件的 不同组件打包进去 生成的apk 是权限不一样 所以才蛋疼。。

**Comment by yoyiyi** [comment]
不过后来找到方法了  定义一个数组 把需要的权限加进去 只调用一次 PermissionUtils.permission方法

**Comment by Blankj** [comment]
嗯哼，解决了就好，你这问题太古怪了哈

**Comment by yoyiyi** [comment]
没办法，特殊需求，打包出来程序需要不同权限，不能一次性全部申请。。。
