### ISSUE TITLE
TimeUtils.getTimeSpan永远返回大于0的值

### ISSUE THREAD

**Issue by liunewshine** [Blankj/AndroidUtilCode#509]
获取时间差的方法,应该支持正负值,目前
TimeUtils.getTimeSpan("2018-05-01","2018-05-03")
TimeUtils.getTimeSpan("2018-05-03","2018-05-01")
返回同样的值,无法获取时间的大小

**Comment by liunewshine** [comment]
@Blankj 判断本地文件否有更新,比如由时间由2018-05-03变为2018-05-04视为有更新,时间由2018-05-03变为2018-05-02视为无更新

**Comment by Blankj** [comment]
既然你都可以获取到两时间了，那就都 string2Millis 减一下不就可以了么，如果 timeSpan 作符号区分那你还得看源码区分我是前面减后面还是后面减前面，timeSpan 就是时间跨度，应该不分正负比较妥当。

**Comment by liunewshine** [comment]
@Blankj 我现在就是这么做的,但是感觉有负值更和jdk的一致,比如java8的Period.between

**Comment by Blankj** [comment]
好的，我已了解，下版本会去掉绝对值

**Comment by Blankj** [comment]
已发布 1.16.2 版本，你可以试试

**Comment by liunewshine** [comment]
多谢
