### ISSUE TITLE
监听键盘变化，EditText放在布局底部时不起作用

### ISSUE THREAD

**Issue by woshiyizhijiao** [Blankj/AndroidUtilCode#514]
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <EditText
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_gravity="bottom"/>

</FrameLayout>

     KeyboardUtils.registerSoftInputChangedListener(this, new KeyboardUtils.OnSoftInputChangedListener() {
            @Override
            public void onSoftInputChanged(int height) {
                
            }
        });
该方法没有监听到，针对这种情况

**Comment by zhangxiaofan000123** [comment]
android:windowSoftInputMode="adjustPan|stateHidden" 你在清单文件中加入这个试一下

**Comment by Blankj** [comment]
试试最新版本 1.20.2 也许能够帮到你
