### ISSUE TITLE
ZipUtil Exception

### ISSUE THREAD

**Issue by WangChangQin** [Blankj/AndroidUtilCode#515]
End Of Central Directory signature not found

**Comment by WangChangQin** [comment]
解压的时候报这个错 @Blankj

**Comment by Blankj** [comment]
压缩是用的我工具类吗

**Comment by WangChangQin** [comment]
是啊

**Comment by Blankj** [comment]
每次都会异常？ 我看你调用的代码

**Comment by WangChangQin** [comment]
`private void zipFiles(DownloadTask task) {
        File file = task.getFile();
        String ext = file.getAbsolutePath().substring(file.getAbsolutePath().lastIndexOf("."));
        if (ext.contains("zip")){
            try {
                ZipUtils.unzipFile(file,file.getParentFile());
            }catch (Exception e){
                QLog.e(e.toString());
            }
        }
    }`

**Comment by WangChangQin** [comment]
java.util.zip.ZipException: End Of Central Directory signature not found

**Comment by Blankj** [comment]
搜索出来的结果是文件还没下载完你就开始解压了，你等文件下载完再解压试试

**Comment by WangChangQin** [comment]
行，我试试^ ^

**Comment by Blankj** [comment]
你 zip 文件大小是多少 超过 2G 了吗

**Comment by WangChangQin** [comment]
不到5m，还是报错

**Comment by WangChangQin** [comment]
我延时5s解压还是有问题

**Comment by Blankj** [comment]
那你把 zip 包拿出来手动解压呢

**Comment by WangChangQin** [comment]
可以啊，我pull出来是可以的

**Comment by Blankj** [comment]
那你把可以的包放到固定路径下，用我工具类试试

**Comment by Blankj** [comment]
或者你先发给我，我来试下

**Comment by WangChangQin** [comment]
我先试下，您先忙着

**Comment by WangChangQin** [comment]
老哥，搞明白了，是我用的流利说下载框架配置有问题，之前下载的都可以，这个类问题，可以解压
