### ISSUE TITLE
CrashUtils类为什么还要去调用默认的异常处理器

### ISSUE THREAD

**Issue by peterforme** [Blankj/AndroidUtilCode#521]
![default](https://user-images.githubusercontent.com/4645357/41144319-1dfff4fa-6b2f-11e8-9053-afb9bbfc3c3e.PNG)
想问下为什么自定义的异常处理器在处理完了后还要再去调用默认的异常处理器呢？（为何不是处理完了直接调用killProcess退出）

**Comment by Blankj** [comment]
默认的会输出异常到 logcat 中，我只是在中间多做了点事情而已，不影响原先的实现
