### ISSUE TITLE
开启日志功能滑动的时候频繁输出日志有点卡顿

### ISSUE THREAD

**Issue by hlgithub369** [Blankj/AndroidUtilCode#522]
![image](https://user-images.githubusercontent.com/15081751/41215392-ab3c3c66-6d82-11e8-9064-1191392cf38d.png)

下面是我的初始化代码:
 private void initUtils() {
        //输出日志的时候比较卡.
        com.blankj.utilcode.util.Utils.init(this);
        //多进程使用的时候日志写入文件不要用同一个文件  否则交替写会出问题的 初始化的时候根据进程名设置不同文件名
        final LogUtils.Config config = LogUtils.getConfig()
                .setLogSwitch(BuildConfig.DEBUG)// 设置 log 总开关，包括输出到控制台和文件，默认开
                .setConsoleSwitch(BuildConfig.DEBUG)// 设置是否输出到控制台开关，默认开
                .setGlobalTag("")// 设置 log 全局标签，默认为空
                // 当全局标签不为空时，我们输出的 log 全部为该 tag，
                // 为空时，如果传入的 tag 为空那就显示类名，否则显示 tag
                .setLogHeadSwitch(true)// 设置 log 头信息开关，默认为开

                .setLog2FileSwitch(true)// 打印 log 时是否存到文件的开关，默认关
                .setDir("")// 当自定义路径为空时，写入应用的/cache/log/目录中
                .setFilePrefix("zs")// 当文件前缀为空时，默认为"util"，即写入文件为"util-MM-dd.txt"
                .setBorderSwitch(false)// 输出日志是否带边框开关，默认开
                .setConsoleFilter(LogUtils.V)// log 的控制台过滤器，和 logcat 过滤器同理，默认 Verbose
                .setFileFilter(LogUtils.V)// log 文件过滤器，和 logcat 过滤器同理，默认 Verbose
                .setStackDeep(1);// log 栈深度，默认为 1
        new Thread(new Runnable() {
            @Override
            public void run() {
                LogUtils.d(config.toString());
            }
        }).start();
    }
手机我这边小米.乐视都有点卡顿的.

**Comment by hlgithub369** [comment]
.setLog2FileSwitch(true)// 打印 log 时是否存到文件的开关，默认关
测试后这个功能打开后就会比较卡.

**Comment by Blankj** [comment]
你写入文件要占 cpu 的，高频操作可能就会造成卡顿， debug 开启可以，正式版本只需要把关键性的日志写入文件即可。

**Comment by hlgithub369** [comment]
好.谢谢
