### ISSUE TITLE
Utils.java  function < getTopActivity>

### ISSUE THREAD

**Issue by charles88** [Blankj/AndroidUtilCode#523]
java.lang.NoSuchFieldException: No field mActivityList in class Landroid/app/ActivityThread; (declaration of 'android.app.ActivityThread' appears in /system/framework/framework.jar)

android P

**Comment by Blankj** [comment]
是 android-p 开始不让反射系统私有 api 了  https://developer.android.google.cn/preview/restrictions-non-sdk-interfaces

**Comment by charles88** [comment]
目前有替代方案吗？ActivityManager 里面获取也不保险

**Comment by Blankj** [comment]
一般情况不会走反射啊，只有 mActivityList 为空才会走啊，你除非没初始化或者 activity 都退出了
![image](https://user-images.githubusercontent.com/17978187/41279117-2c418c04-6e5e-11e8-978f-315b485f4ca7.png)

**Comment by charles88** [comment]
目前在海外手机上piexl sang, 内存吃紧的情况 在游戏里 java 存储的单例 数据都被释放 导致我需要重新刷新创建 ，需要获取当前上下文

**Comment by charles88** [comment]
![image](https://user-images.githubusercontent.com/2108766/41279413-ff5682f2-6e5e-11e8-899d-4369c196520b.png)

**Comment by charles88** [comment]
这里返回 返回null

**Comment by Blankj** [comment]
getAssets 不需要 activity，用 application 就行

**Comment by charles88** [comment]
我试试

**Comment by charles88** [comment]
谢谢作者
