### ISSUE TITLE
怎么把.png图片转成Base64？我用FileIOUtils.readFile2BytesByStream()和EncodeUtils.base64Encode2String()这两个方法，把.png文件转成Base64，但透明度消失了。怎么把.png图片转成Base64并保留透明度呢？

### ISSUE THREAD

**Issue by 1690251766** [Blankj/AndroidUtilCode#525]
**问题描述：将.png文件用FileIOUtils.readFile2BytesByStream()和EncodeUtils.base64Encode2String()这两个方法获得的base64，丢失了透明度，变成了没有透明的图片。**

The version of utilcode: 1.16.4

The device:华为mate s

The version of device: API 22

**The code:**
```
    @Nullable
    public static String getJsScript_Base64(Context context, File file) {
        File compressToFile = FileUtils.compressToFile(context, file);
        byte[] bytes = FileIOUtils.readFile2BytesByStream(compressToFile);
        String encode2String = EncodeUtils.base64Encode2String(bytes);
        String type;
        if (isPng(compressToFile)) {
            type = "png";
        } else {
            type = "jpeg";
        }
        String script = "data:image/" + type + ";base64," + encode2String;
        return script;
    }
```

**Screenshots**
**应该是这样的：**
![_20180613124652](https://user-images.githubusercontent.com/11400746/41330865-7d631f9e-6f08-11e8-8907-4d56534141bf.jpg)

**但现在是这样的：**
![_20180613124645](https://user-images.githubusercontent.com/11400746/41330876-8f537262-6f08-11e8-8a7a-8856975df5ac.jpg)

不知道什么原因，麻烦帮忙看一下。
这是一个非常好的库，十分感谢！

**Comment by Blankj** [comment]
你用我的两个操作函数肯定是没有问题的，你其他代码可能会影响到透明度的改变，我感觉你的这个 `FileUtils.compressToFile(context, file)` 函数会出问题吧，压缩保存的格式是什么？你这个不对的话就会影响到最终显示效果。

**Comment by 1690251766** [comment]
我测试过这个FileUtils.compressToFile(context, file)函数，压缩出来的是.png图片，是带透明度的，保存的也是.png，是对的

**Comment by Blankj** [comment]
```java
byte[] bytes = FileIOUtils.readFile2BytesByStream(compressToFile);
String encode2String = EncodeUtils.base64Encode2String(bytes);
```
我这两函数肯定没那么高级，会去处理你的透明度，所以你应该 debug 看看到底是哪里出问题了

**Comment by 1690251766** [comment]
我傻了，是我代码的问题，压缩函数没有指明Bitmap.CompressFormat=PNG，导致以jpg格式压缩了。。哎，特意写了获取格式方法，还测试过，但压缩函数里竟然忘记调用了！感谢感谢。

**Comment by Blankj** [comment]
解决了就好
