### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by YY007H** [Blankj/AndroidUtilCode#526]
**The version of utilcode: [e.g. 1.16.3]**
1.16.4
**The device: [e.g. Nexus 5X]**
小米平板2
**The version of device: [e.g. API 27]**
API 23
**The code:**
错误是：
 W/System.err: java.lang.NoSuchFieldException: mActivityList

**Comment by Blankj** [comment]
我给你那么点信息你能找到 bug 吗，你换机器或者新建 demo 测试呢？
