### ISSUE TITLE
使用库动态弹出键盘不成功，直接调用原生的方法缺可以

### ISSUE THREAD

**Issue by qianshengta** [Blankj/AndroidUtilCode#528]
我使用KeyboardUtils.showSoftInput(context);希望在我的dialog弹出的时候就弹出输入发(dialog中EditText)，但是没有效果，我直接调用系统原生的方法，却可以实现
```
   private void showInputMethod() {
        //自动弹出键盘
        InputMethodManager inputManager = (InputMethodManager) context.getSystemService(Context
                .INPUT_METHOD_SERVICE);
        inputManager.toggleSoftInput(0, InputMethodManager.HIDE_NOT_ALWAYS);
        //强制隐藏Android输入法窗口
        // inputManager.hideSoftInputFromWindow(edit.getWindowToken(),0);
    }
```

手机华为 系统6.01

**Comment by Blankj** [comment]
直接调用系统原生的方法是什么？

**Comment by qianshengta** [comment]
@Blankj
   private void showInputMethod() {
        //自动弹出键盘
        InputMethodManager inputManager = (InputMethodManager) context.getSystemService(Context
                .INPUT_METHOD_SERVICE);
        inputManager.toggleSoftInput(0, InputMethodManager.HIDE_NOT_ALWAYS);
        //强制隐藏Android输入法窗口
        // inputManager.hideSoftInputFromWindow(edit.getWindowToken(),0);
    }

**Comment by Blankj** [comment]
你这个是因为 toggleSoftInput，你可以这样来实现，utils.isSoftInputVisible?utils.toggleSoftInput 这样就可以了

**Comment by Blankj** [comment]
我的 demo 是可以做到你说的那样的，你可以试试看，具体你这为啥不能我也不清楚

**Comment by qianshengta** [comment]
好的 谢谢啊大佬
