### ISSUE TITLE
可否考虑改变 proguard 的规则

### ISSUE THREAD

**Issue by ratdream** [Blankj/AndroidUtilCode#530]
现在所有的类默认是全部 keep 住的，如果只用到库的部分方法，最终打包的时候，因为 keep 住所有的类，没有用到的方法还是会打包到 apk 中

**Comment by Blankj** [comment]
开源库一般都不需要混淆的，全 keep 就好了，我这最终占用的也就几百 KB，这几百 KB 对你影响很大吗，你如果实在很想节约空间，那你就把用到的函数复制粘贴到你项目中，这种更加节省。

**Comment by ratdream** [comment]
对于 app 来说，当然是希望 apk 越小越好，混淆开启后会移除未使用的类，建议可以考虑让使用到 AndroidUtilCode 库的开发者自己选择是否要添加混淆规则~
