### ISSUE TITLE
关于SpanUtils的部分文字点击事件

### ISSUE THREAD

**Issue by magic0908** [Blankj/AndroidUtilCode#532]
感谢作者的开源，对我帮助很大，其中我发现有些地方可以再完善下。
1、在demo里面，给部分文字添加点击事件，你是额外写一个ClickableSpan，然后再通过SpanUtils.setClickSpan()，我觉得可以在SpanUtils里面声明一个接口，然后通过接口回调方式去触发点击操作，这样就不需要在activity额外写一个ClickableSpan了。
2、另外发现，假如TextView的一段文字里，我想使用两个以上的部分点击事件，会有问题，因为源码里面setClickSpan方法里，this.clickSpan = clickSpan;始终把参数的span覆盖了全局的span变量，所以想使用两个以上的clickSpan就没办法了。

**Comment by Blankj** [comment]
第一点直接传入一个 ClickSpan 对象跟你传参数和接口没啥区别，而且可变参数太多，所以还不如直接传入 ClickSpan 对象即可；
第二点你说的是不对的，你可以自己再看看源码，或者试试看效果是啥样。

**Comment by magic0908** [comment]
OK，是我这边的问题，已经解决了
