### ISSUE TITLE
CacheUtils中的文件名

### ISSUE THREAD

**Issue by BestMafen** [Blankj/AndroidUtilCode#534]
请问下大神，CacheUtils中的文件名，为什么要用key.hashCode()，而不直接用key呢，hashCode毕竟有极低概率重复，而key通常是开发者定义的不重复的常量。

**Comment by Blankj** [comment]
你直接用 key 太直接明了，不是很安全，而且如果 key 传入是中文、韩文啥的还要考虑编码，用 hashcode 就不用考虑这么多

**Comment by BestMafen** [comment]
明白了，谢谢！
