### ISSUE TITLE
代码好难读，有文档吗？

### ISSUE THREAD

**Issue by Wangct23** [Blankj/AndroidUtilCode#537]
![image](https://user-images.githubusercontent.com/17804057/41848082-d80f98e6-78ae-11e8-8781-f755418c7d71.png)

**Comment by Blankj** [comment]
你怎么引用的？

**Comment by Wangct23** [comment]
var0 和 var1 代表什么含义呢？
我记得以前的版本，变量命名都很清晰，而且还有相当完整的注释。怎么现在又没有了？

**Comment by Wangct23** [comment]
@Blankj
在build.gradle文件
implementation 'com.blankj:utilcode:1.17.1'

**Comment by Blankj** [comment]
我这里边引用的有的啊，左上角显示的是 1.17.1 源码哦
![image](https://user-images.githubusercontent.com/17978187/41848485-2ce47a34-78b0-11e8-8d87-361c29af0eee.png)
你展开 
![image](https://user-images.githubusercontent.com/17978187/41848543-5ee16b6e-78b0-11e8-8f16-ddaa26b9bba9.png) 这个看看

**Comment by Wangct23** [comment]
@Blankj 1.17.1 有了，刚才是1.17.0

**Comment by Blankj** [comment]
1.17.0 也是有的哦我这边

**Comment by xybyuan** [comment]
代码被混淆了
