### ISSUE TITLE
Utils ActivityLifecycle

### ISSUE THREAD

**Issue by AndrLin** [Blankj/AndroidUtilCode#538]
Utils.java 中使用了registerActivityLifecycleCallbacks监听Activity生命周期，并在其中实现了Activity的管理。
但是我本身就想要在项目中registerActivityLifecycleCallbacks监听Activity生命周期，这样就会有冲突，如果Utils.java可以提供addActivityLifecycleCallback回调就好了，让大家可以自己处理Activity生命周期回调，且也不影响Utils的Activity管理。

**Comment by Blankj** [comment]
registerActivityLifecycleCallbacks 注册多个都没关系的，是相互独立的，源码里 
 `mActivityLifecycleCallbacks.add` 就说明了一切。

**Comment by AndrLin** [comment]
感谢回复，看了下源码确实是这样的，又学习了
