### ISSUE TITLE
获取文件大小如何指定单位？只见注释，不见方法

### ISSUE THREAD

**Issue by Andecy** [Blankj/AndroidUtilCode#54]
/**
     * 获取文件大小
     * <p>例如：getFileSize(file, ConstUtils.MB); 返回文件大小单位为MB</p>
     *
     * @param file 文件
     * @return 文件大小
     */
    public static String getFileSize(File file) {
        if (!isFileExists(file)) return "";
        return ConvertUtils.byte2FitSize(file.length());
    }

**Comment by Blankj** [comment]
这个方法已经优化过了，自动会计算返回最佳单位，你可以看下byte2FitSize，注释忘记更新了。

**Comment by Andecy** [comment]
谢谢，看到了，现在才回复，很抱歉
