### ISSUE TITLE
setNavBarVisibility（this, true）没有反应

### ISSUE THREAD

**Issue by Wangct23** [Blankj/AndroidUtilCode#540]
用demo的代码在华为H60-L03 Android4.4.2机器上，setNavBarVisibility(this, true)没有反应
反倒是点击多次setNavBarVisibility(this, false)可以显示虚拟导航栏

AndroidUtilCode 1.17.1

**Comment by Blankj** [comment]
导航栏不是原生的那就自己适配吧，我这个并不适配所有。
