### ISSUE TITLE
新增的CacheDiskUtil,新增key的时候，两个maxCount？是不是写误了？maxSize+maxCount？

### ISSUE THREAD

**Issue by blackbai11** [Blankj/AndroidUtilCode#543]
新增的CacheDiskUtil,新增cacheKey的时候，两个maxCount？是不是写误了？maxSize+maxCount？
原：
final String cacheKey = cacheDir.getAbsoluteFile() + "_" + maxCount + "_" + maxCount;

**Comment by Blankj** [comment]
是的，下版本会修复

**Comment by Blankj** [comment]
1.17.2 已可用
