### ISSUE TITLE
@NonNull注解问题

### ISSUE THREAD

**Issue by lihuanming** [Blankj/AndroidUtilCode#544]
Argument 'text' of type CharSequence (#0 out of 1, zero-based) is marked by @android.support.annotation.NonNull but got null for it

问题是，我的key不为空啊！！请问一下，这是什么问题？？

**Comment by Blankj** [comment]
你打印出你的 key 不为空了？

**Comment by lihuanming** [comment]
是啊，不为空呢

**Comment by Blankj** [comment]
你调用了啥啊？

**Comment by lihuanming** [comment]
框架没问题，是我代码问题！

**Comment by JieSmart** [comment]
我也出现这问题了，你是调用啥出现的
