### ISSUE TITLE
建议在PermissionUtils中添加蓝牙相关权限

### ISSUE THREAD

**Issue by XXQAQ** [Blankj/AndroidUtilCode#545]
建议在PermissionUtils中添加蓝牙相关权限

**Comment by Blankj** [comment]
不明白为什么要添加蓝牙的权限？

**Comment by XXQAQ** [comment]
不好意思是我搞错了，刚刚看了一下蓝牙权限只需要请求android.permission.ACCESS_COARSE_LOCATION即可。不过在安卓6.0以后使用蓝牙搜索功能还需要额外打开GPS功能，很头疼
