### ISSUE TITLE
EncryptUtils line:143 重复调用encryptMD5File

### ISSUE THREAD

**Issue by zuolongxiang** [Blankj/AndroidUtilCode#55]
如题
public static String encryptMD5File2String(File file) {
        return encryptMD5File(file) != null ? bytes2HexString(encryptMD5File(file)) : "";
    }

改成：

    public static String encryptMD5File2String(File file) {
        byte[] bytes = encryptMD5File(file);
        return bytes  != null ? bytes2HexString(bytes ) : "";
    }

**Comment by Blankj** [comment]
GOOD!

**Comment by Blankj** [comment]
好久之前写的了，现在要更新一波规范

**Comment by jp1017** [comment]
更新完再关闭盲 :smile: :+1: :100: :eggplant:
