### ISSUE TITLE
增加获取meta-data值的工具类吧

### ISSUE THREAD

**Issue by 3kqing** [Blankj/AndroidUtilCode#554]
meta-data算常用工具吧

**Comment by Blankj** [comment]
不常用的都在 [subutil](https://github.com/Blankj/AndroidUtilCode/blob/master/subutil/README-CN.md) 里 [MetaUtils](https://github.com/Blankj/AndroidUtilCode/blob/master/subutil/src/main/java/com/blankj/subutil/util/MetaDataUtils.java)
