### ISSUE TITLE
imageutils类里添加文字水印的方法

### ISSUE THREAD

**Issue by CK875430315** [Blankj/AndroidUtilCode#555]
水印文字的大小会随着image图片本身的分辨率的大小改变而改变，这个问题遇到很多次了，在这里也遇到了，希望找到解决方法

**Comment by Blankj** [comment]
那你不同大小的图片自己写入不同大小的文字大小不就好了么，我只是负责给你写入固定大小的水印，哪里还来判断你图片大小什么的啊
