### ISSUE TITLE
SpanUtils # appendImage() 添加图片，默认left 添加一个宽度，vivoX20

### ISSUE THREAD

**Issue by wei3** [Blankj/AndroidUtilCode#557]
![80f48cb750c4d8ab3f29b531a0fd0133](https://user-images.githubusercontent.com/20719661/42510470-90d1ab2a-8481-11e8-9a3e-e2a687775e63.jpg)

**Comment by wei3** [comment]
用系统方法写就不会有此问题

**Comment by Blankj** [comment]
amazing 啊，我这边没机器可以调试，不然可以看看哪里的问题

**Comment by Blankj** [comment]
@wei3 @ParfoisMeng  1.21.1 已修复此 bug
