### ISSUE TITLE
判断是否是手机，是否可以区分手机和平板，还是只区分手机和安卓设备

### ISSUE THREAD

**Issue by qianshengta** [Blankj/AndroidUtilCode#558]
PhoneUtils.isPhone()这个方法是只区分手机和安卓设备(主要区别是有误Sim卡)，还是包括区别手机和平板设备(主要区别是屏幕大小)

**Comment by Blankj** [comment]
应该是是否支持 sim 卡

**Comment by qianshengta** [comment]
好的 谢谢 大佬有没有兴趣添加一个区分手机和平板的方法啊。不过不得不说大佬你每次回复的都好及时啊!

**Comment by Blankj** [comment]
screenutils.isTablet 你可以试试

**Comment by QAQQL** [comment]
isTablet 在模拟器设置如下时失效
<img width="264" alt="96d650b79836494228e9c10be5d220e" src="https://github.com/Blankj/AndroidUtilCode/assets/51136763/72bd376f-5389-4a1b-ba43-bf4e44925290">
