### ISSUE TITLE
状态栏颜色设置问题

### ISSUE THREAD

**Issue by ZJYZJY** [Blankj/AndroidUtilCode#559]
https://github.com/Blankj/AndroidUtilCode/blob/abc7a5da8584fdb419bc7b753f646db49e742562/utilcode/src/main/java/com/blankj/utilcode/util/BarUtils.java#L446
应该是当alpha=255时返回color，而不是alpha=0的时候。

**Comment by Blankj** [comment]
这个 alpha 不是颜色的透明通道 alpha，是谷歌状态栏所谓的 alpha，根据这个 alpha 去计算状态栏的颜色，而不是去改变状态栏的透明度，代码里也写到了透明度都是 255，只是改变颜色。
`return Color.argb(255, red, green, blue);`
