### ISSUE TITLE
AppUtils.isAppForeground(Constants.guardAppName) 判断是否在前台失效

### ISSUE THREAD

**Issue by Xujun770366270** [Blankj/AndroidUtilCode#560]
![image](https://user-images.githubusercontent.com/13106539/42634992-5dbcd2b8-8617-11e8-905b-ad1b6e30de29.png)
AppUtils.isAppForeground(Constants.guardAppName) 判断是否在前台失效 ，拿到的结果永远是false

**Comment by Blankj** [comment]
把 bug 描述清楚好吗，我不是新开 issue 都是有格式的么，设备版本什么的

**Comment by Xujun770366270** [comment]
设备版本Android 7.1 为自己公司定制的Android 主板，Android 版已经root ，但是拿不到su 权限，本来是想用adb 指令去做的，但是因为拿不到，就做不了，使用你这个方法，拿到的结果一致是false

**Comment by Xujun770366270** [comment]
找到原因了,Android的好想是需要一种权限,授权之后才能正常,不过这个权限不知道怎么在代码中授权
![image](https://user-images.githubusercontent.com/13106539/42676904-7e001be4-86ac-11e8-8130-d3ca1598bb0b.png)

**Comment by Blankj** [comment]
我代码里写了的啊，ACTION_USAGE_ACCESS_SETTINGS 要打开这个

**Comment by Xujun770366270** [comment]
加了这个权限,但是这个权限授权页面还是跳不过去,还是要手动授权,系统是Android7.1 已经root 掉的手机

**Comment by Blankj** [comment]
那就母鸡了

**Comment by prczhb** [comment]
> 那就母鸡了
代码中的方法判断前后台方式不准确 当应用有前台服务时,此方法失效,会判断应用一直是前台显示
https://blog.csdn.net/u011386173/article/details/79095757

**Comment by Blankj** [comment]
@prczhb 判断自己的应用那就使用 AppUtils.registerAppStatusChangedListener 就行
