### ISSUE TITLE
可以把Java可以直接用的类都抽取出来做一个单独的模块，然后由AndroidUtilCode依赖那个模块吗？

### ISSUE THREAD

**Issue by YunlongYang** [Blankj/AndroidUtilCode#563]
有时候需要在Java工程里使用这个库的功能，但是有很多类找不到

**Comment by Blankj** [comment]
* CloseUtils
* FileIOUtils
* FileUtils
* ReflectUtils
* RegexUtils
* ShellUtils
* StringUtils
还有吗你看看

**Comment by YunlongYang** [comment]
CloseUtils.java
ConvertUtils.java 部分
CrashUtils.java 部分（Java很需要这个工具）
EncodeUtils.java
EncryptUtils.java
FileIOUtils.java
FileUtils.java
LogUtils.java
ObjectUtils.java
ReflectUtils.java
RegexUtils.java
ShellUtils.java
ThreadUtils.java
TimeUtils.java
UriUtils.java
ZipUtils.java

**Comment by Blankj** [comment]
你说的有些里面参杂 android 的我都不好分离出来，需要再写一套逻辑，那样就会和原来部分的方法签名不同，我再想想办法吧，我说的那几个应该是可以的，你说的有些里面有 android 依赖的就有点麻烦

**Comment by zeplee** [comment]
完全没必要

**Comment by arzu63** [comment]
#
