### ISSUE TITLE
报这个错误

### ISSUE THREAD

**Issue by wjy000** [Blankj/AndroidUtilCode#566]
Suppressed: java.lang.ClassNotFoundException: android.support.v4.content.FileProvider4Util
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 16 more

**Comment by Blankj** [comment]
开混淆了吗

**Comment by wjy000** [comment]
没有,就一个干净的demo,引入这个包就无法编译

**Comment by Blankj** [comment]
什么都没写就这样了？

**Comment by wjy000** [comment]
是啊,你可以试试,用的是最新版的android sutdio,最后我实在没办法就引入了compile 'com.blankj:utilcode:1.13.9'这个老版本就可以了,这个老版本没有android.support.v4.content.FileProvider4Util这个类

**Comment by ujffdi** [comment]
同个问题，退回1.17.2没问题

**Comment by wjy000** [comment]
不知道这个类FileProvider4Util的作用是什么,问题确实存在,现在开发都不引用android.support.v4这个包了

**Comment by Blankj** [comment]
是 3.1.3 android studio 吗，我这边真的没有这个问题，我让群里的小伙伴试了也没发现这个问题，你要不再试试 1.18.0 ？

**Comment by wjy000** [comment]
androidstudio3.2

**Comment by wjy000** [comment]
targetSdkVersion 28

**Comment by wjy000** [comment]
android studio 3.2
targetSdkVersion 28
compileSdkVersion 28
你用这个环境建一个项目,凡是带FileProvider4Util这个类的版本统统无法运行

**Comment by Blankj** [comment]
那你用 3.1.3 版本呢，我这边 3.1.3 28 没事

**Comment by Blankj** [comment]
我刚下了 3.2 beta 5，创建了工程引用了 1.18.0 没你说的问题啊

**Comment by wjy000** [comment]
我可以直接使用源码,把FileProvider4Util删掉就行了,也算解决了吧

**Comment by Blankj** [comment]
那你直接使用源码不删掉 FileProvider4Util 还会有问题？

**Comment by j1406493495** [comment]
同遇到该问题，新建的项目，无其他依赖。
添加implementation "com.android.support:appcompat-v7:27.1.1"后无报错。
