### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by sangsais** [Blankj/AndroidUtilCode#569]
Attempt to read from field 'com.blankj.utilcode.util.PermissionUtils$ThemeCallback com.blankj.utilcode.util.PermissionUtils.mThemeCallback' on a null object reference

1 java.lang.RuntimeException:Unable to start activity ComponentInfo{com.dfs168.ttxn/com.blankj.utilcode.util.PermissionUtils$PermissionActivity}: java.lang.NullPointerException: Attempt to read from field 'com.blankj.utilcode.util.PermissionUtils$ThemeCallback com.blankj.utilcode.util.PermissionUtils.mThemeCallback' on a null object reference
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to read from field 'com.blankj.utilcode.util.PermissionUtils$ThemeCallback com.blankj.utilcode.util.PermissionUtils.mThemeCallback' on a null object reference
6 com.blankj.utilcode.util.PermissionUtils.access$300(PermissionUtils.java:35)
7 com.blankj.utilcode.util.PermissionUtils$PermissionActivity.onCreate(PermissionUtils.java:290)
8 android.app.Activity.performCreate(Activity.java:6357)
9 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
11 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
12 android.app.ActivityThread.access$1000(ActivityThread.java:154)
13 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
14 android.os.Handler.dispatchMessage(Handler.java:102)
15 android.os.Looper.loop(Looper.java:157)
16 android.app.ActivityThread.main(ActivityThread.java:5567)
17 java.lang.reflect.Method.invoke(Native Method)
18 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)

**Comment by sangsais** [comment]
implementation 'com.blankj:utilcode:1.13.5'

**Comment by Blankj** [comment]
为什么不遵循我写好的 issue 格式 你使用的代码也要放上来我才更方便看 有时还会和设备版本啥的有关系的话也需要说明 能更准确的反馈 bug 我才能更好地去修复哈

**Comment by sangsais** [comment]
bugly反馈的异常

implementation 'com.blankj:utilcode:1.13.5'

荣耀 BLN AL10 Android 7.0,level 24 ROM-HuaWei/EMOTION CPU架构 arm64-v8a

onCreate调用如下代码
private void checkPermiss() {

        PermissionUtils.permission(PermissionConstants.PHONE)
                .rationale(new PermissionUtils.OnRationaleListener() {
                    @Override
                    public void rationale(final ShouldRequest shouldRequest) {
                        //DialogHelper.showRationaleDialog(shouldRequest);
                    }
                })
                .callback(new PermissionUtils.FullCallback() {
                    @Override
                    public void onGranted(List<String> permissionsGranted) {
                        toNextActivity();
                    }

                    @Override
                    public void onDenied(List<String> permissionsDeniedForever,
                                         List<String> permissionsDenied) {
                        toNextActivity();
                        if (!permissionsDeniedForever.isEmpty()) {
                        }
                    }
                })
                .theme(new PermissionUtils.ThemeCallback() {
                    @Override
                    public void onActivityCreate(Activity activity) {
                        ScreenUtils.setFullScreen(activity);
                    }
                })
                .request();
    }

**Comment by Blankj** [comment]
你这版本有点低，升级下版本就好了，可以用 1.18.0 最新的就好了。
