### ISSUE TITLE
关于SpanUtils添加文字边框的建议

### ISSUE THREAD

**Issue by XXQAQ** [Blankj/AndroidUtilCode#578]
经过实际测试，使用以下自定义ReplacementSpan即可添加文字边框，建议添加以下代码更新您的SpanUtils
`class RoundBackgroundColorSpan extends ReplacementSpan {
        private int mRadius;
        private int bgColor;
        private int textColor;
        private int mSize;

        public RoundBackgroundColorSpan(int bgColor,
                                        int textColor,
                                        int radius) {
            super();
            this.bgColor = bgColor;
            this.textColor = textColor;
            this.mRadius = radius;
        }

        /**
         * @param start 第一个字符的下标
         * @param end   最后一个字符的下标
         * @return span的宽度
         */
        @Override
        public int getSize(@NonNull Paint paint,
                           CharSequence text,
                           int start,
                           int end,
                           Paint.FontMetricsInt fm) {
            mSize = (int) (paint.measureText(text, start, end) + 2 * mRadius);
            return mSize + 5;//5:距离其他文字的空白
        }

        /**
         * @param y baseline
         */
        @Override
        public void draw(@NonNull Canvas canvas,
                         CharSequence text,
                         int start,
                         int end,
                         float x,
                         int top,
                         int y, int bottom,
                         @NonNull Paint paint) {
            int defaultColor = paint.getColor();//保存文字颜色
            float defaultStrokeWidth = paint.getStrokeWidth();

            //绘制圆角矩形
            paint.setColor(bgColor);
            paint.setStyle(Paint.Style.STROKE);
            paint.setStrokeWidth(5);
            paint.setAntiAlias(true);
            RectF rectF = new RectF(x + 2.5f, y + 2.5f + paint.ascent(), x + mSize, y + paint.descent());
            //设置文字背景矩形，x为span其实左上角相对整个TextView的x值，y为span左上角相对整个View的y值。
            // paint.ascent()获得文字上边缘，paint.descent()获得文字下边缘
            //x+2.5f解决线条粗细不一致问题
            canvas.drawRoundRect(rectF, mRadius, mRadius, paint);

            //绘制文字
            paint.setColor(textColor);
            paint.setStyle(Paint.Style.FILL);
            paint.setStrokeWidth(defaultStrokeWidth);
            canvas.drawText(text, start, end, x + mRadius, y, paint);//此处mRadius为文字右移距离

            paint.setColor(defaultColor);//恢复画笔的文字颜色
        }
    }`

**Comment by Blankj** [comment]
多行的可以吗

**Comment by Blankj** [comment]
不支持换行的话那么加边框那几个字要是正好在换行前后都有怎么办哈

**Comment by XXQAQ** [comment]
这个暂时无解，目前来说只适合小范围固定位置使用 ，大片范围的话我个人觉得其实自定义shape作为background更好

**Comment by Blankj** [comment]
边框这个我以前也自己写过，比你这个考虑得还多，可设置边框粗细还涉及到行高，单单 ReplacementSpan 是做不到的，但就是因为存在很多问题才不写进去的，我用了你的试过了，达不到我想要的效果，你觉得你这个可以的话那就调用我留的拓展 api `setSpan` 就行，下面是我用的示例：
```java
.appendLine("边框边框边框边框\n边框边框边框边框边框边框边框边框边框").setSpans(new RoundBackgroundColorSpan(Color.GREEN, Color.BLACK, 10))
```
