### ISSUE TITLE
为IntentUtils新增检查Intent是否可用的方法

### ISSUE THREAD

**Issue by XXQAQ** [Blankj/AndroidUtilCode#579]
实际使用中发现某些系统中无法使用Intent进行分享，建议为IntentUtils添加该方法用于检查intent是否可用

    /**
     * Check the Intent is Availeble
     *
     * @param intent The intent
     * @return is Availeble
     */
    public static boolean isIntentAvaileble(Intent intent){
        List resolves = getApp().getPackageManager().queryIntentActivities(intent,0);
        return resolves.size()>0;
    }

**Comment by Blankj** [comment]
```java
/**
 * Return whether the intent is available.
 *
 * @param intent The intent.
 * @return {@code true}: yes<br>{@code false}: no
 */
public static boolean isIntentAvailable(final Intent intent) {
    return Utils.getApp().getPackageManager().queryIntentActivities(intent, 0).size() > 0;
}
```
下版本加入吧，可以关注下个版本哦
