### ISSUE TITLE
导入项目报错

### ISSUE THREAD

**Issue by Power-Android** [Blankj/AndroidUtilCode#582]
Error:Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.blankj:utilcode:1.18.5
Could not get resource 'https://jcenter.bintray.com/com/blankj/utilcode/1.18.5/utilcode-1.18.5.aar'.
Could not HEAD 'https://jcenter.bintray.com/com/blankj/utilcode/1.18.5/utilcode-1.18.5.aar'.
Connect to localhost:63052 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Connection refused (Connection refused)

**Comment by Blankj** [comment]
看你这错误就是 gradle 走了本地代理  你自己好好查查吧

**Comment by Power-Android** [comment]
//common
            "gson"                              : "com.google.code.gson:gson:${version["gsonVersion"]}",
            "glide"                             : "com.github.bumptech.glide:glide:${version["glideVersion"]}",
            "glide_compiler"                    : "com.github.bumptech.glide:compiler:${version["glideVersion"]}",
            "eventbus"                          : "org.greenrobot:eventbus:3.1.1",
            "butterknife"                       : "com.jakewharton:butterknife:${version["butterknifeVersion"]}",
            "butterknife-compiler"              : "com.jakewharton:butterknife-compiler:${version["butterknifeVersion"]}",
            "BaseRecyclerViewAdapterHelper"     : "com.github.CymChad:BaseRecyclerViewAdapterHelper:${version["recyclerhelperVersion"]}",
//            "utilcode"                          : "com.blankj:utilcode:${version["utilcodeVersion"]}",

我导入别的三方都没问题，也没发现gradle有问题，求大佬指点。

**Comment by Blankj** [comment]
那是你本地有缓存了，你把其他库升级试下

**Comment by Power-Android** [comment]
刚升级了BaseRecyclerViewAdapterHelper2.9.34—2.9.40      没发现问题。

**Comment by Blankj** [comment]
去除我的依赖或者降低我的依赖的版本，同步后然后再升上来，再同步
或者加入我的 maven 仓库地址：https://dl.bintray.com/blankj/maven/com/blankj/utilcode/1.18.5/

**Comment by Power-Android** [comment]
奇怪，就是不能导入依赖（不知道问题出在哪，一直卡在请求aar包那里），已经手动copy到项目中，谢谢回复。

**Comment by Blankj** [comment]
检查下 gradle.properties 文件，项目里和用的 gradle 目录下面都看下，或者重启下电脑，翻墙试试？

**Comment by Power-Android** [comment]
你所说的我都试过啦，没有效果。很无奈

**Comment by Blankj** [comment]
新建项目导入呢

**Comment by Power-Android** [comment]
新建项目可以了，我等下再测试下老项目。

**Comment by Power-Android** [comment]
试了3个新老项目，导入依赖很快，很成功，很不知道说什么了，到底是为什么...只能用一句话形容，烤面筋，可带劲儿了！
