### ISSUE TITLE
finshActivity() 报了个异常

### ISSUE THREAD

**Issue by andyfun** [Blankj/AndroidUtilCode#584]
testlin 用脚本测试  我们调用了这个方法
public static void finishActivity(@NonNull final Class<?> clz) 

会抛出这个异常：
Caused by: java.util.ConcurrentModificationException
at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
 com.blankj.androidutilcode.util.ActivityUtils.finishActivity(ActivityUtils.java:136)
 com.blankj.androidutilcode.util.ActivityUtils.finishActivity(ActivityUtils.java:125)

**Comment by Blankj** [comment]
你这版本号是多少？ 好像很老的样子了
