### ISSUE TITLE
1.18.6加混淆项目崩溃

### ISSUE THREAD

**Issue by mnb65482** [Blankj/AndroidUtilCode#585]
1.18.6加混淆项目崩溃,加了去混淆如下，
-keep class com.blankj.utilcode.constant.{*;}
-keep class com.blankj.utilcode.util.{*;}
把代码去了混淆就好了

**Comment by mnb65482** [comment]
1.18.6加混淆项目崩溃,加了去混淆如下，
-keep class com.blankj.utilcode.constant.**{*;}
-keep class com.blankj.utilcode.util.**{*;}
把代码去了混淆就好了

**Comment by Blankj** [comment]
开混淆会崩吗？不用加防混就可以的的吧

**Comment by mnb65482** [comment]
是的，开混淆直接就崩溃，之前我用1.16.3没加防混淆没问题，昨天升级到1.18.6没加防混淆就崩了。

**Comment by Blankj** [comment]
看一下这个 https://juejin.im/post/5b6af5655188251a9e171de2  然后把混淆前的错误解析下
或者你试试 1.19.0
