### ISSUE TITLE
EncryptUtils RSA不支持256位加密解密

### ISSUE THREAD

**Issue by zhoumoumou123year** [Blankj/AndroidUtilCode#586]
使用256位的公钥密钥后报错，·EncryptUtils.decryptRSA()、EncryptUtils.encryptRSA() 希望增加对256位的加密解密支持。

**Comment by Blankj** [comment]
是你模式设置的问题吧，我这写的无论多长都可以加解密的，你再试试吧

**Comment by zhoumoumou123year** [comment]
首先我的公钥私钥没有问题，我用其他工具类试过可行。
我是按照测试用例写的：
`encryptData =  EncryptUtils.encryptRSA(data.getBytes(), EncodeUtils.base64Decode(Global.PUBLIC_KEY), true, "RSA/CBC/PKCS1Padding");
            byte[] decryData = EncryptUtils.decryptRSA(encryptData, EncodeUtils.base64Decode(Global.PRIVATE_KEY), false, "RSA/CBC/PKCS1Padding");`

这样运行会报错：
W/System.err: java.security.NoSuchAlgorithmException: No provider found for RSA/CBC/PKCS1Padding
W/System.err:     at javax.crypto.Cipher.createCipher(Cipher.java:919)
        at javax.crypto.Cipher.getInstance(Cipher.java:803)
        at com.blankj.utilcode.util.EncryptUtils.rsaTemplate(EncryptUtils.java:1088)
        at com.blankj.utilcode.util.EncryptUtils.encryptRSA(EncryptUtils.java:1009)

我想是模式的问题吧，我把最后一个参数改成了“RSA”, 不报错了，不过解出来的和原先的不一样。
然后我把测试用例的公钥私钥拿过来运行没问题，我的公钥私钥比测试用例的长一倍，你说跟长度没关系，那我也不知道咋回事了，求解。

**Comment by yuzhiqiang1993** [comment]
确实不支持RSA2，解密要么报错，要么不对，可以用下面两个key试一下
//        val publicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAichGTEP0QFswnvn+ZAQrgGHM8VeDZLJuezGhgxh4d9SyRUfnIW/zefT71rwS4bZUs1MPxJwavOyxABJOHLuckdHXknCsGEWz78gsA6D0+O+9dl1gCZR29nnN/NlzmNbSjFnzvsTJYBlS88qSr35RXFE+6DM7uPsS8Fm2I+65FteJ8p2yMvpSg72QkIX8xvI1F1uwXrciIB+4u7uTozxIplMOo4a6uhAm3W+Kjpz3ni2btjGqHRbqb3ebSZyl+nFfnjQaBe3XyVxAWDSanjgFj/wbqbeug9FBs+nQFVPIZR9z0aE5Ndi5o3eSkV7HFmWpkxaiPZ0BLRK3XHMaBtuSpwIDAQAB";
//        val privateKey = "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCJyEZMQ/RAWzCe+f5kBCuAYczxV4Nksm57MaGDGHh31LJFR+chb/N59PvWvBLhtlSzUw/EnBq87LEAEk4cu5yR0deScKwYRbPvyCwDoPT47712XWAJlHb2ec382XOY1tKMWfO+xMlgGVLzypKvflFcUT7oMzu4+xLwWbYj7rkW14nynbIy+lKDvZCQhfzG8jUXW7BetyIgH7i7u5OjPEimUw6jhrq6ECbdb4qOnPeeLZu2MaodFupvd5tJnKX6cV+eNBoF7dfJXEBYNJqeOAWP/Bupt66D0UGz6dAVU8hlH3PRoTk12Lmjd5KRXscWZamTFqI9nQEtErdccxoG25KnAgMBAAECggEBAIPz1b88ZTMtIgdejA7lH3Q4Nbn8gc1yRPSet3uBd/3rKT/IeMZBHQBzaqxgOgUIRV3n8nXsun6sf2b+IOjLlErimH2agnZMauL85YokH/g4QU6WZl9GXBf41xmMd3SsZ8AadaEBfYoXNqZcHtcLNogfFwvx5QRnD+A3SoRnH8OLBeVvOEe4AqHLT2xEZ9TeCf3fJe0Rf0fUIbw7I5ioiRZV/ir0L1VM7+1k2JODUkdC2Luj5Tl3nl1Eg6EmkYCmGE1bip1NAatsfjPBLMF7XdPNjLboiffjgKVBOjb7Y9vL18BCoLtWeTT2GkMpi5Sr94T1te1Ox77dF4BP33Xn7eECgYEA1TNUrAQsh14NbbkwFtUHXS8/YXt81p9wbSpFBymIawF2Lkk0913TB4CHSun45LhYXjdZZxK/TgqC5EIq5v2RA0jY3cSxoqVe6RZKB04E8wszeJHiEJPdu2vFnpZh9iAyhswiM5FmuKZKoWsVc2SZrBXAI02smSn3lXYok1VBS3sCgYEApXEZS6gjUu4o7ZL53Ur1HDfi/nxpkxqrPh+D1HVYjzjT+4vTeZwtLXt2VCInPWNXH+f11mzhxIrLkI0jMcSCah81DuU8aFXnqvPuyFvt9uaQBYlVWBtkcGZyeaxHFrbfCyeu0jm7SfwmiIg12hKlIHtPTjEZQUX+kkWr8cdaZ8UCgYEAh0Pl+K09QzVc97yC0jmeTnTnlYWvksvdnKUw3nZvYtSukndH75nLhfr524HOs+5xwnUDd+3hCjaJDSEd7yf5lUfmr+1XdoXNTb0igrfxU/JLWbfU4geuqnaaDyACTxHmfLePC4C413ZJ61fxaCDvjsrN+JgTZanGt0EcRT3WC3kCgYEAgf5/GMJxlw0JXbs515a5R8Xl9358Whj/at3KcRsPTeIiNqnkrc54dR9ol60KViMDZ0+VDDobn5pLXzZ26/jzXD1PLHgU4gp18Q6glhAdx/3cNm11gLhtUCA/XLlwVjm0wggZRpgUQIr/IBKe9c3mr8IUS2Uq6e38nKRf+adhst0CgYAM4tvl+U1MPbbz3YzDv8QPepZ7Pglgdfxqfr5OkXA7jNhqTZjSq10B6oClGvirBo1m6f26F02iUKk1n67AuiLlTP/RRZHi1cfq6P9IaXl23PcxJfUMvIxQDS0U+UTFpNXryTw/qNAkSfufN48YzKdGvc8vHrYJyaeemaVlbdJOCw==";

**Comment by Blankj** [comment]
@yuzhiqiang1993 你这公私钥都要 base64 解码之后才是真正的 data 啊

**Comment by yuzhiqiang1993** [comment]
当秘钥长度为2048时，解密时最大的字节数应该为2048/8=256,因此应该将1101行的   int maxLen = isEncrypt ? 117 : 128;  中的128修改为256即可，亲测解密成功。
参考：https://stackoverflow.com/questions/31944374/badpaddingexception-decryption-error

**Comment by Blankj** [comment]
最新版本已支持设置密钥长度。
