### ISSUE TITLE
适配上,横屏7.0版 ，切换全屏和非全屏时，上下两部分重叠了，都是180dp

### ISSUE THREAD

**Issue by i8vi** [Blankj/AndroidUtilCode#587]
适配上,横屏7.0版 ，切换全屏和非全屏时，上下两部分重叠了，都是180dp ，。。。。
就是不能截图，。。。郁。

**Comment by i8vi** [comment]
是的，改了下代码，把状态栏隐藏，或者做成沉浸式透明状态栏 切换全屏时，就不会重叠，

**Comment by Blankj** [comment]
有状态栏顶不上去当然会有重叠了哈，重叠高度就是状态栏高度。

**Comment by i8vi** [comment]
只是看了演示，你那个演示图没重，自己安装你的APK重了，就看了一下

**Comment by Blankj** [comment]
我之前做了算出状态栏高度然后让 180 减去一半的状态栏高度，所以没重叠的。

**Comment by i8vi** [comment]
安装了你的APK，在Genymotion 7.0 上测试，全屏切换时是重的，实体机上，测试也是重的，华为，
不知道是什么 原因，新版本的这个演示在切换时也自动减了一半状态栏的高度吗？

**Comment by Blankj** [comment]
你说是点了全屏后还重叠？还是非全非会有导航栏高度的重叠？

**Comment by i8vi** [comment]
全屏时无重，非全屏时重了状态栏高度，自己加了个 FLAG_LAYOUT_IN_SCREEN 无视了状态栏 ，重新编译，则有状态栏时就不重了。。。

**Comment by Blankj** [comment]
适配和状态栏没有啥关系的，反正能看出整个屏幕高度是你设置的 dp 那就是对的了哈。

**Comment by i8vi** [comment]
是的，我只是看了你简书上的那个演示动画，看到切换时从180P变成了168P，且无重，而下载APK演示时有重的，。。

**Comment by Blankj** [comment]
因为文章更新了很多版本，你要试验可以下载 1.18.0 的代码才是当时的代码哈，我再截图操作一遍比较麻烦，所以配图就不改了

**Comment by Blankj** [comment]
我最新的代码会改成下面这样，这样就可以不需要手动切换了，当时留着切换效果就是因为获取状态栏高度有问题，所以留着来调试，现在已经不需要了。
```java
    @Override
    public void initData(@Nullable Bundle bundle) {
        if (ScreenUtils.isPortrait()) {
            ScreenUtils.adaptScreen4VerticalSlide(this, 720);
        } else {
            ScreenUtils.setFullScreen(this);
            ScreenUtils.adaptScreen4HorizontalSlide(this, 720);
        }
    }
```

**Comment by i8vi** [comment]
EN,大神费心了。。。

**Comment by i8vi** [comment]
error: resource id/tv_fullscreen (aka com.blankj.androidutilcode:id/tv_fullscreen) not found.
Message{kind=ERROR, text=error: resource id/tv_fullscreen (aka com.blankj.androidutilcode:id/tv_fullscreen) not found., sources=[M:\AndroidUtilCode\app\src\main\res_core\layout-port\activity_screen_adapt.xml:11], original message=, tool name=Optional.of(AAPT)}

**Comment by Blankj** [comment]
忘记删除 view 点击代码了
```java
    public void toggleFullScreen(View view) {
        ScreenUtils.toggleFullScreen(this);
    }
```
