### ISSUE TITLE
手机连接扫描枪后  在editext设置隐藏软键盘  界面上隐藏了 但是扫码输入的时候会闪出来一下，然后又隐藏回去

### ISSUE THREAD

**Issue by DeveloperHu** [Blankj/AndroidUtilCode#589]
**Describe the bug**

**The version of utilcode: [e.g. 1.16.3]**

**The device: [e.g. Nexus 5X]**

**The version of device: [e.g. API 27]**

**The code:**
[e.g.
```java
CrashUtils.init();
```
]

**The stack of crash:**
[e.g.
```
```
]

**Screenshots**

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
这只能你自己调试来解决了哈，隐藏之后可能需要修改 Edittext 某些属性，看到底哪里出了问题。

**Comment by DeveloperHu** [comment]
好吧 谢谢大大 你的库很好用 谢谢你的复出
