### ISSUE TITLE
Android 6.0 使用EncryptUtils.encrypt3DES2Base64 方法报错

### ISSUE THREAD

**Issue by ChineseLincoln** [Blankj/AndroidUtilCode#59]
`javax.crypto.IllegalBlockSizeException: data not block size aligned `
我使用另外一段加密代码可以正常加密
代码如下
 
 public static byte[] des3EncodeCBC(byte[] key, byte[] keyiv, byte[] data)
            throws Exception {
        SecretKey deskey = null;
        DESedeKeySpec spec = new DESedeKeySpec(key);
        SecretKeyFactory keyfactory = SecretKeyFactory.getInstance("desede");
        deskey = keyfactory.generateSecret(spec);
        Cipher cipher = Cipher.getInstance("desede" + "/CBC/PKCS5Padding");
        IvParameterSpec ips = new IvParameterSpec(keyiv);
        cipher.init(Cipher.ENCRYPT_MODE, deskey, ips);
        byte[] bOut = cipher.doFinal(data);
        return bOut;
    }

猜测是因为代码中使用的DESede/ECB/NoPadding填充方式有不兼容的问题

**Comment by Blankj** [comment]
我sdk23测试怎么不报错的？

**Comment by ChineseLincoln** [comment]
可能我用的JDK版本是Java8

**Comment by ChineseLincoln** [comment]
可能我用的JDK版本是Java8

**Comment by ChineseLincoln** [comment]
好的 我改改看

**Comment by Blankj** [comment]
你可以看下这个
http://stackoverflow.com/questions/4062015/how-to-solve-javax-crypto-illegalblocksizeexception-data-not-block-size-aligned

**Comment by Blankj** [comment]
我方法是没问题的应该，你输入的数据对NoPadding有问题，你的data长度不是8的倍数吧

**Comment by ChineseLincoln** [comment]
额，好吧，我的数据长度的确不是8的倍数。
抱歉

**Comment by realchen** [comment]
我也遇到了这个问题，修改为8的倍数方法就可以。
但是我数据源长度是不一定的，我修改TripleDES_Transformation 值为DESede/ECB/PKCS5Padding
也还是不行
请问下你们是如何解决的?

**Comment by Blankj** [comment]
设置不同的模式和偏移量，这个你问问你们后台

**Comment by realchen** [comment]
谢谢大神回复，我这边对接的是第三方平台。并不是自己这边的后台，我再联系联系吧
