### ISSUE TITLE
建议增加日志大小

### ISSUE THREAD

**Issue by tvvbbb** [Blankj/AndroidUtilCode#591]
如题，如果日志到了一定的大小就删除之前的日志，或者是触发一个事件，这样可以让开发者决定是上传到服务器，还是删除，还有就是日志的切片，到达一定的大小就进行切片，方便打开

**Comment by Blankj** [comment]
日志暂不打算做这么复杂，不建议 release 还用 IO 频繁操作文件来写入日志，消耗内存，即便要用那也就是把关键性日志写入，所以不会很多，如果日志量大可以参考使用微信的 mars/xlog。
