### ISSUE TITLE
添加gradle失败

### ISSUE THREAD

**Issue by 15050050972** [Blankj/AndroidUtilCode#592]
使用时遇到如下问题：

Gradle sync failed: Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
		Could not determine artifacts for com.blankj:utilcode:1.19.0
		Could not get resource 'https://jcenter.bintray.com/com/blankj/utilcode/1.19.0/utilcode-1.19.0.aar'.
		Could not HEAD 'https://jcenter.bintray.com/com/blankj/utilcode/1.19.0/utilcode-1.19.0.aar'.
		Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/54.230.86.206, d29vzk4ow07wi7.cloudfront.net/54.230.86.33, d29vzk4ow07wi7.cloudfront.net/54.230.86.77, d29vzk4ow07wi7.cloudfront.net/54.230.86.64] failed: Read timed out
		Read timed out
		Consult IDE log for more details (Help | Show Log) (2m 3s 245ms)

在jcenter官网上，确实是打不开的。

**Comment by Blankj** [comment]
应该是网有问题 点击上面的链接应该是可以直接下载的，gradle 访问不到，可以添加我的 maven 仓库到 build.gradle 里 https://dl.bintray.com/blankj/maven/com/blankj/utilcode

**Comment by 15050050972** [comment]
在这个路径，https://dl.bintray.com/blankj/maven/com/blankj/utilcode/1.19.0/，点击那个aar文件，就无法下载。就是这个文件在android中报错

**Comment by Blankj** [comment]
那就是你网的问题，我这边是可以下载的，[这个 issue](https://github.com/Blankj/AndroidUtilCode/issues/582) 也有这问题，你可以参考下。

**Comment by 15050050972** [comment]
我用手机开了个热点，果然就好了。也不知道是为什么。
