### ISSUE TITLE
三星S8+ 使用ScreenUtils進行適配, Dialog顯示不完全

### ISSUE THREAD

**Issue by JyunTimLu** [Blankj/AndroidUtilCode#593]
**Describe the bug**
使用ScreenUtils適配後, 顯示alert dialog變成了下方左方的截圖, 右方是尚未加上適配程式碼的截圖

**The version of utilcode: 1.19.0**

**The device: Samsung Galaxy S8 Plus SM-G955F**

**The version of device: API 26*

**Screenshots**
<img src="https://user-images.githubusercontent.com/6395079/44022294-c9376c2c-9f19-11e8-8420-9df891bb5351.png" width="40%" /><img src="https://user-images.githubusercontent.com/6395079/44022373-fe3d6c64-9f19-11e8-94e8-78090792c75a.png" width="40%" />

**Comment by Blankj** [comment]
你传入的是 mdpi 尺寸的设计图宽度？你这问题应该是传入了高 dpi 的设计图尺寸，也就是调用 `ScreenUtils.adaptScreen4VerticalSlide(this, width);` width 值太小

**Comment by JyunTimLu** [comment]
好的~謝謝
