### ISSUE TITLE
CleanUtils.cleanInternalCache()后CacheDiskUtils数据无法写入

### ISSUE THREAD

**Issue by congjinruo** [Blankj/AndroidUtilCode#595]
**The version of utilcode: 1.18.3**
调用CleanUtils.cleanInternalCache();后，再去使用CacheDiskUtils出现数据无法写入的问题。
跟踪发现这个方法会删除cacheUtils这个文件夹，
而由于CACHE_MAP的存在，再去使用CacheDiskUtils.getInstance()并不会重新创建这个文件夹。
建议在CacheDiskUtils.getInstance().clear()中同时清空CACHE_MAP。
```java
public static CacheDiskUtils getInstance(@NonNull final File cacheDir,
                                             final long maxSize,
                                             final int maxCount) {
        final String cacheKey = cacheDir.getAbsoluteFile() + "_" + maxSize + "_" + maxCount;
        CacheDiskUtils cache = CACHE_MAP.get(cacheKey);
        if (cache == null) {
            if (!cacheDir.exists() && !cacheDir.mkdirs()) {
                throw new RuntimeException("can't make dirs in " + cacheDir.getAbsolutePath());
            }
            cache = new CacheDiskUtils(cacheKey, new DiskCacheManager(cacheDir, maxSize, maxCount));
            CACHE_MAP.put(cacheKey, cache);
        }
        return cache;
    }
```

**Comment by Blankj** [comment]
已修改为如下实现，建议你自己定义一个固定缓存路径用，用系统的话有些手机会不定时清理缓存导致缓存被清。
```java
public static CacheDiskUtils getInstance(@NonNull final File cacheDir,
                                         final long maxSize,
                                         final int maxCount) {
    final String cacheKey = cacheDir.getAbsoluteFile() + "_" + maxSize + "_" + maxCount;
    if (cacheDir.exists()) {
        CacheDiskUtils cache = CACHE_MAP.get(cacheKey);
        if (cache == null) {
            DiskCacheManager cacheManager = new DiskCacheManager(cacheDir, maxSize, maxCount);
            cache = new CacheDiskUtils(cacheKey, cacheManager);
            CACHE_MAP.put(cacheKey, cache);
        }
        return cache;
    }
    if (cacheDir.mkdirs()) {
        DiskCacheManager cacheManager = new DiskCacheManager(cacheDir, maxSize, maxCount);
        return CACHE_MAP.put(cacheKey, new CacheDiskUtils(cacheKey, cacheManager));
    } else {
        throw new RuntimeException("can't make dirs in " + cacheDir.getAbsolutePath());
    }
}
```

**Comment by congjinruo** [comment]
好的，非常感谢大佬的代码，帮了很多忙。

**Comment by Blankj** [comment]
1.19.1 已可用

**Comment by scsfwgy** [comment]
测试出来的其它问题

Exception in thread "Thread-3" Exception in thread "Thread-2" Exception in thread "Thread-1" Exception in thread "Thread-0" java.util.ConcurrentModificationException
	at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:440)
	at com.blankj.utilcode.util.CacheMemoryUtils.getInstance(CacheMemoryUtils.java:56)
	at com.blankj.utilcode.util.CacheMemoryUtils.getInstance(CacheMemoryUtils.java:42)
	at com.blankj.utilcode.util.CacheMemoryUtils.getInstance(CacheMemoryUtils.java:32)
	at com.blankj.utilcode.util.CacheDoubleUtils.getInstance(CacheDoubleUtils.java:36)



 @Test
    public void testCacheTest() {
        System.out.println("--------");
        for (int i = 0; i < 5; i++) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    CacheDoubleUtils instance = CacheDoubleUtils.getInstance();
                    Log.d(TAG, "run: "+instance);
                    System.out.println("---->"+instance);
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }).start();
        }
    }

**Comment by scsfwgy** [comment]
@Blankj  有可能是多进程的问题，之前在Application中初始化的时候没注意，realm、还有你这个工具类都出现了问题，并且一般都是在极光的推送进程中出现了此问题。你可以测试一下。我这边也在测试。
