### ISSUE TITLE
CacheMemoryUtils Parameters

### ISSUE THREAD

**Issue by scsfwgy** [Blankj/AndroidUtilCode#599]
`CacheMemoryUtils `
line:21:    
`private static final SimpleArrayMap<String, CacheMemoryUtils> CACHE_MAP = new SimpleArrayMap<>();`

Maybe the code is no usages,please check or What is the purpose of this?

    /**
     * Return the single {@link CacheMemoryUtils} instance.
     *
     * @param maxCount The max count of cache.
     * @return the single {@link CacheMemoryUtils} instance
     */
    public static CacheMemoryUtils getInstance(final int maxCount) {
        final String cacheKey = String.valueOf(maxCount);
        CacheMemoryUtils cache = CACHE_MAP.get(cacheKey);
        if (cache == null) {
            cache = new CacheMemoryUtils(cacheKey, new LruCache<String, CacheValue>(maxCount));
            CACHE_MAP.put(cacheKey, cache);
        }
        return cache;
    }

**Comment by Blankj** [comment]
都是国人哈，说中文就行，作用就是将多个单例缓存起来。

**Comment by scsfwgy** [comment]
哈哈哈，主要看reamdme都是英文的。我看了这一块的代码，有两点疑问：
1. 那意思就是根据“ maxCount”创建多个CacheMemoryUtils。我不知道这个的应用场景是啥。但是有这样的一种需求，业务上有需要缓存的数据类型：比较大的数据、中等类型的数据、只有几个字节的数据、bitmap类型等等，比如比较大的数据我想要缓存10个，bitmap缓存1000个，比较小的数据缓存也是1000个。想要不同的数据类型根据lru进行各自的管理。如果根据“ maxCount”实例化CacheMemoryUtils就会导致数量相同的数据类型被一起管理。能否添加一个key获取不同的CacheMemoryUtils，而不是根据“ maxCount”？
2. 对于缓存时间的处理，对于超时的缓存的并不会移除，而是在下一次取的时候返回默认值顺便移除缓存。这样的话如果缓存比较大的数据可能不太好。能否在每次get()任意缓存时都去检查一遍过期数据或者其它更好的策略？
@Blankj

**Comment by Blankj** [comment]
1. CacheMemoryUtils#getInstance 1.19.1 新增一个可传入自定义 cacheKey 的参数。
2. 没有什么更好的策略暂时。
