### ISSUE TITLE
可能需要添加的工具类方法

### ISSUE THREAD

**Issue by zhaoxiuyu** [Blankj/AndroidUtilCode#60]
时间相关→TimeUtils.java→Test , 可能需要添加的方法
1.两个时间相差距离多少天多少小时多少分多少秒
2.两个时间之间相差距离多少天
3.本月第一天
4.计算当月最后一天
5.根据日期计算当前是什么星座,返回如"天蝎座"
6.返回当前日期xxxx年x月xx日 星期x(得到当前的年月日和星期几)
7.毫秒换成几天前几小时几分钟 (通过毫秒数得到天数小时和分钟)
8.判断两个时间是否相等,比大小
9.将秒转换成小时分钟
10.date时间增加一秒 And 时间增減少一秒 返回得到的时间
12.当前时间增加一天 And 减少一天 返回得到的时间
13.当前时间增加一个月  And 减少一个月 返回得到的时间
14.两个日期相隔的天数

图片相关→ImageUtils.java
1.图片转bitmap
2.将一个image,做成毛玻璃再设置给view
3.Drawable转换成Bitmap
4.毛玻璃效果
5.重新计算图片的最大尺寸
6.按指定宽高截取中间一段图片
7.保存图片 
8.指定图片的切边,对图片进行圆角处理

正则相关→RegexUtils.java→Test
1.判断是否为整数
2.验证日期（年月日）
3.验证URL地址
4.匹配中国邮政编码

**Comment by Blankj** [comment]
你说的大部分我都有了，即使没有的话简单调一下也就出来了，
比如相距多少天调用getIntervalTime(time0, time1, TimeUnit.DAY)即可，很多方法都是组装一下就可以出来的，使用一下就知道是干嘛的了，单元测试用例很多的。
图片的话你说的我都有了，没看到的话那就是你不够仔细了。
正则的话isMatch(String regex, String string)可以判断任意的了，常用的都写在ConstUtils了
