### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by ffmpeg1** [Blankj/AndroidUtilCode#602]
implementation 'com.blankj:utilcode:1.19.0'

报以下错误
Error:Could not resolve all dependencies for configuration ':sofa:debugRuntimeClasspath'.
Could not determine artifacts for com.blankj:utilcode:1.19.0
Could not get resource 'https://jcenter.bintray.com/com/blankj/utilcode/1.19.0/utilcode-1.19.0.aar'.
Could not HEAD 'https://jcenter.bintray.com/com/blankj/utilcode/1.19.0/utilcode-1.19.0.aar'.
Software caused connection abort: recv failed

**Comment by Blankj** [comment]
网络的问题吧，换个环境试试可以
