### ISSUE TITLE
getMobileDataEnabled 出错

### ISSUE THREAD

**Issue by zhufengi** [Blankj/AndroidUtilCode#605]
**Describe the bug**
getMobileDataEnabled 没有打开移动数据时获取依然是true

**The version of utilcode: [e.g. 1.17.3]**

**The device: [e.g. OPPO R15]**

**The version of device: [e.g. API 27]**

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
试试 1.19.1 版本

**Comment by zhufengi** [comment]
这个版本还会有改动吗




| |
王小童
邮箱：zhufeng_l@126.com
|

签名由 网易邮箱大师 定制

在2018年08月23日 22:28，布兰柯基 写道：

试试 1.19.1 版本

**Comment by zhufengi** [comment]
我之前看了源码 好像没有改动 后面的版本




| |
王小童
邮箱：zhufeng_l@126.com
|

签名由 网易邮箱大师 定制

在2018年08月23日 22:34，andafeng 写道：
这个版本还会有改动吗




| |
王小童
邮箱：zhufeng_l@126.com
|

签名由 网易邮箱大师 定制

在2018年08月23日 22:28，布兰柯基 写道：

试试 1.19.1 版本

**Comment by Blankj** [comment]
今天刚发布的 1.19.1
