### ISSUE TITLE
调用修复软键盘内存泄漏（fixSoftInputLeaks ）内存依然泄漏

### ISSUE THREAD

**Issue by qianshengta** [Blankj/AndroidUtilCode#606]
'com.blankj:utilcode:1.19.0'

    @Override
    protected void onDestroy() {
        super.onDestroy();
        //修复软键盘内存泄漏
        KeyboardUtils.fixSoftInputLeaks(this);
    }
我在Activity调用onDestroy()的时候调用 KeyboardUtils.fixSoftInputLeaks(this);
但是Leaks依然会报InputMethodManager内存泄漏
![screenshot_2018-08-23-18-44-08](https://user-images.githubusercontent.com/29747624/44521200-df212800-a704-11e8-92d3-e61e7c5d7386.png)

**Comment by Blankj** [comment]
1.19.1 版本加入了 mLastSrvView 你可以再试试

**Comment by qianshengta** [comment]
试过了 依然是报内存泄漏  还有mLastSrvView 是什么？我在README里没找到这个方法？

**Comment by Blankj** [comment]
就是那个方法里我加入了对这个 view 滞空

**Comment by qianshengta** [comment]
好的 我明天上班的时候去试试看

**Comment by qianshengta** [comment]
@Blankj 大佬非常抱歉 关于之前的问题我忘记去测试了 最近我试了后发现1.19.1版本依然存在InputMethodManager内存泄漏
![screenshot_2018-08-28-18-51-11](https://user-images.githubusercontent.com/29747624/44718687-72869e80-aaf3-11e8-82de-4373f07a1e0d.png)
![screenshot_2018-08-28-18-51-06](https://user-images.githubusercontent.com/29747624/44718688-72869e80-aaf3-11e8-8118-a95905ec77a2.png)
![screenshot_2018-08-28-18-50-50](https://user-images.githubusercontent.com/29747624/44718689-731f3500-aaf3-11e8-9335-be23dcbec0ab.png)
![screenshot_2018-08-28-18-50-45](https://user-images.githubusercontent.com/29747624/44718690-73b7cb80-aaf3-11e8-859a-ae1d06baa0d0.png)

**Comment by Basakerone** [comment]
fixSoftInputLeaks中view.getContext() == context   按照程序正常启动会从SplashActivity到MainActivity，那么view.getContext()就是mainactivity,所以你永远执行不了 declaredField.set(imm, null);，但是如果你放开判断那么就会出现输入法不弹出得问题，这个希望有个好得解决办法。
