### ISSUE TITLE
建议：FileUtils.getFileSize(path)提供根据单位返回大小的方法

### ISSUE THREAD

**Issue by 3kqing** [Blankj/AndroidUtilCode#608]
1.FileUtils.getFileSize(path)提供根据单位返回大小的方法
2.提供根据单位比较大小的方法
例如：FileUtils.getFileSize(String path, enum unit)

**Comment by Blankj** [comment]
结合 `ConvertUtils#byte2MemorySize` 或者 `ConvertUtils#byte2FitMemorySize`
