### ISSUE TITLE
BarUtils里面关于透明度的设置

### ISSUE THREAD

**Issue by CJR10032** [Blankj/AndroidUtilCode#609]
透明度可以在设置颜色的时候就设置吧, #FF000000; 最前面那里就可以设置透明度, Android的色值是ARGB的; 然后就是...另外设置透明度也可以, 但是255是不透明, 0是全透明吧...应该没错吧. 结果看楼主的代码里面0是不透明...

**Comment by Blankj** [comment]
```java
private static int getStatusBarColor(final int color, final int alpha) {
    if (alpha == 0) return color;
    float a = 1 - alpha / 255f;
    int red = (color >> 16) & 0xff;
    int green = (color >> 8) & 0xff;
    int blue = color & 0xff;
    red = (int) (red * a + 0.5);
    green = (int) (green * a + 0.5);
    blue = (int) (blue * a + 0.5);
    return Color.argb(255, red, green, blue);
}
```

设置颜色的透明度这个你估计理解错了，设置到状态栏上的不是一个包含透明度的颜色，这里的计算颜色其实是为了模拟官方半透明的状态栏，你如果需要纯色那就设置 0 透明度就行了。

设置状态栏透明度就是你说的 0 是全透明，你可以下载 [APK] (https://github.com/Blankj/AndroidUtilCode/releases/download/1.19.2/util_1_19_2.apk) 来实验。
