### ISSUE TITLE
有关EncryptUtils的疑惑问答

### ISSUE THREAD

**Issue by Troll4it** [Blankj/AndroidUtilCode#611]
您好，看了下EncryptUtils里面的代码，发现很多加密方法都调用类似下面的方法   

private static String bytes2HexString(final byte[] bytes) {
        if (bytes == null) return "";
        int len = bytes.length;
        if (len <= 0) return "";
        char[] ret = new char[len << 1];
        for (int i = 0, j = 0; i < len; i++) {
            ret[j++] = HEX_DIGITS[bytes[i] >> 4 & 0x0f];
            ret[j++] = HEX_DIGITS[bytes[i] & 0x0f];
        }
        return new String(ret);
    }想问下，这样用意何在，有什么好处

**Comment by Blankj** [comment]
把 byte 转成字符串看哈，你见到的 MD5 什么的难道不是字符串吗

**Comment by Troll4it** [comment]
在详细的问下，知道是把byte转成字符串，但是为什么需要如此复杂，不是直接new String(byte)就可以了吗，这样有上面好处或者需要解决一些其他的问题，谢谢

**Comment by Blankj** [comment]
那你比较下两种结果看是否一样
