### ISSUE TITLE
请求权限时,背景黑屏,是怎么回事? PermissionUtils中

### ISSUE THREAD

**Issue by prczhb** [Blankj/AndroidUtilCode#612]
version 1.19.3

手机版本 小米6
ROM MIUI 9  9.6.3.0 
Android 版本 8.0

不止这个手机这种情况,其他手机也是.

![image](https://user-images.githubusercontent.com/26354648/44844648-13a16080-ac7e-11e8-9a9d-4c294c81228a.png)

![image](https://user-images.githubusercontent.com/26354648/44845016-f8832080-ac7e-11e8-8abc-3c74daee783b.png)

拿微信的权限请求和它做个对比,注意背景.

When requesting permission, the background is black, what is going on?
请求权限时,背景黑屏,是怎么回事?

可以使用demo里的权限工具进行场景重现
去掉应用中的所有权限,改为询问,然后点击权限请求,然后系统就蹦出权限请求弹窗,但是白色的dialog后是黑色的背景.并不是应用的背景图

**Comment by Blankj** [comment]
之前有个版本把 window 设置成了 @null，现在改回去了，用 1.19.4 版本即可
