### ISSUE TITLE
ToastUtils BUG

### ISSUE THREAD

**Issue by atoliu** [Blankj/AndroidUtilCode#618]
ToastUtils 在Redmi 5A  上无法显示 

版本1.19.4

Redmi 5A 

API 25 Android 7.1.2

为什么对 25 做特殊处理 
if (Build.VERSION.SDK_INT == Build.VERSION_CODES.N_MR1) {
            try {
                //noinspection JavaReflectionMemberAccess
                Field field = View.class.getDeclaredField("mContext");
                field.setAccessible(true);
                field.set(sToast.getView(), new ApplicationContextWrapperForApi25());
            } catch (Throwable throwable) {
                throwable.printStackTrace();
            }
        }
这段代码 导致 需要悬浮窗 权限

**Comment by Blankj** [comment]
连续显示多次 Toast 会导致崩溃在 25 版本
