### ISSUE TITLE
大佬是有时间帮我看看1.19.1版本的键盘内存泄漏还在。

### ISSUE THREAD

**Issue by qianshengta** [Blankj/AndroidUtilCode#621]
版本是1.19.1，我在我的Acitivity
    @Override
    protected void onDestroy() {
        super.onDestroy();
        //修复软键盘内存泄漏
        KeyboardUtils.fixSoftInputLeaks(this);
    }
调用修复软键盘内存泄漏，但是Leaks显示内存泄漏还在，上次这个问题我提过了，大佬你让我试试1.19.1
版本的，我因为工作忙就忘了没有回复，后来发现1.19.1内存泄漏还存在。
![screenshot_2018-09-04-20-08-13](https://user-images.githubusercontent.com/29747624/45030517-ac6d1d00-b07e-11e8-9e76-d328ce7d48d6.png)
![screenshot_2018-09-04-20-08-23](https://user-images.githubusercontent.com/29747624/45030521-b0993a80-b07e-11e8-8e9b-1f8d97a2ed3e.png)
![screenshot_2018-09-04-20-08-43](https://user-images.githubusercontent.com/29747624/45030529-b55dee80-b07e-11e8-8d59-91ce9a274ab9.png)

**Comment by zhxcryptic** [comment]
这个内存溢出我都忽略了,可以解决但是如果使用
startActivity(...);
finish();
这样会导致软键盘始终弹不出来 毕竟在onDestroy中调用了方法 只能是不用的地方调用 需要的地方不调用
```
public static void fixHwSoftInputLeaks(final Context context) {
        if (context == null) {
            return;
        }
        InputMethodManager imm = (InputMethodManager) context.getSystemService(Context.INPUT_METHOD_SERVICE);
        if (imm == null) {
            return;
        }
        Object obj_get = null;
        String[] fieldValues = new String[]{"mCurRootView", "mServedView", "mNextServedView", "mLastSrvView"};
        Field oomField = null;
        for (String fieldValue : fieldValues) {
            try {
                oomField = InputMethodManager.class.getDeclaredField(fieldValue);
                if (oomField == null) {
                    continue;
                }
                if (!oomField.isAccessible()) {
                    setFieldAccessible(oomField);
                }
                oomField.set(imm, null);
            } catch (Throwable e) {
            }
        }
    }

    private static void setFieldAccessible(final Field field) {
        AccessController.doPrivileged(new PrivilegedAction() {
            @Override
            public Object run() {
                field.setAccessible(true);
                return null;
            }
        });
    }
```

**Comment by Blankj** [comment]
你 StartActivity 做了什么，为何会和软键盘有关系？

**Comment by qianshengta** [comment]
账号密码输入

**Comment by qianshengta** [comment]
其实是 StartActivity上门的LoginFragment上账号密码输入，我是否应该在LoginFragment销毁的时候调用而不是他依赖的StartActivity

**Comment by Blankj** [comment]
我这没有华为手机测试，其他手机都是好的吗？你把你涉及的代码和布局写个 demo 出来，我再仔细分析下看我这是否可以复现出来，这样才能解决。

**Comment by qianshengta** [comment]
所有手机都是这样的，小米也一样

**Comment by Blankj** [comment]
那你给我个 demo 吧

**Comment by qianshengta** [comment]
好的，争取今晚给到，工作上有点忙

**Comment by qianshengta** [comment]
还有大佬你的RxBus还有也存在内存泄漏，时候CacheUtils相关的

**Comment by Blankj** [comment]
onDestroy 注销了吗？你确定是因为用了 RxBus 泄露的？

**Comment by qianshengta** [comment]
注销了，是用了RxBus，包名是com.blankj.rxbus 我去哪个githun提吧，随便截图

**Comment by Blankj** [comment]
你把用的相关代码片段截取下来，我看对不对

**Comment by Blankj** [comment]
怎么说？

**Comment by qianshengta** [comment]
我这里的Activity被泄露了，然后导致你那也同意内存泄漏了

**Comment by Blankj** [comment]
ok
