### ISSUE TITLE
是否在设置了白色状态栏之后，做了黑色字体的处理或者适配

### ISSUE THREAD

**Issue by tangxianqiang** [Blankj/AndroidUtilCode#623]
在有的app虽然大部分会有自己主题的状态栏颜色，但是总会添加白色背景色的状态栏的界面。遇到这样的需求我们希望工具类自动帮我们完成，仅仅在调用了设置白色状态栏的代码

**Comment by Blankj** [comment]
这就偏向业务了，白色状态栏 #FFFFFE 这肉眼看起来也是白色，这就需要根据你业务层自己设置了
