### ISSUE TITLE
Toast在努比亚手机上无发显示

### ISSUE THREAD

**Issue by scxiaoHou** [Blankj/AndroidUtilCode#626]
Toast在努比亚手机上无发显示

**Comment by Blankj** [comment]
api 25 吗？是的话需要弹框权限的。 不是的话你试试原生 toast 可以吗

**Comment by scxiaoHou** [comment]
是API 25 原生的Toast是可以的

**Comment by Blankj** [comment]
toast 在 api 25 有问题，所以需要修复，就用到了相关 hook，导致 toast 需要悬浮窗权限，你如果不想我这样的话那就自己再封装下。

**Comment by scxiaoHou** [comment]
好的 谢谢 我已经解决啦

**Comment by Blankj** [comment]
怎么解决啦？

**Comment by scxiaoHou** [comment]
我自己封装了一个  哈哈

**Comment by Blankj** [comment]
api 25  当心某些机型会出问题哈

**Comment by scxiaoHou** [comment]
恩恩 暂时没出问题 先用着哈哈

**Comment by Blankj** [comment]
升级到 1.20.2 试试最新版，我做了另一种方式
