### ISSUE TITLE
KeyboardUtils.fixAndroidBug5497 is not scrolling

### ISSUE THREAD

**Issue by alihabbash** [Blankj/AndroidUtilCode#628]
**Describe the bug**
I Use the KeyboardUtils.fixAndroidBug5497 to resize the activity UI when the soft key is shown/hidden
the method is working as expected but the UI cannot be scrolled.
I have a `scrollView` as root for my layout and the child is `ConstraintLayout` which contains the `TextInputLayout` elements which contains the `TextInputEditText`.

I put this `android:windowSoftInputMode="stateHidden|adjustResize"` to my activity tag in AndroidManifest.xml

**The version of utilcode: [e.g. 1.16.3]**
The version of utilcode is 1.19.3.
**The device: [e.g. Nexus 5X]**
Samsung j2 prime (Samsung Grand Prime plus).
**The version of device: [e.g. API 27]**
Android 6.0.1 API 23

**Screenshots**

in normal state:
[normal state](https://ibb.co/bAHJUp)

First `TextInputEditText` clicked:
[First input clicked](https://ibb.co/fry3vU)

Second`TextInputEditText` clicked:
[Second input clicked](https://ibb.co/fx8Q9p)

**Comment by Blankj** [comment]
update the version of library to newest, and delete the code of `android:windowSoftInputMode="stateHidden|adjustResize"`.
