### ISSUE TITLE
java.lang.NullPointerException Attempt to invoke virtual method 'void android.view.View.getWindowVisibleDisplayFrame(android.graphics.Rect)' on a null object reference

### ISSUE THREAD

**Issue by yanchengdeng** [Blankj/AndroidUtilCode#629]
1 com.blankj.utilcode.util.KeyboardUtils.getContentViewInvisibleHeight(Unknown Source)
--
2 com.blankj.utilcode.util.KeyboardUtils.access$100(Unknown Source)
3 com.blankj.utilcode.util.KeyboardUtils$1.onGlobalLayout(Unknown Source)

**Comment by Blankj** [comment]
update to 1.20.2 may help you.
