### ISSUE TITLE
KeyboardUtils.fixAndroidBug5497 Bug

### ISSUE THREAD

**Issue by moneeWong** [Blankj/AndroidUtilCode#634]
在含有底部导航栏的手机如华为 （honor 8，8.0版本）底部的栏会被顶上去
在全屏手机也也会有底部错乱（vivo y85）

**Comment by Blankj** [comment]
库什么版本？

**Comment by 13483865820** [comment]
最新的1.20.1

**Comment by 13483865820** [comment]
> 库什么版本？

最新的1.20.1

**Comment by Blankj** [comment]
截图发上来看下吧

**Comment by 13483865820** [comment]
![164564512555631885](https://user-images.githubusercontent.com/17845920/45398500-f786c180-b676-11e8-9f7f-038e472a47ae.jpg)
我发现好像是和一个状态栏的库冲突：https://github.com/yanzhenjie/Sofia

**Comment by 13483865820** [comment]
> 截图发上来看下吧

我发现好像是和一个状态栏的库冲突：https://github.com/yanzhenjie/Sofia
![164564512555631885](https://user-images.githubusercontent.com/17845920/45398706-c0fd7680-b677-11e8-918a-a26e509d683d.jpg)

**Comment by Blankj** [comment]
试试最新版  1.20.2
