### ISSUE TITLE
定位权限问题

### ISSUE THREAD

**Issue by zcychinese** [Blankj/AndroidUtilCode#638]
Android系统7.0，华为Honor8。
PermissionUtils.isGranted(PermissionConstants.LOCATION)，我的定位权限已经授权了，位置已经拿到，但是在后续使用中，用到了该方法，检测某权限是否授予，但是返回的是false。这是为什么呢？是因为版本的问题么，求大神告知。

**Comment by Blankj** [comment]
那就是系统 rom 和原生系统不太一致，国产的有自己修改过些什么，具体你可以取华为官网问问或者搜索下相关问题看其他人有没有类似问题

**Comment by BTFTUK** [comment]
@Blankj  高于6.0就返回false?
private static boolean isGranted(final String permission) {
        return Build.VERSION.SDK_INT < Build.VERSION_CODES.M
                || PackageManager.PERMISSION_GRANTED
                == ContextCompat.checkSelfPermission(Utils.getApp(), permission);
    }

**Comment by Blankj** [comment]
这是 小于 6.0 返回 true
