### ISSUE TITLE
Utils 的 getApplicationByReflect() 方法

### ISSUE THREAD

**Issue by QuincySx** [Blankj/AndroidUtilCode#639]
这个方法使用反射的方式获取 Application 不知道在 9.0 系统上会不会出问题

**Comment by Blankj** [comment]
只有 application 为空才会走到这一步，正常是不会走到的，所以不会有什么问题

**Comment by QuincySx** [comment]
我只是单纯讨论这块代码，没有说咱们软件逻辑

**Comment by Blankj** [comment]
android p-pre 版本反射 SDK api 会警告， p-beta 及 p 都会崩。

**Comment by Sopage** [comment]
这个方法不会被android P 限制，我测试是有没问题，android P的发布不实不让使用反射，而是一些系统关键api被禁止反射了，google有黑名单和灰名单，了解下
