### ISSUE TITLE
刚拉下来的代码demo跑起来很多崩溃的地方

### ISSUE THREAD

**Issue by gzpaiwxc** [Blankj/AndroidUtilCode#640]
刚拉下来的代码跑的demo有很多崩溃的，BarUtils Demo 崩溃，PermissionUtils Demo 崩溃，demo 对比以前的版本改动很大，但是不应该让这些崩溃的情况出现吧，崩溃的情况都是没有找到点击的方法(代码里边被注释掉了，把注释去掉却找不到跳转的目标类了)

**Comment by gzpaiwxc** [comment]
本来就是想测一下权限的工具类的，却发现 activity 都不见了

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases
