### ISSUE TITLE
English version of Update Log

### ISSUE THREAD

**Issue by thiagotalma** [Blankj/AndroidUtilCode#641]
Hello!

Your library is one of the most used, congratulations to the work.

What do you think about creating a log version in English?
Many of the users do not read Chinese 😉 

I am not native English speaker (I am Brazilian), but I agree that English has become an international language.
I like to follow the changelog of the projects I use, but in Chinese it gets complicated.

Thanks!!

**Comment by Blankj** [comment]
Ok, I will do it.
