### ISSUE TITLE
SpanUtils 设置行高导致不换行

### ISSUE THREAD

**Issue by yinxtno1** [Blankj/AndroidUtilCode#643]
## Describe the bug

- The version of utilcode: 1.20.3
- The device: 小米 4c
- The version of device: Android 7.0 MIUI10

## The code of bug
SpanUtils 设置行高导致不会换行，堆叠在一行
## The stack of crash
无
## Screenshots

![fs r h s l i 5ff 7a _ y](https://user-images.githubusercontent.com/19941667/45739441-9b4b1100-bc25-11e8-8e09-f285443c5f34.png)
![v9_4otua376gn8 ucdm g b](https://user-images.githubusercontent.com/19941667/45739469-aef67780-bc25-11e8-9033-f54fd27f3ff5.png)

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
试试最新版本，1.21.2，源码里曾经注释掉了 if 判断导致了这个原因
