### ISSUE TITLE
Vulnerability methods

### ISSUE THREAD

**Issue by romanpauesov** [Blankj/AndroidUtilCode#646]
Hi,
Antivirus Kaspersky Lab checked our app for vulnerability , and some methods is marked as Spy.Agent in your library;

> Packet contains dangerous methods, likes sendSmsSilent, captureWithStatusBar and words "u can't fuck me..."

We know, dirty phrase is resolved, but 1.20.* versions contains dangerous methods.
Also Eset NOD32 marked your code as dangerous.

**Comment by Blankj** [comment]
You can set `minifyEnabled true` to delete the useless code which contains dangerous methods.
