### ISSUE TITLE
设备上如果屏幕底部有虚拟按键栏，这个按键栏会覆盖视图，如何解决呢

### ISSUE THREAD

**Issue by jt1024** [Blankj/AndroidUtilCode#648]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
这和我库有什么关系？ 你可以设置导航栏透明度为 0 呢？
