### ISSUE TITLE
混淆配置

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#649]
- The version of utilcode: 1.20.3
- The version of device: API 26
请问混淆配置依旧是如下这些么?
-keep class com.blankj.utilcode.** { *; }
-keepclassmembers class com.blankj.utilcode.** { *; }
-dontwarn com.blankj.utilcode.**

我是从https://github.com/Blankj/AndroidUtilCode/issues/312 这里找到的混淆配置

**Comment by Blankj** [comment]
我这个库不用配置混淆的哈
