### ISSUE TITLE
可否再增加一个工具类

### ISSUE THREAD

**Issue by telenewbie** [Blankj/AndroidUtilCode#655]
可否增加一个工具类：用来修改域名服务器的方法

主要是因为：设备的域名服务器可能发生问题，所以想要强制去请求别的域名服务器，从而获取真实的IP地址。

问题是，再JavaAPI里面有javax这个库，而Android里面是没有的。所以不知道怎么实现。

**Comment by Blankj** [comment]
这个我也不清楚哈，无能为力
