### ISSUE TITLE
Request to add Rom recognition tool class

### ISSUE THREAD

**Issue by tcqq** [Blankj/AndroidUtilCode#658]
@Blankj Like this [RomUtils](https://www.jianshu.com/p/ba9347a5a05a).

**Comment by Blankj** [comment]
[RomUtils](https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/lib/src/main/java/com/blankj/utilcode/util/RomUtils.java) 1.23.4 版本已加入
