### ISSUE TITLE
能不能更新一个依赖，适配一下AndroidX的库导入

### ISSUE THREAD

**Issue by xiaoyvyv** [Blankj/AndroidUtilCode#663]
## Describe the bug

- The version of utilcode: 1.20.3
- The device: MI8
- The version of device: API 27 

## The code of bug

```java
![default](https://user-images.githubusercontent.com/29088158/46812557-89353c00-cda7-11e8-8bdf-47b6c88f0b79.png)

  FragmentUtils.add(manager, view.getGradeFragment(), view.getFragmentContainer().getId(), true);

```

```
![default](https://user-images.githubusercontent.com/29088158/46812460-5c812480-cda7-11e8-94f2-1c96c5eaf07d.png)

```

## The stack of crash

```
put the stack of crash here
```

## Screenshots
![default](https://user-images.githubusercontent.com/29088158/46812819-17a9bd80-cda8-11e8-9be0-1e62ddbc51cc.png)

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
你传入的是 androidx 的 fragment，这我太了解哈，它继承于什么的啊

**Comment by xiaoyvyv** [comment]
** 那个是谷歌今年重新发布的支持库，希望能适配一下 ** 

### 谷歌使用AndroidX代替Android支持库 #

** 新的Android扩展库  [AndroidX  ](https://www.jianshu.com/p/7dc111353328) 取代了使用七年之久的Android支持库。希望大佬适配一下 **

**Comment by Blankj** [comment]
adroidx 还在开发阶段  尚不稳定 暂时不打算搞进来  等后续稳定了我会考虑的

**Comment by van048** [comment]
神奇的是。虽然lint报错。但是可以打包成功。。

**Comment by Blankj** [comment]
@van048 是我某些工具类不支持 androidx，比如 FragmentUtils 支持的是 v4 里的，而不是 androidx 的哈，是这个意思。

**Comment by Blankj** [comment]
已发布 androidx 版本
