### ISSUE TITLE
setStatusBarAlpha支持4.0吗

### ISSUE THREAD

**Issue by Bruce8hou** [Blankj/AndroidUtilCode#664]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
支持的哈，就是从 api 19 开始支持的 可以参见 https://juejin.im/post/5981858a51882556437fb19a
