### ISSUE TITLE
用PermissionUtils 怎么申请Manifest.permission.REQUEST_INSTALL_PACKAGES？

### ISSUE THREAD

**Issue by candyguy242** [Blankj/AndroidUtilCode#667]
尝试使用PermissionUtils(Manifest.permission.REQUEST_INSTALL_PACKAGES)，编译却通不过，又不想修改源码和用反射，可有解决办法？

**Comment by Blankj** [comment]
这个权限不是运行时权限哦，相关运行时权限都在 PermissionConstant 哦

**Comment by candyguy242** [comment]
8.0系统上这个就成了运行时权限了，要安装apk，比如更新就得有这个权限。现在的初始化方法有注解限定了能传入的参数，这个不在注解限制的里面。

**Comment by Blankj** [comment]
直接调用 AppUtils.installApk 就行啊，具体操作看这个函数的注释，要添加你说的那个权限，不过不用动态申请

**Comment by candyguy242** [comment]
了解了，谢谢指点，不过这一步也是需要打开系统设置界面，让用户主动开启“安装未知来源”并获取结果的，可否提供一个类似的工具方法？

**Comment by Blankj** [comment]
我不了解这方面，你要是找到能设置的可以告诉我

**Comment by candyguy242** [comment]
请参考这篇：https://blog.csdn.net/qq_30889373/article/details/79643319
谢谢大神~~

**Comment by Blankj** [comment]
这需要你自己组装了，先允许未知应用安装，允许之后再调用我的工具类即可。我一个函数做不到这么一条龙的

**Comment by candyguy242** [comment]
只是觉得这一步申请安装的也是常用操作，并且也可以工具类化~

**Comment by candyguy242** [comment]
跟现在的方法类似，做一个假的完全透明的Activity作为代理去申请，调用的地方只用回调来处理相应结果即可~

**Comment by candyguy242** [comment]
或者完全可以在现有基础上进行扩展，因为申请权限的流程类似，无非是系统弹窗，或者是系统弱出一个页面来确认而已。
