### ISSUE TITLE
ZipUtils解压有中文报错

### ISSUE THREAD

**Issue by pengbs** [Blankj/AndroidUtilCode#669]
您好，使用ZipUtils解压zip包的时候，如果压缩包里面目录有中文命名的，会报异常java.lang.IllegalArgumentException: MALFORMED[1]

**Comment by Blankj** [comment]
https://blog.csdn.net/aitangyong/article/details/40430467 看一下这篇文章，windows 下编码问题，你指定 utf8 即可

**Comment by Blankj** [comment]
我这边修改为 ZipFile(File file, Charset charset) api要 24 才支持，所以你考虑自己修改下编码吧

**Comment by iBotasky** [comment]
@pengbs @Blankj 
嗯嗯，我也遇到这个问题，有没有什么方法可以获取他的编码格式吗？我找了半天没有找到办法。
或者请问有没有其他比较好的解决方案呢？

**Comment by Blankj** [comment]
rename 为全英文，再解压，再 rename 回去
