### ISSUE TITLE
工具类应该是没有判断设备是否打开开发者选项的工具类!!!可否考虑增加一个!!!

### ISSUE THREAD

**Issue by lydlovezjr** [Blankj/AndroidUtilCode#670]

**Comment by Huazhiling** [comment]
public static boolean getADBEnabled() {
        return Settings.Secure.getInt(context.getContentResolver(), Settings.Global.ADB_ENABLED, 0) > 0;
    }

**Comment by Blankj** [comment]
最新版本 1.21.0 在 DeviceUtils#isAdbEnabled
