### ISSUE TITLE
NetworkUtils报null异常

### ISSUE THREAD

**Issue by tvvbbb** [Blankj/AndroidUtilCode#671]
版本：implementation 'com.blankj:utilcode:1.19.0'
异常信息：
at com.blankj.utilcode.util.NetworkUtils.isWifiConnected(NetworkUtils.java:229)

在最新的版本有解决了么？

**Comment by Blankj** [comment]
你说清楚下哪里空指针？

**Comment by tvvbbb** [comment]
这个就是错误信息，行数都有了，但要回到对应的版本

**Comment by Blankj** [comment]
这是 1.19.0 版本的源码，229 看不出来会空指针的把
![image](https://user-images.githubusercontent.com/17978187/47058455-b34b8b80-d1f7-11e8-8842-37fa2250b4fc.png)

**Comment by tvvbbb** [comment]
我也看不出会有空指针，但日志报了这个错误。

**Comment by tvvbbb** [comment]
10:25:26.712 E   java.lang.NullPointerException
	at com.blankj.utilcode.util.NetworkUtils.isWifiConnected(NetworkUtils.java:237)
还是会报错，也是null的问题
