### ISSUE TITLE
rt

### ISSUE THREAD

**Issue by cervy** [Blankj/AndroidUtilCode#672]
运行编译时Android studio3.2.1：最新版

Execution failed for task ':acadsocbyapp:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\a\.gradle\caches\modules-2\files-2.1\com.blankj\bus\1.0\5301ffd634fa654db5d21487eaacc64563750abe\bus-1.0.jar' 
to
 'F:\Project\xxxx\build\intermediates\transforms\dex\debug\folders\1000\10\bus-1.0_4ba049a44ddaccf0834ec0ab6abe666fd8864020'

**Comment by Blankj** [comment]
我这边没问题的哦，你新建个项目试试？
