### ISSUE TITLE
Monkey测试com.blankj.utilcode.util.NetworkUtils.isAvailableByPing 导致应用ANR

### ISSUE THREAD

**Issue by hxmeie** [Blankj/AndroidUtilCode#676]
java.lang.Object.wait!
(waiting on <0x04f3f945> (a java.lang.Object))
java.lang.ProcessManager$ProcessImpl.waitFor (ProcessManager.java)
(locked <0x04f3f945> (a java.lang.Object))
com.blankj.utilcode.util.ShellUtils.execCmd (unavailable)
com.blankj.utilcode.util.ShellUtils.execCmd (unavailable)
com.blankj.utilcode.util.NetworkUtils.isAvailableByPing (unavailable)
com.blankj.utilcode.util.NetworkUtils.isAvailableByPing (unavailable)
com.yicaihui.credit.net.manager.NetException.throwable (NetException.java)
com.yicaihui.credit.net.manager.BaseObserver.onError (BaseObserver.java)
io.reactivex.internal.observers.BasicFuseableObserver.onError (BasicFuseableObserver.java)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated (ObservableObserveOn.java)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal (ObservableObserveOn.java)
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run (ObservableObserveOn.java)
io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java)
android.os.Handler.handleCallback (Handler.java)
android.os.Handler.dispatchMessage (Handler.java)
android.os.Looper.loop (Looper.java)
android.app.ActivityThread.main (ActivityThread.java)
java.lang.reflect.Method.invoke!
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java)

**Comment by Blankj** [comment]
这个是要异步的哈
