### ISSUE TITLE
AppUtils.relaunchApp();需要加什么前奏吗，直接调会跳一针黑屏再重启

### ISSUE THREAD

**Issue by zhufengi** [Blankj/AndroidUtilCode#679]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```java
AppUtils.relaunchApp();
```

## The stack of issue

```
重启前会先跳一阵黑屏再重启
```

**Comment by Blankj** [comment]
```java
/**
 * Relaunch the application.
 */
public static void relaunchApp() {
    relaunchApp(false);
}
/**
 * Relaunch the application.
 *
 * @param isKillProcess True to kill the process, false otherwise.
 */
public static void relaunchApp(final boolean isKillProcess) {
    PackageManager packageManager = Utils.getApp().getPackageManager();
    Intent intent = packageManager.getLaunchIntentForPackage(Utils.getApp().getPackageName());
    if (intent == null) return;
    intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
    Utils.getApp().startActivity(intent);
    if (!isKillProcess) return;
    android.os.Process.killProcess(android.os.Process.myPid());
    System.exit(0);
}
```
下版本代码会改成这样

**Comment by zhufengi** [comment]
我自己也写了两种




| |
王小童
邮箱：zhufeng_l@126.com
|

签名由 网易邮箱大师 定制

在2018年10月25日 20:13，布兰柯基 写道：
/** * Relaunch the application.*/publicstaticvoid relaunchApp() {
    relaunchApp(false);
}
/** * Relaunch the application. * * @param isKillProcess True to kill the process, false otherwise.*/publicstaticvoid relaunchApp(finalboolean isKillProcess) {
    PackageManager packageManager =Utils.getApp().getPackageManager();
    Intent intent = packageManager.getLaunchIntentForPackage(Utils.getApp().getPackageName());
    if (intent ==null) return;
    intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
    Utils.getApp().startActivity(intent);
    if (!isKillProcess) return;
    android.os.Process.killProcess(android.os.Process.myPid());
    System.exit(0);
}

下版本代码会改成这样
