### ISSUE TITLE
CloseUtils has a problem?

### ISSUE THREAD

**Issue by DanielYP** [Blankj/AndroidUtilCode#68]
`public static void closeIO(Closeable... closeables) {
        if (closeables == null) return;
        try {
            for (Closeable closeable : closeables) {
                if (closeable != null) {
                    closeable.close();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }`
change to 
`public static void closeIO(Closeable... closeables) {
        if (closeables == null) return;
            for (Closeable closeable : closeables) {
            if (closeable != null) {
               try{
                     closeable.close();
                   }
              }catch(IOException e){
                    e.printStackTrace();
                    continue;
              }
           }
    }`

**Comment by Blankj** [comment]
thx for ur issues, I will fix it in next version,

**Comment by DanielYP** [comment]
:)
