### ISSUE TITLE
ToastUtils 关闭通知栏权限无法显示toast

### ISSUE THREAD

**Issue by CaojingCode** [Blankj/AndroidUtilCode#682]
## Describe the bug

- The version of utilcode:  1.21.1 
- The device: 华为P20
- The version of device: android 8.1

## The code of bug
android 8.0以上谷歌把toast加入通知栏权限，如果关闭通知，将不能显示toast,能不能把ToastUtils修改一下兼容8.0

**Comment by Blankj** [comment]
这个做不到的，谷歌对 API 25 及以上的 Toast 类型的悬浮窗权限做了限制，所以我这边只能做到小于 25 可以无条件显示
