### ISSUE TITLE
LocationActivity  LocationService 定位成功了 也回调了 但是 UI刷新有很大概率失败

### ISSUE THREAD

**Issue by chuwe1** [Blankj/AndroidUtilCode#684]
一直都没有定位成功的回调我试了两部手机 nubia z11 和 samsung s9

  @Override
        public void onServiceConnected(ComponentName name, IBinder service) {
            mLocationService = ((LocationService.LocationBinder) service).getService();
            mLocationService.setOnGetLocationListener(new LocationService.OnGetLocationListener() {
                @Override
                public void getLocation(final String lastLatitude, final String lastLongitude, final String latitude, final String longitude, final String country, final String locality, final String street) {
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            tvAboutLocation.setText(new SpanUtils()
                                    .appendLine("lastLatitude: " + lastLatitude)
                                    .appendLine("lastLongitude: " + lastLongitude)
                                    .appendLine("latitude: " + latitude)
                                    .appendLine("longitude: " + longitude)
                                    .appendLine("getCountryName: " + country)
                                    .appendLine("getLocality: " + locality)
                                    .appendLine("getStreet: " + street)
                                    .create()
                            );
                        }
                    });
                }
            });
        }

这一段代码 调试大断电 执行到了UI就会刷新 但是吧debug断开正常运行 这里不执行 UI没有变化。
我的机器samsung s9/ nubia z11 都是这样

**Comment by Blankj** [comment]
用第三方的吧，原生的太差了哈，具体咋回事我也不清楚哈

**Comment by chuwe1** [comment]
搜嘎。。。。。 兄得 去 鸿洋wanandroid 加个友链啊
