### ISSUE TITLE
Unable to delete file: E:\test\AndroidUtilCode\app\build\intermediates\transforms\busTransform\debug\7.jar

### ISSUE THREAD

**Issue by BoyYangyang** [Blankj/AndroidUtilCode#685]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
重新拉下代码哈，或者把根目录 build.gradle 文件中 bus 插件从 1.0 升级到 1.3，之前在 windows 系统有点问题。
