### ISSUE TITLE
android8.0Toast需要开启通知权限

### ISSUE THREAD

**Issue by wangzipei** [Blankj/AndroidUtilCode#686]
在8.0的系统以上需要开启通知权限才能使用toast，大牛能不能兼容一下这方面的问题

**Comment by lydlovezjr** [comment]
不用吧,大兄弟!!!我这荣耀8.1什么权限都没开,可以正常弹出toast!!!

**Comment by Blankj** [comment]
8.0 是需要悬浮窗权限的，Toast 没权限你做不到的
