### ISSUE TITLE
studio 3.2.1 无法编译

### ISSUE THREAD

**Issue by tianshaokai** [Blankj/AndroidUtilCode#688]
Failed to transform file 'android.jar' to match attributes {artifactType=android-mockable-jar, returnDefaultValues=false} using transform MockableJarTransform

**Comment by Blankj** [comment]
windows系统？

**Comment by tianshaokai** [comment]
mac os 10.13.6

**Comment by Blankj** [comment]
我最新工程的代码吗

**Comment by Zziv** [comment]
osx10.13.6  as 3.2.1  依赖失败

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.blankj:utilcode:1.21.2.

**Comment by tianshaokai** [comment]
是的，最新的代码

**Comment by Blankj** [comment]
@tianshaokai 把  id "com.blankj.bus" 注释掉试试

**Comment by Blankj** [comment]
@Zziv 网络问题吧？开个 vpn 试试？

**Comment by Zziv** [comment]
@Blankj 同一个网络下 window依赖是没问题的

**Comment by tianshaokai** [comment]
Could not get unknown property 'generateReleaseBuildConfig' for root project 'AndroidUtilCode' of type org.gradle.api.Project.

**Comment by Blankj** [comment]
@tianshaokai 拉下最新的哈

**Comment by tianshaokai** [comment]
你的studio是什么版本，我studio 3.2.1就一直无法编译

**Comment by Blankj** [comment]
我一直都是最新的哈 也是 3.2.1

**Comment by tianshaokai** [comment]
我已经改好了
 compileSdkVersion = 28
targetSdkVersion = 28
support_version = '28.0.0'
![image](https://user-images.githubusercontent.com/6706496/48108667-f93bc280-e27e-11e8-969d-790165dc4173.png)
![image](https://user-images.githubusercontent.com/6706496/48108687-0eb0ec80-e27f-11e8-9c39-e0d8e4687a66.png)

**Comment by tianshaokai** [comment]
要不就死活编译不过去

**Comment by tianshaokai** [comment]
我是mac os，stuido 3.2.1，jdk 1.8

**Comment by 490965536** [comment]
> 我已经改好了
> compileSdkVersion = 28
> targetSdkVersion = 28
> support_version = '28.0.0'
> ![image](https://user-images.githubusercontent.com/6706496/48108667-f93bc280-e27e-11e8-969d-790165dc4173.png)
> ![image](https://user-images.githubusercontent.com/6706496/48108687-0eb0ec80-e27f-11e8-9c39-e0d8e4687a66.png)

我也是遇见这个错误, 改了编译器,编译版本, 还是不行,,, 一直报这个错... 试了很多了  clean cleanbuildcache  sync , invalidate等都不行....

**Comment by liuxujian** [comment]
我也是同样的问题，但是退回到到1.21.2就可以  正常编译  
implementation 'com.blankj:utilcode:1.21.2'
我现在使用的就是1.21.2
