### ISSUE TITLE
Android 9刘海屏下，获取状态栏高度错误

### ISSUE THREAD

**Issue by tcqq** [Blankj/AndroidUtilCode#689]
问题描述：
-
@Blankj 当使用Pixel 3 XL隐藏刘海后，状态栏的高度会变小，但是使用当前的方法获取状态栏的高度不会更新，获取的高度还是没隐藏刘海之前的高度。

设备：Pixel 3 XL
Android 版本：9

代码：
-

当前获取状态栏高度代码：
```
    public static int getStatusBarHeight() {
        Resources resources = Resources.getSystem();
        int resourceId = resources.getIdentifier("status_bar_height", "dimen", "android");
        return resources.getDimensionPixelSize(resourceId);
    }
```

修复后获取状态栏高度代码：
```
    private fun getStatusBarHeight(context: Context): Int {
        try {
            var result = 0
            val resourceId = context.resources.getIdentifier("status_bar_height", "dimen", "android")
            if (resourceId > 0) {
                result = context.resources.getDimensionPixelSize(resourceId)
            }
            return result
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return 0
    }
```
修复后截图：
-
![tim 20181101065001](https://user-images.githubusercontent.com/10644057/47823275-81632900-dda2-11e8-893e-b55d7ee815eb.png)![tim 20181101064241](https://user-images.githubusercontent.com/10644057/47823229-39440680-dda2-11e8-8028-139986fa3e7b.png)![tim 20181101064245](https://user-images.githubusercontent.com/10644057/47823232-3a753380-dda2-11e8-9bdf-587c4feccd1c.png)

**Comment by Blankj** [comment]
模拟器还是真机？

**Comment by Blankj** [comment]
最新代码已支持

**Comment by wanghaibao123** [comment]
升级了最新代码，还是有这个问题了
