### ISSUE TITLE
FileUtils.getFileMD5 oom

### ISSUE THREAD

**Issue by scrat000** [Blankj/AndroidUtilCode#69]
FileUtils.getFileMD5  处理大文件，报内存溢出。
建议EncryptUtils.encryptMD5File中使用：
`
public static byte[] encryptMD5File(File file) {
        if (file == null) return null;
        FileInputStream fis = null;
        DigestInputStream digestInputStream = null;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            fis = new FileInputStream(file);
            digestInputStream = new DigestInputStream(fis, md);
            byte[] buffer = new byte[256 * 1024];
            while (digestInputStream.read(buffer) > 0) ;
            // 获取最终的MessageDigest
            md = digestInputStream.getMessageDigest();
            return md.digest();
        } catch (NoSuchAlgorithmException | IOException e) {
            e.printStackTrace();
            return null;
        } finally {
            CloseUtils.closeIO(fis);
        }
    }
`

**Comment by Blankj** [comment]
下个版本修正哈

**Comment by Blankj** [comment]
你的是多大的文件？

**Comment by Blankj** [comment]
这个确实是最快的

**Comment by scrat000** [comment]
几十MB吧，对文件MD5

**Comment by Blankj** [comment]
我几百兆，几个G的都测了，就这个digestInputStream 最快

**Comment by scrat000** [comment]
是android平台上测的吗？不要忽略内存限制

**Comment by Blankj** [comment]
这个只依赖java层，所以单元测试一下就可以了，再说算这个MD5码不应该放在异步么
