### ISSUE TITLE
检查相机权限的疑问

### ISSUE THREAD

**Issue by sangsais** [Blankj/AndroidUtilCode#691]
使用PermissionUtils在vivoy75这台测试机上，一直进入onGranted，事实上权限是被禁止的
是我使用的方式不对还是有什么使用差异，还望告知下。

implementation 'com.blankj:utilcode:1.20.4'
vivoy75A     
7.1.1 
rom funtouch os 3.2

代码段：
private void checkPermiss() {
        LogUtils.e("animation");
        PermissionUtils.permission(PermissionConstants.CAMERA)// STORAGE // PHONE
                .rationale(new PermissionUtils.OnRationaleListener() {
                    @Override
                    public void rationale(final ShouldRequest shouldRequest) {
                        LogUtils.e("Permission", "rationale");
                        shouldRequest.again(true);
                    }
                })
                .callback(new PermissionUtils.FullCallback() {
                    @Override
                    public void onGranted(List<String> permissionsGranted) {
                        LogUtils.e("Permission", "onGranted");
                        if (null != networkUnstableDialog) {
                            networkUnstableDialog.dismiss();
                        }
                    }

                    @Override
                    public void onDenied(List<String> permissionsDeniedForever,
                                         List<String> permissionsDenied) {
                        showPermissionDialog();
                        LogUtils.e("Permission", "onDenied");
                    }
                })
                .theme(new PermissionUtils.ThemeCallback() {
                    @Override
                    public void onActivityCreate(Activity activity) {
                        ScreenUtils.setFullScreen(activity);
                    }
                })
                .request();
    }

**Comment by Blankj** [comment]
国产机 你自己做兼容只能 搞不过来的那么多

**Comment by sangsais** [comment]
@Override
    protected void onRestart() {
        super.onRestart();
        checkPermiss();

        if (Build.BRAND.equals("vivo")) {
            if (!isHasPermission()) {
                showPermissionDialog();
            }
        }
    }
private boolean isHasPermission() {
        Field fieldPassword = null;
        try {
            Camera camera = Camera.open();
            fieldPassword = camera.getClass().getDeclaredField("mHasPermission");
            fieldPassword.setAccessible(true);
            return (boolean) fieldPassword.get(camera);
        } catch (Exception e) {
            e.printStackTrace();
            return true;
        }

    }

我暂时这样处理 我只试了一台vivo不知兼容性怎样

**Comment by s8cm** [comment]
360N6pro 表示一模一样的问题，某些国产机瞎几把改api接口
