### ISSUE TITLE
运行时权限，代码直接复制粘贴Demo的，在onResume里调用的话rationale会一直回调，去掉rationale的话onDenied就会一直回调，MI5手机，8.0

### ISSUE THREAD

**Issue by jiapengtao** [Blankj/AndroidUtilCode#692]

**Comment by Blankj** [comment]
我的库你也是复制的吗

**Comment by jiapengtao** [comment]
AndroidStudio的gradle里依赖的，我监听button试过了，没有问题的。但是放在onCreate里然后拒绝授权的话不走rationale的回调，我又放到onResume里，这次正好相反，疯狂走rationale回调，我干脆不要这个回调了，然后试了下，又不停的走onDenied回调，我想是不是源码有个循环的代码块有问题，然后顺着源码找，找不到。

**Comment by jiapengtao** [comment]
对了，我把你的DialogHelper类单独拿出来使用了，因为不停回调的原因，dialog一直被创建弹出来，一分钟不到我的测试机就自动重启了

**Comment by Blankj** [comment]
那么我的 Demo 呢，你试试看会有这种情况不，自己比对下哈，拷出类还是会有区别的哦

**Comment by Blankj** [comment]
我 Utils 代码里有对 PermissionActivity 操作哦
