### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by jacksPeak** [Blankj/AndroidUtilCode#693]
版本：1.21.2
请问最新版没有混淆规则么？为什么我开启混淆后有很多没有用到的类也都被打包进了 apk 包

![image](https://user-images.githubusercontent.com/13911593/47914204-adcd9100-ded9-11e8-97f7-0084ffbf2b59.png)

![image](https://user-images.githubusercontent.com/13911593/47914236-ca69c900-ded9-11e8-917b-62744a3d38c4.png)

**Comment by Blankj** [comment]
看你防混淆里是不加了我的库 我没做任何配置

**Comment by jacksPeak** [comment]
我逐行检查了自己所有的混淆文件里并没有关于你库的代码，你的库不需要混淆规则麽？我记得之前的版本你会在 README 里提到关于混淆你有自己的规则的，后来的版本没有看到这句话了。是不是 连锁 引用导致混淆时以为用到了其他不相关代码导致代码保留了呢

**Comment by Blankj** [comment]
那是防混淆规则，加了才会保留下来，我的库没用到反射的东西，所以不用混淆

**Comment by Blankj** [comment]
不信你可以创建个 demo 试试

**Comment by jacksPeak** [comment]
刚创建了一个 Demo 试了一下，开启混淆后只保留了 Utils 和 PermissionUtils 没有问题的。我的项目中有可能就是有 连锁 引用了，我回头查一下~
