### ISSUE TITLE
为了使用LocationUtils 我几乎复制了你全部的工具类. 各个工具类之间耦合太严重,希望能推出一个library

### ISSUE THREAD

**Issue by sunjiaxin** [Blankj/AndroidUtilCode#695]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
你依赖的版本很老吧，LocationUtils 是一个独立的类在 [subutil](https://github.com/Blankj/AndroidUtilCode/tree/master/subutil) 下面，推荐还是用第三方的定位比较好。
