### ISSUE TITLE
getActivityLifecycle 方法会失效 1.20.4

### ISSUE THREAD

**Issue by open9527** [Blankj/AndroidUtilCode#698]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by open9527** [comment]
目前判断和接入Bugly接入有影响.

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/issues/702
