### ISSUE TITLE
网络类型判断相关

### ISSUE THREAD

**Issue by ssyijiu** [Blankj/AndroidUtilCode#7]
https://github.com/ssyijiu/android-helper/blob/master/utils/NetUtil.java  判断网络类型2G、3G、4G、WIFI，感觉这个更谨慎一些，仅供参考。这个项目中其他utils有错误，谨慎观看。

**Comment by Blankj** [comment]
代码需要一个迭代过程的啊，有错误帮忙提一下，一起修复哈

**Comment by Blankj** [comment]
已参照修改完毕
