### ISSUE TITLE
Manifest merger faild

### ISSUE THREAD

**Issue by Kent-GitHub** [Blankj/AndroidUtilCode#70]
是不是可以删掉AndroidManifest文件application 的label标签 ，
如果项目里的application的label@的string不是app_name，会出现Manifest merger faild

**Comment by Blankj** [comment]
你是说我这个项目里的吗

**Comment by Kent-GitHub** [comment]
是滴

**Comment by Kent-GitHub** [comment]
嗯，去掉您项目的Application的label，
如果我的项目的Application的label@的string不是app_name，
比如   android:label="@string/my_app_name"  ，
就会出现Manifest merger faild的问题。

**Comment by Blankj** [comment]
我照着你说的那样做可以运行啊

**Comment by Kent-GitHub** [comment]
问题已经解决。。。
https://my.oschina.net/u/232595/blog/519131

**Comment by Blankj** [comment]
所以不是我的问题喽

**Comment by jp1017** [comment]
一般库里的清单就一个包名就可以了，比如：

```
<manifest
    package="com.blankj.utilcode">
</manifest>

```

**Comment by Blankj** [comment]
我那时as自带生成的，既然可以你说的那样，那我就都去掉了
