### ISSUE TITLE
关于ActivityUtils.finishAllActivities()

### ISSUE THREAD

**Issue by zmemo** [Blankj/AndroidUtilCode#701]
启动：
在MainActivity中多次启动IntentActivity
```
 startActivity(IntentActivity::class.java)
        startActivity(IntentActivity::class.java)
        startActivity(IntentActivity::class.java)
```
栈中为 MainActivity -> IntentActivity -> IntentActivity -> IntentActivity
在IntentActivity中：
```
override fun onBackPressed() {
        ActivityUtils.finishAllActivities(true)
    }
```
在IntentActivity点击返回键 返回上一个IntentActivity 
再次点击 返回上一个IntentActivity
再次点击 退出App
我的理解应该是在最后一个打开的IntentActivity中点击返回键 就直接退出App了 不知道是哪里的问题

**Comment by Blankj** [comment]
调了这个函数就全关闭了啊
