### ISSUE TITLE
关于使用了 tinker, 并且配置enableProxyApplication = true 的 app的相关问题

### ISSUE THREAD

**Issue by ldj365** [Blankj/AndroidUtilCode#702]
对于utils 版本超过1.19.0的库,由于采用了FileProvider4UtilCode注册初始化,该项初始化是在 oncreate 之前的,对于没有使用 tinker 的用户来说并没有问题,但是对于使用了 tinker ,并且配置enableProxyApplication = true的同学来说,由于 tinker 使用了代理,所以在 FileProvider4UtilCode初始化时,会被 tinker hook住,并替换为 tinker 的壳 application, 并不是真正的你们代码中写的 application, 这就会导致 utils 中注册的registerActivityLifecycleCallbacks都注册到了 tinker 的 application 中,从而导致 ActivityUtils.getTopActivity()为空,和Utils.getApp()获得到的 application为 tinker 的壳.
目前我的解决方案就是设置enableProxyApplication = false,并采取相关 tinker 配置,具体配置请查阅 tinker 的文档,由于我是使用了 bugly 的间接使用 tinker, 所以具体参数名称可能有出入,还有一种方案就是保留在1.19.0版本上,要么不使用 tinker, 暂时没想到其他的解决方法,如果有其他的解决方法,欢迎反馈

**Comment by candyguy242** [comment]
没详细看过，有个思路 ：把bugly打的包打开后，看看注册的apllication类的内容，可以找找线索。
