### ISSUE TITLE
Android 6.0之后动态权限

### ISSUE THREAD

**Issue by haiker2011** [Blankj/AndroidUtilCode#71]
是否考虑加一个Android 6.0之后动态权限管理相关的帮助类？

**Comment by Blankj** [comment]
我现在还没用到，国内还不多现在，之后应该会加

**Comment by Yang-zh** [comment]
附议，这个调个系统原生对话框放在UtilCode里蛮不错的

**Comment by Blankj** [comment]
@haiker2011 手机已升级到6.0，这两天会添加上去

**Comment by Blankj** [comment]
@haiker2011 @Yang-zh 1.11.0 版本开始已经加入了PermissionUtils
