### ISSUE TITLE
英文文档  下面放支付宝和微信支付码合适么？？？？

### ISSUE THREAD

**Issue by pengMaster** [Blankj/AndroidUtilCode#712]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by yuruxuan** [comment]
我觉得合适
