### ISSUE TITLE
AppUtils#isAppInstalled(java.lang.String)方法判断不了没有界面的安装包

### ISSUE THREAD

**Issue by candyguy242** [Blankj/AndroidUtilCode#713]
AppUtils#isAppInstalled(java.lang.String)方法判断不了没有界面的安装包
使用另一个方法isAppInstalled(java.lang.String, java.lang.String)有办法判断，但不够直接，我是想通过包名直接判断，所以建议增加一个方法isAppInstalledIncludeAll(String)来遍历所有已安装的包，进行比对。

**Comment by Blankj** [comment]
你试试 PackageManager.GET_META_DATA 改为 0

**Comment by candyguy242** [comment]
测试了一下，用0也可以，编译器也不提示有问题，不过之前用过MATCH_DEFAULT_ONLY，编译器提示是：
Must be one or more of: PackageManager.GET_META_DATA, PackageManager.GET_SHARED_LIBRARY_FILES, PackageManager.MATCH_UNINSTALLED_PACKAGES, PackageManager.MATCH_SYSTEM_ONLY, PackageManager.MATCH_DISABLED_COMPONENTS, PackageManager.MATCH_DISABLED_UNTIL_USED_COMPONENTS, PackageManager.GET_DISABLED_UNTIL_USED_COMPONENTS, PackageManager.GET_UNINSTALLED_PACKAGES

所以我觉得还是符合规范，使用GET_META_DATA更好，避免兼容性的问题

**Comment by Blankj** [comment]
升级到 1.22.0 即可哈
