### ISSUE TITLE
大案要案：ThreadUtils.cancel 惊现ANR，必现！！！！

### ISSUE THREAD

**Issue by candyguy242** [Blankj/AndroidUtilCode#714]
今天搞一个需要延迟处理的功能，并根据情况取消，结果遇上了ANR!!!一开始没反应过来，后来逐步排察，发现是取消任务这步导致的。知道真相的我流下泪来^....^ 
这个必须要修改啊，请大神列为高优问题。

下面这两句简单的代码就能复现：
ThreadUtils.executeByCpuWithDelay(test,20,TimeUnit.SECONDS);
ThreadUtils.cancel(test);

implementation 'com.blankj:utilcode:1.20.4'

**Comment by Blankj** [comment]
升级到 1.22.0 即可哈

**Comment by candyguy242** [comment]
测试通过~~赞~~
