### ISSUE TITLE
页面跳转404

### ISSUE THREAD

**Issue by sunxlfred** [Blankj/AndroidUtilCode#717]
文档(主页) -> Documentation -> utilcode -> README of Chinese -> ActivityUtil(及以下多个util) 打开为空

**Comment by Blankj** [comment]
已修复

**Comment by sunxlfred** [comment]
文件相关的 fileIOUtils.java, 这个跳转还是不行哦

**Comment by Blankj** [comment]
真是心细哦，哈哈，当时替换出错啦，已修改。
