### ISSUE TITLE
构建错误

### ISSUE THREAD

**Issue by ZhangKuixun** [Blankj/AndroidUtilCode#718]
org.codehaus.groovy.ast.expr.TupleExpression cannot be cast to org.codehaus.groovy.ast.expr.ArgumentListExpression Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by Blankj** [comment]
重新拉下？

**Comment by ZhangKuixun** [comment]
打不开，一致处于：starting gradle daemon。按照网上改了

**Comment by Blankj** [comment]
把我项目里 gradle.properties 那行注释了就行  我开启了 gradle 调试，所以需要开启调试才能。我疏忽了

**Comment by Blankj** [comment]
重新拉下代码哈

**Comment by ZhangKuixun** [comment]
ok
