### ISSUE TITLE
ToastUtils，切换语言后，显示的字还是原来的语言，重启应用才正常显示

### ISSUE THREAD

**Issue by ChestnutMu** [Blankj/AndroidUtilCode#726]
![image](https://user-images.githubusercontent.com/17003301/48965589-29af8a80-effb-11e8-9eea-67b9b2702b15.png)

例如，从简体切换成繁体，但是这行代码获取到的text还是简体。

**Comment by ChestnutMu** [comment]
需求不想重启应用，因为有启动页，比较慢，使用Android默认的Toast不会有这个问题。

**Comment by Blankj** [comment]
那你要用 application 的 context，不要用 activity 的

**Comment by ChestnutMu** [comment]
嗯嗯~还是不打算适配这部vivo了，5.0.2版本的
