### ISSUE TITLE
DeviceUtils 只有判断设备是否已经被root ，无法判断软件是否已经获取到root

### ISSUE THREAD

**Issue by baiyulinlin** [Blankj/AndroidUtilCode#73]
不够完美

**Comment by Blankj** [comment]
如果存在你说的这种方法，找到了给我pr哦

**Comment by baiyulinlin** [comment]
可以参考下rootshell：https://github.com/Stericson/RootShell，这个用RootShell.isAccessGiven()就可以判断出来了

**Comment by baiyulinlin** [comment]
可以参考下rootshell：https://github.com/Stericson/RootShell
这个用RootShell.isAccessGiven()就可以判断出来了

**Comment by Blankj** [comment]
nice

**Comment by Blankj** [comment]
AppUtils中已加入
