### ISSUE TITLE
AppUtils registerAppStatusChangedListener的问题

### ISSUE THREAD

**Issue by wimvogt** [Blankj/AndroidUtilCode#732]
## Describe the bug

- The version of utilcode: 1.22.1
- The device: 锤子 pro
- The version of device: 26

## The code of bug

AppUtils.registerAppStatusChangedListener(this, new Utils.OnAppStatusChangedListener() {
            @Override
            public void onForeground() {
                Log.d(TAG, "onForeground: ");
            }

            @Override
            public void onBackground() {
                Log.d(TAG, "onBackground: ");
            }
        });
其中的回调onForeground与onBackground都会回调两次。

**Comment by Blankj** [comment]
我这边只有一次，你换个手机试试要不？
