### ISSUE TITLE
 Could not find bus.jar

### ISSUE THREAD

**Issue by guangzq** [Blankj/AndroidUtilCode#734]
## 问题：ld not resolve all files for configuration ':app:debugCompileClasspath'.
   Could not find bus.jar (com.blankj:bus:1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/blankj/bus/1.0/bus-1.0.jar

**Comment by Blankj** [comment]
用最新版本哈

**Comment by guangzq** [comment]
谢谢~
