### ISSUE TITLE
maven仓库依赖出问题了

### ISSUE THREAD

**Issue by helixs** [Blankj/AndroidUtilCode#735]
gradle:sync..........

Failed to resolve: bus-1.0.jar

不知道是不是我本地的问题

**Comment by Blankj** [comment]
升级到 1.22.1 最新版本即可

**Comment by helixs** [comment]
还是不行 一直用的这个版本。今天下午突然出问题了。清了缓存也是

**Comment by Blankj** [comment]
用的什么版本

**Comment by helixs** [comment]
1.22.1用了10多天。换成了1.22.0还是一样。

**Comment by Blankj** [comment]
亲，我 1.22.1 才发布不到 10 天呢吧

**Comment by helixs** [comment]
我新建一个项目没问题。。。尴尬了。可能是冲突了。我再试试

**Comment by helixs** [comment]
Could not find bus.jar (com.blankj:bus:1.0).
Searched in the following locations:
    https://jcenter.bintray.com/com/blankj/bus/1.0/bus-1.0.jar
报的这个错 知道什么意思吗

**Comment by Blankj** [comment]
模仿下面写 utilcode 的版本为 1.22.1 在根 gradle 的 allprojects 中
```
    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'

        resolutionStrategy.eachDependency {
            if (it.requested.group == 'com.android.support'
                    && !it.requested.name.contains('multidex')) {
                it.useVersion support_version
            }
        }
    }
```

**Comment by Blankj** [comment]
![image](https://user-images.githubusercontent.com/17978187/49582613-95e1a500-f990-11e8-95c7-da67565f883c.png)
执行 dependencies 看哪个依赖了我的 bus

**Comment by Blankj** [comment]
执行 ./gradlew build --refresh-dependencies  试试

**Comment by helixs** [comment]
。。。god。我重启电脑好了。
