### ISSUE TITLE
可以加上快捷方式的增删改查，虽然说也有很多不适配的，但可以做些通用的

### ISSUE THREAD

**Issue by baiyulinlin** [Blankj/AndroidUtilCode#74]
参考：https://github.com/fanOfDemo/ShortcutLib
https://github.com/xuyisheng/ShortcutHelper
https://github.com/leolin310148/ShortcutBadger

**Comment by Blankj** [comment]
这已经不是一个工具类可以完成的了，我做的一般都是依赖一个工具类可以完成的，追求精简，如果需要构建依赖多个类的话那就是另一个response了 😆

**Comment by baiyulinlin** [comment]
可以写成一个类的..........组织好点就行了,我只是提议一下，还是挺实用的这个功能的

**Comment by Blankj** [comment]
恩，做到肯定是可以做到的，但逻辑肯定就没那么清晰了，毕竟都混在一个类里了，后续会考虑的哈
