### ISSUE TITLE
ImageUtils.scale的问题

### ISSUE THREAD

**Issue by jiezigg** [Blankj/AndroidUtilCode#754]
Bitmap的createScaledBitmap方法的官方描述是If the specified width and height are the same as the current width and height of the source bitmap, the source bitmap is returned and no new bitmap is created.所以原始的bitmap和返回的bitmap可能是同一个,所以在是否回收的判断上应该这样更好点：
 if (recycle && !src.isRecycled() && ret != src) src.recycle();
该类的其他方法同理

**Comment by Blankj** [comment]
好的哈

**Comment by Blankj** [comment]
新版本已修复哈
