### ISSUE TITLE
ImageUtils.toRound会改变图片比例

### ISSUE THREAD

**Issue by llx547305571** [Blankj/AndroidUtilCode#755]
## Describe the bug
使用ImageUtils.toRound生成圆形图片时，若原图为长方形，生成的bitmap比例会被压缩

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
那你是要裁剪？

**Comment by Blankj** [comment]
你传入剪裁后的方图不就好了么，你给我长方形的图我怎么知道你要处理哪里，给你压缩成正方形这是最好的了。
