### ISSUE TITLE
SDCardUtils的getFreeSpace方法，用oppo系列的手机亲测几乎都报错，其他手机都倒不会

### ISSUE THREAD

**Issue by baiyulinlin** [Blankj/AndroidUtilCode#76]
java.lang.NoSuchMethodError: android.os.StatFs.getAvailableBlocksLong
at com.blankj.utilcode.utils.SDCardUtils.getFreeSpace(SDCardUtils.java:100)

**Comment by Blankj** [comment]
那你试试里面的getSDCardInfo呢，或者提供下报错信息

**Comment by baiyulinlin** [comment]
同样报错，oppo的系统内部好像没这个方法

**Comment by baiyulinlin** [comment]
10-31 10:13:59.666: E/AndroidRuntime(4503): FATAL EXCEPTION: main
10-31 10:13:59.666: E/AndroidRuntime(4503): java.lang.NoSuchMethodError: android.os.StatFs.getBlockCountLong
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at com.blankj.utilcode.utils.SDCardUtils.getSDCardInfo(SDCardUtils.java:118)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at com.show.shuaji.activity.MainActivity.initView(MainActivity.java:66)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at com.show.shuaji.activity.MainActivity.onCreate(MainActivity.java:59)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.app.Activity.performCreate(Activity.java:5203)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1156)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.app.ActivityThread.access$600(ActivityThread.java:166)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.os.Looper.loop(Looper.java:194)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at android.app.ActivityThread.main(ActivityThread.java:5427)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at java.lang.reflect.Method.invoke(Method.java:525)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-31 10:13:59.666: E/AndroidRuntime(4503): 	at dalvik.system.NativeStart.main(Native Method)
10-31 10:14:01.281: E/Parcel(4503): Reading a NULL string not supported here.

**Comment by Blankj** [comment]
安卓版本多少

**Comment by baiyulinlin** [comment]
4.4

**Comment by Blankj** [comment]
用stat.getBlockSize();呢，就是把后面的Long全去掉

**Comment by baiyulinlin** [comment]
一样不行

**Comment by baiyulinlin** [comment]
还真是行了，oppo居然只支持以前的方法。。
