### ISSUE TITLE
报告bug

### ISSUE THREAD

**Issue by 258459885596** [Blankj/AndroidUtilCode#760]
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               FATAL EXCEPTION: main
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               Process: com.sakura.water, PID: 21485
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/base.apk"],nativeLibraryDirectories=[/data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/lib/arm64, /data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.ActivityThread.access$1100(ActivityThread.java:199)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:106)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.os.Looper.loop(Looper.java:193)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:6669)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.reflect.Method.invoke(Native Method)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.blankj.utilcode.util.Utils$FileProvider4UtilCode" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/base.apk"],nativeLibraryDirectories=[/data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/lib/arm64, /data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at android.app.ActivityThread.installProvider(ActivityThread.java:6380)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               ... 10 more
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.VMClassLoader.findLoadedClass(Native Method)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               ... 13 more
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/base.apk"],nativeLibraryDirectories=[/data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/lib/arm64, /data/app/com.sakura.water-qibgGmlEu2XoAwH1-a68tA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-19 10:34:41.107 21485 21485 E   AndroidRuntime                               ... 16 more
12-19 10:34:41.114 1309 10083 W    ActivityManager                              Force finishing activity com.sakura.water/.LauncherActivity.LogoActivity

**Comment by Blankj** [comment]
升级到最新版本 1.22.4
