### ISSUE TITLE
Utils 中的 Activity 栈多线程异常

### ISSUE THREAD

**Issue by imliujun** [Blankj/AndroidUtilCode#762]
## Describe the bug
版本号：1.22.3

## Screenshots
![image](https://user-images.githubusercontent.com/9779970/50210278-a93d3900-03b0-11e9-9e4f-c73ceda57a63.png)

**Comment by oneapp1e** [comment]
+1 遇到同样的问题

**Comment by Blankj** [comment]
在 onDestroy 不都是主线程的么，咋会有多线程的错误。

**Comment by Blankj** [comment]
好啦 修复了 用 1.22.7 版本试试看吧
