### ISSUE TITLE
屏幕适配存在两个问题 1.两个均分宽度的textview 如果gravity设置方式不一样，textview就无法对齐。 2.如果后期这个存在问题，pt自动转化为dp 还得修改布局（原本540pt表示二分之一的屏幕宽度   取消适配后 变为540dp 就可能变为充满屏幕）

### ISSUE THREAD

**Issue by lcl6** [Blankj/AndroidUtilCode#763]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by lcl6** [comment]
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:orientation="horizontal"
    android:layout_height="match_parent">
    <TextView
        android:layout_width="540pt"
        android:layout_height="308pt"
        android:text="测试"
        android:background="@color/app_color_blue"
        android:textSize="30sp"
        android:gravity="left"
        android:textColor="@color/white"
        />

    <TextView
        android:layout_width="540pt"
        android:layout_height="308pt"
        android:text="测试2"
        android:background="#445544"
        android:textSize="30sp"
        android:gravity="center"
        android:textColor="@color/white"
        />


</LinearLayout>

没办法贴效果图 就这个布局运行后 这两个textview 无法在一个水平线上  可否麻烦大佬运行看看？

**Comment by lcl6** [comment]
`<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:orientation="horizontal"
    android:layout_height="match_parent">
    <TextView
        android:layout_width="540pt"
        android:layout_height="308pt"
        android:text="测试"
        android:background="@color/app_color_blue"
        android:textSize="30sp"
        android:gravity="left"
        android:textColor="@color/white"
        />
    <TextView
        android:layout_width="540pt"
        android:layout_height="308pt"
        android:text="测试2"
        android:background="#445544"
        android:textSize="30sp"
        android:gravity="center"
        android:textColor="@color/white"
        />
</LinearLayout>`

不知道怎么上图 大佬有空可以运行一下这个布局代码  会出现两个textview不在同一个水平线上的情况

**Comment by Blankj** [comment]
你不会贴代码块吗？
\```
方这里
\```

**Comment by lcl6** [comment]
```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:orientation="horizontal"
    android:layout_height="match_parent">
    <TextView
        android:layout_width="540pt"
        android:layout_height="308pt"
        android:text="测试"
        android:background="@color/app_color_blue"
        android:textSize="30sp"
        android:gravity="left"
        android:textColor="@color/white"
        />
    <TextView
        android:layout_width="540pt"
        android:layout_height="308pt"
        android:text="测试2"
        android:background="#445544"
        android:textSize="30sp"
        android:gravity="center"
        android:textColor="@color/white"
        />
</LinearLayout>
 ```

**Comment by Blankj** [comment]
你这不是适配的问题哈，你不论用什么单位都会这样啊，gravity 决定了内部元素放在哪的啊，你怕是刚学 Android 不久吧
