### ISSUE TITLE
Attribute "borderlessButtonStyle" has already been defined

### ISSUE THREAD

**Issue by fengyao120** [Blankj/AndroidUtilCode#77]
属性borderlessButtonStyle；colorAccent存在被定义的问题

**Comment by Blankj** [comment]
哪里?

**Comment by fengyao120** [comment]
编译的时候提示这两个错误，项目引用了10多个包，一下也找不出跟哪个包重复了，这个有好的解决方案吗？

**Comment by Blankj** [comment]
我现在把snackbar的属性都抽出来了，等等发个版本你再试试

**Comment by Blankj** [comment]
compile 'com.blankj:utilcode:1.3.3'

**Comment by fengyao120** [comment]
找到解决方案了，今天完全新建一个空项目引入com.blankj:utilcode:1.3.2同样遇到这个编译错误了，然后就把你的项目下载下来看了下又没问题，后来反复测试原来是buildToolsVersion的问题，24.0.3没有问题，换成23的编译就报这个错了。谢啦^_^

**Comment by Blankj** [comment]
用compile 'com.blankj:utilcode:1.3.3'

**Comment by fengyao120** [comment]
恩，1.3.3在buildToolsVersion 23上编译也没有问题了
