### ISSUE TITLE
 ToastUtils 在小米手机显示 Toast 带有 App 名

### ISSUE THREAD

**Issue by 06304322** [Blankj/AndroidUtilCode#772]
- The version of utilcode: 1.22.7
- The device: MI 8 SE
- The version of device: API 27

**Comment by Blankj** [comment]
我这边测试了 没有问题 不会显示 app 名的

**Comment by 06304322** [comment]
搞定了，是我这边的问题。

**Comment by qianshengta** [comment]
> 搞定了，是我这边的问题。

请求下是怎么搞到的？我这边也是这样 跟你一样的手机

**Comment by 06304322** [comment]
检查下你用的是ToastUtils 还是原生的Toast，ToastUtils 版本是不是更新后的。正常使用ToastUtils 这个就可以了。

**Comment by 06304322** [comment]
> 搞定了，是我这边的问题。
> 
> 请求下是怎么搞到的？我这边也是这样 跟你一样的手机
检查下你用的是ToastUtils 还是原生的Toast，ToastUtils 版本是不是更新后的。正常使用ToastUtils 这个就可以了。

**Comment by 06304322** [comment]
> 搞定了，是我这边的问题。
> 
> 请求下是怎么搞到的？我这边也是这样 跟你一样的手机

检查下你用的是ToastUtils 还是原生的Toast，ToastUtils 版本是不是更新后的。正常使用ToastUtils 这个就可以了。
