### ISSUE TITLE
toRound 图片有黑边

### ISSUE THREAD

**Issue by HaoYundong** [Blankj/AndroidUtilCode#774]
转为圆形图片后图片有黑边

**Comment by HaoYundong** [comment]
图片黑边效果图：
![circle](https://user-images.githubusercontent.com/14197731/50509729-e779dd00-0ac1-11e9-81b6-c2d8debdc7aa.png)

**Comment by Blankj** [comment]
你单独放到一个 ImageView 里呢？我这边 demo 没问题的，你可以试下 https://github.com/Blankj/AndroidUtilCode/releases
