### ISSUE TITLE
DES加密，key不是hexString，报java.security.InvalidKeyException: Wrong key size

### ISSUE THREAD

**Issue by wmjwmj828** [Blankj/AndroidUtilCode#775]
EncryptUtils：

        String data = "hello encrypt demo";
        String key = "SKJKJ_KSH564854545";
        // des加密
        String des = encryptDES2HexString(data.getBytes(), key.getBytes(), "DES/CBC/PKCS5Padding", null);

symmetricTemplate这个方法获取SecretKeySpec对象是直接通过key获取不行啊
   SecretKeySpec secretKey = new SecretKeySpec(key, algorithm);

如果是用密匙工厂就可以用非十六进制字符串的key
            SecretKeyFactory keyFactory = SecretKeyFactory.getInstance(algorithm);
            DESKeySpec desKey = new DESKeySpec(key);
            SecretKey secretKey = keyFactory.generateSecret(desKey);

**Comment by Blankj** [comment]
是你 key 长度不对，SecretKeyFactory 只是截取了 8 字节长度，你如果传入 key.getBytes()[0..7]。所有加密密钥长度都有限制的

**Comment by wmjwmj828** [comment]
好的
