### ISSUE TITLE
 AdaptScreenUtils的使用问题

### ISSUE THREAD

**Issue by sun1594732** [Blankj/AndroidUtilCode#776]
之前一直使用1.21.1的ScreenUtils适配，更新使用1.22.7的 AdaptScreenUtils的适配后无效，请问一下是adaptHeight和adaptWidth同时使用还是单独定义一个维度，这俩种情况我都有试过但是没有效果，现在的pt适配是需要改变之前布局的dp为pt吗？

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/issues/758

**Comment by WWGtest** [comment]
请问在哪里能找到具体完整的 AdaptScreenUtils.adaptWidth() 调用流程？

**Comment by XuanYuan1122** [comment]
全局适配的话 在哪里调用呢？

**Comment by Blankj** [comment]
@XuanYuan1122 baseactivity 里写了就行

**Comment by Blankj** [comment]
@WWGtest 什么意思
