### ISSUE TITLE
unzip解压缩（ZipperDown） 安全风险提示

### ISSUE THREAD

**Issue by TxcA** [Blankj/AndroidUtilCode#777]
## Describe the safe

- The version of utilcode: 1.22.7
- The device: all
- The version of device:  all

360加固：解压zip文件，使用getName0获取压缩文件名后未对名称进行校验。
方法名：getFilesPath                   类名：Lcom/blankj/utilcode/util/ZipUtils；
方法名：unzipChildFile                类名：Lcom/blankj/utilcode/util/ZipUtils；

修复建议：解压文件时，判断文件名是否有.…/特殊字符。

**Comment by Blankj** [comment]
有判断的啊
```
String entryName = entry.getName();
if (entryName.contains("../")) {
    Log.e("ZipUtils", "it's dangerous!");
    return files;
}
```

**Comment by TxcA** [comment]
> 有判断的啊
> 
> ```
> String entryName = entry.getName();
> if (entryName.contains("../")) {
>     Log.e("ZipUtils", "it's dangerous!");
>     return files;
> }
> ```

我自己没调用压缩/解压的方法，360加固是提示这个问题，就发上来了。

**Comment by Blankj** [comment]
先混淆去掉再加固吧

**Comment by TxcA** [comment]
> 先混淆去掉再加固吧

感谢提供轮子。

**Comment by Blankj** [comment]
我在 360 加固上已经改了代码可以通过了，下版本会修复这个了的，你关注下我发布的下个版本即可。
