### ISSUE TITLE
miui10上面DisplayMetrics获取的widthPixels和heightPixels的值都为0

### ISSUE THREAD

**Issue by codesunshine** [Blankj/AndroidUtilCode#780]
## Describe the bug

- The version of utilcode: 1.22.9
- The device: 小米4c
- The version of device: API 27

## The code of bug
AdaptScreenUtils.java

adaptWidth();
adaptHeight();

put your code here

public class BaseActivity extends Activity {

    private static final String TAG = BaseActivity.class.getSimpleName();

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    protected void onStart() {
        super.onStart();
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        MLog.d(TAG, "onConfigurationChanged");
    }

    @Override
    public Resources getResources() {
        return AdaptScreenUtils.adaptHeight(super.getResources(), 1280);
    }
}

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
还会有这种事？你 debug 看下 getMiuiTmpMetrics 这个怎么跑的

**Comment by Blankj** [comment]
还会有这种事？你帮忙 debug 看下 getMiuiTmpMetrics 这个里面的逻辑和各参数值

**Comment by codesunshine** [comment]
您好!
       下面是debug的截图. 
![image](https://user-images.githubusercontent.com/17443570/50578555-7dbd5280-0e76-11e9-96ac-a9198275cb31.png)

**Comment by Blankj** [comment]
@codesunshine 大兄弟，加个 qq 吧，我的是 625783482，方便调试。
