### ISSUE TITLE
SPUtils连续的put数据，第二次总是失败

### ISSUE THREAD

**Issue by qianshengta** [Blankj/AndroidUtilCode#781]
版本  1.19.1
就是我连续put四个值，每次间隔打印数据。其他都是正常的，但是第二个数据总put不成功。以下是的截图
![o pl5tum _n3 z b_8f3d l](https://user-images.githubusercontent.com/29747624/50578835-01c50980-0e7a-11e9-9bc1-1e3429d95994.png)

**Comment by qianshengta** [comment]
我刚刚又试一下布尔值，第一次也可能失败

**Comment by qianshengta** [comment]
这一次更是一次都没成功，我是在Fragment的onResume生命周期里调用的
![zksqq_pv wvji yco 407o](https://user-images.githubusercontent.com/29747624/50579151-659d0180-0e7d-11e9-8cbc-2c3f1e788ff7.png)

**Comment by qianshengta** [comment]
我试了一下  应该是连续调用不行的 我间隔一秒调用就没问题。

**Comment by hxmeie** [comment]
> 我试了一下 应该是连续调用不行的 我间隔一秒调用就没问题。

apply方法不是同步的方法

**Comment by Blankj** [comment]
apply是异步的，你调用 put 最后有个参数 `isCommit` 传入 true 的话就不是用 apply，是 commit 了。

**Comment by qianshengta** [comment]
OK明白( • ̀ω•́ )✧
