### ISSUE TITLE
ToastUtils可以增加showCustomShort(View view)方法吗

### ISSUE THREAD

**Issue by hxmeie** [Blankj/AndroidUtilCode#783]
现有的只能传id,  showCustomShort(@LayoutRes final int layoutId)，因为需要处理相应数据显示在view里面

**Comment by Blankj** [comment]
参考 https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/pkg/src/main/java/com/blankj/utilcode/pkg/feature/toast/CustomToast.java
