### ISSUE TITLE
PermissionUtils请教两个问题！

### ISSUE THREAD

**Issue by LLQQHH** [Blankj/AndroidUtilCode#785]
为什么一定要跟PermissionConstants强行关联，如果Android 升级版本，添加新的权限，那不是不能用您的的PermissionUtils，因为PermissionConstants，没有这个新权限。
我自己的app是否要需要在AndroidManifest.xml注册这个PermissionActivity，我没有注册直接报错了，我看到demo里面PermissionActivity是用来做测试的界面，我不需要这个测试的PermissionActivity！

**Comment by Blankj** [comment]
你依赖了我的库会自己合并 Manifest.xml，又不需要你注册的。升级版本我也会升级版本啊，我这版本又不是死的，我这个库从很早就出现了，难道我不做适配的吗，当然你自己拷贝我的类去用那报错就不关我事了。

**Comment by Blankj** [comment]
权限申请是系统弹框，跟手机有关系。你怕是个新手吧，这么不清不楚的都。

**Comment by LLQQHH** [comment]
哈哈，是啊，我是新手，我知道权限申请是系统弹框，我的意思是，就是某个权限被拒绝之后，我们不是要弹出一个说明对话框说某某权限被拒绝过，不总不能说Manifest.permission_group.LOCATION被拒绝，而应该说定位权限被拒绝，就是把英文权限转化为中文！

**Comment by Blankj** [comment]
这不能自定义的哈。

**Comment by LLQQHH** [comment]
![image](https://user-images.githubusercontent.com/19651932/50622039-597c7700-0f45-11e9-8564-230396602363.png)
![image](https://user-images.githubusercontent.com/19651932/50622056-77e27280-0f45-11e9-84c7-370d9bf5cb80.png)
上面是我们的DialogHelper的，下面是某个开源库的。当用户拒绝过权限之后，我们再次申请，你们做法类似，都是弹出对话框，说为什么要申请这个权限，但是那个开源库，把申请的权限列表转换中文，更好的去显示对话框文字！我们是否也可以加一个！

**Comment by Blankj** [comment]
工具类只管申请权限的啊，至于拒绝之后要显示什么，这是交互设计师来定的，一百个产品有一百种可能，这不是规范，没必要放我这。

**Comment by LLQQHH** [comment]
说的也对，最后问大佬一个问题：这个工具有没有打算兼容：支持请求6.0悬浮窗权限8.0请求安装权限，

**Comment by Blankj** [comment]
这不是运行时权限，逻辑不同
