### ISSUE TITLE
LogUtils 日志文件foramt

### ISSUE THREAD

**Issue by VeHan** [Blankj/AndroidUtilCode#791]
## LogUtils 日志文件foramt

- The version of utilcode: 最新
- The device: 无
- The version of device:无
## The code of bug

能不能把日志文件名称的formater接口开放出来可以定制，这样的话方便日志的上传。上传的时候可以找到指定的日志文件。

**Comment by VeHan** [comment]
还有就是打印String对象的时候也走了这个转Json的方法，应该直接打印即可
![image](https://user-images.githubusercontent.com/12841131/50810751-3a675600-1346-11e9-82c2-c27500618934.png)

**Comment by Blankj** [comment]
下版本会修复的
