### ISSUE TITLE
Unable to get provider com.blankj.utilcode.util.Utils$FileProvider4UtilCode: java.lang.SecurityException: Provider must not be exported

### ISSUE THREAD

**Issue by susong0526** [Blankj/AndroidUtilCode#797]
## Describe the bug

- The version of utilcode: 1.22.10
- The device: mi 5
- The version of device: API 26

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by van048** [comment]
同样有这个问题

**Comment by Blankj** [comment]
@van048 什么版本

**Comment by Blankj** [comment]
试试 1.23.0 已发布

**Comment by lushang1geren** [comment]
1.30.0同样有这个问题
