### ISSUE TITLE
建议添加 检测已装载的外置SD卡

### ISSUE THREAD

**Issue by Sujie1** [Blankj/AndroidUtilCode#798]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
SDCardUtils.getSDCardPaths(true);

**Comment by Sujie1** [comment]
这个方法在未装载外置SD卡时也能获取到路径   还有一个是否装载的属性  mounted 需要比较的

**Comment by Blankj** [comment]
系统 API 有吗，反射这种 Android 9 不行的吧，你有现成代码吗

**Comment by Sujie1** [comment]
可能我考虑的不够全面  这是我的代码
public static ArrayList<StorageInfo> getAvailableStorageList(Context context) {
		ArrayList<StorageInfo> storagges = new ArrayList<>();
		StorageManager storageManager = (StorageManager) context.getSystemService(Context.STORAGE_SERVICE);
		try {
			Class<?>[] paramClasses = {};
			Method getVolumeList = StorageManager.class.getMethod("getVolumeList", paramClasses);
			getVolumeList.setAccessible(true);
			Object[] params = {};
			Object[] invokes = (Object[]) getVolumeList.invoke(storageManager, params);
			if (invokes != null) {
				StorageInfo info = null;
				for (int i = 0; i < invokes.length; i++) {
					Object obj = invokes[i];
					Method getPath = obj.getClass().getMethod("getPath", new Class[0]);
					String path = (String) getPath.invoke(obj, new Object[0]);
					info = new StorageInfo(path);
					File file = new File(info.path);
					if ((file.exists()) && (file.isDirectory()) && (file.canWrite())) {
						Method isRemovable = obj.getClass().getMethod("isRemovable", new Class[0]);
						String state = null;
						try {
							Method getVolumeState = StorageManager.class.getMethod("getVolumeState", String.class);
							state = (String) getVolumeState.invoke(storageManager, info.path);
							info.state = state;
						} catch (Exception e) {
							e.printStackTrace();
						}

						if (info.isMounted()) {
							info.isRemoveable = (Boolean) isRemovable.invoke(obj, new Object[0]);
							storagges.add(info);
						}
					}
				}
			}
		} catch (NoSuchMethodException | IllegalArgumentException | IllegalAccessException | InvocationTargetException e1) {
			e1.printStackTrace();
		}
		storagges.trimToSize();
		return storagges;
	}

	public static class StorageInfo {

		public String path;
		public String state;
		public boolean isRemoveable;

		public StorageInfo(String path) {
			this.path=path;
		}

		public boolean isMounted() {
			return "mounted".equals(state);
		}

		public String getPath() {
			return path;
		}

		public void setPath(String path) {
			this.path = path;
		}

		public String getState() {
			return state;
		}

		public void setState(String state) {
			this.state = state;
		}

		public boolean isRemoveable() {
			return isRemoveable;
		}

		public void setRemoveable(boolean removeable) {
			isRemoveable = removeable;
		}

		@Override
		public String toString() {
			return "StorageInfo{" +
					"path='" + path + '\'' +
					", state='" + state + '\'' +
					", isRemoveable=" + isRemoveable +
					'}';
		}
	}

**Comment by Blankj** [comment]
```
/**
 * Returns list of paths for all mountable volumes.
 * @hide
 */
@Deprecated
public @NonNull String[] getVolumePaths() {
    StorageVolume[] volumes = getVolumeList();
    int count = volumes.length;
    String[] paths = new String[count];
    for (int i = 0; i < count; i++) {
        paths[i] = volumes[i].getPath();
    }
    return paths;
}
```
注释写的是 all mountable volumes.

**Comment by Blankj** [comment]
下版本更新为
```java
/**
 * Return the paths of sdcard.
 *
 * @return the paths of sdcard
 */
public static List<SDCardInfo> getSDCardInfo() {
    List<SDCardInfo> paths = new ArrayList<>();
    StorageManager sm =
            (StorageManager) Utils.getApp().getSystemService(Context.STORAGE_SERVICE);
    if (sm == null) return paths;
    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
        List<StorageVolume> storageVolumes = sm.getStorageVolumes();
        try {
            //noinspection JavaReflectionMemberAccess
            Method getPathMethod = StorageVolume.class.getMethod("getPath");
            for (StorageVolume storageVolume : storageVolumes) {
                boolean isRemovable = storageVolume.isRemovable();
                String state = storageVolume.getState();
                String path = (String) getPathMethod.invoke(storageVolume);
                paths.add(new SDCardInfo(path, state, isRemovable));
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
        return paths;
    } else {
        try {
            Class<?> storageVolumeClazz = Class.forName("android.os.storage.StorageVolume");
            //noinspection JavaReflectionMemberAccess
            Method getPathMethod = storageVolumeClazz.getMethod("getPath");
            Method isRemovableMethod = storageVolumeClazz.getMethod("isRemovable");
            //noinspection JavaReflectionMemberAccess
            Method getVolumeStateMethod = StorageManager.class.getMethod("getVolumeState", String.clas
            //noinspection JavaReflectionMemberAccess
            Method getVolumeListMethod = StorageManager.class.getMethod("getVolumeList");
            Object result = getVolumeListMethod.invoke(sm);
            final int length = Array.getLength(result);
            for (int i = 0; i < length; i++) {
                Object storageVolumeElement = Array.get(result, i);
                String path = (String) getPathMethod.invoke(storageVolumeElement);
                boolean isRemovable = (Boolean) isRemovableMethod.invoke(storageVolumeElement);
                String state = (String) getVolumeStateMethod.invoke(sm, path);
                paths.add(new SDCardInfo(path, state, isRemovable));
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return paths;
    }
}
public static class SDCardInfo {
    private String  path;
    private String  state;
    private boolean isRemovable;
    SDCardInfo(String path, String state, boolean isRemovable) {
        this.path = path;
        this.state = state;
        this.isRemovable = isRemovable;
    }
    public String getPath() {
        return path;
    }
    public String getState() {
        return state;
    }
    public boolean isRemovable() {
        return isRemovable;
    }
    @Override
    public String toString() {
        return "SDCardInfo {" +
                "path = " + path +
                ", state = " + state +
                ", isRemovable = " + isRemovable +
                '}';
    }
}
```
