### ISSUE TITLE
fragment没有跟着activity适配

### ISSUE THREAD

**Issue by Bruce8hou** [Blankj/AndroidUtilCode#799]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
上图和代码啊？

**Comment by Bruce8hou** [comment]
我刚刚重新建立了一个工程 好像适配不生效 ：`public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    public Resources getResources() {
        return  AdaptScreenUtils.adaptHeight( super.getResources(),1920);
        //return super.getResources();
    }
}`
布局：
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <ImageView
        android:layout_width="300dp"
        android:layout_height="500dp"
        android:background="@color/colorPrimary"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</android.support.constraint.ConstraintLayout>
```
![qq 20190115155958](https://user-images.githubusercontent.com/20390458/51166613-1922de80-18df-11e9-8276-bbf83b2383cd.png)
![qq 20190115155948](https://user-images.githubusercontent.com/20390458/51166623-2049ec80-18df-11e9-84d5-da64644a8a5f.png)

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/issues/758
看下文章把

**Comment by Bruce8hou** [comment]
是我的项目里也需要用pt 不能用dp 对吧
