### ISSUE TITLE
截屏有没有可以截取视频播放View的方案？

### ISSUE THREAD

**Issue by renyanxu2000** [Blankj/AndroidUtilCode#8]
现有提供的方案对布局中有SurfaceView的laytou不能完美适配，截屏的图片中surfaceView的背景是黑色的。

**Comment by Blankj** [comment]
谷歌搜一下吧，应该有人跟你一样会碰到相同的问题，我不可能整理得会那么细，有些情况还是需要具体情况具体分析的
