### ISSUE TITLE
微信中文件选择其他应用打开获取文件路径出错

### ISSUE THREAD

**Issue by icetea0822** [Blankj/AndroidUtilCode#807]
## Describe the bug

- The version of utilcode: 1.22.10
- The device: Samsung S8
- The version of device: 7.0

在微信中打开一个docx文件，点击右上角菜单选择其他应用打开后选择我自己的app
在我的app中用拿到的uri调用UriUtils.uri2File()方法，传入uri值为content://com.tencent.mm.external.fileprovider/external/tencent/MicroMsg/Download/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3.docx时，转换为file错误

具体为执行到UriUtils第126行报错，错误为：
content://com.tencent.mm.external.fileprovider/external/tencent/MicroMsg/Download/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3.docx parse failed. -> 1
和column '_data' does not exist

**Comment by Blankj** [comment]
那需要怎么转换才能拿到？

**Comment by icetea0822** [comment]
这个我也不清楚
我通过uri直接获取path可以得到/external/tencent/MicroMsg/Download/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3.docx 然后把external删掉换直接换成正常的路径先凑活用的

**Comment by lingyunzhu** [comment]
可以试试这样：
`
final Uri uri = intent.getData();
            String path = uri.getPath();
            if (Build.VERSION.SDK_INT >= 24 && path.startsWith("/external")) {
                path = Environment.getExternalStorageDirectory().getAbsolutePath() + path.replace("/external", "");
            }
`

**Comment by icetea0822** [comment]
> 可以试试这样：
> `final Uri uri = intent.getData(); String path = uri.getPath(); if (Build.VERSION.SDK_INT >= 24 && path.startsWith("/external")) { path = Environment.getExternalStorageDirectory().getAbsolutePath() + path.replace("/external", ""); }`

我现在就是这么处理的，但是感觉不太好吧，不应该只有微信需要这样处理

**Comment by Blankj** [comment]
试试 1.24.0
