### ISSUE TITLE
PathUtil获取外部下载文件夹路径报空指针异常

### ISSUE THREAD

**Issue by supersugar** [Blankj/AndroidUtilCode#810]
在部分机型上会产生该问题
## Describe the bug

- The version of utilcode: 1.19.3
- The device: Nexus5  波导 R7PLUS
- The version of device: 

## The code of bug
```
.setDownloadFolder(PathUtils.getExternalAppDownloadPath())//默认下载路径
```

## The stack of crash

```
Caused by:
java.lang.NullPointerException:
com.blankj.utilcode.util.PathUtils.getExternalAppDownloadPath(PathUtils.java:360)
com.xx.xx.App.initUpDown(App.java:180)
```

**Comment by Blankj** [comment]
因为某些机型没有外存的原因？放在 getInternalAppFilesPath 下就行了

**Comment by Blankj** [comment]
![image](https://user-images.githubusercontent.com/17978187/51517157-e6379800-1e54-11e9-9e30-68be96b9f5af.png)

**Comment by Blankj** [comment]
好的
