### ISSUE TITLE
华为应用市场检测出来病毒,上不了架

### ISSUE THREAD

**Issue by BoBoJiangs** [Blankj/AndroidUtilCode#811]
依赖库之后上架华为应用市场报病毒,我是新建的项目打包就会检查出来,去掉工具库依赖就不会有问题能看一下是哪里代码造成的么,工具类非常NICE不想换，能帮忙看一下么
![image](https://user-images.githubusercontent.com/12790814/51594554-a8f40880-1f2f-11e9-9339-ff949210d302.png)

**Comment by Blankj** [comment]
混淆开了吗

**Comment by Blankj** [comment]
具体我也不清楚是哪里

**Comment by BoBoJiangs** [comment]
没有混淆的 其他应用市场没问题 就华为不让上架

**Comment by BoBoJiangs** [comment]
https://www.virustotal.com/zh-cn/ 这是华为给我的检测网址 你可以试一下

**Comment by Blankj** [comment]
你混淆开启下呢

**Comment by BoBoJiangs** [comment]
开启混淆之后 好像没有报这个病毒了 谢谢！

**Comment by bingdu0** [comment]
您好，不开启混淆有解决办法吗？
