### ISSUE TITLE
很多Demo都打不开了，建议修正下

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#813]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
README 没来得及改 把地址最后 java 换成 kt 即可

**Comment by Blankj** [comment]
已修复
