### ISSUE TITLE
exitApp方法并不能真正退出App

### ISSUE THREAD

**Issue by AndyLeeBlue** [Blankj/AndroidUtilCode#818]
exitApp方法并不能真正退出App，看了下源码只是将所有Activity都finish了。建议参考这个帖子选择一种真正退出App的方法。https://www.jianshu.com/p/269873a16937

**Comment by Blankj** [comment]
都 finish 了怎么就不能退出？

**Comment by AndyLeeBlue** [comment]
不好意思，是我程序逻辑错误，请close，打扰了
