### ISSUE TITLE
屏幕亮度的调节

### ISSUE THREAD

**Issue by HeroZ-Dodge** [Blankj/AndroidUtilCode#82]
可以在屏幕中,添加屏幕亮度调节

**Comment by Javen205** [comment]
http://www.jianshu.com/p/8f3cb4439d3a

**Comment by Blankj** [comment]
@Javen205 :+1:

**Comment by Blankj** [comment]
已添加到 [BrightnessUtils](https://github.com/Blankj/AndroidUtilCode/blob/bc1fadee6bc340e50e2979ed07d33be41803523b/subutil/src/main/java/com/blankj/subutil/util/BrightnessUtils.java)
