### ISSUE TITLE
LogUtils.json 输出的数据

### ISSUE THREAD

**Issue by protectedMan** [Blankj/AndroidUtilCode#821]
![image](https://user-images.githubusercontent.com/17565737/51827591-bee53d00-2324-11e9-8d42-fe6354e78e66.png)
![image](https://user-images.githubusercontent.com/17565737/51827612-cad0ff00-2324-11e9-91f8-a474b09a350a.png)
这样的数据输出没有格式化，试了下，不带前面的\ r\ n 就没问题，格式化正常

**Comment by Blankj** [comment]
1.23.3 试试吧

**Comment by protectedMan** [comment]
1.23.3解决了
