### ISSUE TITLE
能提供一个sp2dp/dp2sp的方法吗？

### ISSUE THREAD

**Issue by AndyLeeBlue** [Blankj/AndroidUtilCode#828]
我现在这么用是不是很别扭：`ConvertUtils.px2dp(ConvertUtils.sp2px(18));`

**Comment by Blankj** [comment]
请问这个功能是用在哪？

**Comment by AndyLeeBlue** [comment]
文字。文字指定为dp为单位就不会随着系统字体大小变化（就是希望不随着系统变），但是又希望文字是随着app内的字体大小设置变化，app内文字大小预设了几种大小，都用sp为单位的，显示的大小是随着当前系统的。不知道我说清楚了没。

**Comment by Blankj** [comment]
所以哪一步用到了这个函数

**Comment by AndyLeeBlue** [comment]
`public TextInfo getDialogMenuTextInfo() {
        int menuSize = ConvertUtils.px2dp(ConvertUtils.sp2px(CONFIGs.CONFIG_FONT_DIALOG_MENU));
        return new TextInfo().setFontSize(menuSize);//字号（单位dp）
    }`
例如准备初始化一个对话框时候，常量CONFIGs.CONFIG_FONT_DIALOG_MENU是sp的

**Comment by Blankj** [comment]
建议你本地自己写一个 SizeHelper 里加个 sp2Dp 哈，你这有点太绕了哈，应用范围小哈

**Comment by AndyLeeBlue** [comment]
好的，理解，谢谢回复。的确绕，只是大多数App并不注意自身字体和系统字体的关系，尤其是自己App还提供字体大小设置的时候。试试看将系统字体调到最大，再看看自己的界面会吓一跳的。哈哈~不得不说WeChat这一点做的还是很优秀的。

**Comment by Blankj** [comment]
因为微信用的是 dp 来控制字体哈
