### ISSUE TITLE
给个aar的地址，我想直接依赖aar文件。

### ISSUE THREAD

**Issue by zhuzhushang** [Blankj/AndroidUtilCode#830]
如题  给个aar的地址，我想直接依赖aar文件。

**Comment by danyunliuhen** [comment]
>  如题  给个aar的地址，我想直接依赖aar文件。

建议最好依赖源码 可以自己调整

**Comment by zhuzhushang** [comment]
明白，另外请教一个问题，implementation 'com.blankj:utilcode:1.23.4'  根据依赖可以获取aar文件吗？或者查询到arr地址？

**Comment by Blankj** [comment]
implementation 'com.blankj:utilcode:1.23.4' 之后你在工程里查看我的类定位过去就是本地 aar 里面的啊
