### ISSUE TITLE
SpanUtils出现异常字符串

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#831]
## Describe the bug

- The version of utilcode: 1.10.0
- The device:小米5X
- The version of device: 27

## The code of bug

```
String content = new SpanUtils()
                .append("我正在看")
                .append(mVideoDetailBean.getPublisherNick())
                .append("的精彩内容，速来围观~")
                .create().toString();
        Log.d("XXX","content = "+content);
```
![image](https://user-images.githubusercontent.com/8555893/52757116-9f495680-303e-11e9-83b6-f87adf93de70.png)
Log截图如上,结尾会有异常字符

**Comment by sweet2o09** [comment]
这个bug很奇怪,在某一些界面上使用SpanUtils会出现异常字符串,但是我还没找到具体原因,希望大神能帮忙看下,项目上暂时没更新到最新版本,怕会引入别的问题

**Comment by Blankj** [comment]
你用最新版的试试哈

**Comment by sweet2o09** [comment]
新版本没问题了,就是Gson冲突,已解决
/** 工具类 */
    compile('com.blankj:utilcode:1.23.4'){
        exclude group: 'com.google.code.gson'
    }
