### ISSUE TITLE
多项目安装的时候提示com.blankj.utilcode.utilcode.provider已经被使用

### ISSUE THREAD

**Issue by sweet2o09** [Blankj/AndroidUtilCode#834]
## Describe the bug

- The version of utilcode: 1.23.4
- The device: 小米5X
- The version of device: 28

## The code of bug

多项目安装的时候提示com.blankj.utilcode.utilcode.provider已经被使用
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/app.daogou-75RcPq62EhSHvsyB9vob4Q==: Can't install because provider name com.blankj.utilcode.utilcode.provider (in package app.youxiting) is already used by app.youxitingsj]

我的项目代码里面有两个app,使用同一个框架,utilcode是在框架中引入的,当安装第二个app的时候提示安装失败

**Comment by sweet2o09** [comment]
![image](https://user-images.githubusercontent.com/8555893/52893996-a5296e00-31dd-11e9-8908-903ee056b85b.png)

**Comment by tagmic** [comment]
"你的应用包名".provider

**Comment by Blankj** [comment]
你用我的库的版本太老了

**Comment by sweet2o09** [comment]
@Blankj  使用的是最新的版本呀 1.23.4

**Comment by Blankj** [comment]
其他库依赖了老版本吧，这个 provider 只有我老版本有，你可以强制使用我最新的版本

**Comment by sweet2o09** [comment]
@Blankj 
找到问题了
<provider
            android:name="com.blankj.utilcode.util.Utils$FileProvider4UtilCode"
            android:authorities="${applicationId}.utilcode.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            android:multiprocess="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/util_code_provider_paths" />
        </provider>
我公司的项目是旧项目,在项目build的defaultConfig中没有设置applicationId,包名是在AndroidManifest中设置的package="youxitingsj",所以${applicationId}.utilcode.provider拿到的applicationId=com.blankj.utilcode
