### ISSUE TITLE
NoSuchFieldException 每次关闭actitvity都报错

### ISSUE THREAD

**Issue by StoneXL** [Blankj/AndroidUtilCode#835]
![default](https://user-images.githubusercontent.com/18682525/52924037-c1581700-3365-11e9-9ce3-350081506a20.png)

**Comment by murgupluoglu** [comment]
![screen shot 2019-02-20 at 11 30 05](https://user-images.githubusercontent.com/11410147/53077388-f057bf80-3502-11e9-8536-0601e67a09d6.png)

**Comment by Blankj** [comment]
只是报错而已吧，并没有崩溃哈，那我下版本把异常 ignore 好了

**Comment by StoneXL** [comment]
还有个问题要请教下 textview.settext(new SpanUtils().append("确认已收 ").setForegroundColor(ContextCompat.getColor(this, R.color.color_f7a302)).setFontSize(18, true).create()

**Comment by StoneXL** [comment]
还有个问题要请教下 textview.settext(new SpanUtils().append("确认已收 ").setForegroundColor(ContextCompat.getColor(this, R.color.color_f7a302)).setFontSize(18, true).create()有效果能改变颜色  但button.settext(new SpanUtils().append("确认已收 ").setForegroundColor(ContextCompat.getColor(this, R.color.color_f7a302)).setFontSize(18, true).create()) 没效果改不了颜色   这个是为什么

**Comment by Blankj** [comment]
<Button
    ...
    android:textAllCaps="false" />

**Comment by Blankj** [comment]
这种问题搜索引擎一搜就有的，不需要来专门请叫我的哈。

**Comment by Sum-sdl** [comment]
很需要把异常关闭ignore！不然没日志，都打印出来很多异常日志出来

**Comment by Blankj** [comment]
1.22.5 版本即可
