### ISSUE TITLE
BarUtils.setStatusBarColor()疑问？

### ISSUE THREAD

**Issue by DaiFalin** [Blankj/AndroidUtilCode#838]
版本：1.23.4
调用BarUtils.setStatusBarColor()
BarUtils.setStatusBarLightMode(activity, true)失效。
必须在调用BarUtils.setStatusBarColor()后，再调用BarUtils.setStatusBarLightMode(activity, true)才能生效

**Comment by Blankj** [comment]
这个版本你先这么调用吧，下版本我修复哈。

**Comment by Blankj** [comment]
1.23.5 已发布
