### ISSUE TITLE
BarUtils里的bug

### ISSUE THREAD

**Issue by DearZack** [Blankj/AndroidUtilCode#84]
如果想设置状态栏的颜色一般会
```
        BarUtils.setTransparentStatusBar(this);
        BarUtils.setColor(this, 0xff0000);
```

以上两句可以完美的解决，但是当我有很多activity都想这么做，于是我就写了个一个基类，把上述代码写了了基类中，然而出现了问题。少了一部分的padding属性。
```
        BarUtils.setTransparentStatusBar(this);
        BarUtils.setColor(this, 0xff0000);
        ViewGroup contentView = ((ViewGroup) this.findViewById(android.R.id.content));
        contentView.setPadding(0, BarUtils.getStatusBarHeight(this), 0, 0);
```

需要这些代码才可以。
作者知道是为什么吗？？为什么写在基类里就不行啊？

是因为子类又setContentView时，把之前的属性都覆盖掉了，导致失效了吗？？

**Comment by Blankj** [comment]
* <p>需在顶部控件布局中加入以下属性让内容出现在状态栏之下</p>
     * <p>android:clipToPadding="true"</p>
     * <p>android:fitsSystemWindows="true"</p>
加这个属性了吗

**Comment by DearZack** [comment]
加了后试了下还是不行

**Comment by Blankj** [comment]
你在BaseActivity中加入加入自己的跟布局，然后加上属性，然后再把子Activity的布局加到根布局里，应该是可以的吧
