### ISSUE TITLE
FileIOUtils.writeFileFromIS支持增加写入进度callback，FileUtils增加判断后缀的方法

### ISSUE THREAD

**Issue by houyuehai** [Blankj/AndroidUtilCode#841]
FileIOUtils.writeFileFromIS是否可以增加支持写入进度callback，大文件写入时可能需要知道进度。
FileUtils是否可以 根据http contentType判断下载的文件的后缀。柯基大佬牛皮！

**Comment by Blankj** [comment]
试试最新版，已支持进度。
