### ISSUE TITLE
UriUtils uri2File解析失败的问题

### ISSUE THREAD

**Issue by wexia** [Blankj/AndroidUtilCode#844]
## Describe the bug

- The version of utilcode: 1.23.4
- The device: Google pixel 2
- The version of device:  API 27

## The code of bug
1. uri:content://com.android.providers.media.documents/document/image%3A243
2. uri:content://media/external/images/media/243

工具类中
if (ContentResolver.SCHEME_CONTENT.equals(scheme)) {
}
此判断写在了前面，以致于
if ("com.android.providers.media.documents".equals(authority)) {
}
没执行到所导致的解析失败

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
试试 1.23.6.0

**Comment by Blankj** [comment]
没问题的话那我 close 了哦
