### ISSUE TITLE
UriUtils getFileFromUri 图片选取未刷新

### ISSUE THREAD

**Issue by wexia** [Blankj/AndroidUtilCode#845]
## Describe the bug

- The version of utilcode:  1.23.4
- The device:  Google pixel 2
- The version of device:  API 27

## The code of bug
第一次选取图片，展示的是正常的，第二次选取图片，展示的还是上次的图片。
打印结果，获取的uri是正常的，解析后的文件路劲不对。

目前所使用以下代码是正常的：

 private static String getDataColumn(final Uri uri,
                                        final String selection,
                                        final String[] selectionArgs) {

        final Cursor cursor = Utils.getApp().getContentResolver().query(
                uri, new String[]{MediaStore.Images.ImageColumns.DATA}, selection, selectionArgs, null);
        if (cursor != null) {
            if (cursor.moveToFirst()) {
                final int columnIndex = cursor.getColumnIndex(MediaStore.Images.ImageColumns.DATA);
                if (columnIndex> -1) {
                    return cursor.getString(columnIndex);
                }
            }
            cursor.close();
        }
        return null;
    }

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
试试 1.23.6.0

**Comment by wexia** [comment]
> 试试 1.23.6.0
