### ISSUE TITLE
ImageUtils.getBitmap's parameters are confusing

### ISSUE THREAD

**Issue by hendrawd** [Blankj/AndroidUtilCode#847]
## Describe the bug
`ImageUtils` has methods `getBitmap`
I want to get a bitmap with maxWidth/maxHeight: 720 pixel.
The real image size: 2976 x 3968
Then I run below code
```
val maxWidth = 720
val maxHeight = 720
val bitmap = ImageUtils.getBitmap(it.path, maxWidth, maxHeight)
```
I expect to get the maximal size 720 pixel as the highest width/height and the lower size will resized proportionally, but I got 744 x 992 bitmap.
I know how `BitmapFactory.Options.inSampleSize` works, but I think it is confusing since the `getBitmap` use parameters:
```
@param maxWidth  The maximum width.
@param maxHeight The maximum height.
```
and implying that the width/height will never exceed maxWidth/maxHeight

- The version of utilcode: 1.22.1
- The device: Any
- The version of device: Any

## The code of bug
https://github.com/Blankj/AndroidUtilCode/blob/a5fc6028ce0f2920185bdfa47ce52ab777760db7/utilcode/lib/src/main/java/com/blankj/utilcode/util/ImageUtils.java#L193
And similar methods

## The stack of crash
Nothing

## Screenshots
Nothing

**Comment by Blankj** [comment]
hi, the version of 1.23.6 have fixed it.

**Comment by hendrawd** [comment]
After updating to 1.23.6 the size become 372 x 496, worked as expected. Thank you @Blankj !
