### ISSUE TITLE
建议增加androidx支持或单独提供androidx版本，当前androidx已发布稳定版本1.0.2了。

### ISSUE THREAD

**Issue by cxyzy1** [Blankj/AndroidUtilCode#854]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
implementation 'com.blankj:utilcodex:1.23.7'
