### ISSUE TITLE
建议: 增加一个通知栏工具类

### ISSUE THREAD

**Issue by xzm1102207843** [Blankj/AndroidUtilCode#855]
## 建议: 要是能增加一个针对不同版本的通知栏适配就好了，以后我们就只用柯基大佬工具，类似NotificationUtils.show(Context , CHANNEL_ID, CHANNEL_NAME,title,content, ) .....，然后重载出各种不同show方法，  是不是更nice，小建议，看能不能采纳，哈哈哈

**Comment by Skqing** [comment]
来版本的不支持8了

**Comment by NicodeLee** [comment]
+1，现在写通知越来越麻烦了

**Comment by stonebirds** [comment]
+1

**Comment by Blankj** [comment]
1.26.0 已发布支持
