### ISSUE TITLE
BarUtils如何将状态栏设置透明

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#856]
试了所有的方法都无法设置透明

**Comment by Blankj** [comment]
demo https://github.com/Blankj/AndroidUtilCode/releases/download/1.23.6/util_1_23_6.apk 不行吗

**Comment by li-xiaojun** [comment]
@Blankj 
写法和Demo中的一样，仍然有个半透明的背景。

**Comment by Blankj** [comment]
那我 demo 有吗？

**Comment by li-xiaojun** [comment]
@Blankj 
好了，我的问题。
