### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3033

### ISSUE THREAD

**Issue by newlai913** [Blankj/AndroidUtilCode#861]
## Describe the bug

- The version of utilcode: 1.23.7
- The device: 小米6 
- The version of device: API 26

## The code of bug

```java
UriUtils.uri2File
```

```
@Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == 111 && data != null) {
            if (resultCode == Activity.RESULT_OK) {
                Uri uri = data.getData();
                File file = UriUtils.uri2File(FilePickerActivity.this, uri);
                String absolutePath = file.getAbsolutePath();
            }
        }
    }
```

## The stack of crash

```
2019-03-08 14:15:38.213 8143-8143/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wiki.cc, PID: 8143
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=111, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/3033 flg=0x1 }} to activity {com.wiki.cc/com.wiki.cc.ui.a.FilePickerActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3033
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4434)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3033
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:756)
        at android.content.ContentResolver.query(ContentResolver.java:705)
        at android.content.ContentResolver.query(ContentResolver.java:663)
        at com.wiki.cc.util.UriUtils.getFileFromUri(UriUtils.java:120)
        at com.wiki.cc.util.UriUtils.getFileFromUri(UriUtils.java:113)
        at com.wiki.cc.util.UriUtils.uri2File(UriUtils.java:79)
        at com.wiki.cc.ui.a.FilePickerActivity.onActivityResult(FilePickerActivity.java:53)
        at android.app.Activity.dispatchActivityResult(Activity.java:7310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4387)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4434) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
```

**Comment by Blankj** [comment]
```java
UriUtils.uri2File(FilePickerActivity.this, uri);
```
我没有需要传入 context 的啊

**Comment by Blankj** [comment]
发布了 1.23.7.0 版本帮你修复了，你试试

**Comment by newlai913** [comment]
> 发布了 1.23.7.0 版本帮你修复了，你试试
好，谢谢大佬，我试一下

**Comment by newlai913** [comment]
还是没法获取到文件路径
 `Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
        intent.setType("*/*");//设置类型，我这里是任意类型，任意后缀的可以这样写。
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        startActivityForResult(intent, 111);`
这是我打开系统文件管理器的方法，选择的文件在下载内容那一栏，获取到的uri没法成功转化为路径

**Comment by newlai913** [comment]
[https://github.com/flutter/flutter/issues/21863]与这个问题有点类似

**Comment by Blankj** [comment]
我就是参照这个的最新代码修复的啊

**Comment by Blankj** [comment]
```java
public static File uri2File(@NonNull final Uri uri) {
    Log.d("UriUtils", uri.toString());
    String authority = uri.getAuthority();
    String scheme = uri.getScheme();
    if (ContentResolver.SCHEME_FILE.equals(scheme)) {
        String path = uri.getPath();
        if (path != null) return new File(path);
        Log.d("UriUtils", uri.toString() + " parse failed. -> 0");
        return null;
    } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT
            && DocumentsContract.isDocumentUri(Utils.getApp(), uri)) {
        if ("com.android.externalstorage.documents".equals(authority)) {
            final String docId = DocumentsContract.getDocumentId(uri);
            final String[] split = docId.split(":");
            final String type = split[0];
            if ("primary".equalsIgnoreCase(type)) {
                return new File(Environment.getExternalStorageDirectory() + "/" + split[1]);
            }
            Log.d("UriUtils", uri.toString() + " parse failed. -> 1");
            return null;
        } else if ("com.android.providers.downloads.documents".equals(authority)) {
            String id = DocumentsContract.getDocumentId(uri);
            if (!TextUtils.isEmpty(id)) {
                if (id.startsWith("raw:")) {
                    return new File(id.substring(4));
                }
                final Uri contentUri = ContentUris.withAppendedId(
                        Uri.parse(Environment.DIRECTORY_DOWNLOADS),
                        Long.valueOf(id)
                );
                return getFileFromUri(contentUri, 2);
            }
            Log.d("UriUtils", uri.toString() + " parse failed. -> 3");
            return null;
        } else if ("com.android.providers.media.documents".equals(authority)) {
            final String docId = DocumentsContract.getDocumentId(uri);
            final String[] split = docId.split(":");
            final String type = split[0];
            Uri contentUri;
            if ("image".equals(type)) {
                contentUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;
            } else if ("video".equals(type)) {
                contentUri = MediaStore.Video.Media.EXTERNAL_CONTENT_URI;
            } else if ("audio".equals(type)) {
                contentUri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI;
            } else {
                Log.d("UriUtils", uri.toString() + " parse failed. -> 4");
                return null;
            }
            final String selection = "_id=?";
            final String[] selectionArgs = new String[]{split[1]};
            return getFileFromUri(contentUri, selection, selectionArgs, 5);
        } else if (ContentResolver.SCHEME_CONTENT.equals(scheme)) {
            return getFileFromUri(uri, 6);
        } else {
            Log.d("UriUtils", uri.toString() + " parse failed. -> 7");
            return null;
        }
    } else if (ContentResolver.SCHEME_CONTENT.equals(scheme)) {
        return getFileFromUri(uri, 8);
    } else {
        Log.d("UriUtils", uri.toString() + " parse failed. -> 9");
        return null;
    }
}
private static File getFileFromUri(final Uri uri, final int code) {
    return getFileFromUri(uri, null, null, code);
}
private static File getFileFromUri(final Uri uri,
                                   final String selection,
                                   final String[] selectionArgs,
                                   final int code) {
    Cursor cursor = null;
    try {
        cursor = Utils.getApp().getContentResolver().query(
                uri, new String[]{"_data"}, selection, selectionArgs, null);
        if (cursor == null) {
            Log.d("UriUtils", uri.toString() + " parse failed(cursor is null). -> " + code);
            return null;
        }
        if (cursor.moveToFirst()) {
            final int columnIndex = cursor.getColumnIndex("_data");
            if (columnIndex > -1) {
                return new File(cursor.getString(columnIndex));
            } else {
                Log.d("UriUtils", uri.toString() + " parse failed(columnIndex: " + columnIndex + " is wrong). -> " + code);
                return null;
            }
        } else {
            Log.d("UriUtils", uri.toString() + " parse failed(moveToFirst return false). -> " + code);
            return null;
        }
    } catch (Exception e) {
        Log.d("UriUtils", uri.toString() + " parse failed. -> " + code);
        return null;
    } finally {
        if (cursor != null) {
            cursor.close();
        }
    }
}
```
试一下这个

**Comment by newlai913** [comment]
还是不行，
`cursor = Utils.getApp().getContentResolver().query( uri, new String[]{"_data"}, selection, selectionArgs, null);`
这一步得到的cursor是null

**Comment by Blankj** [comment]
你根据那个 issue 试试，解决了跟我说下把

**Comment by newlai913** [comment]
换了一个方法，`https://github.com/coltoscosmin/FileUtils/blob/master/FileUtils.java`

**Comment by Blankj** [comment]
你打断点走流程跟我说下，我改下代码

**Comment by Blankj** [comment]
@newlai913 hi，麻烦打断点把具体步骤写一下哈

**Comment by newlai913** [comment]
哈，周末没看github，我一会补上步骤

**Comment by newlai913** [comment]
`
import android.content.ContentUris;
import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.DocumentsContract;
import android.provider.MediaStore;
import android.provider.OpenableColumns;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;


public final class UriUtils {

    /**
     * Get a file path from a Uri. This will get the the path for Storage Access
     * Framework Documents, as well as the _data field for the MediaStore and
     * other file-based ContentProviders.<br>
     * <br>
     * Callers should check whether the path is local before assuming it
     * represents a local file.
     *
     * @param context The context.
     * @param uri     The Uri to query.
     */
    public static String getPath(final Context context, final Uri uri) {

        final boolean isKitKat = Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT;

        // DocumentProvider
        if (isKitKat && DocumentsContract.isDocumentUri(context, uri)) {

            // ExternalStorageProvider
            if (isExternalStorageDocument(uri)) {
                final String docId = DocumentsContract.getDocumentId(uri);
                final String[] split = docId.split(":");
                final String type = split[0];

                if ("primary".equalsIgnoreCase(type)) {
                    return Environment.getExternalStorageDirectory() + "/" + split[1];
                }
            }
            // DownloadsProvider
            else if (isDownloadsDocument(uri)) {

                final String id = DocumentsContract.getDocumentId(uri);

                if (id != null && id.startsWith("raw:")) {
                    return id.substring(4);
                }

                String[] contentUriPrefixesToTry = new String[]{
                        "content://downloads/public_downloads",
                        "content://downloads/my_downloads"
                };

                for (String contentUriPrefix : contentUriPrefixesToTry) {
                    Uri contentUri = ContentUris.withAppendedId(Uri.parse(contentUriPrefix), Long.valueOf(id));
                    try {
                        String path = getDataColumn(context, contentUri, null, null);
                        if (path != null) {
                            return path;
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

                // path could not be retrieved using ContentResolver, therefore copy file to accessible cache using streams
                String fileName = getFileName(context, uri);
                File cacheDir = getDocumentCacheDir(context);
                File file = generateFileName(fileName, cacheDir);
                String destinationPath = null;
                if (file != null) {
                    destinationPath = file.getAbsolutePath();
                    saveFileFromUri(context, uri, destinationPath);
                }

                return destinationPath;
            }
            // MediaProvider
            else if (isMediaDocument(uri)) {
                final String docId = DocumentsContract.getDocumentId(uri);
                final String[] split = docId.split(":");
                final String type = split[0];

                Uri contentUri = null;
                if ("image".equals(type)) {
                    contentUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;
                } else if ("video".equals(type)) {
                    contentUri = MediaStore.Video.Media.EXTERNAL_CONTENT_URI;
                } else if ("audio".equals(type)) {
                    contentUri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI;
                }

                final String selection = "_id=?";
                final String[] selectionArgs = new String[]{
                        split[1]
                };

                return getDataColumn(context, contentUri, selection, selectionArgs);
            }
        }
        // MediaStore (and general)
        else if ("content".equalsIgnoreCase(uri.getScheme())) {

            // Return the remote address
            if (isGooglePhotosUri(uri)) {
                return uri.getLastPathSegment();
            }

            return getDataColumn(context, uri, null, null);
        }
        // File
        else if ("file".equalsIgnoreCase(uri.getScheme())) {
            return uri.getPath();
        }

        return null;
    }

    public static boolean isExternalStorageDocument(Uri uri) {
        return "com.android.externalstorage.documents".equals(uri.getAuthority());
    }

    /**
     * @param uri The Uri to check.
     * @return Whether the Uri authority is DownloadsProvider.
     */
    public static boolean isDownloadsDocument(Uri uri) {
        return "com.android.providers.downloads.documents".equals(uri.getAuthority());
    }

    /**
     * @param uri The Uri to check.
     * @return Whether the Uri authority is MediaProvider.
     */
    public static boolean isMediaDocument(Uri uri) {
        return "com.android.providers.media.documents".equals(uri.getAuthority());
    }

    /**
     * @param uri The Uri to check.
     * @return Whether the Uri authority is Google Photos.
     */
    public static boolean isGooglePhotosUri(Uri uri) {
        return "com.google.android.apps.photos.content".equals(uri.getAuthority());
    }

    public static String getDataColumn(Context context, Uri uri, String selection,
                                       String[] selectionArgs) {

        Cursor cursor = null;
        final String column = MediaStore.Files.FileColumns.DATA;
        final String[] projection = {
                column
        };

        try {
            cursor = context.getContentResolver().query(uri, projection, selection, selectionArgs, null);
            if (cursor != null && cursor.moveToFirst()) {

                final int column_index = cursor.getColumnIndexOrThrow(column);
                return cursor.getString(column_index);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (cursor != null)
                cursor.close();
        }
        return null;
    }

    public static String getFileName(@NonNull Context context, Uri uri) {
        String mimeType = context.getContentResolver().getType(uri);
        String filename = null;

        if (mimeType == null) {
            String path = getPath(context, uri);
            if (path == null) {
                filename = getName(uri.toString());
            } else {
                File file = new File(path);
                filename = file.getName();
            }
        } else {
            Cursor returnCursor = context.getContentResolver().query(uri, null,
                    null, null, null);
            if (returnCursor != null) {
                int nameIndex = returnCursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
                returnCursor.moveToFirst();
                filename = returnCursor.getString(nameIndex);
                returnCursor.close();
            }
        }

        return filename;
    }

    public static String getName(String filename) {
        if (filename == null) {
            return null;
        }
        int index = filename.lastIndexOf('/');
        return filename.substring(index + 1);
    }

    public static File getDocumentCacheDir(@NonNull Context context) {
        File dir = new File(context.getCacheDir(), "document");
        if (!dir.exists()) {
            dir.mkdirs();
        }
        return dir;
    }

    @Nullable
    public static File generateFileName(@Nullable String name, File directory) {
        if (name == null) {
            return null;
        }

        File file = new File(directory, name);

        if (file.exists()) {
            String fileName = name;
            String extension = "";
            int dotIndex = name.lastIndexOf('.');
            if (dotIndex > 0) {
                fileName = name.substring(0, dotIndex);
                extension = name.substring(dotIndex);
            }

            int index = 0;

            while (file.exists()) {
                index++;
                name = fileName + '(' + index + ')' + extension;
                file = new File(directory, name);
            }
        }

        try {
            if (!file.createNewFile()) {
                return null;
            }
        } catch (IOException e) {
            return null;
        }

        return file;
    }

    private static void saveFileFromUri(Context context, Uri uri, String destinationPath) {
        InputStream is = null;
        BufferedOutputStream bos = null;
        try {
            is = context.getContentResolver().openInputStream(uri);
            bos = new BufferedOutputStream(new FileOutputStream(destinationPath, false));
            byte[] buf = new byte[1024];
            is.read(buf);
            do {
                bos.write(buf);
            } while (is.read(buf) != -1);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (is != null) is.close();
                if (bos != null) bos.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
`

**Comment by Blankj** [comment]
我需要更细粒度的。
```java
public static String getFileName(@NonNull Context context, Uri uri) {
    String mimeType = context.getContentResolver().getType(uri);
    String filename = null;

    if (mimeType == null) {
        String path = getPath(context, uri);
        if (path == null) {
            filename = getName(uri.toString());
        } else {
            File file = new File(path);
            filename = file.getName();
        }
    } else {
        Cursor returnCursor = context.getContentResolver().query(uri, null,
                null, null, null);
        if (returnCursor != null) {
            int nameIndex = returnCursor.getColumnIndex(OpenableColumns.DISPLAY_NAME);
            returnCursor.moveToFirst();
            filename = returnCursor.getString(nameIndex);
            returnCursor.close();
        }
    }

    return filename;
}
```
比如这个方法到底是哪个 return 的，要一个精简版本的

**Comment by Blankj** [comment]
@newlai913 有空的话帮我实现下哈

**Comment by diver2** [comment]
anyone translate?

**Comment by newlai913** [comment]
这个方法好像还是不行，我试了apk文件，复制后得到的文件貌似不能用了，所以还要换过另外的方法

**Comment by Blankj** [comment]
试试 1.24.0

**Comment by newlai913** [comment]
试了一下，结果是一样的，也是unknown uri

**Comment by 15050050972** [comment]
同样的问题

```
the version of utilcode: 1.26.0
device: 小米9 SE
device version: Android 9, API 28
```
选择`下载`里的文件，uri 为`content://com.android.providers.downloads.documents/document/239`
使用`UriUtils.uri2File(uri)`会崩溃
但使用`https://github.com/coltoscosmin/FileUtils/blob/master/FileUtils.java`可以正常运行

**Comment by Blankj** [comment]
@tianyuxf  试试 1.28.2 版本，https://github.com/Blankj/AndroidUtilCode/issues/1223
