### ISSUE TITLE
图片旋转问题

### ISSUE THREAD

**Issue by yuzhiqiang1993** [Blankj/AndroidUtilCode#863]
小米8 SE通过ImageUtils的getBitmap会导致图片旋转

**Comment by Blankj** [comment]
旋转我没做处理哦，我只是读取内容给 bitmap 而已哈

**Comment by AItsuki** [comment]
@yuzhiqiang1993 你看的图片旋转问题应该是相机方向的结果。不仅小米，很多手机的相机都是旋转了90度的，竖屏拍出来的是横屏的照片。所以getBitmap获取到的图片旋转了才是正确的结果，你可以获取图片的旋转角度自己旋转回去。
ps：如果你是通过相册直接选择一张图片显示到ImageView(通过setImageUri方式)时，ImageView会自动旋转该照片显示。

**Comment by yuzhiqiang1993** [comment]
嗯  我这边已经处理好了，忘了关了。
