### ISSUE TITLE
PermissionUtils 在请求单项权限的时候不好调用

### ISSUE THREAD

**Issue by zjianflys** [Blankj/AndroidUtilCode#867]
` private static final String[] GROUP_CUS = {
            permission.BLUETOOTH, permission.BLUETOOTH_ADMIN, permission.VIBRATE
    };`
我使用自定义这种    权限请求弹不出来？
不知道单项请求  是怎么请求的  常量里面的能请求到
` @StringDef({CALENDAR, CAMERA, CONTACTS, LOCATION, MICROPHONE, PHONE, SENSORS, SMS, STORAGE, CUS})
    @Retention(RetentionPolicy.SOURCE)
    public @interface Permission {
    }`

**Comment by zjianflys** [comment]
我试了一下危险权限  可以

**Comment by Blankj** [comment]
android 运行时权限了解一下
