### ISSUE TITLE
巴士插件没支持AndroidX

### ISSUE THREAD

**Issue by wexia** [Blankj/AndroidUtilCode#870]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

implementation 'com.blankj:utilcodex:1.23.7'

提示这个
PLUGIN-BUS >>> u should <implementation "com.blankj:utilcode:1.22.+">

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
你用了 gradle 的 bus 插件？

**Comment by wexia** [comment]
> 你用了 gradle 的 bus 插件？

是的 ヾ(◍°∇°◍)ﾉﾞ

**Comment by Blankj** [comment]
升级下版本 1.7

**Comment by Blankj** [comment]
没想到你这么超前啊，啥都用

**Comment by wexia** [comment]
> 没想到你这么超前啊，啥都用
=-= OK
