### ISSUE TITLE
建议：PhoneUtils增加获取手机号

### ISSUE THREAD

**Issue by Skqing** [Blankj/AndroidUtilCode#871]
建议：PhoneUtils增加获取手机号

**Comment by Skqing** [comment]
public static String getLine1Number(Context context) {
        TelephonyManager tm = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
        return tm.getLine1Number();
    }

**Comment by Blankj** [comment]
就不要搞这种费力也解决不了的事情了
