### ISSUE TITLE
SpanUtil设置模糊效果

### ISSUE THREAD

**Issue by loyilin** [Blankj/AndroidUtilCode#873]
setBlur 设置模糊效果， 一排文字没有全部生效，  设置radius最大也只有2个字有效果

SpanUtils.with(tv_time).appendLine(String.format("拍摄时间：%2s",dateTime)).setBlur(1f, BlurMaskFilter.Blur.NORMAL)
                                .create();

![image](https://user-images.githubusercontent.com/20967855/54798932-dcd07d80-4c95-11e9-883e-f4bb31f22c4c.png)
![TIM图片20190322112827](https://user-images.githubusercontent.com/20967855/54798918-caeeda80-4c95-11e9-804e-f8f012cfa39f.jpg)

**Comment by Blankj** [comment]
Android 自带的 bug 貌似是
