### ISSUE TITLE
BarUtils遇到的bug

### ISSUE THREAD

**Issue by Shirwee** [Blankj/AndroidUtilCode#876]
@Blankj 楼主，问一个关于BarUtils的问题，在Fragment中使用透明状态栏，跳转到登录页面，弹起软键盘，这时候点下返回按钮返回到上一个页面，会有一个和状态栏一样的高度的白色的条子。如果在点返回前隐藏软键盘，就不会有这个问题。

**Comment by Blankj** [comment]
录制个动画上来

**Comment by Shirwee** [comment]
![Uploading barutils.gif…]()

**Comment by Shirwee** [comment]
![barutils](https://user-images.githubusercontent.com/19380366/54905033-f6cec200-4f1a-11e9-9b0a-9bb27b0f7d4e.gif)

**Comment by Blankj** [comment]
相关代码发一下，我这边模拟一下

**Comment by Shirwee** [comment]
fragment_me中的xml：
----------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ScrollView
        android:id="@+id/contentWrap"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:clipChildren="false"
            android:orientation="vertical">

            <FrameLayout
                android:id="@+id/container"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dp_135"
                android:background="@drawable/shape_linear_gradient_bg" />

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="@dimen/dp_15"
                android:layout_marginTop="-45dp"
                android:layout_marginRight="@dimen/dp_15"
                android:background="@drawable/shape_corner_bg_white_4"
                android:elevation="@dimen/dp_2">

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginTop="-40dp"
                    android:layout_marginBottom="@dimen/dp_22"
                    android:gravity="center_horizontal"
                    android:orientation="vertical">

                    <de.hdodenhof.circleimageview.CircleImageView
                        android:id="@+id/iv_head"
                        android:layout_width="@dimen/dp_80"
                        android:layout_height="@dimen/dp_80"
                        android:scaleType="centerCrop"
                        android:src="@mipmap/icon_people_default"
                        app:civ_border_color="#FFFFFF"
                        app:civ_border_width="@dimen/dp_3" />

                    <TextView
                        android:id="@+id/tvName"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="@dimen/dp_10"
                        android:includeFontPadding="false"
                        android:text="未登录"
                        android:textColorHint="@color/color_33"
                        android:textSize="@dimen/sp_18" />
                </LinearLayout>
            </FrameLayout>

            <com.qmuiteam.qmui.widget.grouplist.QMUIGroupListView
                android:id="@+id/groupListView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/dp_10" />


            <com.flyco.roundview.RoundTextView
                android:id="@+id/btn_loginout"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dp_43"
                android:layout_gravity="center_horizontal"
                android:layout_margin="@dimen/dp_15"
                android:gravity="center"
                android:visibility="gone"
                android:text="退出登录"
                android:textColor="@color/white"
                android:textSize="@dimen/sp_17"
                app:rv_backgroundColor="#FF5050"
                app:rv_cornerRadius="@dimen/dp_22" />
        </LinearLayout>
    </ScrollView>

    <View
        android:id="@+id/barStatusImageViewFragmentFakeStatusBar"
        android:layout_width="match_parent"
        android:layout_height="0dp" />
</FrameLayout>

MeFragment中使用：
----------------------------------------------------------------------------------------------------
 BarUtils.setStatusBarColor(rootView.findViewById(R.id.barStatusImageViewFragmentFakeStatusBar), Color.argb(0, 0, 0, 0));
        FrameLayout container = rootView.findViewById(R.id.container);
        ViewGroup.LayoutParams layoutParams = container.getLayoutParams();
        layoutParams.height += BarUtils.getStatusBarHeight();

**Comment by Shirwee** [comment]
xml文件外层还有一个FrameLayout

**Comment by Shirwee** [comment]
我用你的demo模拟不出来这个问题

**Comment by Shirwee** [comment]
我发现是fitSystemWindows = true这行代码的问题
https://github.com/hehonghui/android-tech-frontier/blob/master/issue-35/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BB%AC%E8%A6%81%E7%94%A8fitsSystemWindows.md

**Comment by Blankj** [comment]
用我的状态栏适配是不需要加任何 fitSystemWindows = true 这行代码的
