### ISSUE TITLE
AppUtils#getApkInfo() 导致程序crash

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#877]
## Describe the bug

- The version of utilcode: 1.23.7
- The device: Android Tablet
- The version of device:  5.1.1 API 22

## The code of bug

```
AppUtils.AppInfo apkInfo = AppUtils.getApkInfo(fileInfo.getFilePath());
```

## The stack of crash

```
 java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference
        at com.blankj.utilcode.util.AppUtils.getApkInfo(AppUtils.java:788)
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
试试 1.24.0
