### ISSUE TITLE
建议 LogUtils 的输出日志长度3000可以自己设置

### ISSUE THREAD

**Issue by ViShadowFiend** [Blankj/AndroidUtilCode#878]
## Screenshots
![image](https://user-images.githubusercontent.com/22252325/55127158-2b749080-514a-11e9-8198-42513ad60d6a.png)
数据太长的话会被分割开, 复制起来不是很方便

**Comment by Blankj** [comment]
太长了 as 就不会输出了，明白了吗

**Comment by ViShadowFiend** [comment]
这样啊, 谢谢回复. 那有没有其他办法能处理这个问题呢

**Comment by Blankj** [comment]
除了分割 暂无他法
