### ISSUE TITLE
PinyinUtil 里无法识别部分汉字

### ISSUE THREAD

**Issue by Camsson** [Blankj/AndroidUtilCode#88]
用该工具类，会将覃，邝，闫，滕，邬等大量姓氏识别为 “zuo”

**Comment by FloHin** [comment]
I would be eager to help, but i don't understand

**Comment by huzhicheng1993** [comment]
岑 cen 的首字母会识别为z。以前做个汉字转拼音，因为存在多音字所以或多或少存在问题（做一些特殊处理），有一个库叫做pinyi4j倒是挺好用的。

**Comment by Blankj** [comment]
@huzhicheng1993 那个我知道，我不想引进jar包，常用的可以解决就好了，多音字的话就要加多音字的一个集合，后续等我完善吧

**Comment by Blankj** [comment]
@Camsson 现在试试，已经更新了哦，简繁体都可以
