### ISSUE TITLE
建议：CacheDiskUtils增加获取所有KEY的方法

### ISSUE THREAD

**Issue by Skqing** [Blankj/AndroidUtilCode#881]
建议：CacheDiskUtils增加获取所有KEY的方法

目的是做小量数据临时缓存，联网同步后删除缓存数据，但目前操作起来比较麻烦。因为无法根据KEY获取里面 的缓存

**Comment by Blankj** [comment]
新增多个 CacheDiskUtils 实例即可。

**Comment by Skqing** [comment]
> 新增多个 CacheDiskUtils 实例即可。

什么意思？我用的相同的示例啊，如果保存几百个数据还得几百个示例啊

**Comment by Skqing** [comment]
`
private DiskCacheManager(final File cacheDir, final long sizeLimit, final int countLimit) {
            this.cacheDir = cacheDir;
            this.sizeLimit = sizeLimit;
            this.countLimit = countLimit;
            cacheSize = new AtomicLong();
            cacheCount = new AtomicInteger();
            mThread = new Thread(new Runnable() {
                @Override
                public void run() {
                    int size = 0;
                    int count = 0;
                    final File[] cachedFiles = cacheDir.listFiles(new FilenameFilter() {
                        @Override
                        public boolean accept(File dir, String name) {
                            return name.startsWith(CACHE_PREFIX);
                        }
                    });
                    if (cachedFiles != null) {
                        for (File cachedFile : cachedFiles) {
                            size += cachedFile.length();
                            count += 1;
                            lastUsageDates.put(cachedFile, cachedFile.lastModified());
                        }
                        cacheSize.getAndAdd(size);
                        cacheCount.getAndAdd(count);
                    }
                }
            });
            mThread.start();
        }
`
这里已经统计了cacheSize和cacheCount，干嘛不用Set呢，key是文件的KEY，value可以是文件大小，这样一举三得，既能通过这个Set知道cacheSize和cacheCount又能获得所有的KEY。

**Comment by Blankj** [comment]
把你要删除的统一放在一个实例里就行啊，到时候统一删除就行，不需要根据 key 删除的

**Comment by Skqing** [comment]
是这样的，我首先 保存数据到缓存，然后在service里去一条一条取数据，但此时我并不知道缓存里的KEY是什么，我怎么取数据呢？除非自己定义有规则的KEY，但这样循环起来也很麻烦。

**Comment by Blankj** [comment]
那么你不需要知道 value 的类型的吗

**Comment by Skqing** [comment]
> 那么你不需要知道 value 的类型的吗

不需要，value的类型是固定的，并且可以根据KEY前缀判断类型。

**Comment by Skqing** [comment]
怎样，这个功能会添加吗？

**Comment by Blankj** [comment]
下版本加入哈

**Comment by Skqing** [comment]
好的，多谢！

**Comment by Blankj** [comment]
我使用 key 的 hashcode 作为文件名的，这个不能逆向过来，所以读取不到 key 的，除非我另换规则
