### ISSUE TITLE
ToastUtils 在未获取权限的时候 在页面后面显示。

### ISSUE THREAD

**Issue by androidflying** [Blankj/AndroidUtilCode#882]
## Describe the bug

- The version of utilcode: 1.23.7
- The device: OPPO-PBBM00
- The version of device: 8.1.0

**Comment by androidflying** [comment]
开启权限之后能正常显示

**Comment by androidflying** [comment]
demo也会出现一样的问题

**Comment by Blankj** [comment]
怎么个后面？上个图看看

**Comment by Blankj** [comment]
试试 1.24.0
