### ISSUE TITLE
在自定义application里重写了getResources方法导致白屏，view无法绘制

### ISSUE THREAD

**Issue by fansangg** [Blankj/AndroidUtilCode#886]
我在issues里看到了有一个说 悬浮窗适配需要在application里重写getResources，我这么做了之后app跑起来什么都无法绘制。嗯？这不是官方用法？

**Comment by Blankj** [comment]
什么设备？

**Comment by fansangg** [comment]
> 什么设备？

华为BND_AL00 
Android 8.0

**Comment by Blankj** [comment]
试试这份代码
```java
import android.content.res.Resources;
import android.util.DisplayMetrics;
import android.util.Log;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;


public final class AdaptScreenUtils {

    private static List<Field> sMetricsFields;

    /**
     * Adapt for the horizontal screen, and call it in [android.app.Activity.getResources].
     */
    public static Resources adaptWidth(final Resources resources, final int designWidth) {
        float newXdpi = (Resources.getSystem().getDisplayMetrics().widthPixels * 72f) / designWidth;
        applyDisplayMetrics(resources, newXdpi);
        return resources;
    }

    /**
     * Adapt for the vertical screen, and call it in [android.app.Activity.getResources].
     */
    public static Resources adaptHeight(final Resources resources, final int designHeight) {
        float newXdpi = (Resources.getSystem().getDisplayMetrics().heightPixels * 72f) / designHeight;
        applyDisplayMetrics(resources, newXdpi);
        return resources;
    }

    /**
     * @param resources The resources.
     * @return the resource
     */
    public static Resources closeAdapt(final Resources resources) {
        float newXdpi = Resources.getSystem().getDisplayMetrics().density * 72f;
        applyDisplayMetrics(resources, newXdpi);
        return resources;
    }

    /**
     * Value of pt to value of px.
     *
     * @param ptValue The value of pt.
     * @return value of px
     */
    public static int pt2Px(final float ptValue) {
        DisplayMetrics metrics = Utils.getApp().getResources().getDisplayMetrics();
        return (int) (ptValue * metrics.xdpi / 72f + 0.5);
    }

    /**
     * Value of px to value of pt.
     *
     * @param pxValue The value of px.
     * @return value of pt
     */
    public static int px2Pt(final float pxValue) {
        DisplayMetrics metrics = Utils.getApp().getResources().getDisplayMetrics();
        return (int) (pxValue * 72 / metrics.xdpi + 0.5);
    }

    private static void applyDisplayMetrics(final Resources resources, final float newXdpi) {
        resources.getDisplayMetrics().xdpi = newXdpi;
        Utils.getApp().getResources().getDisplayMetrics().xdpi = newXdpi;
        applyOtherDisplayMetrics(resources, newXdpi);
    }

    private static void applyOtherDisplayMetrics(final Resources resources, final float newXdpi) {
        if (sMetricsFields == null) {
            sMetricsFields = new ArrayList<>();
            Class resCls = resources.getClass();
            Field[] declaredFields = resCls.getDeclaredFields();
            while (declaredFields != null && declaredFields.length > 0) {
                for (Field field : declaredFields) {
                    if (field.getType().isAssignableFrom(DisplayMetrics.class)) {
                        field.setAccessible(true);
                        DisplayMetrics tmpDm = getMetricsFromField(resources, field);
                        if (tmpDm != null) {
                            sMetricsFields.add(field);
                            tmpDm.xdpi = newXdpi;
                        }
                    }
                }
                resCls = resCls.getSuperclass();
                if (resCls != null) {
                    declaredFields = resCls.getDeclaredFields();
                } else {
                    break;
                }
            }
        } else {
            applyMetricsFields(resources, newXdpi);
        }
    }

    private static void applyMetricsFields(final Resources resources, final float newXdpi) {
        for (Field metricsField : sMetricsFields) {
            try {
                DisplayMetrics dm = (DisplayMetrics) metricsField.get(resources);
                if (dm != null) dm.xdpi = newXdpi;
            } catch (Exception e) {
                Log.e("AdaptScreenUtils", "applyMetricsFields: " + e);
            }
        }
    }

    private static DisplayMetrics getMetricsFromField(final Resources resources, final Field field) {
        try {
            return (DisplayMetrics) field.get(resources);
        } catch (Exception e) {
            Log.e("AdaptScreenUtils", "getMetricsFromField: " + e);
            return null;
        }
    }
}
```

**Comment by fansangg** [comment]
> 试试这份代码
> 
> ```java
> import android.content.res.Resources;
> import android.util.DisplayMetrics;
> import android.util.Log;
> 
> import java.lang.reflect.Field;
> import java.util.ArrayList;
> import java.util.List;
> 
> 
> public final class AdaptScreenUtils {
> 
>     private static List<Field> sMetricsFields;
> 
>     /**
>      * Adapt for the horizontal screen, and call it in [android.app.Activity.getResources].
>      */
>     public static Resources adaptWidth(final Resources resources, final int designWidth) {
>         float newXdpi = (Resources.getSystem().getDisplayMetrics().widthPixels * 72f) / designWidth;
>         applyDisplayMetrics(resources, newXdpi);
>         return resources;
>     }
> 
>     /**
>      * Adapt for the vertical screen, and call it in [android.app.Activity.getResources].
>      */
>     public static Resources adaptHeight(final Resources resources, final int designHeight) {
>         float newXdpi = (Resources.getSystem().getDisplayMetrics().heightPixels * 72f) / designHeight;
>         applyDisplayMetrics(resources, newXdpi);
>         return resources;
>     }
> 
>     /**
>      * @param resources The resources.
>      * @return the resource
>      */
>     public static Resources closeAdapt(final Resources resources) {
>         float newXdpi = Resources.getSystem().getDisplayMetrics().density * 72f;
>         applyDisplayMetrics(resources, newXdpi);
>         return resources;
>     }
> 
>     /**
>      * Value of pt to value of px.
>      *
>      * @param ptValue The value of pt.
>      * @return value of px
>      */
>     public static int pt2Px(final float ptValue) {
>         DisplayMetrics metrics = Utils.getApp().getResources().getDisplayMetrics();
>         return (int) (ptValue * metrics.xdpi / 72f + 0.5);
>     }
> 
>     /**
>      * Value of px to value of pt.
>      *
>      * @param pxValue The value of px.
>      * @return value of pt
>      */
>     public static int px2Pt(final float pxValue) {
>         DisplayMetrics metrics = Utils.getApp().getResources().getDisplayMetrics();
>         return (int) (pxValue * 72 / metrics.xdpi + 0.5);
>     }
> 
>     private static void applyDisplayMetrics(final Resources resources, final float newXdpi) {
>         resources.getDisplayMetrics().xdpi = newXdpi;
>         Utils.getApp().getResources().getDisplayMetrics().xdpi = newXdpi;
>         applyOtherDisplayMetrics(resources, newXdpi);
>     }
> 
>     private static void applyOtherDisplayMetrics(final Resources resources, final float newXdpi) {
>         if (sMetricsFields == null) {
>             sMetricsFields = new ArrayList<>();
>             Class resCls = resources.getClass();
>             Field[] declaredFields = resCls.getDeclaredFields();
>             while (declaredFields != null && declaredFields.length > 0) {
>                 for (Field field : declaredFields) {
>                     if (field.getType().isAssignableFrom(DisplayMetrics.class)) {
>                         field.setAccessible(true);
>                         DisplayMetrics tmpDm = getMetricsFromField(resources, field);
>                         if (tmpDm != null) {
>                             sMetricsFields.add(field);
>                             tmpDm.xdpi = newXdpi;
>                         }
>                     }
>                 }
>                 resCls = resCls.getSuperclass();
>                 if (resCls != null) {
>                     declaredFields = resCls.getDeclaredFields();
>                 } else {
>                     break;
>                 }
>             }
>         } else {
>             applyMetricsFields(resources, newXdpi);
>         }
>     }
> 
>     private static void applyMetricsFields(final Resources resources, final float newXdpi) {
>         for (Field metricsField : sMetricsFields) {
>             try {
>                 DisplayMetrics dm = (DisplayMetrics) metricsField.get(resources);
>                 if (dm != null) dm.xdpi = newXdpi;
>             } catch (Exception e) {
>                 Log.e("AdaptScreenUtils", "applyMetricsFields: " + e);
>             }
>         }
>     }
> 
>     private static DisplayMetrics getMetricsFromField(final Resources resources, final Field field) {
>         try {
>             return (DisplayMetrics) field.get(resources);
>         } catch (Exception e) {
>             Log.e("AdaptScreenUtils", "getMetricsFromField: " + e);
>             return null;
>         }
>     }
> }
> ```

和之前的一样

**Comment by Blankj** [comment]
华为具体机器是啥，我这边可以试验下。
你可以看看这个 issue: https://github.com/Blankj/AndroidUtilCode/issues/869

**Comment by fansangg** [comment]
> 华为具体机器是啥，我这边可以试验下。
> 你可以看看这个 issue: #869

华为荣耀X7，集成了tinker，在tinker的applicationlike里重写getresources和我自己的application里写都无效

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/download/1.23.7/util_1_23_7.apk

**Comment by fansangg** [comment]
> 试试我的 demo：https://github.com/Blankj/AndroidUtilCode/releases/download/1.23.7/util_1_23_7.apk

你demo能跑，所以是我的问题？

**Comment by fansangg** [comment]
你demo的BaseApplication并没有重写getresources

**Comment by Blankj** [comment]
你 adaptScreenUtils 那个界面进去了正常的是吗

**Comment by fansangg** [comment]
> 你 adaptScreenUtils 那个界面进去了正常的是吗

是的，正常

**Comment by fansangg** [comment]
> 你 adaptScreenUtils 那个界面进去了正常的是吗

我之前使用，不在application重写也都是正常的

**Comment by Blankj** [comment]
悬浮窗用了 application 就有问题了是吗，这很奇怪

**Comment by fansangg** [comment]
> 悬浮窗用了 application 就有问题了是吗，这很奇怪

并没运用到悬浮窗，只是打算用，然后出现的这个问题
