### ISSUE TITLE
加固后AcitivityUtils部分功能失效的问题

### ISSUE THREAD

**Issue by franticn** [Blankj/AndroidUtilCode#887]
## Describe the bug

大致问题是这样的，我使用`ActivityUtils`管理APP中的任务栈，结果在调用`ActivityUtils#finshActivity`和`ActivityUtils#finshToActivity`时发现，debug包及未加固的混淆后的release包都可以正常调用，但是用加固后就不起作用了。

在查看issue时候发现，[#604](https://github.com/Blankj/AndroidUtilCode/issues/604)和我的问题很相似，但是我并没有调用过`Utils#init`，然后我在我的`Application`中调用此方法在进行混淆加固后问题就没有出现了。

但是您对应文档上面没有说需要对`Utils`进行初始化操作，所以我再次提一个issue询问一下您。

- The version of utilcode: 1.23.7
- The device:  Nexus6
- The version of device: Andoird 9.0

**Comment by Blankj** [comment]
我把初始化放在了 Utils 中的 provider 里了，所以外界无需初始化，加固的这个问题我也不是很清楚。
