### ISSUE TITLE
ToastLUtils在切换语言后没有及时更新,因为没有重启应用，有什么办法在不重启应用更新语言的？

### ISSUE THREAD

**Issue by DarshanYang** [Blankj/AndroidUtilCode#889]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
更新下我 application 的 resource
```java 
Resources resources = Utils.getApp().getResources();
DisplayMetrics dm = resources.getDisplayMetrics();
Configuration config = resources.getConfiguration();
config.locale = Locale.ENGLISH;
resources.updateConfiguration(config, dm);
```

**Comment by DarshanYang** [comment]
谢谢，问题解决了
