### ISSUE TITLE
NetworkUtils获取IP地址为何是跟在网上查询的本机IP不一样？

### ISSUE THREAD

**Issue by Lsy1992** [Blankj/AndroidUtilCode#89]

**Comment by Lsy1992** [comment]
每次获取到的都是局域网IP，怎么获取手机外网IP呢？

**Comment by Blankj** [comment]
你手机连外网就是外网的了吧

**Comment by Lsy1992** [comment]
不是的，工具类中查询到的其实是在手机网络信息里查到的一样，是内网IP，这样是查不到归属地的，我在网上找资料发现只能借助外部网站来查询外网的IP

**Comment by Blankj** [comment]
那我也没办法了

**Comment by scsfwgy** [comment]
@Blankj  有这个需求呀，比如网络特别慢，想要上传当时的ip,针对性的优化....没有办法吗？
