### ISSUE TITLE
现在手机号码有170开头的，阿里手机号码

### ISSUE THREAD

**Issue by zhuzhushang** [Blankj/AndroidUtilCode#891]
现在手机号码有170开头的，阿里手机号码 
这个精准验证 可能不准  public static final String REGEX_MOBILE_EXACT  = "^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(16[6])|(17[0,1,3,5-8])|(18[0-9])|(19[8,9]))\\d{8}$";
    /**

**Comment by Blankj** [comment]
是你 util 版本不够新吗

**Comment by Blankj** [comment]
试试 1.24.0
