### ISSUE TITLE
root权限机器 静默安装报这个错，大佬帮忙看看，谢谢

### ISSUE THREAD

**Issue by bux-git** [Blankj/AndroidUtilCode#892]
pkg:/storage/emulate/0/test.apk
INSTALL_FAILED_INVALID_APK
直接下载demo里面的运行也是一样，正常安装方法可以执行

**Comment by Blankj** [comment]
https://blog.csdn.net/nicebooks/article/details/7954048

**Comment by bux-git** [comment]
谢谢，大佬
