### ISSUE TITLE
ActivityUtils中@NonNull final Bundle options的注解问题

### ISSUE THREAD

**Issue by cymok** [Blankj/AndroidUtilCode#893]
请问<a href="https://github.com/Blankj/AndroidUtilCode/blob/master/utilcode/lib/src/main/java/com/blankj/utilcode/util/ActivityUtils.java">ActivityUtils.java</a>
类中多个方法的`@NonNull final Bundle options`参数的NonNull注解是否可去掉, 查看到源码中最后调用的地方已经做了判空了. 部分没有 部分有 此注解, 有的方法在实际使用中容易报NonNull警告. 虽然不影响正常使用, 但有代码洁癖的人看着难受, 也不想多此一举在调用处再次判空
</p>
部分没有注解的方法和, 部分有注解的方法

```
ActivityOptionsCompat compat = ActivityOptionsCompat.makeScaleUpAnimation(...);
ActivityUtils.startActivity(bundle, atyClass, compat.toBundle());//有警告
```

```
ActivityUtils.startActivity(atyClass, compat.toBundle());//没有警告
```

**Comment by Blankj** [comment]
你传入的第一个 bundle 可能为空是吗

**Comment by cymok** [comment]
@Blankj 不是第一个bundle,是后面的bundle. 有部分ActivityUtils.startActivity()方法的options参数有NonNull注解, 部分没有. 实际上现在给你代码传null是可以的, 你做了非空判断, 但方法的NonNull注解没去掉所以依然有警告

**Comment by Blankj** [comment]
下版本统一为 Nullable，之前忽略了
