### ISSUE TITLE
手机卡根目录下有个特殊文件,读取报错

### ISSUE THREAD

**Issue by SSSSunrise** [Blankj/AndroidUtilCode#894]
![image](https://user-images.githubusercontent.com/31717774/56260776-19638d80-610b-11e9-9a93-5c65ce66a3b4.png)
手机卡根目录下有个这种文件,读取报错

**Comment by Blankj** [comment]
带中文吗？

**Comment by SSSSunrise** [comment]
不带中文,手机里看是乱码
![image](https://user-images.githubusercontent.com/31717774/56403178-bf8dcf80-6292-11e9-945a-c5e02b2142ec.png)

**Comment by SSSSunrise** [comment]
而且无法删除,无法对其操作,手机连上电脑,在电脑上显示不出来这个文件.

**Comment by SSSSunrise** [comment]
![image](https://user-images.githubusercontent.com/31717774/56403362-96ba0a00-6293-11e9-99c5-f89261857994.png)

**Comment by Blankj** [comment]
所以你调用的是哪个方法报错的？

**Comment by SSSSunrise** [comment]
FileUtils.java.listFilesInDirWithFilter() 获取已经过滤的文件

**Comment by Blankj** [comment]
在那个 Activity 加上 android:debuggable="false"

**Comment by SSSSunrise** [comment]
好的，我试试

**Comment by SSSSunrise** [comment]
加了还是没用,不加这个正式打包成release版本却是可以使用的,就是调试debug没用

**Comment by Blankj** [comment]
谷歌的 bug，用 release 版本就行
