### ISSUE TITLE
PermissionUtils does not work on DialogFragment

### ISSUE THREAD

**Issue by Zulqurnain** [Blankj/AndroidUtilCode#895]
I am trying to request camera permission in dialog fragment but it always return true , even if not granted yet

Library version: 1.23.7
AndroidX

**Comment by Blankj** [comment]
- The device: 
- The version of device: 
??

**Comment by Zulqurnain** [comment]
- Device: SAMSUNG
- Android Version: 6.0

**Comment by Blankj** [comment]
Maybe the devide of Samsun didn‘t use Google's permissions control. You should adapt it yourself.
