### ISSUE TITLE
屏幕适配，可用屏幕高度并不一定等于heightPixels;

### ISSUE THREAD

**Issue by ziktang** [Blankj/AndroidUtilCode#896]
红米note5 miui10 ,当把虚拟键关闭之后，contentView的高度是把原导航栏区域高度算进去的，但是getResources().getDisplayMetrics().heightPixel;获取的确还是减去导航栏的高度，这样就会导致适配的屏幕高度变小，实际底部会留出导航栏区域的空白

**Comment by Blankj** [comment]
最外层布局一般都是 scrollview 啊，导航栏有没有都无所谓的吧，你控件写 pt 就会按设计图尺寸走的啊。

**Comment by ziktang** [comment]
> 最外层布局一般都是 scrollview 啊，导航栏有没有都无所谓的吧，你控件写 pt 就会按设计图尺寸走的啊。

我的意思是heightPixel，比实际可显示的区域要小，因为现在可显示的区域是包括导航栏那块区域的(导航栏隐藏了),但是heightPixel却不包括，这样会导致适配的整体尺寸要小于应该要有的效果。

**Comment by Blankj** [comment]
下版本会增加如下的一个方法：
```java
public static Resources adaptHeight(final Resources resources, final int designHeight, final boolean includeNavBar)
```
