### ISSUE TITLE
日志文件超过保存时间没有删除。

### ISSUE THREAD

**Issue by weihuawei** [Blankj/AndroidUtilCode#899]
## Describe the bug

日志文件超过保存时间没有删除。
- The version of utilcode: 1.23.7
- The version of device: api22

Utils.init(this);
Config config = LogUtils.getConfig();
        config.setBorderSwitch(true)
                .setConsoleFilter(LogUtils.E)
                .setConsoleSwitch(true)
                .setFilePrefix("jh")
                .setFileFilter(LogUtils.E)
                .setLogHeadSwitch(true)
                .setGlobalTag("jh")
                .setLogSwitch(true)
                .setLog2FileSwitch(true)
                .setDir(SDCardUtils.getSDCardPathByEnvironment()+"/jinheng/Log")
                .setSaveDays(3);

**Comment by Blankj** [comment]
应用重启就会删除了吧

**Comment by Blankj** [comment]
试试 1.24.0
