### ISSUE TITLE
建议对文件工具类增加一个监听

### ISSUE THREAD

**Issue by EoniJJ** [Blankj/AndroidUtilCode#90]
建议对文件工具类增加一个复制进度的回调，
在一些大文件复制的场景下这个还是蛮常用的。

**Comment by Blankj** [comment]
那还得计算总文件大小，然后根据复制的多少计算出百分比毁掉给你比分比是吗

**Comment by Blankj** [comment]
计算文件大小也是需要异步的哈，很慢的也是，这种的话你们自己根据我的代码去做就好了，我只提供方法，具体你们怎么处理你们自己办哈，我说的对吗

**Comment by EoniJJ** [comment]
等我有空写一下提交上来，你来决定整不整合哈~

**Comment by Blankj** [comment]
@EoniJJ 好哒
