### ISSUE TITLE
在全面屏手机上获取屏幕高度时没有包含状态栏高度

### ISSUE THREAD

**Issue by WangYang19980318** [Blankj/AndroidUtilCode#900]

**Comment by WangYang19980318** [comment]
建议采用以下方式获取屏幕高度
public static int[] getScreenSize(Context context) {
        int[] size = new int[2];

        WindowManager w = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
        Display d = w.getDefaultDisplay();
        DisplayMetrics metrics = new DisplayMetrics();
        d.getMetrics(metrics);
        // since SDK_INT = 1;
        int widthPixels = metrics.widthPixels;
        int heightPixels = metrics.heightPixels;

        // includes window decorations (statusbar bar/menu bar)
        if (Build.VERSION.SDK_INT >= 14 && Build.VERSION.SDK_INT < 17)
            try {
                widthPixels = (Integer) Display.class.getMethod("getRawWidth").invoke(d);
                heightPixels = (Integer) Display.class.getMethod("getRawHeight").invoke(d);
            } catch (Exception ignored) {
            }
        // includes window decorations (statusbar bar/menu bar)
        if (Build.VERSION.SDK_INT >= 17)
            try {
                Point realSize = new Point();
                Display.class.getMethod("getRealSize", Point.class).invoke(d, realSize);
                widthPixels = realSize.x;
                heightPixels = realSize.y;
            } catch (Exception ignored) {
            }
        size[0] = widthPixels;
        size[1] = heightPixels;
        return size;
    }

来自https://www.jianshu.com/p/b7594ae3900f

**Comment by Blankj** [comment]
你用的是什么版本？

**Comment by WangYang19980318** [comment]
> 你用的是什么版本？

com.blankj:utilcode:1.23.7

**Comment by Blankj** [comment]
```java
public static int getScreenHeight() {
    WindowManager wm = (WindowManager) Utils.getApp().getSystemService(Context.WINDOW_SERVICE);
    if (wm == null) return -1;
    Point point = new Point();
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
        wm.getDefaultDisplay().getRealSize(point);
    } else {
        wm.getDefaultDisplay().getSize(point);
    }
    return point.y;
}
```
我这个用的就是 getRealSize 啊

**Comment by WangYang19980318** [comment]
> ```java
> public  static  int getScreenHeight（）{
>      WindowManager wm =（WindowManager）Utils 。getApp（）。getSystemService（上下文。 WINDOW_SERVICE）;
>     if（wm ==  null）return  - 1 ;
>     Point point =  new  Point（）;
>     如果（构建。 VERSION 。 SDK_INT  > =  生成。 VERSION_CODES 。JELLY_BEAN_MR1）{
>         WM 。getDefaultDisplay（）。getRealSize（点）;
>     } else {
>         WM 。getDefaultDisplay（）。的getSize（点）;
>     }
>     回归点。Ÿ;
> }
> ```
> 
> 我这个用的就是getRealSize啊

抱歉  是我老眼昏花 木有看清 之前用ScreenUtils测的小米Max系列获取到的屏幕高度不包含状态栏  可能是设备或者我的代码的问题  待我明天再测一下再给你答复

**Comment by WangYang19980318** [comment]
> ```java
> public static int getScreenHeight() {
>     WindowManager wm = (WindowManager) Utils.getApp().getSystemService(Context.WINDOW_SERVICE);
>     if (wm == null) return -1;
>     Point point = new Point();
>     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
>         wm.getDefaultDisplay().getRealSize(point);
>     } else {
>         wm.getDefaultDisplay().getSize(point);
>     }
>     return point.y;
> }
> ```
> 
> 我这个用的就是 getRealSize 啊

抱歉  我是我写的代码有问题  ScreenUtils能够正确获取到屏幕的高度  我用两种方法设置Dialog高度时的代码有问题，导致了我的误判  没有能够正确的发现问题所在  再次抱歉!
