### ISSUE TITLE
使用Toast出现异常

### ISSUE THREAD

**Issue by FynnJason** [Blankj/AndroidUtilCode#901]
W/System.err: java.lang.Exception: denglibo Toast callstack! strTip=章节已经全部缓存啦~
W/System.err:     at android.widget.Toast.show(Toast.java:127)
W/System.err:     at com.blankj.utilcode.util.ToastUtils$SystemToast.show(ToastUtils.java:384)
W/System.err:     at com.blankj.utilcode.util.ToastUtils$1.run(ToastUtils.java:265)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Blankj** [comment]
什么版本什么设备都不说的吗？这我怎么确定啊
