### ISSUE TITLE
大佬这个吐司工具类在个别机型没有通知栏权限会显示不出来。

### ISSUE THREAD

**Issue by xuehao0217** [Blankj/AndroidUtilCode#902]
大佬这个吐司工具类在个别机型没有通知栏权限会显示不出来。建议参考下进行~修改谢谢！https://github.com/getActivity/ToastUtils

**Comment by xuehao0217** [comment]
大佬这个吐司工具类在个别机型没有通知栏权限会显示不出来。建议参考下进行~修改谢谢！https://github.com/getActivity/ToastUtils

**Comment by Blankj** [comment]
1.24.0 已修复，支持全机型
