### ISSUE TITLE
isAppForegound()在使用中遇到问题

### ISSUE THREAD

**Issue by Halo-CHN** [Blankj/AndroidUtilCode#903]
您好，是这样，由于我的App有推送功能，源码中 for循环调用下段代码
return aInfo.processName.equals(Utils.getApp().getPackageName()); 
若此时aInfo为推送服务实例，aInfo.processName为推送服务channel名，导致直接返回false；

修改了代码如下：
static boolean isAppForeground() {
        ActivityManager am = (ActivityManager) Utils.getApp().getSystemService(Context.ACTIVITY_SERVICE);
        if (am == null) return false;
        List<ActivityManager.RunningAppProcessInfo> info = am.getRunningAppProcesses();
        if (info == null || info.size() == 0) return false;
        for (ActivityManager.RunningAppProcessInfo aInfo : info) {
            if (aInfo.importance == ActivityManager.RunningAppProcessInfo.IMPORTANCE_FOREGROUND) {
                if (aInfo.processName.equals(AppUtils.getAppPackageName())) {
                    return true;
                }
            }
        }
        return false;
    }

**Comment by Blankj** [comment]
好的 下版本修复

**Comment by Blankj** [comment]
1.24.0 已修复
