### ISSUE TITLE
NetworkUtils.getIPAddress

### ISSUE THREAD

**Issue by daidaishuiping** [Blankj/AndroidUtilCode#904]
ANR Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it. Outbound queue length: 0. Wait queue length: 1.)

com.blankj.utilcode.util.NetworkUtils.getIPAddress(NetworkUtils.java)

**Comment by Blankj** [comment]
1.24.0 使用 getIPAddressAsync
