### ISSUE TITLE
GsonUitls.fromjson方法有错误

### ISSUE THREAD

**Issue by luomantic** [Blankj/AndroidUtilCode#907]
没有抓logo了：
解析下面这段json可还原错误
`{"WINDOWS":{"x":0,"y":0,"w":1280,"h":800,"VERSIONINFO":{"version":"1.0.0","timeDate":"2018-03-02"},"PROGRAM":{"startDate":"2012-06-03","endDate":"2035-12-12","nConfigType":0,"nDispTimes":1,"nweekList":"0,1,2,3,4,5,6","PRGORAMNAME":"prog003","nMaCount":1},"MAIN_WINDOW":{"ZERO":{"x":640,"y":0,"w":640,"h":100},"ITEMS":{"ITEM":[{"FILE":{"filename":"\/3\/000.txt","filetype":68},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"т̎ͥ","fontsize":72,"textcolor":33023,"backcolor":0}},{"FILE":{"filename":"\/3\/001.JPG","filetype":48},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"","fontsize":0,"textcolor":0,"backcolor":0}}]}},"SUB_WINDOW":[{"ZERO":{"x":640,"y":100,"w":640,"h":600},"ITEMS":{"ITEM":[{"FILE":{"filename":"\/3\/001.JPG","filetype":48},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"","fontsize":0,"textcolor":0,"backcolor":0}},{"FILE":{"filename":"\/3\/000.txt","filetype":68},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"т̎ͥ","fontsize":72,"textcolor":33023,"backcolor":0}}]}},{"ZERO":{"x":0,"y":400,"w":640,"h":400},"ITEMS":{"ITEM":[{"FILE":{"filename":"\/3\/002.gif","filetype":33},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"","fontsize":0,"textcolor":0,"backcolor":0}},{"FILE":{"filename":"\/3\/003.mp4","filetype":48},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"","fontsize":0,"textcolor":0,"backcolor":0}}]}},{"ZERO":{"x":0,"y":0,"w":640,"h":400},"ITEMS":{"ITEM":[{"FILE":{"filename":"\/3\/003.mp4","filetype":48},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"","fontsize":0,"textcolor":0,"backcolor":0}},{"FILE":{"filename":"\/3\/000.txt","filetype":68},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"т̎ͥ","fontsize":72,"textcolor":33023,"backcolor":0}},{"FILE":{"filename":"\/3\/001.JPG","filetype":48},"SHOWFORMAT":{"showtype":0,"InType":2,"inSpeed":16,"stayTime":0},"FONTCOLOR":{"fontname":"","fontsize":0,"textcolor":0,"backcolor":0}}]}}]}}`

**Comment by Blankj** [comment]
这个应该去 gson 那边问一下哈

**Comment by luomantic** [comment]
> 这个应该去 gson 那边问一下哈

引入gson解析成功：
utils版本：implementation 'com.blankj:utilcode:1.23.7'
gson版本：implementation 'com.google.code.gson:gson:2.8.5'

please check thinx

**Comment by Blankj** [comment]
试试把 implementation 改成 api，然后不用引入 gson

**Comment by luomantic** [comment]
> 试试把 implementation 改成 api，然后不用引入 gson

OK 这样子的话就没问题了!
