### ISSUE TITLE
UriUtils.uri2File(uri)

### ISSUE THREAD

**Issue by s8cm** [Blankj/AndroidUtilCode#909]
uri.toString -> {
content://com.tencent.mtt.fileprovider/QQBrowser/soushuwang/file/-1720568076/1120213.txt
}

val file  = UriUtils.uri2File(uri)

the file is null

i fo le

all it ->

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4398, result=-1, data=Intent { dat=content://com.tencent.mtt.fileprovider/QQBrowser/PixivPictures/73448232_p3.jpeg typ=file/* flg=0x3 }}
......
......
 Caused by: java.lang.IllegalStateException: file must not be null

and

uri = content://com.android.providers.downloads.documents/document/31
文件名含有中文字符
it also retrun null
我佛了

**Comment by Blankj** [comment]
试试 1.24.0
