### ISSUE TITLE
ResourceUtils中建议增加以下方法

### ISSUE THREAD

**Issue by XXQAQ** [Blankj/AndroidUtilCode#914]
public static int getIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "id", getApp().getPackageName());
    }

    public static int getStringIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "string", getApp().getPackageName());
    }

    public static int getColorIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "color", getApp().getPackageName());
    }

    public static int getDimenIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "dimen", getApp().getPackageName());
    }

    public static int getDrawableIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "drawable", getApp().getPackageName());
    }

    public static int getMipmapIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "mipmap", getApp().getPackageName());
    }

    public static int getLayoutIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "layout", getApp().getPackageName());
    }

    public static int getStyleIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "style", getApp().getPackageName());
    }

    public static int getAnimIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "anim", getApp().getPackageName());
    }

    public static int getMenuIdByName(String name) {
        return getApp().getResources().getIdentifier(name, "menu", getApp().getPackageName());
    }

**Comment by XXQAQ** [comment]
只获取drawable还是太少了建议全部加上

**Comment by Blankj** [comment]
1.24.0 已新增
