### ISSUE TITLE
LogUtils的LogBorderSwitch分行机制对中文支持不好

### ISSUE THREAD

**Issue by fly904021125** [Blankj/AndroidUtilCode#916]
## Describe the bug

- The version of utilcode: 1.23.0
- The device: 
- The version of device: API 27 

## The code of bug

     StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 1024; i++) {
            sb.append("{测试内容 = ").append(i).append("}");
        }
        LogUtils.d(sb.toString());

## Screenshots
库中的核心判断代码如下：

    int len = msg.length();
    int countOfSub = len / MAX_LEN;

建议改成： 

    int len = msg.getBytes().length();
    int countOfSub = len / MAX_LEN;

**Comment by Blankj** [comment]
这不行的，后面 substring 不是根据这个 len 来会出问题的，我把 MAX_LEN 值改小点到 2000 好了

**Comment by Blankj** [comment]
1.24.0 已修复

**Comment by fly904021125** [comment]
修改MAX_LEN不失为一种有效率的方法

    public static List<String> splitLog(String msg) {
        List<String> list = new ArrayList<>();
        int index = 0;
        int step = 1;
        while (index < msg.length()) {
            int stepTotal = step * 500;
            boolean isEnd = false;
            if (stepTotal + index > msg.length()) {
                stepTotal = msg.length() - index;
                isEnd = true;
            }
            if (msg.substring(index, index + stepTotal).getBytes().length > MAX_LEN || isEnd && step == 1) {
                if (isEnd && step == 1) {
                    list.add(msg.substring(index, index + stepTotal));
                    index = index + stepTotal;
                } else {
                    step--;
                    list.add(msg.substring(index, index + step * 500));
                    index = index + step * 500;
                }

                step = 1;
            } else {
                step++;
            }

        }
        return list;
    }

这是个人所写的将一个长字符串分割成小于MAX_LEN字节长度的字符串List的方法，可能对您后续优化会有帮助

**Comment by Blankj** [comment]
已经修复了哈
