### ISSUE TITLE
关于SpanUtils构造出来的的SpannableStringBuilder无法利用Intent|Bundle跨页面传值的解决方法

### ISSUE THREAD

**Issue by XXQAQ** [Blankj/AndroidUtilCode#918]
由于项目需求，有些SpannableStringBuilder数据需要跨页面传值调用，实际操作后发现没有作用。经过查询源码后发现是SpannableStringBuilder本身并没有实现任何序列号接口，这样导致富文本对象无法通过Intent|Bundle传值。不过还好SpannableStringBuilder中的所有属性都都满足Serializable定义要求，只要继承SpannableStringBuilder并自行实现序列化接口并使用该继承类即可

在SpanUtils中新增
    public static class CustomSpannableStringBuilder extends SpannableStringBuilder implements Serializable {
        
    }

并在初始化阶段使用即可
`mBuilder = new CustomSpannableStringBuilder();`

**Comment by Blankj** [comment]
1.24.0 已新增
