### ISSUE TITLE
适配问题，直接写pt数值变得很小

### ISSUE THREAD

**Issue by li-xiaojun** [Blankj/AndroidUtilCode#919]
utilcode version: 1.23.7
activity重写getResource：
```kotlin
override fun getResources(): Resources {
        return AdaptScreenUtils.adaptWidth(super.getResources(), 720)
    }
```
布局文件中直接写pt，运行出来比直接写dp要小一半左右，为什么呢？

**Comment by Blankj** [comment]
你写的 xxpt 占的是 xx / 720 的百分比， dp 就还是 dp

**Comment by li-xiaojun** [comment]
设计图是720x1080，如果一个view的高度在设计图上是100px，pt应该怎么写呢

**Comment by Blankj** [comment]
设计图宽度是 720px， view 高度是 100px，那么 adaptWidth 720， view 写 100 pt 就行啊

**Comment by li-xiaojun** [comment]
明白了，感谢大佬

**Comment by li-xiaojun** [comment]
@Blankj 
我想问下，文字大小怎么写，如果写sp，预览的时候很小，如果写pt的话也能自动适配吗？
