### ISSUE TITLE
variant.getJavaCompiler()过时

### ISSUE THREAD

**Issue by yuchen931201** [Blankj/AndroidUtilCode#923]
## Describe the bug

- The version of utilcode:
`implementation 'com.blankj:utilcodex:1.23.7'`
 
- The device: 
- The version of device: 

## The code of bug

```
put your code here

`WARNING: API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompiler(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app`

```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by roybill** [comment]
把项目根build.gradle内的gradle版本调低就可以了,比如我以前是classpath 'com.android.tools.build:gradle:3.4.0',现在改为classpath 'com.android.tools.build:gradle:3.2.1'就可以了

**Comment by yuchen931201** [comment]
额，这样对我不是最好的解决方案。。。 我的新项目中用了很多kotlin支持的新插件，并且还要兼容flutter的环境，虽然3.2- 3.4.0 是正好可以支持的，担心以后的新插件会有不兼容问题必须3.4.0， 降版本可能不太好。。。
