### ISSUE TITLE
日志打印边框格式问题

### ISSUE THREAD

**Issue by fansangg** [Blankj/AndroidUtilCode#925]
边框不能对齐，之前用Alog也是这样，是我ide设置的问题？

**Comment by fansangg** [comment]
<img width="1245" alt="屏幕快照 2019-05-20 下午2 37 22" src="https://user-images.githubusercontent.com/17351112/58001514-42ae7980-7b0e-11e9-81b4-3a45f3ee8c17.png">

**Comment by fansangg** [comment]
<img width="1020" alt="屏幕快照 2019-05-20 下午2 50 41" src="https://user-images.githubusercontent.com/17351112/58001647-aa64c480-7b0e-11e9-9800-ecc6039a1a95.png">
json也无法格式化，这是为什么...

**Comment by fansangg** [comment]
这是我的json 

{"data":[],"message":"获取购物车商品信息成功！","status":"200","sign":"a439b9d09393328ae929921b7da1c197"}

**Comment by fansangg** [comment]
边框不能对齐的原因找到了 是因为我logcat开启了换行

**Comment by liyujiang-gzu** [comment]
![图片](https://user-images.githubusercontent.com/16816717/58063424-cc168800-7bb0-11e9-9a12-0ba6ad937447.png)
楼上正解，不要选中它就可以

**Comment by fansangg** [comment]
@Blankj  大佬，我的在okhttp interceptor里log返回的json，为什么不能格式化？
