### ISSUE TITLE
非root权限下的静默升级貌似失败

### ISSUE THREAD

**Issue by dongyiming** [Blankj/AndroidUtilCode#926]
/**
     * 静默安装App
     * <p>非root需添加权限 {@code <uses-permission android:name="android.permission.INSTALL_PACKAGES" />}</p>
     *
     * @param filePath 文件路径
     * @return {@code true}: 安装成功<br>{@code false}: 安装失败
     */
    public static boolean installAppSilent(String filePath) {
        File file = FileUtils.getFileByPath(filePath);
        if (!FileUtils.isFileExists(file)) return false;
        String command = "LD_LIBRARY_PATH=/vendor/lib:/system/lib pm install " + filePath;
        ShellUtils.CommandResult commandResult = ShellUtils.execCmd(command, false, true);
        String errorMsg = commandResult.errorMsg;
        return commandResult.successMsg != null && commandResult.successMsg.toLowerCase().contains("success");
    }

这个应该必须root吧？

**Comment by Blankj** [comment]
看看这个 issue：https://github.com/Blankj/AndroidUtilCode/issues/788
