### ISSUE TITLE
Logutils打印长日志分段显示数据缺失的问题

### ISSUE THREAD

**Issue by fansangg** [Blankj/AndroidUtilCode#927]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/17351112/58161757-6f4fc600-7cb3-11e9-9e72-d23978269aa3.png">

当日志超出4K？分段继续打印超出部分时，中间有一部分数据会丢失

**Comment by Blankj** [comment]
因为有中文的缘故，下版本会修复的

**Comment by Blankj** [comment]
1.24.0 已修复
