### ISSUE TITLE
权限工具类未适配5.0部分手机并且Rational弹窗和拒绝弹窗报错

### ISSUE THREAD

**Issue by KaelInvoker** [Blankj/AndroidUtilCode#932]
oppo a59s 已经关闭了存储和摄像权限，但用工具类检测出来是有的

**Comment by KaelInvoker** [comment]
![image](https://user-images.githubusercontent.com/37531571/58367527-1ed6a380-7f13-11e9-853a-b42c4e2f3774.png)
在弹出ration弹窗时，弹窗显示不出来，并报这个错误

**Comment by KaelInvoker** [comment]
![image](https://user-images.githubusercontent.com/37531571/58367657-86d9b980-7f14-11e9-81d4-a3b623811395.png)
![image](https://user-images.githubusercontent.com/37531571/58367669-9c4ee380-7f14-11e9-8908-2ae4fe748813.png)
我这样改就解决了

**Comment by Blankj** [comment]
运行时权限是 6.0 才有的哦，6.0 以下的我这边不予处理的，直接返回 true'

**Comment by KaelInvoker** [comment]
@Blankj 是的 大佬 为什么我拷贝出去就报错了？

**Comment by Blankj** [comment]
我在 DialogHelper 获取到的 topActivity 不可取因为，我在 Utils 中生命周期判断了
