### ISSUE TITLE
ClickSpan设置后，ForegroundColorSpan失效

### ISSUE THREAD

**Issue by xcc410922911** [Blankj/AndroidUtilCode#935]
同一段文字，同时设置ClickSpan和ForegroundColorSpan，ClickSpan的linkColor会覆盖ForegroundColorSpan。

**Comment by Blankj** [comment]
clickSpan 可以自己定义颜色

**Comment by nxnyk** [comment]
> clickSpan 可以自己定义颜色

怎么自定义呀。没看到方法

**Comment by Blankj** [comment]
看 demo 去吧

**Comment by nxnyk** [comment]
> 看 demo 去吧

刚刚看到了。。哈哈

**Comment by nxnyk** [comment]
> 看 demo 去吧

            @Override
            public void updateDrawState(@NonNull TextPaint ds) {
                super.updateDrawState(ds);
                ds.linkColor = Color.parseColor("#FFFFB946");
            }

我设置了颜色 但是没有生效。。咋回事

**Comment by nxnyk** [comment]
> > 看 demo 去吧
> 
> 刚刚看到了。。哈哈

用paint的方法 设置了。。。好了~
