### ISSUE TITLE
建议将ShellUtils和root相关放到subutil，部分应用如果去过检测的话，会提示root权限问题

### ISSUE THREAD

**Issue by DaiFalin** [Blankj/AndroidUtilCode#937]
建议将ShellUtils和root相关放到subutil，部分应用如果去过检测的话，会提示root权限问题

**Comment by Blankj** [comment]
项目开启混淆即可，你没用到的自然会剃掉的

**Comment by DaiFalin** [comment]
好的

**Comment by OvenCroc** [comment]
大佬我想问一下 shellutils 这个类里面的方法需要手机root才可以么? 我试了一下会报 permission denied错
