### ISSUE TITLE
LogUtils has some errors

### ISSUE THREAD

**Issue by xiexin52k** [Blankj/AndroidUtilCode#938]
## Describe the bug

- The version of utilcode: 1.24.0
- The device: Genymotion
- The version of device: 25

## The code of bug

```java
LogUtils.getConfig()
                .setLogSwitch(true)
                .setConsoleSwitch(true)
                .setGlobalTag("demo (" + BuildConfig.VERSION_CODE + ")---> ")
                .setLogHeadSwitch(true)
                .setLog2FileSwitch(true)
                .setDir(new File(getExternalFilesDir(null), "DemoLog"))
                .setFilePrefix("serviceframework")
                .setBorderSwitch(true)
                .setSingleTagSwitch(true)
                .setConsoleFilter(LogUtils.V)
                .setFileFilter(LogUtils.V)
                .setSaveDays(30)
        ;
```

```java
LogUtils.iTag(TAG, "test log");
```

## The stack of crash
No crash.  but "Date of Log" is error. for example:
```
************* Log Head ****************
Date of Log        : nable.demo
Device Manufacturer: Genymotion
Device Model       : Custom Tablet
Android Version    : 7.1.1
Android SDK        : 25
App VersionName    : 1.0
App VersionCode    : 1
************* Log Head ****************
```

In your LogUtils source code , i find this:

```java
String time = filePath.substring(filePath.length() - 14, filePath.length() - 4);
```

Are you kidding me?
How can you think that the last 14 character of a file name is the beginning of the time?
In The old version, There is no process name for the file name.
You need a different way to get time.

## The Second.
~~LogUtils fileName contains "-" , same systems not support this path. can you replace to "_" or other ? this helps improve compatibility.~~

## The Third.
Can file names support custom suffixes? "txt" is easy to find and change, or easily cleared by other apps

**Comment by Blankj** [comment]
这么叼的吗，English，1.24.0 这个版本修复了吧

**Comment by xiexin52k** [comment]
OFO告诉我们,  中文不好推押金. 要伪装成老外, 问题才能妥善解决. 😂😂😂

**Comment by xiexin52k** [comment]
sorry,文件名的中划线问题不大, 出问题的是在多进程中, 子进程以冒号 : 作为进程名的时候文件名会带上冒号, 而冒号在某些设备系统中不能用作文件名的.

**Comment by Blankj** [comment]
1.24.2 published
