### ISSUE TITLE
Android 9.0 Level 28 关于隐私API的使用限制

### ISSUE THREAD

**Issue by fishwjy** [Blankj/AndroidUtilCode#941]
## Describe the bug
Android 9.0 Level 28 限制使用隐私API
不知道'com.blankj:utilcode:1.24.2'这个版本做相应处理了吗？在Android9.0机器上能正常运行否？

感谢您的库，为广大我们节省了很多时间，提供了很好的解决方案！

**Comment by fishwjy** [comment]
手边没有9.0的真机，在模拟器上试了一下，没有崩溃
主要是看到Util中getApplicationByReflect()函数通过反射获取Context，不过看代码，一般情况下，似乎都不会走反射获取Context的那个分支，所以想请问一下，本库中的代码是否能在9.0 上顺利运行，多谢解答！

`public static void init(final Application app) {
        if (sApplication == null) {
            if (app == null) { // 这里一般情况下都是不为空的，所以一般都不会调用反射获取那个函数
                sApplication = getApplicationByReflect();
            } else {
                sApplication = app;
            }
            sApplication.registerActivityLifecycleCallbacks(ACTIVITY_LIFECYCLE);
        } else {
            if (app != null && app.getClass() != sApplication.getClass()) {
                sApplication.unregisterActivityLifecycleCallbacks(ACTIVITY_LIFECYCLE);
                ACTIVITY_LIFECYCLE.mActivityList.clear();
                sApplication = app;
                sApplication.registerActivityLifecycleCallbacks(ACTIVITY_LIFECYCLE);
            }
        }
    }`

**Comment by Blankj** [comment]
我在 Utils 中的 FileProvider 中会初始化的，不会走到 反射 的地方的，那只是我对其最终的容错处理而已
