### ISSUE TITLE
建议：FileUtils增加方法，刷新MediaScanner状态，或直接在执行文件操作时执行刷新

### ISSUE THREAD

**Issue by zhousongchao** [Blankj/AndroidUtilCode#943]
fun notifySystemToScan(filePath: String) {
        val intent = Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE)
        val file = File(filePath)
        val uri = Uri.fromFile(file)
        intent.data = uri
        Utils.getApp().sendBroadcast(intent)
}

**Comment by Blankj** [comment]
1.26.0 的 FileUtils 中加了 notifySystemToScan 方法可以调用
