### ISSUE TITLE
东西很全，但是有个建议

### ISSUE THREAD

**Issue by DanteAndroid** [Blankj/AndroidUtilCode#95]
首先感谢作者的辛苦劳动。但是这个库有个地方我很不满意，就是竟然没有context free。就是可以提供一个init接口，初始化application的context，这样很多只要求application的context的utils就可以不用传入context。
例如`SPUtils`我想保存东西发现竟然不能直接调用静态方法。（以防不知道，有一个`PreferenceManager.getDefaultSharedPreferences()
`方法可以传入application的context）
另外，
```
    public void putInt(String key, int value) {
        editor.putInt(key, value).apply();
    }
    public void putString(String key, String value) {
        editor.putString(key, value).apply();
    }

```
竟然没有使用重载，也许我too young，实在无法理解。

**Comment by jp1017** [comment]
> 竟然没有使用重载，也许我too young，实在无法理解。

怎么重载？？？

**Comment by DanteAndroid** [comment]
```
    public static void save(String key, String value) {
        editor.putString(key, value);
        editor.apply();
    }
    public static void save(String key, boolean value) {
        editor.putBoolean(key, value);
        editor.apply();
    }
    public static void save(String key, int value) {
        editor.putInt(key, value);
        editor.apply();
    }
```
这是我写的util，这样一个save 方法，根据需要传入int、String、bool都可以。

**Comment by Blankj** [comment]
@DanteAndroid 第一个提议不错， 第二个你虽然save可以有很多重载，但是取呢，还是得写成我这样的，可以参考Bundle的读写亦是如此。

**Comment by DanteAndroid** [comment]
取我知道不能写重载啊。。谢谢采纳。

**Comment by Blankj** [comment]
@DanteAndroid 所以为了对称，不然看着舒服吗

**Comment by jp1017** [comment]
> 所以为了对称，不然看着舒服吗

强迫症重度患者

**Comment by Blankj** [comment]
@jp1017 这也是设计之美，不然Bundle的put和SP原生的put都可以封装为一个save哈

**Comment by jp1017** [comment]
> 这也是设计之美

这波我服 :+1: :smile:

**Comment by DanteAndroid** [comment]
@Blankj 说为了对称，我没意见。但是后面举例感觉完全不是一回事。官方提供的方法本来就该是低耦合的，不会帮你封装太多的

**Comment by Blankj** [comment]
仁者见仁智者见智吧

**Comment by Blankj** [comment]
@DanteAndroid 已加入`Utils.init(context);`来初始化
