### ISSUE TITLE
请问下导入项目就报错是什么问题

### ISSUE THREAD

**Issue by qzqs** [Blankj/AndroidUtilCode#950]
导入AS就报错：文件缺失
Error:Could not read script 'E:\YG\YGGIT\AndroidUtilCode-master\AndroidUtilCode-master\gradle\config\config.gradle' as it does not exist.

**Comment by Blankj** [comment]
你是 windows 吗

**Comment by qzqs** [comment]
是的，我是Windows7系统

**Comment by Blankj** [comment]
文件路径不对，怎么会有两个 AndroidUtilCode-master 呢

**Comment by qzqs** [comment]
不是呀，另一个是我新建的文件夹，只是路径而已。文件夹里面就只有项目而已。

**Comment by Blankj** [comment]
那事实上 config.gradle 路径对吗

**Comment by qzqs** [comment]
我发现下载下来的项目都没有config.gradle这个文件...

**Comment by Blankj** [comment]
github 上面有的啊

**Comment by qzqs** [comment]
我又重新全部导入了您的项目，还是报错Gradle 'AndroidUtilCode-master' project refresh failed
Error:Failed to notify build listener. 好难哦，就是想看下源码而已。

**Comment by qzqs** [comment]
我现在是用AS3.1.2 gla版本是4.4。

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases
在这里面选个版本下 source-code 就行吧
