### ISSUE TITLE
UriUtils.uri2File(uri)选择下载内容里的文件会崩溃

### ISSUE THREAD

**Issue by beiger** [Blankj/AndroidUtilCode#954]
Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/app-release1.30.apk"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.valueOf(Long.java:808)
        at com.blankj.utilcode.util.UriUtils.uri2File(UriUtils.java:81)

![image](https://user-images.githubusercontent.com/18483100/59581422-724da300-9107-11e9-9033-86fce5c0dfc4.png)
Long.valueOf(id),id是"raw:/storage/emulated/0/Download/app-release1.30.apk"

**Comment by Blankj** [comment]
试一下 1.24.3

**Comment by MElfikyAmaz** [comment]
still exist in 1.24.4

**Comment by Blankj** [comment]
@MElfikyAmaz 什么报错？

**Comment by beiger** [comment]
可以了，谢谢

**Comment by beiger** [comment]
不过有时候显示的文件实际不存在了，选择这个文件之后，就会出错

**Comment by beiger** [comment]
@Blankj

**Comment by beiger** [comment]
带raw的是正确的，这种有id的会出错：
![image](https://user-images.githubusercontent.com/18483100/59919174-5294e280-9459-11e9-90ed-eec720e67773.png)

**Comment by MElfikyAmaz** [comment]
@Blankj sorry it was error in my side not yours

**Comment by yuzhiqiang1993** [comment]
1.24.4 版UriUtils.uri2File(uri)报错，拿到的数据不对，1.23.7没有这个问题

**Comment by yuzhiqiang1993** [comment]
![image](https://user-images.githubusercontent.com/18605757/60333854-ae68e980-99cc-11e9-9602-e605d21abcfa.png)

debug下来发现最后的路径不对

**Comment by yuzhiqiang1993** [comment]
![image](https://user-images.githubusercontent.com/18605757/60334730-b9247e00-99ce-11e9-819d-38a5d78edaa3.png)

1.23.7返回的是正确的

**Comment by Blankj** [comment]
试试 1.24.5

**Comment by yuzhiqiang1993** [comment]
1.24.6  返回路劲依然错误
![image](https://user-images.githubusercontent.com/18605757/60406131-03804780-9be7-11e9-8c6d-746ce1578125.png)

**Comment by sunnycoffee** [comment]
1.24.7 还没修复。
我对比了1.23.7的代码发现了问题
1.23.7
![image](https://user-images.githubusercontent.com/3132535/60945914-6bd5d400-a31f-11e9-91db-7c193d64adaa.png)
1.24.7
![image](https://user-images.githubusercontent.com/3132535/60945977-9fb0f980-a31f-11e9-9232-05482ae0e5de.png)

**Comment by Blankj** [comment]
@sunnycoffee 1.23.7 直接进入了这个返回了是吗
![image](https://user-images.githubusercontent.com/17978187/60946792-b3f5f600-a321-11e9-966f-6e536aed63e3.png)

**Comment by sunnycoffee** [comment]
@Blankj 
不是。测试的scheme是content
新版本（1.24.7）直接进入了
![image](https://user-images.githubusercontent.com/3132535/60947655-a8a3ca00-a323-11e9-8602-35694442c9d3.png)
而旧版本（1.23.7）调用了，下面的方法
![image](https://user-images.githubusercontent.com/3132535/60947686-c5d89880-a323-11e9-81bb-5736d4663ea8.png)

**Comment by Blankj** [comment]
@sunnycoffee 新版本可以吗

**Comment by sunnycoffee** [comment]
@Blankj 新版本可以
