### ISSUE TITLE
ToastUtil问题

### ISSUE THREAD

**Issue by zhupengxiang** [Blankj/AndroidUtilCode#955]
The version of utilcode:  1.24.2
ToastUtil.showShort(@StringRes final int resId)
项目里有多语言  直接传resId导致每次取的都是默认的string.xml

**Comment by Blankj** [comment]
语言切换后执行：
```java
Resources resources = Utils.getApp().getResources();
DisplayMetrics dm = resources.getDisplayMetrics();
Configuration config = resources.getConfiguration();
config.locale = Locale.ENGLISH;
resources.updateConfiguration(config, dm);
```

**Comment by zhupengxiang** [comment]
我现在是在baseactivity的attachBaseContext这样写的    为什么要用utils的app呢
![image](https://user-images.githubusercontent.com/17894209/59816030-17a58880-934d-11e9-8333-cb2da0edc2b5.png)

**Comment by Blankj** [comment]
只要你确保是 application 就行

**Comment by zhupengxiang** [comment]
这么写的取的还是默认的string.xml的   resources.updateConfiguration我给换成了createConfigurationContext   因为update方法在7.0是过时的
![image](https://user-images.githubusercontent.com/17894209/59818314-f4cba200-9355-11e9-8b52-3782bb5e8282.png)

**Comment by Blankj** [comment]
现在可以直接用 LanguageUtils 来切换语言
