### ISSUE TITLE
Application is treated as virus by ESET when we include blankJ (Not confirmed)

### ISSUE THREAD

**Issue by vijayakumar52** [Blankj/AndroidUtilCode#956]
One of my Application has been categorized as "Potentially unsafe Application" by ESET Antivirus software. 
Threat Name: Android/DataCollector.UtilCode.A (variant)

I couldn't find the root cause and I searched over the internet and found this thread,
https://github.com/Meituan-Dianping/walle/issues/274
Where people are saying when they include this library their application was treated as a virus by some AntiVirus Software.
Does this library has any issue related to security? or is it a false positive?

**Comment by Blankj** [comment]
Try to open proguard, and don't keep my library.

**Comment by vijayakumar52** [comment]
I haven't added proguard into the application. Should I need to add to resolve this issue?

**Comment by Blankj** [comment]
just set `minifyEnabled true` to open proguard.
```
buildTypes {
    release {
        minifyEnabled true
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

**Comment by vijayakumar52** [comment]
Hey, thanks for the response. I know how to add progaurd in my app. I've had some issues when enabling progaurd that's why I haven't implemented yet. It it solves the problem then I'll happily enable the progaurd. 

My question is, 
1. Is this is a known issue with the library treating the app as "Potentially unsafe application"
2. Is "enabling the progaurd" the only way to resolve this issue?

**Comment by Blankj** [comment]
@vijayakumar52  Yes, this is a known issue. Because I don't know which APIs cause the problem, I can't fix it.

**Comment by Blankj** [comment]
try to use the version of 1.24.6

**Comment by jhansche** [comment]
Please also see: https://www.virustotal.com/gui/file/52c11711e1d8c3023f509ee77b456c2047472296725c8eb0fcd3d09ada950621/detection

It detects PhoneUtils.dex (a pre-dexed version of the PhoneUtils.class) as `Trojan.SMS.AndroidOS.Agent.a3`.

**Comment by Blankj** [comment]
@jhansche version of 1.25.7 is ok.

**Comment by fantasyado** [comment]
Threat Name: Android/DataCollector.UtilCode.A (variant)
请问这个问题在新版解决了吗 @Blankj
