### ISSUE TITLE
ToastUtil在魅族手机不显示问题

### ISSUE THREAD

**Issue by LXLYHM** [Blankj/AndroidUtilCode#957]
## Describe the bug
最新版本1.24.2的ToastUtil在魅族手机不显示:ToastUtils.showShort("hello");
机型名称：M1822
设备型号：M822Q
Android版本：8.1.0
版本号：Flyme 7.3.0.0A

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/download/1.24.2/util_1_24_2.apk
跑我这个 demo 呢

**Comment by LXLYHM** [comment]
跑你这个demo能弹

我自己的同一个项目
classpath 'com.android.tools.build:gradle:3.1.0'  distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip  ToastUtils在魅族这把手机能弹窗
但是
classpath 'com.android.tools.build:gradle:3.3.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip  ToastUtils在这把魅族手机就不弹窗了额
好奇怪
这跟我之前AndroidUtilCode都用1.9.1版，忽然升级到1.24.2版有影响吗？

**Comment by Blankj** [comment]
和 gradle 无关的，你要确保用的是 1.24.2 的包那就可以的

**Comment by LXLYHM** [comment]
嗯，最终确实是导入1.24.2的版本。
排查出来原因：
请求返回错误时连续调用ToastUtils三次 弹相同或不同提示内容的时候 弹不出来
我改成请求错误只弹一次提示内容 魅族那把手机就ok了
别的手机都不会因为连续弹多次有问题(⊙o⊙)…

**Comment by LXLYHM** [comment]
感谢大佬抽空指点
