### ISSUE TITLE
UriUtils.uri2File 会出现找不到文件

### ISSUE THREAD

**Issue by dozyx** [Blankj/AndroidUtilCode#958]
## Describe the bug
通过文件管理器选取图片获得 uri，然后调用 UriUtils.uri2File 活动的 File 是错误的
- The version of utilcode: 1.24.2
- The device: 小米 9
- The version of device:  API 28

## The code of bug

选取图片代码
```kotlin
    val intent = Intent(Intent.ACTION_PICK)
    intent.setDataAndType(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, "image/*")
    startActivityForResult(intent, 1)
```
不使用默认相册，而是使用文件管理来选取图片，返回的 File 是不存在的。
打印 uri 的 path，显示的是 /external_files/DCIM/1553440231192.jpg，这样 UriUtils.uri2File 里 path.replace("/external", "") 就有问题了。

**Comment by Blankj** [comment]
试一下 1.24.3

**Comment by dozyx** [comment]
1.24.3 可以了，谢谢
