### ISSUE TITLE
SpanUtils.appendImage能设置图片宽高么?

### ISSUE THREAD

**Issue by open9527** [Blankj/AndroidUtilCode#959]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
这个不支持的哈，想支持的话那就自定义 span 吧
