### ISSUE TITLE
FileIOUtils中writeFileFromString造成部分数据未被写入到文件

### ISSUE THREAD

**Issue by hehuiran** [Blankj/AndroidUtilCode#961]
FileIOUtils中

public static boolean writeFileFromString(final File file,
                                              final String content,
                                              final boolean append) {
        if (file == null || content == null) return false;
        if (!createOrExistsFile(file)) return false;
        BufferedWriter bw = null;
        try {
            bw = new BufferedWriter(new FileWriter(file, append));
            bw.write(content);
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        } finally {
            try {
                if (bw != null) {
                    bw.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

BufferedWriter 调用write之后直接close，如果此时缓冲区没有装满，会造成缓冲区中数据没有被写入到文件中，会造成数据丢失，是不是应该在write之后调用flush方法

**Comment by Blankj** [comment]
看一下 BufferedWriter.close 方法

**Comment by hehuiran** [comment]
我使用该方法发现有一条数据写入不完全，请问大佬知道是什么原因吗？

**Comment by Blankj** [comment]
什么数据，可以在本地单元测试跑一下试试。
