### ISSUE TITLE
当前在Activity界面,为什么调用 KeyboardUtils.hideSoftInput(this);不会隐藏软键盘呢?

### ISSUE THREAD

**Issue by roybill** [Blankj/AndroidUtilCode#964]
@Override
    protected void onPause() {
        super.onPause();
        if (KeyboardUtils.isSoftInputVisible(this)) {
            KeyboardUtils.hideSoftInput(this);
        }
    }

**Comment by Blankj** [comment]
库什么版本？

**Comment by roybill** [comment]
@Blankj      implementation 'com.blankj:utilcode:1.23.7'

**Comment by Blankj** [comment]
用最新的试试

**Comment by roybill** [comment]
@Blankj    更新为最新的implementation 'com.blankj:utilcode:1.24.4', 还是不行,当前处于Activity,我直接就放this,也就是这样:  KeyboardUtils.hideSoftInput(this); 你那边可以试试

**Comment by roybill** [comment]
我的测试手机是小米8,当前Activity这样就可以:getWindow().setSoftInputMode( WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN);//隐藏软键盘  
建议参考这个?

**Comment by Blankj** [comment]
你这是设置键盘模式，那么用 toggle 呢

**Comment by roybill** [comment]
toggleSoftInput可以隐藏软键盘, 我的键盘是点击EditText输入内容时弹出的

**Comment by Blankj** [comment]
你 Activity 设置了什么键盘模式，我 Demo 是没问题的在 onPause 中 hide 键盘

**Comment by roybill** [comment]
默认什么模式都没有设置 , 这个我是后面加的:getWindow().setSoftInputMode( WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN);

**Comment by Blankj** [comment]
[app-debug.apk.zip](https://github.com/Blankj/AndroidUtilCode/files/3333252/app-debug.apk.zip)

试试这个 util demo 中的 KeyBoard Demo，进入之后返回 home 看键盘是否会隐藏

**Comment by Blankj** [comment]
或者你可以建一个最近本的 demo 试一下

**Comment by roybill** [comment]
@Blankj  谢谢,我再研究一下

**Comment by Blankj** [comment]
@roybill 实在不行就判断下键盘是否显示，然后调用 toggle 即可
