### ISSUE TITLE
代码不全, 报错. 

### ISSUE THREAD

**Issue by MAIMIHO** [Blankj/AndroidUtilCode#97]
AndroidUtilCode/app/src/main/java/com/blankj/androidutilcode/activities/HandlerActivity.java
setContentView(R.layout.activity_handler);
tvAboutHandler0 = (TextView) findViewById(R.id.tv_about_handler0);
tvAboutHandler1 = (TextView) findViewById(R.id.tv_about_handler1);

AndroidUtilCode/app/src/main/res/layout/activity_handler.xml
里面没有这两个id

**Comment by Blankj** [comment]
我改了，没同步
