### ISSUE TITLE
Fragment中onDebouncingClick没效果

### ISSUE THREAD

**Issue by androidflying** [Blankj/AndroidUtilCode#970]
## Fragment中onDebouncingClick没效果 demo也是，Activity中可以。

- The version of utilcode: 1.24.4
- The device: oppo reno
- The version of device: 28

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by androidflying** [comment]
BaseFragment中
 private ClickUtils.OnDebouncingClickListener mDebouncingClick = new ClickUtils.OnDebouncingClickListener() {
        @Override
        public void onDebouncingClick(View v) {
            BaseFragment.this.onDebouncingClick(v);
        }
    };


替换成


 private View.OnClickListener mClickListener = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            onDebouncingClick(v);
        }
    };


就可以了。

**Comment by Blankj** [comment]
代码忘记修改了，嗯，我提交一下
