### ISSUE TITLE
AntiShakeUtils 最新版本移除了?是有什么问题么?还是有新方法替代了?

### ISSUE THREAD

**Issue by open9527** [Blankj/AndroidUtilCode#971]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Blankj** [comment]
ClickUtils 中包含更多功能了
