### ISSUE TITLE
 UriUtils.file2Uri使用上一个奇怪的问题

### ISSUE THREAD

**Issue by houyuehai** [Blankj/AndroidUtilCode#972]
## Describe the bug
我创建一个excel文件，放在外部存储中。
然后在应用内分享打开这个文件。
问题就在，app安装完成**_第一次_**调用这个方法选择其他的app打开这个文件的时候，会提示找不到这个文件。只有第一次，只要不卸载，之后创建新的文件正常打开。
我用阿里华为的远端测试机好像没有这个问题（因为我忘记了是华为哪一个手机了，这好像是小米适配的问题）
    public static boolean openFile(File file) {
        Intent openIntent = new Intent(Intent.ACTION_VIEW);
        openIntent.addCategory(Intent.CATEGORY_DEFAULT);
        String name = file.getName().trim();
        String extension = name.substring(name.lastIndexOf('.') + 1);
        String type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
        _**Uri uri = UriUtils.file2Uri(file);**_
        openIntent.setDataAndType(uri, type);//此处可发送多种文件
        openIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        openIntent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
        openIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        if (Utils.getApp().getPackageManager().queryIntentActivities(openIntent, PackageManager.MATCH_DEFAULT_ONLY).size() > 0) {
            ActivityUtils.startActivity(Intent.createChooser(openIntent, file.getName()));
            return true;
        }
        return false;
    }

版本:1.24.3
手机：小米mx6 android N
感谢柯基。

**Comment by Blankj** [comment]
你这 title 和内容怎么不对应呢

**Comment by houyuehai** [comment]
我搞错了。现在修改了题目。

**Comment by Blankj** [comment]
这我也无能为力哈，只能单独处理了你
