### ISSUE TITLE
建议SpanUtils增加的功能

### ISSUE THREAD

**Issue by Glorylan** [Blankj/AndroidUtilCode#973]
增加图文混排间距设置，图片位置设置，图片大小设置，字体位置设置，字体大小设置

**Comment by Glorylan** [comment]
图片支持scaleType类型设置

**Comment by Blankj** [comment]
大哥 你用 ImageView 吧。

**Comment by Glorylan** [comment]
> 大哥 你用 ImageView 吧。

大佬我跟你说说具体场景，在一个单纯的TexView里，有一段文本换行是图片再换行是文本再换行又是图片最后又是文本（文本\n-图-\n文本\n-图-\n文本的形式）,此时图片按照原始的ImageSpan是不能设置水平居中的，并且图片距离文本的相对位置也是不可设置的。我想到的是你的工具类里新增一个appenddp（距离可以是水平的也可以是竖直的）用于设置上下链式调用之间的距离的比如append(文本).append(dp距离).append(图片)……

**Comment by Glorylan** [comment]
> 大哥 你用 ImageView 吧。

大佬我跟你说说具体场景，在一个单纯的TexView里，有一段文本换行是图片再换行是文本再换行又是图片最后又是文本（文本\n-图-\n文本\n-图-\n文本的形式）,此时图片按照原始的ImageSpan是不能设置水平居中的，并且图片距离文本的相对位置也是不可设置的。我想到的是你的工具类里新增一个appenddp（距离可以是水平的也可以是竖直的）用于设置上下链式调用之间的距离的比如append(文本).append(dp距离).append(图片)……

**Comment by Blankj** [comment]
设置间距有的啊 appendSpace

**Comment by Blankj** [comment]
你这格式都固定了为何不直接写布局写死不就行了么，啥都好调整，复杂的肯定是用布局的，何况你这图片还可能会导致 OOM。
