### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by Herryl** [Blankj/AndroidUtilCode#974]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by Herryl** [comment]
ping 打包加固之前何以正常使用，加固之後安裝的第一次ping失敗

**Comment by Blankj** [comment]
ping 是为了判断是否有网络吗？
