### ISSUE TITLE
日志文件超过设置的保存时间没有被清除

### ISSUE THREAD

**Issue by wudilun** [Blankj/AndroidUtilCode#977]
## Describe the bug

日志文件超过设置的保存时间没有被删除

- The version of utilcode: 1.24.7

## The code of bug

LogUtils.getConfig()
                .setLog2FileSwitch(true)
                .setDir(path)
                .setFilePrefix(AppConfig.LOG_NAME)
                .setBorderSwitch(false)
                .setLogHeadSwitch(false)
                .setSaveDays(AppConfig.LOG_SAVE_DAYS);

## Screenshots
![image](https://user-images.githubusercontent.com/18107178/60936065-7764d300-a2fe-11e9-821a-44c61cc1d473.png)
return返回false

**Comment by Blankj** [comment]
name 是什么啊那么

**Comment by wudilun** [comment]
> name 是什么啊那么

name:VersionUpdate-2019-05-22-com.nbpt.www.versionupdate.txt

**Comment by Blankj** [comment]
这个是因为版本有过更新，以前是 - 分割，现在是 _ 分割导致的。以前的就不要管了吧，新版本之后会起作用的。
