### ISSUE TITLE
1.24.7，多语言适配

### ISSUE THREAD

**Issue by luciferChou** [Blankj/AndroidUtilCode#978]
从utilcodex1.24.4x升级到1.24.7，我项目里的多语言适配就不生效，没整明白原因。有人有碰到相同问题么，大神一起来找找看这个问题呗

**Comment by Blankj** [comment]
https://blankj.com/2019/06/29/only-one-code-change-language/
试试这个切换语言

**Comment by luciferChou** [comment]
没用你们的切换语言就不行，是做了什么限制么。还有你们的切换语言还有白屏哦。

**Comment by Blankj** [comment]
先上你的代码

**Comment by abc306026450** [comment]
在切换语言的地方直接点用        LanguageUtils.applyLanguage(Locale.CHINESE,"com.test.muiltlandemo.MainActivity");
没有效果 ，还是英语。。。

**Comment by abc306026450** [comment]
多语言资源文件配置没问题。。自定义context重新加载资源可以，但是使用依赖库中的方法不行。。

**Comment by Blankj** [comment]
https://github.com/Blankj/AndroidUtilCode/releases/download/1.24.6/util_1_24_6_release.apk
试试我的 demo

**Comment by abc306026450** [comment]
您的demo可以 但是我这边调用方法感觉也没什么问题啊，我再研究下吧。。

**Comment by Blankj** [comment]
可能你项目中还存有设置语言的地方把我设置的给还原了。

**Comment by abc306026450** [comment]
好，我重新创建个DEMO项目试试

**Comment by luciferChou** [comment]
我还是降回1.24.4，你们这个切换的不好用。

**Comment by Blankj** [comment]
@luciferChou 说一下具体不好的地方 我可以改进的

**Comment by Blankj** [comment]
使用最新版 1.25.0 试试
