### ISSUE TITLE
EncryptUtils RSA 解密公钥失败

### ISSUE THREAD

**Issue by niyaode** [Blankj/AndroidUtilCode#984]
我现在还不关心RSA2 的问题，我想知道为什么公钥BASE64解密我究竟该用哪款加解密
```xml
java.lang.RuntimeException: Method decode in android.util.Base64 not mocked. See http://g.co/androidstudio/not-mocked for details.

	at android.util.Base64.decode(Base64.java)
	at com.blankj.utilcode.util.EncodeUtils.base64Decode(EncodeUtils.java:117)
	a
```
请指明 Java Spring中到底用那个Base64 进行加解密啊，不同的工具 生成的都不一样啊
是 org.springframework.util.Base64Utils
还是 java.util.Base64;
还是 sun公司的Base64啊
# 还有重要的一点就是RSA加密是否和Java后台一样啊，我自己找过RSA加密工具类，但是andriod和Java加密的密文都不一样，原因是他们两者的提供商不一样，所以我在工具类中更换了提供商就可以了

**Comment by Blankj** [comment]
所以最终你 Base64 用的哪个啊

**Comment by Blankj** [comment]
base64 应该没问题的呀
