### ISSUE TITLE
关于ThreadUtils,有几个地方不解，还望大佬们可以赐教

### ISSUE THREAD

**Issue by softsnow** [Blankj/AndroidUtilCode#988]
默认的几种方式，任务队列默认都是LinkedBlockingQueue，这是出于什么考虑呢？而且默认corePoolSize都是0，那这几个和SingleThreadExecutor有什么区别呢？都会阻塞吧，岂不是无论用哪种，都只会创建一个线程吗？

**Comment by softsnow** [comment]
![image](https://user-images.githubusercontent.com/20201897/61694938-16f57d00-ad65-11e9-9ae2-544dccef7a7a.png)
我用了 ThreadUtils.executeByCached方法，通过日志看也只是创建了一个县城，这和内置的SingleThreadExecutor有所不同，请问这么设计是为什么呢

**Comment by Blankj** [comment]
我的错，试试 1.25.1 版本吧。

**Comment by softsnow** [comment]
可以了，大佬。
