### ISSUE TITLE
权限异常

### ISSUE THREAD

**Issue by androidGhost** [Blankj/AndroidUtilCode#993]
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.（com.blankj.utilcode.util.PermissionUtils$PermissionActivity）
使用的版本是1.23.5

**Comment by androidGhost** [comment]
.theme(new PermissionUtils.ThemeCallback() {
                    @Override
                    public void onActivityCreate(Activity activity) {
                        ScreenUtils.setFullScreen(activity);
                        setTheme(R.style.ActivityTheme);
                    }
                })
是不是可以在这里设置主题处理上面的问题

**Comment by Blankj** [comment]
最简单就是把你 application 的主题设置为 appcompat 的

**Comment by androidGhost** [comment]
parent="Theme.AppCompat.Light.NoActionBar"
之前就是这样设置了

**Comment by Blankj** [comment]
这样设置不行的吗

**Comment by androidGhost** [comment]
![image](https://user-images.githubusercontent.com/9106628/62261710-d4a8fb80-b448-11e9-8194-c416150c9ca4.png)
少部分机型有这个问题

**Comment by Blankj** [comment]
所以你那边也复现不了是吗

**Comment by androidGhost** [comment]
没有现有的机型测试，我试试到优测上看看有没有对应机型测试

**Comment by Blankj** [comment]
请问找到问题了吗

**Comment by Jcdroid** [comment]
当用户拒绝提供**存储权限**会出现这个问题

**Comment by Jcdroid** [comment]
我这边有尝试过在onDenied中获取当前的activity用来打开一个Dialog，这时候获取到时PermissionActivity，所以报了这个错，把Dialog的context改为使用自己应用的context就可以了。

**Comment by Blankj** [comment]
你应该是使用了 TopActivity 来唤起弹窗，而 TopActivity 是我的 TransActivity，TransActivity 是 FragmentActivity，并不支持 appCompat 主题，所以在这个 Activity 中弹 appCompat 主题的 dialog 会有问题。

**Comment by Jcdroid** [comment]
是的，用的是v7的AlertDialog，继承自AppCompatDialog
