### ISSUE TITLE
BusUtils.post(”XXX“”);日志一直显示The bus of tag <XXX> is not exists.

### ISSUE THREAD

**Issue by jiqianwen** [Blankj/AndroidUtilCode#994]
## Describe the bug

- The version of utilcode: 
- The device: 
- The version of device: 

## The code of bug

```
put your code here
```

## The stack of crash

```
put the stack of crash here
```

## Screenshots

Please delete the current line and the followings.

Thank you for supporting [AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode).

**Comment by jiqianwen** [comment]
求教，什么原因？我在广播接收里面post一个tag消息，想更新UI，一直显示这个。。。

**Comment by Blankj** [comment]
__bus__.json 文件里有这个 tag 吗

**Comment by jiqianwen** [comment]
这个文件在哪看？

**Comment by jiqianwen** [comment]
BusUtils.post(“refresh”);就post了一个这么简单的消息，post的时候不需要注册啥的吧，直接调用post方法就行了？

**Comment by Blankj** [comment]
https://blankj.com/2019/07/22/busutils/ 好好看文章了吗

**Comment by jiqianwen** [comment]
我是说在需要发消息的地方只要调用post方法就行了吧？然后在接收的地方写注册和接收的方法

**Comment by Blankj** [comment]
是的呀

**Comment by jiqianwen** [comment]
我在广播里调用BusUtils.post(tag);然后再其中一个Activity里面调用@Override
    public void onStart() {
        super.onStart();
        BusUtils.register(this);
    }

    @Override
    public void onStop() {
        super.onStop();
        BusUtils.unregister(this);
    }

    @BusUtils.Bus(tag)
    public void noParamFun() {
        LogUtils.d("收到Bus消息");
    }
是这么调用吧- -

**Comment by jiqianwen** [comment]
但是现在就直接死在post这一步了。。。。  跟断点发现BusInfo busInfo = mTag_BusInfoMap.get(tag);这里一直是null

**Comment by Blankj** [comment]
插件加了吗

**Comment by jiqianwen** [comment]
妈耶，好像是的，我直接用的utilcode，还以为不用加这个- -  我去试试

**Comment by Blankj** [comment]
最好用最新的 1.25.5 版本。

**Comment by jiqianwen** [comment]
好的，多谢了~
