### ISSUE TITLE
ActivityUtils 的finishAllActivities 与finishAllActivitiesExceptNewest

### ISSUE THREAD

**Issue by tang5011235** [Blankj/AndroidUtilCode#996]
## 

finishAllActivities 与finishAllActivitiesExceptNewest内部维护的list产生了问题

- The version of utilcode: 1.25.5
- The device: 暂时有vivo,红米note2，当前只有这两款手机
- The version of device: 7.1

## The code of bug
IosToast.showSucceed("账号已退出", false);
PersistentUtils.getInstance(PersistentFile.USER_INFO).clearAll();
ActivityUtils.startActivity(LoginActivity.class);
ActivityUtils.finishAllActivitiesExceptNewest();

## The stack of crash

acitvity的list 我查看了下没有最新的activity，即上面代码的LoginActivity
所以finish的时候没有关闭当前界面

**Comment by Blankj** [comment]
你调用 start 之后又不是同步执行的，你要在新的 Activity#onCreate 再 finish 啊。
