### ISSUE TITLE
PhoneUtils里好像有SEND_SMS这个权限，但由于项目中并没用到对应这个权限的方法导致被网警约谈了

### ISSUE THREAD

**Issue by bigbobi** [Blankj/AndroidUtilCode#997]
PhoneUtils里好像有SEND_SMS这个权限，但由于项目中并没用到对应这个权限的方法sendSmsSilent()，导致被网警约谈了，请问有没有什么比较好的办法可以解决这个窘境

**Comment by Blankj** [comment]
网警请你喝茶了吗，你项目都不开混淆的吗

**Comment by bigbobi** [comment]
> 网警请你喝茶了吗，你项目都不开混淆的吗

因为某些我们自身项目的原因，所以没有开启混淆，不好意思，见笑了

**Comment by Blankj** [comment]
其他方法没问题吗？没的话我就把这个函数拿出去给你个包好了

**Comment by bigbobi** [comment]
> 其他方法没问题吗？没的话我就把这个函数拿出去给你个包好了
大神您先等会，我们先自己试试能不能把之前的不能开启混淆的问题解决

**Comment by bigbobi** [comment]
> 其他方法没问题吗？没的话我就把这个函数拿出去给你个包好了

大神，我这边试了半天还是没解决混淆的问题，所以能不能麻烦你重新弄一个不带SEND_SMS权限和READ_CONTACTS权限的包呢？

**Comment by Blankj** [comment]
用 1.25.6-alpha2 试试

**Comment by bigbobi** [comment]
> 用 1.25.6-alpha2 试试

多谢大神慷慨协助

**Comment by phoebewow** [comment]
这个方法好像可以避开
    permissions {
        exclude "android.permission.READ_PHONE_STATE", "android.permission.RECEIVE_SMS"
    }
