### ISSUE TITLE
ApiBus 是否可用于插件化中

### ISSUE THREAD

**Issue by adaJQD** [Blankj/AndroidUtilCode#999]
在`VirtualApk`插件化项目中，是否可使用`ApiBus`进行通信？

插件化中宿主是不直接依赖插件的，那么`api-gradle-plugin`就扫描不到带有 `@ApiUtils.Api` 注解的类。

**Comment by Blankj** [comment]
扫描不到那就插入不了就做不了通信的哦。

**Comment by adaJQD** [comment]
> 扫描不到那就插入不了就做不了通信的哦。

有没有计划支持插件化？
插件化通信有没有建议？

**Comment by Blankj** [comment]
各个插件中的 Utils 都不是同一份，跨插件通讯肯定做不到的，BusUtils 和 ApiUtils 插件内都是可以用的。
插件与插件，插件与宿主之间的代码完全隔离，因此，插件与插件，插件与宿主直接通信只能通过android 系统级别的通信方式。
